### ISSUE TITLE
choose subtitle renamer iso 2 or 3 characters

### ISSUE THREAD

**Issue by pdefert** [tinyMediaManager/tinyMediaManager#10]
Add the choice of number of letter ofr specify the language of subtitles 
Today, by default subtitles are suffixed by 3 characters for language.

Plex media server support only 2 characters.

is it possible to have the choice in settings ?

Best regards

**Comment by pdefert** [comment]
it seems that kodi support language on 2 characters

**Comment by myron0815** [comment]
well, basically everything between the last dot and extension is the "subtitle name" displayed in GUI.
So, we could write EN, ENG, English, Anglais.. or any other (localized) naming.
Dunno how to make this easy configureable... so we've chosen to write ISO3 codes, as we do for streamdetails...

**Comment by myron0815** [comment]
according to https://support.plex.tv/hc/en-us/articles/200471133-Adding-Local-Subtitles-to-Your-Media Plex should be fine with 3 char names....

**Comment by pdefert** [comment]
ok i read the post, and test it

Plex support **ISO-639-2/B** codes  but java locale(use by tinymediamanager) produce only **ISO-639-2/T** codes.
in my case, french language, the iso3 code supported by plex is **fre**. iso3 code produce by tinymediamanager is **fra**.
For Plex, **fra** is unknown locale. I check also mkvtoolnix, it use ISO-639-2/B codes 

I search some libraires that purpose ISO-639-2/B codes  [https://github.com/TakahikoKawasaki/nv-i18n](url) 
[http://henningpetersen.com/post/13/iso-639-2-b-language-codes-in-java](url)

is it possible to consider my first proposal or use ISO-639-2/B codes as an option?

**Comment by myron0815** [comment]
awwww... never heard of a bibliographic code :D
Have to think, how we could integrate this....

One (long outstanding) feature is, to add more NFO types to TMM (not only Kodi / MediaPortal)
If we add Plex (and others), we might integrate the needed changes here per type...
Damn standards...

Thanks for information :)

**Comment by pdefert** [comment]
Thanks 

yes, damn I18N standards ... not standards  :-p

**Comment by mlaggner** [comment]
pdefert could you try the latest nightly build (http://nightly.tinymediamanager.org) whether that feature works for your requirement or not?

**Comment by pdefert** [comment]
i will test this wekk

**Comment by mlaggner** [comment]
added for TV shows too. please test

**Comment by pdefert** [comment]
Hi,  i found the option for tvshow but it doesn't work

it drops the subtitle langage info
mytvshow.fra.srt  ->> mytvshow.srt

**Comment by pdefert** [comment]
Hi,

i've tested the tuesday (31/05) version on linux it's work

and i' ve tested Wednesday (01/06) version on macos it doesn't works
it doesn't rename  in 2 letter and it 's only support one 3 letters format 
And if subtitle have no langage define, the renamer do this
mytvshow.srt => mytvshow..srt


The new nightly build (02/06) under linux works fine, both movies and tvshow

i need to re test the last version on macos

**Comment by mlaggner** [comment]
> And if subtitle have no langage define, the renamer do this
mytvshow.srt => mytvshow..srt

this is fixed in the next build

**Comment by pdefert** [comment]
i 'v tested with the latest version (02/06) on mac and the problem exist as describe below

**Comment by mlaggner** [comment]
could you give me an example of your file names from your mac?
The logic itself is system independent - if that works on linux it must work on Mac OSX.

for filenames not containing any language hint (like mytvshow.srt) we cannot extract any info for renaming from it..

**Comment by pdefert** [comment]
Ok i found the bug, 

(on mac) the tvshow renamer use the property from movie's preference, not tvshow's preference and it work well.

strange  :-(

**Comment by mlaggner** [comment]
thanks for the hint - was a copy and paste error..
new build is up

**Comment by pdefert** [comment]
ok  work fine on mac and linux, i can't test on windows

good job, this feature is really usefull
