### ISSUE TITLE
Error when downloading TV metadata

### ISSUE THREAD

**Issue by deadman36g** [tinyMediaManager/tinyMediaManager#100]
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/591011/tmm_logs.zip)
Version: 2.9
Build: 2016-10-27 18:39
OS: Mac OS X 10.12.1
JDK: 1.8.0_111 x86_64 Oracle Corporation

__What is the actual behaviour?__

When downloading tv series metadata error appears

__What is the expected behaviour?__
Downloading of tv metadata

__Steps to reproduce:__
Scaping of tv shows metadata

__Additional__
Have you attached the logfile from the day it happened? Yes

**Comment by deadman36g** [comment]
<img width="817" alt="screen shot 2016-11-15 at 11 19 57 am" src="https://cloud.githubusercontent.com/assets/3932793/20315949/91d4a2f2-ab25-11e6-9099-5b3988349919.png">

**Comment by myron0815** [comment]
The logfile is full of "permission denied" errors, when downloading images or writing NFO metadata :|
Can you check your write rights on /mnt/OMV/NAS4/SONARR/... ?

**Comment by deadman36g** [comment]
That was it, thanks @myron0815 for the quick fix
