### ISSUE TITLE
When renaming, won't work if the folder name is already correct

### ISSUE THREAD

**Issue by foux** [tinyMediaManager/tinyMediaManager#101]
__What TMM version are you using?__
2.9

__What is the actual behaviour?__
Trying to rename a movie file. The movie file has the wrong name, but the folder is already fine. TNM won't rename the movie file because the folder already exists

__What is the expected behaviour?__
TNM should rename the movie file, leaving it in the same folder

__Steps to reproduce:__
- Place a movie with the wrong name, in the folder expected from TNM
- Try to rename the movie

__Additional__
Running on OS X Sierra

**Comment by myron0815** [comment]
can you please upload the logfile (somewhere)?
And the movie name where it happened?
Thx

**Comment by foux** [comment]
Hi. I'll upload it as soon as I'm back on the computer where it happens.
Just one more information I've notices later : it's only when there's a case sensitive issue : for example, when the folder "Star wars" exists but TNM wants to put it into "Star Wars".

Hope that helps, and I'll upload the logs as soon as I can!

**Comment by myron0815** [comment]
That's a good catch!
We already fixed this type of problem once.
(At least for Windows it worked)
Problem here was, that the NTFS filesystem IS case insensitive, but case preserving.
Might be something similar on MacOS - let's check the logs :)

On what type of filesystem are your files?

**Comment by foux** [comment]
SMB

**Comment by foux** [comment]
And here are the logs. As they are not big, I'm pasting them here directly

`18:59:30.079 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data/scraper_fanarttv.conf' - using defaults
18:59:30.085 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data/scraper_imdb.conf' - using defaults
18:59:30.313 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data/scraper_metadata.album.universal.conf' - using defaults
18:59:30.321 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data/scraper_metadata.artists.universal.conf' - using defaults
18:59:30.328 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data/scraper_metadata.themoviedb.org.conf' - using defaults
18:59:30.334 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data/scraper_metadata.tvdb.com.conf' - using defaults
18:59:30.478 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data/scraper_moviemeter.conf' - using defaults
18:59:30.501 WARN  org.tinymediamanager.scraper.config.MediaProviderConfig - Cannot load settings 'data/scraper_opensubtitles.conf' - using defaults
18:59:54.812 ERROR org.tinymediamanager.core.movie.MovieRenamer - error moving folder: 
org.apache.commons.io.FileExistsException: Destination '/Volumes/Medias/Movies/Zombieland (2009)' already exists
	at org.tinymediamanager.core.Utils.moveDirectorySafe(Utils.java:637)
	at org.tinymediamanager.core.movie.MovieRenamer.renameMovie(MovieRenamer.java:245)
	at org.tinymediamanager.core.movie.tasks.MovieRenameTask$RenameMovieTask.call(MovieRenameTask.java:93)
	at org.tinymediamanager.core.movie.tasks.MovieRenameTask$RenameMovieTask.call(MovieRenameTask.java:83)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
18:59:54.813 ERROR org.tinymediamanager.core.movie.MovieRenamer - Could not move to destination '/Volumes/Medias/Movies/Zombieland (2009)' - NOT renaming folder`

**Comment by myron0815** [comment]
can you post a bit more / the complete log?
I'm missing some needed lines.... thx

**Comment by foux** [comment]
I've put all I've got in my error window. Can you telle me where I can find the logs?

**Comment by myron0815** [comment]
inside the TMM directory, folder logs.
Just the TXT file from today... (maybe zip it first)

**Comment by foux** [comment]
I haven't got (afaik) a TMM directory. I've just got the app in my Applications folder

**Comment by myron0815** [comment]
puh - i'm no Mac user :|
but there must be somewhere this directory:
tinyMediaManager.app/Contents/Resources/Java
and there should be a logs folder...

**Comment by foux** [comment]
Here you are! http://pastebin.com/7YbxxmPu

**Comment by myron0815** [comment]
thx... will have a look.
And yes, it is a filesystem case sensitivity problem.

You said SMB.
Is it a Windows share?
Or a Linux NAS?
..?

**Comment by foux** [comment]
Linux NAS with BTRFS (of course, case sensitive)

**Comment by myron0815** [comment]
Hmm... need to debug this on a Mac
@mlaggner 😜 

I'm unsure, who the culprit is.
Either the SMB filesystem implementation inside Java on the Mac... or...
Something seems to be case insensitive in the chain, where it shouldn't :|

**Comment by mlaggner** [comment]
that was (again) a problem of case insensitive file systems (since on your mac the CIFS share is mounted unter /Volumes which is on your main file system, Java handles access to that with the same rules of /).
I suppose the fixes from this January (2ef2158 and e90b901) did not work at all :D 

at least on my mac this fix works now
