### ISSUE TITLE
This error continues for months. I do not even try on different computers ...

### ISSUE THREAD

**Issue by kilingon** [tinyMediaManager/tinyMediaManager#102]
Version: 2.9.1-SNAPSHOT - NIGHTLY
Build: 2016-11-21 00:02
OS: Windows 8 6.2
JDK: 1.7.0_51 x86 Oracle Corporation

__What is the actual behaviour?__
When I press the Settings button, java gives an error.

**Error code;**

> java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key Settings.certification.medıum
> 	at java.util.ResourceBundle.getObject(Unknown Source)
> 	at java.util.ResourceBundle.getObject(Unknown Source)
> 	at java.util.ResourceBundle.getString(Unknown Source)
> 	at org.tinymediamanager.ui.movies.settings.MovieSettingsPanel$CertificationStyleWrapper.toString(MovieSettingsPanel.java:619)
> 	at javax.swing.plaf.basic.BasicComboBoxRenderer.getListCellRendererComponent(Unknown Source)
> 	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(Unknown Source)
> 	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source)
> 	at javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(Unknown Source)
> 	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
> 	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
> 	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
> 	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
> 	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
> 	at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
> 	at javax.swing.JList.setSelectedIndex(Unknown Source)
> 	at javax.swing.plaf.basic.BasicComboPopup.setListSelection(Unknown Source)
> 	at javax.swing.plaf.basic.BasicComboPopup.access$300(Unknown Source)
> 	at javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(Unknown Source)
> 	at javax.swing.JComboBox.fireItemStateChanged(Unknown Source)
> 	at javax.swing.JComboBox.selectedItemChanged(Unknown Source)
> 	at javax.swing.JComboBox.contentsChanged(Unknown Source)
> 	at javax.swing.AbstractListModel.fireContentsChanged(Unknown Source)
> 	at javax.swing.DefaultComboBoxModel.setSelectedItem(Unknown Source)
> 	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
> 	at org.tinymediamanager.ui.movies.settings.MovieSettingsPanel.<init>(MovieSettingsPanel.java:473)
> 	at org.tinymediamanager.ui.movies.settings.MovieSettingsContainerPanel.<init>(MovieSettingsContainerPanel.java:46)
> 	at org.tinymediamanager.ui.movies.MovieUIModule.getSettingsPanel(MovieUIModule.java:169)
> 	at org.tinymediamanager.ui.settings.SettingsPanel.<init>(SettingsPanel.java:83)
> 	at org.tinymediamanager.ui.dialogs.SettingsDialog.<init>(SettingsDialog.java:68)
> 	at org.tinymediamanager.ui.dialogs.SettingsDialog.getInstance(SettingsDialog.java:56)
> 	at org.tinymediamanager.ui.actions.SettingsAction.actionPerformed(SettingsAction.java:45)
> 	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
> 	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
> 	at javax.swing.AbstractButton.doClick(Unknown Source)
> 	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
> 	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
> 	at java.awt.Component.processMouseEvent(Unknown Source)
> 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
> 	at java.awt.Component.processEvent(Unknown Source)
> 	at java.awt.Container.processEvent(Unknown Source)
> 	at java.awt.Component.dispatchEventImpl(Unknown Source)
> 	at java.awt.Container.dispatchEventImpl(Unknown Source)
> 	at java.awt.Component.dispatchEvent(Unknown Source)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
> 	at java.awt.Container.dispatchEventImpl(Unknown Source)
> 	at java.awt.Window.dispatchEventImpl(Unknown Source)
> 	at java.awt.Component.dispatchEvent(Unknown Source)
> 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> 	at java.awt.EventQueue.access$200(Unknown Source)
> 	at java.awt.EventQueue$3.run(Unknown Source)
> 	at java.awt.EventQueue$3.run(Unknown Source)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
> 	at java.awt.EventQueue$4.run(Unknown Source)
> 	at java.awt.EventQueue$4.run(Unknown Source)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
> 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.awt.EventDispatchThread.run(Unknown Source)

__Additional__
Have you attached the logfile from the day it happened?

**Comment by kilingon** [comment]
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/613446/tmm_logs.zip)

**Comment by myron0815** [comment]
Thx.
I'm now able to reproduce your error with your settings :)
Seems to be language dependant.

Meanwhile, you can try to change the language in ./data/config.xml to
<language>en</language>
(At least, this worked for me)

**Comment by kilingon** [comment]
thank you so much. How many months "will it be correct?" I'm trying the new version.

**Comment by myron0815** [comment]
After reading this great article
http://blog.thetaphi.de/2012/07/default-locales-default-charsets-and.html
we have some more work to do.
It's really weird in Turkey :|
(but at least, it doesn't crash anylonger)
