### ISSUE TITLE
tmm scraping

### ISSUE THREAD

**Issue by peram1** [tinyMediaManager/tinyMediaManager#103]
Version: 2.9.1-SNAPSHOT - NIGHTLY
Build: 2016-11-28 00:04
OS: Linux 4.4.0-47-generic
JDK: 1.8.0_111 amd64 Oracle Corporation

__What is the actual behaviour?__
error when scraping: Fehler beim Herunterladen von Artwork : /home/peter/Downloads/Filme/Wiener Dog (2016 BDRip H264 720x418)/folder.jpg

__What is the expected behaviour?__
add image to directory and link into tmm

__Steps to reproduce:__
reproduceable with different movies
[Uploading tmm_logs.zip…]()

__Additional__
Have you attached the logfile from the day it happened?
yes
[Uploading tmm_logs.zip…]()

**Comment by mlaggner** [comment]
you haven't attached any logs...

**Comment by peram1** [comment]
sorry - hat in github wohl irgendwie nich funktioniert ...

---

"Can you imagine the moment when you've just met an attractive stranger
at a party, or you're online looking for someone, anyone, but you don't
ask: 'So, what do you do?'"
https://aeon.co/essays/what-if-jobs-are-not-the-solution-but-the-problem


Dr. Peter Raetz

peter.raetz@ownbay.net
voip d'Italia +39 0733 177 60 24
voip von Deutschland +49 7531 58 44 196
Belle Ile en mer +33 (0)9 72 50 61 99 

Am 2016-11-29 08:31, schrieb Manuel Laggner:

> you haven't attached any logs... 
> 
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/tinyMediaManager/tinyMediaManager/issues/103#issuecomment-263497178
[2]

**Comment by peram1** [comment]
DANKE ... super ... 

lg

---

"Can you imagine the moment when you've just met an attractive stranger
at a party, or you're online looking for someone, anyone, but you don't
ask: 'So, what do you do?'"
https://aeon.co/essays/what-if-jobs-are-not-the-solution-but-the-problem


Dr. Peter Raetz

peter.raetz@ownbay.net
voip d'Italia +39 0733 177 60 24
voip von Deutschland +49 7531 58 44 196
Belle Ile en mer +33 (0)9 72 50 61 99 

Am 2016-11-29 08:31, schrieb Manuel Laggner:

> you haven't attached any logs... 
> 
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/tinyMediaManager/tinyMediaManager/issues/103#issuecomment-263497178
[2]

**Comment by myron0815** [comment]
Links still do not work ;)
But you could contact us and attach the logs here: http://www.tinymediamanager.org/contact/

**Comment by peram1** [comment]
after latest update the issue is fixed ... thx
