### ISSUE TITLE
Feature Request: Enhance filter/search options

### ISSUE THREAD

**Issue by mxmehl** [tinyMediaManager/tinyMediaManager#104]
__What TMM version are you using?__

Version 2.9 on Arch Linux

__release, pre-release, nightly, or directly from GitHub/branch?__

Release

__What is the expected behaviour?__

I'd love to have a better filter (searching in my local movie database), for example

- Filter for the country and language of the movie
- For genre filter, enable searching for multiple genres at the same time (e.g. Drama + History)

Thanks! :)

**Comment by shubhamplank** [comment]
I would say the same,:
1.  checkbox for genres too instead of single select
2.  For foreign movies lovers, Country And/Or language filter.

**Comment by mlaggner** [comment]
already done for v3 - just be patient until v3 reaches stable quality ;)

**Comment by shubhamplank** [comment]
Thanks a lot! Let me just say that your work is a treasure for all the film hobbyist. TMM has made the biggest impact on the way I explore and watch movies, I can't be grateful enough.

**Comment by shubhamplank** [comment]
Have you postponed this feature to next build?

**Comment by ProIcons** [comment]
As Manuel mentioned,for Version 3. This won't be implemented on Version 2

**Comment by shubhamplank** [comment]
@ProIcons @mlaggner What is approx release timeline for the V3 build?

**Comment by ProIcons** [comment]
A Stable Release is not going to happen soon
. A Public Beta will be. V3's state at the moment is in Alpha. You can download straight through our github repository and build it using our maven script. Whatsoever is still buggy.

**Comment by getzze** [comment]
I tried the v3, the new filters are awesome.
A small request, is it possible to add an easy way to add country, language, genre or actor/director to the filters from movie details?
For example with a contextual menu on the elements or adding a button next to each element.

**Comment by mlaggner** [comment]
I probably won't do that..
I don't want to overload the UI and make things complicated - every filter you want is already available from the filter view

**Comment by the-solipsist** [comment]
One potential solution might be to allow for keyword searching (the way Google search / Gmail does), with search keywords like:
- director:Truffaut
- lang:eng / language:en (depending on whether you use 2 or 3 character languages)
- country:India
... and so on.

This way, new checkboxes don't need to be added (overloading the UI), and things can be kept simple while still allowing for flexible searches.

**Comment by ProIcons** [comment]
I don't think elastic search is a feature we want to implement at this very moment. Whatsoever we will have it on our minds for a future version update.
