### ISSUE TITLE
Scraper gone

### ISSUE THREAD

**Issue by Gizmo-Ger** [tinyMediaManager/tinyMediaManager#105]
Version: 2.9.1-SNAPSHOT - PRE-RELEASE
Build: 2016-11-29 14:55
OS: Windows 10 10.0
JDK: 1.8.0_111 x86 Oracle Corporation

__What is the actual behaviour?__

The scraper went missing from settings menu.

__What is the expected behaviour?__

The ability to choose from different scraper.

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
looks like there is a problem loading plugins from a path with a space in there now.. 
Just try to move the tmm dir to a path without a space in it till that is solved

**Comment by mlaggner** [comment]
a2a0de1427bbd27768df86b5d88870ea0d9c87e5 should fix that issue
