### ISSUE TITLE
IMDb TV scraping, no Director/Writers

### ISSUE THREAD

**Issue by SteverB11** [tinyMediaManager/tinyMediaManager#106]
Version: 2.9
Build: 2016-10-27 18:39
OS: Mac OS X 10.11.6
JDK: 1.8.0_101 x86_64 Oracle Corporation

__What is the actual behaviour?__
When using IMDb to scrape TV Shows, program scrapes cast and characters correctly, but leaves Director and Writers blank.

__What is the expected behaviour?__
To scrape Director and Writers along with Cast list. (IMDb has much more complete cast lists than TVDb.

__Steps to reproduce:__
Scrape TV Show using IMDb
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/637385/tmm_logs.zip)

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
well on imdb there is no director/writer info in the ep overview (e.g. http://www.imdb.com//title/tt0903747/epcast#year-2008). 
To scrape director/writer info would result into a website call for _every_ episode if we change it to scrape the ep detail page just for director/writer, scraping from imdb would result in an endless task (e.g. breaking bad would need ~65 site calls from imdb and now we need just 4)

**Comment by mlaggner** [comment]
we are implementing a scraaper for omdbapi - which uses basically the same data as imdb and offers an api.
with this scraper you will get all data you miss here

**Comment by mlaggner** [comment]
has been added with https://github.com/tinyMediaManager/scraper-imdb/commit/9927b4cafc0446f14af0e70fb36dc8656e2abf0f

will be in the next release
