### ISSUE TITLE
Swedish subtitles labeled incorrectly

### ISSUE THREAD

**Issue by TweetyDaBird** [tinyMediaManager/tinyMediaManager#107]
Version: 2.9
Build: 2016-10-27 18:39
OS: Windows 10 10.0
JDK: 1.8.0_91 x86 Oracle Corporation

When using three letter language codes and renaming, tmm labels them as sme instead of swe.

Files should be named *.swe.(srt) (or other file ending). 

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/637754/tmm_logs.zip)
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/637762/tmm_logs.zip)

**Comment by mlaggner** [comment]
this will be fixed in the next release.
you may have to rename the wrong subs after upgrading
