### ISSUE TITLE
TMDB Set Info In NFO File With Movieset Disabled

### ISSUE THREAD

**Issue by MediaSnog** [tinyMediaManager/tinyMediaManager#108]
Version: 2.9
Build: 2016-10-27 18:39
OS: Linux 3.16.0-38-generic
JDK: 1.7.0_121 amd64 Oracle Corporation

__What is the actual behaviour?__
When you have Movieset disabled in the movie scraper options, the movie set is still in the nfo file created by the manager.

`        <entry>
            <key>tmdbSet</key>
            <value xsi:type="xs:int" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">115570</value>
        </entry>`

__What is the expected behaviour?__
No set info should be in the nfo file.

__Steps to reproduce:__
Disable Movieset in the TMDB scraper.
Scrape a movie using the TMDB database, such as a Star Trek movie.
The set info will be in the nfo file for the movie.

__Additional__
Have you attached the logfile from the day it happened?
No, not needed. This isn't an error producing problem.

**Comment by mlaggner** [comment]
yes, we scrape all IDs we get and store it in our internal database (and NFO for re-importing).
the option only belongs to the movie set info (association, title and plot)
