### ISSUE TITLE
[Feature Request] Anime Tab

### ISSUE THREAD

**Issue by pschonmann** [tinyMediaManager/tinyMediaManager#109]
__What TMM version are you using?__
2.9 release

__What is the actual behaviour?__
Missing Anime tab

__What is the expected behaviour?__
Anime tab added between movies and tv show, series on left side

__Additional__
Hi! Would be fine that anime will have own tab. Should this be posible ?

**Comment by mlaggner** [comment]
Anime is basically just a special case for TV shows and can be handled via our TV show module
To implement an own module just for anime would be too much work for that little effort, thus we won't do that

**Comment by Stibbons** [comment]
Hello. If not direct support for anime, can you add ability to specify some series should not be divided into season folder ?
