### ISSUE TITLE
Coud you create episode thumb file with tbn extension #master

### ISSUE THREAD

**Issue by danielxaraujo** [tinyMediaManager/tinyMediaManager#11]
Create new option for thumb file name with tbn extension #master

**Comment by mlaggner** [comment]
.tbn is deprecated by Kodi for a while now

> Note: Kodi v14 still supports the older ".tbn" file extension, but users are advised to rename those file extensions from .tbn back to .jpg, in order to help ensure future support.

why exactly would you need that?

**Comment by danielxaraujo** [comment]
It's for boxee box. i have a fork and made this changes.

**Comment by danielxaraujo** [comment]
I would like to know you could incorporate these changes in the product

**Comment by mlaggner** [comment]
added support for this naming scheme with dcb227f97963ec618e6b9917737c025c147bf7e7

**Comment by danielxaraujo** [comment]
Thanks
