### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#110]
Version: 2.9.1
Build: 2016-12-12 17:48
OS: Windows 7 6.1
JDK: 1.8.0_60 x86 Oracle Corporation

Dont' scrape country movie in polish language.
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/656664/tmm_logs.zip)

**Comment by mlaggner** [comment]
what exactly did not get scraped? did not find any obvious errors in the logs..

**Comment by Zwanzig2** [comment]
My OS Windows 7 and TMM in Polish language.
Earlier, the country movie scrape in Polish - now English lanuage
example - Hiszpania ---  Spain, Francja --- France, Niemcy --- Germany et
![bez_tytulu_1](https://cloud.githubusercontent.com/assets/23637884/21663344/e2de6994-d2df-11e6-86aa-7297eed478b6.jpg)
c.

**Comment by Zwanzig2** [comment]
Ok it works :)
thank you very much
