### ISSUE TITLE
Movie Set graphics Removed

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#111]
[tmm_logs3.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/667043/tmm_logs3.zip)
[tmm_logs2.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/666537/tmm_logs2.zip)
![bez_tytulu_1](https://cloud.githubusercontent.com/assets/23637884/21638607/4342126e-d26c-11e6-8c83-d152ac8dd537.jpg)

Version: 2.9.1
Build: 2016-12-12 17:48
OS: Windows 7 6.1
JDK: 1.8.0_60 x86 Oracle Corporation

**What is the actual behaviour?**
Program removes graphics MovieSet

**Description**
- I set the path to the movies,
- loading information,
- I write graphic movieset and add description (example: Ace Ventura Collection),
- I change the name of the collection (example: Ace Ventura Kolekcja),
- Finished.
Then changed the name of the folder with movies or I move them and I set a new path to the movies in the program,
- I scan path movie,
and they are removed graphics movieset (movieset-fanart.jpg, movieset-poster.jpg) (deleted from the disk completely),
- movieset-logo.png, movieset-banner.jpg, movieset-clearart.png replace files logo.png, clearart.png (change the extension to .jpg)
- does not show ID movieset - in view Movie sets

**Comment by mlaggner** [comment]
there was a problem with keeping movieset-logo and movie logo separated (worked only for poster and fanart).
Should work in the next version (or nightly build tomorrow if you want to test it)

**Comment by Zwanzig2** [comment]
Hello
far nothing has changed. did not work
![bez_tytulu_1](https://cloud.githubusercontent.com/assets/23637884/21854265/6b831710-d81a-11e6-99a9-ad56d2bd3867.jpg)

**Comment by mlaggner** [comment]
do you run the nightly build?
because we did not have any release since mid december

**Comment by Zwanzig2** [comment]
Yes - last version
version=2.9.2-SNAPSHOT
build=nightly
date=2017-01-12 00\:02

**Comment by mlaggner** [comment]
could you please update to the latest build?
the movieset-* files should disappear from the list and should not being renamed with the movie

also a new update datasources should not bring these files back to the movie in the list (but should stay on the disk)

**Comment by Zwanzig2** [comment]
Hi
It looks like it works when it comes to movieset-banner, clearlogo, logo etc. :)
But deletes from disk movieset-poster and movieset-fanart. as I described earlier.

**Comment by mlaggner** [comment]
now I see your point.
The movieset-* artwork get deleted, when the movie gets disconnected from the movie set inside tmm (cleanup).
We won't keep movieset artwork inside the movie folder if the movie is not in a movieset.

When you move your movies around, you somehow break the connection to the movie set and this is the case tmm triggers the cleanup

**Comment by Zwanzig2** [comment]
I think just the opposite
Now all files are deleted movieset- *
Movies are still in collections, sometimes need to move folders to another location, and reload the Tiny Media Manger - and that's when files are removed movieset- * (!!! so I do not want !!!)
I want to make movies still have a graphics movieset. I do not change the information in the movies - only I move them to another location.

sorry for poor English, it can cause confusion

renamed movieset-* OK :)

**Comment by mlaggner** [comment]
your workflow works here for me..

do you delete the movie from tmm prior to moving? (this would break the connection!)

**Comment by Zwanzig2** [comment]
No, I no delete movies from TMM.
Deleting path of movies (Collections) of TMM, I move folder to another location (or changing the name of the root folder).
I set a new path for these movies in TMM and update data sources - and HERE removes graphics movieset- * , and removes TMDBset id in the view Movie Sets
I do not change in the .nfo - movies, and I still want to have in the collection
Maybe I did not write that - movieset artwork in the store each movie folders

P.S.
The first part of the query is OK - rename movieset graphics :)
so we leave - it works.

I'm sorry - I help myself translator :)
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/713896/tmm_logs.zip)

**Comment by mlaggner** [comment]
okay, if i get you right, you _remove_ the datasource from the settings, movie the movies to another location, _add_ this location to the movie datasources and update after that?

removing a datasource also removes all movies inside it from tmm -> breaking movie set connection..

btw: movie sets (and their set tmdb id) should never be dropped from tmm unless you delete the movieset

**Comment by Zwanzig2** [comment]
Ok 
- _"[remove the datasource from the settings, move the movies to another location, add this location to the movie datasources and update after that?]"_   **YES**
- _"[removing a datasource also removes all movies inside it from tmm -> breaking movie set connection.]"_  **YES**
- _"[movie sets (and their set tmdb id) should never be dropped from tmm unless you delete the movieset]"_
**I not removed movie sets**,
remove datasource does not delete graphics movieset- * and TMDb id,
**removes graphics** movieset- * and TMDb id **makes Update datasource**

Sample folder structure:
[Folder root.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/714760/Folder.root.txt)
I hope that clearly written :)

**Comment by mlaggner** [comment]
I've changed the cleanup logic that it is only triggered, when you manually remove the movie from the movie set;
If you remove the movie from tmm (DEL button or remove a data source) then there is no more cleanup!

the newest nightly should work as you desire

**Comment by Zwanzig2** [comment]
**Great, PERFECT.**  :1st_place_medal: 
**Thanks a lot**
