### ISSUE TITLE
Atmos and DTS:X logos do not display

### ISSUE THREAD

**Issue by jmulvaney1** [tinyMediaManager/tinyMediaManager#117]
__What TMM version are you using?__
2.9.1

__release, pre-release, nightly, or directly from GitHub/branch?__

__What is the actual behaviour?__
Dolby Atmos and DTS:X icons not showing (both HD Object Based codecs)

__What is the expected behaviour?__
Relevant logos appear in banner as opposed to their more inferior logos (eg, not just DTS or DD)

__Steps to reproduce:__
- first
- second
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

**Comment by jmulvaney1** [comment]
Note:  The scraper does detect these new codecs and the file rename uses correct tag.

**Comment by alexsisk** [comment]
I came onto Github to make this feature request myself, but I see it has already been discussed, I want to mention that I'd love to see this as well! 

By the way, when this is added, I believe that the icons for Dolby Atmos and DTS:X would be fine simply saying Atmos or DTS:X, even though they contain TrueHD and DTS-HD MA. (There is more detail on the Media Information tab anyway.)

**Comment by alexsisk** [comment]
I see that the above requests are set as a milestone for v3. That's great! Please note that I am simply throwing in my thoughts with this post - I am by no means demanding anything from anyone. Let me know if I need to add this as a different thread, but it really just expands on the existing topic.

I'm trying not to clutter with multiple threads for similar tag-related requests. 

**1)** For audio that is **only** Dolby TrueHD (no Atmos): in addition to displaying the tag, can we see _two TrueHD tags to differentiate between TrueHD 5.1 and 7.1?_

Example -  Star Trek: Into Darkness (2013), 7.1 Channel Dolby TrueHD, currently nothing shows as we already know.
![screen shot 2017-06-27 at 5 17 18 pm](https://user-images.githubusercontent.com/18446260/27610493-83092bd4-5b5c-11e7-93e0-7c11163e8209.png)

**2)** For audio that is **only** DTS-HD Master Audio (no DTS:X): can we see _two DTS-HD MA tags to differentiate between DTS-HD MA 5.1 and 7.1?_

Example -  Thor: The Dark World, 7.1 Channel DTS-HD Master Audio, currently shows only "DTS-HD"
![screen shot 2017-06-27 at 5 20 06 pm](https://user-images.githubusercontent.com/18446260/27610603-03012148-5b5d-11e7-8682-c08a3218d807.png)

in contrast to Lone Survivor, 5.1 Channel DTS-HD Master Audio, which shows the perfect audio tag:
![screen shot 2017-06-27 at 5 21 59 pm](https://user-images.githubusercontent.com/18446260/27610658-44601a4a-5b5d-11e7-9158-b2d880c8cc63.png)

**3)** And finally, here is what shows for the 4K version of the first John Wick film (in Dolby Atmos) - 4K tags may very well have already been mentioned, but I'm new to 4K and I've been focused mainly on audio. I am hoping that another v3 addition will be _the detection of 4K and display of a corresponding icon._
![screen shot 2017-06-27 at 5 06 52 pm](https://user-images.githubusercontent.com/18446260/27610824-dde8441c-5b5d-11e7-99f1-c462ac819450.png)

Let me know if I was unclear about anything...

**Comment by myron0815** [comment]
well, we have simply no icons for 4K, Atmos & DTS:X 😃 
Had some spare time, and tried myself as graphic designer (awww) and fixed some detections...
You might want to try latest nightly ON SOME TEST FILES - feedback welcome.

**Comment by mlaggner** [comment]
some icons added for 2.9.4
