### ISSUE TITLE
[Feature Request] Indication of the Bit Depth

### ISSUE THREAD

**Issue by ddiaboo** [tinyMediaManager/tinyMediaManager#118]
Hello,

Please add the indication if a media file is 8 or 10 Bit depth.

Example:

![image](https://cloud.githubusercontent.com/assets/24974397/21741517/76c0933e-d4d0-11e6-8b07-715bcfc94e23.png)

**Comment by alexsisk** [comment]
I don't know if there is a more official way to do this, but I second the suggestion!

**Comment by myron0815** [comment]
bitDepth has been added for all types of files where applicable.
But no ico yet, nor filtering for that...
You need to do a "force reload" of MediaInformation in next release....
