### ISSUE TITLE
Subtitle downloading issue

### ISSUE THREAD

**Issue by Fortiori** [tinyMediaManager/tinyMediaManager#119]
Version: 2.9.1
Build: 2016-12-12 17:48
OS: Windows 10 10.0
JDK: 1.8.0_111 x86 Oracle Corporation

__What is the actual behaviour?__
Batch downloading subtitles by selecting and using "Search and download subtitles" in context menu or toolbar (tried both)
Can find the sub and select it but does not download

__What is the expected behaviour?__

Entry in bottom bar showing subtitle download, srt file in folder

__Steps to reproduce:__

using "Search and download subtitles" in context menu or toolbar

__Additional__

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/705874/tmm_logs.zip)

**Comment by mlaggner** [comment]
selecting alone does not start the download. did you click on the icon in the leftmost column?
