### ISSUE TITLE
Deleted Titles in TMM wouldnt deleted on hdd

### ISSUE THREAD

**Issue by Sweetbeat** [tinyMediaManager/tinyMediaManager#120]
Version: 2.9.1
Build: 2016-12-12 17:48
OS: Windows 10 10.0
JDK: 1.8.0_111 amd64 Oracle Corporation

__What is the actual behaviour?__

The films i marked to delete (in database AND on HDD) wouldnt get deleted after closing and reopening TMM.
On hdd they are renamed as .deletedByTMM*********

__What is the expected behaviour?__

Normally i expect that the .deletedByTMM*** folders gonna deleted after closing TMM or restarting TMM

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/721252/tmm_logs.zip)

**Comment by mlaggner** [comment]
I was not able to reproduce the creation of these wrong backup folders (.deletedByTMM<movie name>).
Nevertheless I've included two possible fixes - could you try such a case with the nightly build?
http://nightly.tinymediamanager.org (please do not use the nightly build on productive data)

**Comment by Sweetbeat** [comment]
Hi manuel,

unfortunately i cant test it with the nightly :(
By trying to start the nightly one my system (Explorer.exe crashes -> windows 10 Enterprise) and i dont have another computer to test this :(

Regards

Kathrin

**Comment by Sweetbeat** [comment]
Hi Manuel,

so in managed to make it run and now youre right, it works fine (with the nightly)
The deleted folders (deleted over tmm) were now dropped into a folder deletedbyttm
After closing ttm this folder was deleted automatically

Thanks a lot

Kathrin
