### ISSUE TITLE
TMM isnt starting

### ISSUE THREAD

**Issue by ptube** [tinyMediaManager/tinyMediaManager#121]
__What TMM version are you using?__
newest pre-release, i tried also the standard release

__release, pre-release, nightly, or directly from GitHub/branch?__

__What is the actual behaviour?__
start cancel (Window: Java/TM) Platform SE binary funktioniert nicht mehr)

__What is the expected behaviour?__

__Steps to reproduce:__
- first
- second
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
Windows 10, Java Version 8 Update 121
[launcher.log.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/730920/launcher.log.txt)
[tmm.log.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/730921/tmm.log.txt)

**Comment by myron0815** [comment]
your are the 5th today, reporting that issue :|
There seems to be a problem on W10 with latest Java....
Please see http://forum.kodi.tv/showthread.php?tid=304981

**Comment by ptube** [comment]
oh I have a high place, so im proud!!! 📦 
I searched the forum today and I found nothing, so I created this thread
P.S.: installing old version of Java didnt fix the prob!

**Comment by mlaggner** [comment]
update in the forums: http://forum.kodi.tv/showthread.php?tid=304981&pid=2509292#pid2509292

short: a new NVIDIA driver causes crashes to java/tmm.
adding `-Dsun.java2d.d3d=false` to the file extra.txt in the tmm folder let tmm start again
