### ISSUE TITLE
Feature Request: Build/present a list of missing media from set/show/season

### ISSUE THREAD

**Issue by abreksa4** [tinyMediaManager/tinyMediaManager#122]
__What TMM version are you using?__
2.9.2 on Ubuntu 16.10

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the expected behaviour?__

It'd be great to get a list of "missing" media from a collection managed by TMM, thinking of the following use cases:
1. Get a list of movies missing from all or a specified set without needing to re-scrape the metadata
2. Get a list of seasons missing from a show
3. Get a list of episodes missing from a season

Not sure if this would be best represented as a list, but having programmatic access to such a list would be very helpful.

**Comment by Uatschitchun** [comment]
I would second this request!

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
