### ISSUE TITLE
Feature Request: Update tMM application from commandline

### ISSUE THREAD

**Issue by timothymowens** [tinyMediaManager/tinyMediaManager#124]
__What TMM version are you using?__
N/A

__release, pre-release, nightly, or directly from GitHub/branch?__
N/A

__What is the actual behaviour?__
Currently, you cannot update tinyMediaManager application from the commandline, you can only download and install updates via the GUI.

__What is the expected behaviour?__
I would like to be able to update the application from the commandline without having to use the GUI to download updates and update the application.

__Steps to reproduce:__
- N/A

__Additional__
Have you attached the Logfile from the day it happened? No
Your Operating system? Linux

**Comment by myron0815** [comment]
mhm.. yes.
We have the tinyMediaManagerUpdater.sh for that.
But i guess, there's the "silent" parameter missing...

So we might need to expand that skript... maybe $DISPLAY is a reliable source for a check?

Meanwhile, could you try the following command line?
`java -Dsilent -Djava.net.preferIPv4Stack=true -Dappbase=http://www.tinymediamanager.org/ -jar getdown.jar .`

**Comment by msdos** [comment]
I tried both `tinyMediaManagerUpdater.sh` and the command from https://github.com/tinyMediaManager/tinyMediaManager/issues/124#issuecomment-277284633 but nothing happens.

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
