### ISSUE TITLE
Feature Request: change location where (TMM) stores user data

### ISSUE THREAD

**Issue by fedeliallalinea** [tinyMediaManager/tinyMediaManager#126]
__What TMM version are you using?__
N/A

__release, pre-release, nightly, or directly from GitHub/branch?__
N/A

__What is the actual behaviour?__
User data, log and settings are added in application directory.

__What is the expected behaviour?__
I would like to be able to use program with different users, but install the program only once.
This it's also very useful  for create package for linux distributions.
I created a patch that change path of directories data, log and backup (missing launcher.log and cache directory) under:

- /home/username/.tmm for linux
- /Users/username/Library/Application Support/tmm for OSX
- C\Users\username\AppData\tmm for Windows

I don't know if it's proper but seems to work.
I also added a property (-Dsilent=noupdate) for skip the check updates.

__Steps to reproduce:__
N/A

__Additional__
[patch](https://drive.google.com/uc?export=download&id=0BwtkLrqFAWz7UlJzRjRxejNsUm8)

**Comment by myron0815** [comment]
Thx for the patch - will have a look.

On the other side, TMM is a portable app and everything is self contained.
Barely want to break that.
So you can easily work with different versions of TMM without any interference..

Have to think, if we can get the best out of both worlds...

**Comment by fedeliallalinea** [comment]
[Here](https://drive.google.com/uc?export=download&id=0BwtkLrqFAWz7WHhvNkVta3FKaGc) a new patch (incremental with other one), where I introduced new system property -Dsystemuserdata. If isn't set tmm work normal (all in program directory) otherwise if is set to yes uses default system user data directory .
Always missing launcher.log and cache directory (created by api-scraper?).

**Comment by simon04** [comment]
I'm packaging this application for Arch Linux, [tiny-media-manager](https://aur.archlinux.org/packages/tiny-media-manager/). Using a [custom launch script](https://aur.archlinux.org/cgit/aur.git/tree/tinymediamanager?h=tiny-media-manager) I ensure that the user data is written to `$HOME/.tiny-media-manager/` whereas the program lies in `/usr/share/tinyMediaManager/`.

Please consider adhering to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for Linux and similar standards for Windows and Mac OS. As a good example, you can inspect how JOSM handles the user data directories, see its [`PlatformHookUnixoid.java`](https://github.com/openstreetmap/josm/blob/76764049549c92b150af790de5f14535706178e4/src/org/openstreetmap/josm/tools/PlatformHookUnixoid.java#L354-L397) for instance.

**Comment by mlaggner** [comment]
I suppose this won't work since tmm also has a self update algorithm which writes to the install dir.
Having tmm in /usr/share will break that too.
Do you know how JDownloader has solved that?

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel

**Comment by mlaggner** [comment]
already works with v3 using a JVM parameter (does not support auto expansion):

```
-Dtmm.datafolder=/home/manuel/.tmmv3
```

**Comment by fedeliallalinea** [comment]
> already works with v3 using a JVM parameter (does not support auto expansion):
> 
> ```
> -Dtmm.datafolder=/home/manuel/.tmmv3
> ```

I see that in the source code and I create a package for gentoo [1].
Thank you very much for your great job.

[1] https://github.com/fedeliallalinea/gallifrey/tree/master/app-misc/tinymediamanager-bin

**Comment by mlaggner** [comment]
do you think that we should add a flag to disable upgrade lookup for managed versions?
e.g. that your starters in gentoo add a flag to tmm, that tmm does not offer the dialog to upgrade to a newer version

**Comment by mlaggner** [comment]
@fedeliallalinea just had a thought about this feature and it is not as stable as I want it;
there are some other subfolders in die tmm folder which should get moved to the user dir (/logs, /backup, /cache, ...)

do you want to join our discord channel to have a talk how we could implement this?

https://discord.gg/U5n4N4

**Comment by mlaggner** [comment]
added further improvements for this feature:

https://gitlab.com/tinyMediaManager/tinyMediaManager/wikis/Installation#datasettingscachebackup-locations

see https://gitlab.com/tinyMediaManager/tinyMediaManager/commit/717b586b85b778910670d33e0cafe9af3501f3ea

**Comment by fedeliallalinea** [comment]
Sorry for delay response but I was on holiday.
I'll try new feature when are added in a new tag.

> do you want to join our discord channel to have a talk how we could implement this?

For me is better via email my english is not fluent.

Thanks again for your good work

**Comment by mlaggner** [comment]
I've added one more jvm arg to help you:

```
tmm.noupdate=true
```

this will suppress the update check inside tmm, so package maintainers can completely manage versions of tmm in linux!
