### ISSUE TITLE
mvn package : Failure to find net.xeoh.jspf:jspf-core:jar:1.0.3 

### ISSUE THREAD

**Issue by bdouxx** [tinyMediaManager/tinyMediaManager#127]
__What TMM version are you using?__
tinyMediaManager-2.9.2

__release, pre-release, nightly, or directly from GitHub/branch?__
tag  tinyMediaManager-2.9.2 on github

__What is the actual behaviour?__
mvn package
[ERROR] Failed to execute goal on project tinyMediaManager: Could not resolve dependencies for project org.tinymediamanager:tinyMediaManager:jar:2.9.2: The following artifacts could not be resolved: net.xeoh.jspf:jspf-core:jar:1.0.3, org.tinymediamanager:JTattoo:jar:1.6.12.1, com.github.stephenc.java-iso-tools:loop-fs-iso-impl:jar:2.0.1-TMM: Failure to find net.xeoh.jspf:jspf-core:jar:1.0.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

__What is the expected behaviour?__
mvn package OK

__Steps to reproduce:__
- read readme.md
- git clone https://github.com/tinyMediaManager/tinyMediaManager.git
- git checkout tinyMediaManager-2.9.2
- mvn package

__Additional__
compilation with linux.

**Comment by myron0815** [comment]
Should be working exactly like that.
Have to try on a complete empty machine.

In TMM parent, we have an additional repository specified.
(For some non-mavenized dependencies)
It should be taken into account...

**Comment by mlaggner** [comment]
worked on my laptop where no extra maven settings have been done

**Comment by bdouxx** [comment]
After reading this pom : https://maven-repository.com/artifact/org.tinymediamanager/api-scraper/1.0/pom_effective
adding this to my pom resolve my problem.
```
  <repository>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>tinymediamanager-3rd-party</id>
      <name>tinyMediaManager 3rd-party releases</name>
      <url>https://repository-tinymediamanager.forge.cloudbees.com/release/</url>
    </repository>
```

**Comment by myron0815** [comment]
works here out-of-the-box too. (repository resolved from tmm-parent)
Dunno what does not work on your side, but if you have a solution, great :)

**Comment by bdouxx** [comment]
hi,

using a old version of maven (3.0.4-r1) resolve the problem, but failed with version 3.1.1 and 3.3.9

I think the problem come from this:
https://cwiki.apache.org/confluence/display/MAVEN/Maven+3.x+Compatibility+Notes#Maven3.xCompatibilityNotes-ResolutionfromLocalRepository

can you confirm that is ok for you with a recent maven version?

**Comment by myron0815** [comment]
Using 3.3.9 since ages - never had any problems.
Even @work with proxy and inhouse repository manager, the dependencies resolve correctly.
(The issue you mentioned does not count here - all in remote repository available)

as a test, you could try the following.
delete (rename) the already checked out folder from your maven storage (in userhome)
.m2/repository/org/tinymediamanager

check .m2/settings.xml for abandoned things like proxies, profiles et all
also check output of "mvn -version" (jdk/jre/maven versions et all)

try again a "mvn clean install -U -X" (X is for debug output - maybe we see something)
Try it always outside any IDE, since they also cache everything :p

[...]

**Comment by bdouxx** [comment]
thanks.

you solved my problem
