### ISSUE TITLE
TVShows whose title already contains a year designation get a 2nd year appended with renaming

### ISSUE THREAD

**Issue by glave** [tinyMediaManager/tinyMediaManager#128]
Version: 2.9.2
Build: 2017-01-27 15:08
OS: Windows 10 10.0
JDK: 1.8.0_91 amd64 Oracle Corporation

__What is the actual behaviour?__
If a tv show has the premier year already in the title, a 2nd year can get appended to the show folder when using "$N ($Y)" as the renaming scheme.
It appears this may not happen to every show with the year in the name.

__What is the expected behaviour?__
If the year is already in the scheme, the append shouldn't occur.

__Steps to reproduce:__
Examples:
American Gothic (2016)
The Americans (2013)
The Librarians (2014)
The Killing Season (2016)
The Flash (2014)
Scream Queens (2015)

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
yes, that's the _fault_ of tvdb - they offer show titles with a year in it.
simply correct the show name in tmm and everything is fine. We will not put any logic there to prevent false positives
