### ISSUE TITLE
Add a rename / cleanup that changes the source folder

### ISSUE THREAD

**Issue by glave** [tinyMediaManager/tinyMediaManager#129]
__Feature Request__

If you have two or more data sources, the ability to transition from one source to a chosen one during a Rename/Cleanup would be a nice feature.

__Example:__
Two data sources:
\\server\temp\movies
\\server\movies

Performing a Rename/Cleanup on:
\\server\temp\movies\empirestrikesback

Would result in:
\\server\movies\The Empire Strikes Back (1981)

**Comment by mlaggner** [comment]
we've discussed that several times:
a datasource is some sort of sandbox for us - we will not support moving files in/out of a datasource
