### ISSUE TITLE
PT109 not imported, other movie duplicated but wrong

### ISSUE THREAD

**Issue by bobreese** [tinyMediaManager/tinyMediaManager#132]
Version: 2.9.2
Build: 2017-01-27 15:08
OS: Windows Server 2012 R2 6.3
JDK: 1.8.0_101 amd64 Oracle Corporation

__What is the actual behaviour?__
I have a folder on my raid (F:movies done), within this folder are my movies in separate folders.
Every time I move the movie PT109 into the folder movies done and tell tiny media to rescan, PT109 does not show up in the list but some other movie is duplicated And 2 JPG files are placed in the root at movies done folder.

__What is the expected behaviour?__
The rescan of the root folder to show PT109

__Steps to reproduce:__
f:movies done
known good movies in separate folders moved into the root.
Scan for movies
Move PT109 folder into root
Rescan for new movies

__Additional__
Have you attached the logfile from the day it happened? 
No, the system give me the error "We don't support that file type.
I verified it was a ZIP file

![tiny](https://cloud.githubusercontent.com/assets/461610/23265605/bf2d7908-f9aa-11e6-93e5-83107f0a0961.jpg)

**Comment by myron0815** [comment]
dunno whats the issue on github is - it works for some users, but don't for others :|

Can you please send us the tmm.log via http://www.tinymediamanager.org/contact/ ?

**Comment by bobreese** [comment]
Done.Let me know if you do not get it

**Comment by myron0815** [comment]
This is a nice one :)
The folder "PT109" gets falsely detect as a stacking marker (pt = part), so we remove this.
Now we take the parent folder and parse this (the complete storage) and merge all NFOs together.

Please remove the movie from DB, and rename the folder to something different, like "PT boat 109".
Will be fixed for next version...

**Comment by bobreese** [comment]
Thank you!
