### ISSUE TITLE
Feature Request: Edit metadata of video files

### ISSUE THREAD

**Issue by viktorstrate** [tinyMediaManager/tinyMediaManager#133]
__What TMM version are you using?__
N/A

__release, pre-release, nightly, or directly from GitHub/branch?__
N/A

__What is the actual behaviour?__
When I press the _Rename/Cleanup selected movie(s)_ button, the movies get organized in folders and the actual movie files get renamed.
But if I open the file in VLC it shows the name of the movie, by its Title metatag, which is not set by tinyMediaManager

__What is the expected behaviour?__
To set the metadata automatically, when I press _Rename/Cleanup selected movie(s)_, and the ability to edit the metatags from within _Edit movie_.

__Steps to reproduce:__
- Open movie in tinyMediaManager
- Scrape the movie
- Press the _Rename/Cleanup selected movie(s)_ button
- Open the movie in VLC
- Go to _Tools_ -> _Media Information_ -> _General_

__Additional__
I am running Linux Arch

**Comment by mlaggner** [comment]
we do not/can not alter metatag for mp4/mkv files.
we only write appropriate NFO files for media center tools like Kodi/MediaPortal

**Comment by viktorstrate** [comment]
@mlaggner Okay, I just thought it would be a nice feature... Because I use it to organize my plex library, but plex uses the metadata title.
