### ISSUE TITLE
Feature Request: Handling Local Trailers and Extras

### ISSUE THREAD

**Issue by sanghviharshit** [tinyMediaManager/tinyMediaManager#135]
__What TMM version are you using?__
2.9.2

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
Doesn't identify properly named local trailers and extras files.

__What is the expected behaviour?__
Should be able to identify local trailers and extras

__Steps to reproduce:__
Keeping extras in the movies directory identifies them as separate movies

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?) - Mac

I am trying to follow this [media naming guide for extras withing movie folder from Plex](https://support.plex.tv/hc/en-us/articles/200220677-Local-Media-Assets-Movies)

Two options from Plex - 
Either __Inline__
``Movie/MovieName (Release Date)/Descriptive_Name-Extra_Type.ext``
Where ``-Extra_Type`` is one of:
- -behindthescenes
- -deleted
- -featurette
- -interview
- -scene
- -short
- -trailer

Or __Organized in Subdirectories__
``Movie/MovieName (Release Date)/Extra_Directory_Type/Descriptive_name.ext``

**Comment by myron0815** [comment]
hmm.. cannot reproduce.
It works for me, everything is detected as "Video Extra", and trailer.
Sample movie i used was this: https://github.com/tinyMediaManager/tinyMediaManager/tree/master/src/test/resources/testmovies/Plex/Plextras

Can you upload the logfile after you did an update?
Or a directory screenshot/listing of your names?
