### ISSUE TITLE
Right click / Context menu

### ISSUE THREAD

**Issue by theHalo** [tinyMediaManager/tinyMediaManager#136]
Version: 2.9.2
Build: 2017-01-27 15:08
OS: Mac OS X 10.12.3
JDK: 1.8.0_121 x86_64 Oracle Corporation

__What is the actual behaviour?__
When trying to do a normal right click (MacBook Trackpad) on a movie or show nothing happens.
When trying to use a right click by using a two-finger-tap the list scrolls up by about one entry.
Context menu is then opened for the next show/movie from the one I intended to work with.

__What is the expected behaviour?__
Open context menu of selected movie/show.

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/818304/tmm_logs.zip)

Screenshot 1: Selection ("Contact") right before right-clicking (two-finger-tap)
![tmm1](https://cloud.githubusercontent.com/assets/26176515/23574703/9282056c-0081-11e7-943c-15e40c53a49d.jpg)
Screenshot 2: Selection ("Corner Gas: The Movie" instead of "Contact") and context menu right after right-clicking (two-finger-tap)
![tmm2](https://cloud.githubusercontent.com/assets/26176515/23574704/92867174-0081-11e7-8ac7-20f712ffd51f.jpg)

**Comment by mlaggner** [comment]
just tried on my macbook an nor problem there.
be sure you don't move your mouse when double tapping -> if the mouse cursor is over another movie, this one gets selected (the same with right clicking on a mouse)

**Comment by theHalo** [comment]
Hi. 

Just to be clear: I don't use a mouse and this is only about right clicking not about double tapping. 
This is about the right-click/secondary click -> context menu for a list entry.
I use the secondary click function of the trackpad (tap with two fingers).
I don't move the cursor at all when clicking and i do not scroll.
This works with every other app on my MacBook but TMM scrolls and then clicks (without me scrolling).

The scrolling seems to be somehow associated with the two-finger-tap. When I disable the secondary-click in the Trackpad options the scrolling still happens.
This only happens since the last update (or maybe since the one before). Before that everything just worked fine.

By the way: Ctrl+click works without scrolling but is less practical.

I did a screencast where I try to right-click the episode "The Boss's Wife".
It looks as if I am scolling the list and then clicking with a short delay. But in fact i'm just (right-/secondary-)clicking.

[TMM3.mp4.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/819925/TMM3.mp4.zip)

**Comment by mlaggner** [comment]
as stated above, I have a macbook air too and everything work as it should with the latest release - this is no tmm issue...
