### ISSUE TITLE
Unable to sync to Trakt.tv

### ISSUE THREAD

**Issue by Simiil** [tinyMediaManager/tinyMediaManager#137]
__TMM Version:__
Both the current devel branch and current release:
Version 2.9.2
Build Date 2017-01-27

__What is the actual behaviour?__
On clicking `Synchronize selected TV Show(s)` the following error occurs:

```
2017-03-07 17:10:12,707 INFO  [tmmpool-unnamed-task-T14-G15] o.t.scraper.trakttv.TraktTv:647 - Adding 1 TvShows to Trakt.tv collection
2017-03-07 17:10:13,218 ERROR [tmmpool-unnamed-task-T14-G15] o.t.scraper.trakttv.TraktTv:659 - failed syncing trakt: Created
```
And the show is not added to the trakt library

__What is the expected behaviour?__

No error, and the show should be added correctly.

__Steps to reproduce:__

This Error only occurs on some shows, and so far i could not determine any pattern. The show definitely exists on trakt.tv, and i can successfully use the scraper to get metadata. Anyway, the steps to reproduce are:
* right click on a tv show
* select `Trakt.tv - synchronize selected tv show(s)`

Doing the same thing a few days later or with a new trakt pin sometimes works.

__Additional__
The operating system is a Linux with a `4.9.8-1-ARCH` kernel.

**Comment by myron0815** [comment]
Whoopsie.
It seems, we are missing some negotiations.
Thanks
