### ISSUE TITLE
Feature request: Scraping by Released/Aired-Date instead of Seasons

### ISSUE THREAD

**Issue by Simiil** [tinyMediaManager/tinyMediaManager#138]
__What TMM version are you using?__
Version 2.9.2 (Release)
Build Date 2017-01-27

__What is the actual behaviour?__

TV Shows that are named by Release/Aired Date instead of a Season-Episode naming scheme do not get scraped correctly. A good example would be a talk-show type show that does not have seasons in the traditional sense (The naming I tested was `YYYY-MM-DD - Title`)

__What is the expected behaviour?__

correct scraping into seasons/episodes as provided by the backend

__Steps to reproduce:__
- obtain some files of a show
- name them `YYYY-MM-DD - Title`
- start scraping

__Additional__
The operating system is a Linux with a `4.9.8-1-ARCH` kernel, No logfile is attached

**Comment by mlaggner** [comment]
the whole scraping logic is based on season/episode numbers rather than release dates.
Do you have any example? How does that show appear in the http://thetvdb.com/ database?

**Comment by myron0815** [comment]
we already detect filenames like "2017-03-15 episodetitle.avi"
Unfortunately, we do not scrape this yet...
Will put on todo list...

**Comment by Simiil** [comment]
The shows are generally listed as seasons and episodes in the TVDB (and other sources). The show i had this problem with is the late late show with craig ferguson: https://thetvdb.com/?tab=series&id=73387&lid=7

Scraping the episodes into the seasons and episodes format is the expected behaviour imho, expecially because the scraping sources provide this format... But currently its just one huge folder with `YYYY-MM-DD` formatted files
