### ISSUE TITLE
Subtitles do not download

### ISSUE THREAD

**Issue by Joostzilla** [tinyMediaManager/tinyMediaManager#140]
Version: 2.9.2
Build: 2017-01-27 15:08
OS: Mac OS X 10.12.3
JDK: 1.8.0_121 x86_64 Oracle Corporation

__What is the actual behaviour?__
Subtitles are never downloaded

__What is the expected behaviour?__
Subtitles are found and should be downloaded

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/844523/tmm_logs.zip)

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
you need to press the download button for each sub you want to download
