### ISSUE TITLE
Donate not work

### ISSUE THREAD

**Issue by sissiwup** [tinyMediaManager/tinyMediaManager#141]
Version: 2.9.2
Build: 2017-01-27 15:08
OS: Mac OS X 10.12.3
JDK: 1.8.0_111 x86_64 Oracle Corporation

__What is the actual behaviour?__

Donate not work

__What is the expected behaviour?__

Donate should work

__Steps to reproduce:__

Donate

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
what exactly does not work?
did you donate and cannot register; did the click on the donate button did not redirect you to paypal?

last night there was a maintenance downtime at our webhost - pressing the donate button works again now

**Comment by sissiwup** [comment]
Hallo,

The Donate Button Works. But in the App I Can Not Register.
It says it might take More Time.

Mit freundlichen Grüßen

Wolfgang Heine

**Comment by mlaggner** [comment]
please make sure you use the email address you used while donating.
we do not have any donation from "Wolfgang Heine"

**Comment by mlaggner** [comment]
nevermind - just saw email delivery did not work while our webhoster had a maintenance.
I just added your email address to the database
