### ISSUE TITLE
movie language in file name

### ISSUE THREAD

**Issue by seb-1204** [tinyMediaManager/tinyMediaManager#142]
__What TMM version are you using?__
2.9.2

__What is the actual behaviour?__

When adding `$L` to the movie renaming scheme on some movies this will add a long line of language e.g.  "English,_French,_Portuguese,_Spanish,_Thai" for the movie _Madagascar (2005)_

__What is the expected behaviour?__

I have movies in several language and want to add the language to the path. e.g. 
`[EN]/{Moviename, date}/{Moviefilename}{Movielanguage}` or ` $L/$T { - $U }($Y)`

The language selected for the movie should be added where '$L' is added. An option to use the short language would be good to EN instead of English

__Steps to reproduce:__

add the $L to the Folder name e.g. ` $L/$T { - $U }($Y)`

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

**Comment by mlaggner** [comment]
looks like you misunderstood the $L (spoken languages) field inside tinyMediaManager.
$L is NOT the language from the audio stream

you could use this field for your expected behaviour, but you may have to alter that field for all your movies..
