### ISSUE TITLE
Bug in TV show renaming when multiple episodes in one file

### ISSUE THREAD

**Issue by tibouh** [tinyMediaManager/tinyMediaManager#143]
__What TMM version are you using?__
2.9.3.1

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
A leading space is added with this configuration (here replaced by a dot):
![tinymediamanage-2](https://cloud.githubusercontent.com/assets/6676310/25015307/79c18a56-207b-11e7-8a65-79e69161490b.png)

__What is the expected behaviour?__
The renaming should give [4x01.4x02]

__Additional__
Here is the line of code I think is responsible:
![tinymediamanage](https://cloud.githubusercontent.com/assets/6676310/25015172/ff6fcc54-207a-11e7-8a1c-df44f2fc962e.png)
The space should only be added after if necessary.

**Comment by myron0815** [comment]
thx
