### ISSUE TITLE
MediaPlayer setting is not used always

### ISSUE THREAD

**Issue by voxspox** [tinyMediaManager/tinyMediaManager#144]
TMM 2.9.3.1 release

It seems that the MediaPlayer setting is used differently. On my Linux system media files like *.mkv are opened via the executable according to MediaPlayer setting but for DVD folders the VIDEO_TS.VOB file is opened via vlc instead.

**Comment by mlaggner** [comment]
we use xdg-open in linux which uses the systems preferred applications for opening files.
Looks like you have VLC as application for .vob files configured

**Comment by voxspox** [comment]
What is the purpose of the mediaPlayer setting? And why this setting is only used for certain file types?

**Comment by mlaggner** [comment]
according to the code every supported file type (from your settings) will be opened by the defined media player (if set).
Otherwise the systems default executable for that file type kicks in

**Comment by voxspox** [comment]
In my case both .mkv and .vob is in the list Settings / File Types / Video filetypes AND the associated default application of my system is VLC. But the launched application via TMM is different.

**Comment by voxspox** [comment]
#209 fixes this issue
