### ISSUE TITLE
popup windows in dual monitor setup

### ISSUE THREAD

**Issue by Ramma18** [tinyMediaManager/tinyMediaManager#145]
__What TMM version are you using?__
2.9.3.1

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
Moving main window to the second screen, tMN keeps for every popup window the resolution of the first screen.

__What is the expected behaviour?__
Adjust popup window sizes accoring to the screen were main window is open.

__Steps to reproduce:__
- first
Open tMN
- second
Move main window to a second monitor with different resolution
- third
Open any popup (About, Settings, double click on a title)

**Comment by mlaggner** [comment]
It's not a bug - it's a feature :) 
we save the location/size of every dialog, whenever you re-open it, that it looks the same way as before.
If you move it to another screen with another resolution, the information stored is from the "bigger" monitor.
You can try to delete the file data/tmm_ui.prop from your tmm installation folder (this will wipe all stored sizes/locations)
