### ISSUE TITLE
Movie rename after scrape broken

### ISSUE THREAD

**Issue by a-m-s** [tinyMediaManager/tinyMediaManager#147]
__What TMM version are you using?__

2.9.3.1

__release, pre-release, nightly, or directly from GitHub/branch?__

Release.

__What is the actual behaviour?__

The movie file is renamed and moved to a new directory, but the meta-data files are left behind. The progress bar takes a long time to "complete" the task, which suggests it's not happy.

__What is the expected behaviour?__

The movie file and all associated files should be renamed and moved together.

__Steps to reproduce:__
- Place a movie file (e.g. mp4) in the top level directory. Use a not-quite-right name.
- Click update.
- Select the newly-discovered movie
- Click "search & scrape", find the right title, and hit OK.
  - The movie and meta-data files are now all in the top directory, all matching the original name of the movie file.
- Click "rename/cleanup".
  - The movie file is moved to a subfolder, correctly. The meta-data files are not.

__Additional__

Logfile attached: [tmm.log.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/951267/tmm.log.txt)
OS is Linux.

**Comment by myron0815** [comment]
tried it, works for me.

What i can see in the logs, is the following:

```
copy file /run/user/1000/gvfs/sftp:host=nuc,user=ams/home/ams/Videos/KidsMovies/Dr Seuss The Lorax-fanart.jpg to /run/user/1000/gvfs/sftp:host=nuc,user=ams/home/ams/Videos/KidsMovies/The Lorax (2012)/fanart.jpg
try to copy file /run/user/1000/gvfs/sftp:host=nuc,user=ams/home/ams/Videos/KidsMovies/Dr Seuss The Lorax-fanart.jpg to /run/user/1000/gvfs/sftp:host=nuc,user=ams/home/ams/Videos/KidsMovies/The Lorax (2012)/fanart.jpg
rename did not work - sleep a while and try again...
[...]
Failed to rename file '/run/user/1000/gvfs/sftp:host=nuc,user=ams/home/ams/Videos/KidsMovies/Dr Seuss The Lorax-fanart.jpg to /run/user/1000/gvfs/sftp:host=nuc,user=ams/home/ams/Videos/KidsMovies/The Lorax (2012)/fanart.jpg
```

seems like access/mounting problems?
Files locked?

**Comment by a-m-s** [comment]
The files are on an SFTP mount, but there's nothing else remarkable there. The movie file itself is moved successfully.

If I click rename first (creating a folder with the old name), then scrape, then click rename again (renaming the directory and the movie file within), then all is fine. I guess the difference is that the metadata files don't have to be moved in that case?

Hmm, for the movie file it says "try to move", but the meta-data it says "try to copy". Moves seem successful, copies fail.

Is there some way to increase the log level and find out why it fails?

**Comment by myron0815** [comment]
weird.
Is this error easily reproducible on your side?
I could add some logs for testing...

FYI:
we do a copy, since we have possibly a M:N copy operation.
2 poster variants might result in 3 different ones (depends on your settings)

**Comment by a-m-s** [comment]
Sorry, I never got back to this one.

I can reproduce it every time with TMM, but not at all via manual copies.
