### ISSUE TITLE
Cant see/select the Metadata scraper in Setting-Movies

### ISSUE THREAD

**Issue by rampageX** [tinyMediaManager/tinyMediaManager#15]
__What TMM version are you using?__
tmm_2.7.3.1_77d213a_win

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
![text](http://imagizer.imageshack.us/a/img923/8247/fxIxTc.png)

__What is the expected behaviour?__
from official screenshot:

![text](http://imagizer.imageshack.us/a/img923/5204/Xy0Ynu.png)

__Steps to reproduce:__
- first change font size, not work;
- second
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
Windows 10 ent x64, Java 1.8, Donate user.

**Comment by myron0815** [comment]
ok, the offical screenshot is a bit outdated ;o)
Nevertheless, there should be all the scrapers listed - which is not the case here.

Please check, if you have a /plugins/ folder inside TMM <- there should be all the scrapers.

Would be nice to see the tmm.log after startup. Can you zip and attach it?

**Comment by rampageX** [comment]
My /plugins/ file list:

![text](http://imagizer.imageshack.us/a/img922/4237/k8C51E.png)

logs:
https://mega.nz/#!XRJUFTST!9wnrAP5cW7oGUHrcFVi52rNn_8tS4fXK4nq9dz7Dn6U

**Comment by rampageX** [comment]
Remove `google-analytics.com` from hosts blocker and remove proxy setting in tmm, still same :((

logs:

https://mega.nz/#!vIoUVIhQ!tfzEKetwVrD7QH9SA7_jsn8KXAQe8GW7tKTqYJ37Cn0

**Comment by myron0815** [comment]
proxy or hostblock has nothing to do with - just keep it :)

But i see, you have TMM inside a folder with "+" sign.
It seems, our plugin framework is not aware of this - try moving to some other folder

**Comment by rampageX** [comment]
@myron0815 
Thanks a lot! Move TMM out `+` folder do the trick!
