### ISSUE TITLE
[Feature Request] make list of media sources and editions extendable

### ISSUE THREAD

**Issue by mcm1957** [tinyMediaManager/tinyMediaManager#150]
__What TMM version are you using?__
2.9.3.1

Please add a possibility to 
      -) add additional values for media sources (like webHD, origDVD, ...)
      -) add additional values for editions (i.e. original, remastered, ...)
using i.e. a config Dialog or by editing some parameter file

**Comment by ProIcons** [comment]
Will be suggested. Thank you for your ideas.

**Comment by mlaggner** [comment]
is already done in V3
