### ISSUE TITLE
[feature request] cleanup files after media file has been deleted

### ISSUE THREAD

**Issue by jochen-01** [tinyMediaManager/tinyMediaManager#151]
__What TMM version are you using?__
2.9.3.1

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
If media files (.mp4, .ts, whatever) has been deleted all the other files (.jpg, .nfo ...) remains as orphans on disk.

__What is the expected behaviour?__
Please add a feature to remove these files if the associated media file has been deleted.

**Comment by mlaggner** [comment]
where did you delete these media files?
iirc if you delete them from inside tmm, all associated files will be deleted too

if you delete them externally, then tmm won't do anything - please delete them externally too!

**Comment by jochen-01** [comment]
I'm used to remove watched TV shows right from kodi GUI. But that removes just the video file (e.g. .mp4) and leaves back the other files added by tinyMediaManager.

**Comment by myron0815** [comment]
No, this is not TMMs job.
Better ask Kodi for a fix.

If you delete this from within TMM, we DO clean (moving to backup folder).
But we simple cannot delete "all folders without video files"...
