### ISSUE TITLE
feature request/future bug: TheTVDB v2 API

### ISSUE THREAD

**Issue by buck2202** [tinyMediaManager/tinyMediaManager#154]
TheTVDB XML API sometimes returns truncated responses which cause parse errors in the scraper. Example as of this posting:
`WARN  o.tinymediamanager.core.tvshow.tasks.TvShowEpisodeScrapeTask - Error getting metadata ExceptionType=MAPPING_FAILED, ResponseCode=0, URL=http://thetvdb.com/api/<API_KEY>/series/278518/all/en.xml, cause=The element type "RatingCount" must be terminated by the matching end-tag "</RatingCount>".`

happens when pulling a file that ends like this:
`<Episode>
  <id>6047301</id>
  <Combined_episodenumber>14</Combined_episodenumber>
  <Combined_season>4</Combined_season>
  <DVD_chapter></DVD_chapter>
  <DVD_discid></DVD_discid>
  <DVD_episodenumber></DVD_episodenumber>
  <DVD_season></DVD_season>
  <Director></Director>
  <EpImgFlag></EpImgFlag>
  <EpisodeName>Episode 103</EpisodeName>
  <EpisodeNumber>14</EpisodeNumber>
  <FirstAired>2017-06-04</FirstAired>
  <GuestStars></GuestStars>
  <IMDB_ID></IMDB_ID>
  <Language>en</Language>
  <Overview></Overview>
  <ProductionCode></ProductionCode>
  <Rating></Rating>
  <RatingCount>0</Rat`

There are some posts about this happening on their forums. One thread below says that this is an XML generation issue that requires a manual refresh on their end; they also encourage migration to their v2 JSON API which bypasses this issue. The XML API will be EOLed on 2017-10-01
https://forums.thetvdb.com/viewtopic.php?f=17&t=36909 (thread with response from thetvdb moderator)
https://forums.thetvdb.com/viewtopic.php?f=17&t=37586 (another instance of this issue, no official response)
http://thetvdb.com/wiki/index.php?title=Programmers_API (note about EOL)
https://api.thetvdb.com/swagger (new API doc)

Failures seem to be sporadic depending on the data-source state, but the forums indicate that they are linked to use of their soon-to-be-defunct XML API. Just wanted to bring it to your attention. Great project!

**Comment by LeLobster** [comment]
I'm encountering this too when trying to scrape episode metadata.

```
2017-05-29 04:25:56,600 DEBUG [tmmpool-unnamed-task-T17-G1951] org.tinymediamanager.scraper.http.Url:241 - getting http://thetvdb.com/api/<API_KEY>/series/76703/all/en.xml
2017-05-29 04:25:56,792 WARN  [tmmpool-unnamed-task-T17-G1951] o.t.c.t.tasks.TvShowEpisodeScrapeTask:139 - Error getting metadata ExceptionType=MAPPING_FAILED, ResponseCode=0, URL=http://thetvdb.com/api/<API_KEY>/series/76703/all/en.xml, cause=Element type "thumb_" must be followed by either attribute specifications, ">" or "/>".
```

**Comment by mlaggner** [comment]
well tvdb has some issues with v1 at the moment
more infos at http://forum.kodi.tv/showthread.php?tid=142723&pid=2592935#pid2592935

**Comment by mlaggner** [comment]
I already worked on implementing apiv2 but encountered a problem. Reported it, but 2 months no response from their devs..
So this has to wait just a bit longer

**Comment by buck2202** [comment]
Sorry to hear that, I think I see your comments in the API discussion thread over there? About language ID and easier access to artwork? It does looks like their devs have gone dark in the API forum.

I think they have to manually add you (maybe PM someone?), but they also have an issue tracker on trello (https://trello.com/b/ZeC1OCZ4/api-v2-tracker)...it also seems kind of dead. I found that link here (https://forums.thetvdb.com/viewtopic.php?f=17&t=29984)
