### ISSUE TITLE
TinyMediaManager is.. well.. Tiny.. 

### ISSUE THREAD

**Issue by seftonH** [tinyMediaManager/tinyMediaManager#156]
Trying to use this app on a surface pro 4  (res 2736x1824) and the app doesnt as per windows settings. 

Hence everything is too small to see and read.. Changing font size (massively) then just cuts off text as its now too large for the unscaled GUI sizes. 

Basically as we now have higher and higher resolution screens, TMM needs to account for much higher resolution. TV screens are routinely 4K now, try using TMM on a 4k resolution !!! 

TMM 2.9.3.1

Smapshot. 

__What is the actual behaviour?__

Text and graphics are too small to see.. 

__What is the expected behaviour?__

Thats text and graphics would scale to a screen size not pixel size.. 
__Steps to reproduce:__

Opening the app.

__Additional__
Have you attached the Logfile from the day it happened?
No happens always.. 

Your Operating system? (win/mac/linux? version?)

Win10..

**Comment by mlaggner** [comment]
to be honest - Java does a bad job on hidpi screens (except on OSX, where it works flawlessly).
On one hand we do not have hardware to test that and on the other hand we would need to re-develop the whole UI to respect also hidpi screens. 
This will be definitely on in our focus since we have much more urgent things to do.

btw: I run tmm on linux with 2560x1440 and everything looks good!?!

**Comment by seftonH** [comment]
Understood.. i appreciate its  niche use case, however I think its one that will be growing. 

Shame as I prefer the simpler solution of TMM over ember, but am forced that way on my surface.

**Comment by mlaggner** [comment]
maybe java 9 brings some built in enhancements for hidpi scaling (http://openjdk.java.net/jeps/263) like on OSX..

**Comment by mlaggner** [comment]
maybe you could create a file called `extra.txt` in the same folder as the tmm.jar is with the following content and restart tmm

```
-Dsun.java2d.dpiaware=true
```

**Comment by gaandu** [comment]
Dang, I have been going crazy trying to fix this. Thank god someone else also has this issue.

BTW, the extra.txt setting didnt fix the issue. 

Still tiny
![image](https://user-images.githubusercontent.com/8316526/29740291-b08d0c5c-8a18-11e7-8b95-3d3d9821598a.png)

**Comment by mlaggner** [comment]
we're still waiting for java 9 to be released before we can work on this issue
btw: kinda hard to work on an hardware issue without having the hardware to test :/

**Comment by seftonH** [comment]
For sure I can really appreciate how hard testing must be.

But higher res monitors are becoming so much more routine, that its a
problem which will only get worse.

**Comment by myron0815** [comment]
would you mind trying this?
https://superuser.com/a/1207925
Does this help?

(Only have access to an 4k screen in a few weeks...)

**Comment by seftonH** [comment]
That worked...

Or rather it didnt work when I changed the Java.exe but did when I made
this change to javaw and javaws

**Comment by seftonH** [comment]
That worked...

Or rather it didnt work when I changed the Java.exe but did when I made
this change to javaw and javaws.. I am unsure which or both are the one..

I have noticed some poor functioning now from auto starting videos in
facebook or other embeds.. Started exact same time some not sure related.

**Comment by ProIcons** [comment]
This will be addressed with the new Java Release. tinyMediaManager as a software and code, can't do anything to fix this for you at this moment.

**Comment by the-solipsist** [comment]
Just a note that JDK 9 has now been released, and has reached the "general availability" (i.e., final) milestone: http://openjdk.java.net/projects/jdk9/

**Comment by ProIcons** [comment]
tmm won't run on JDK9 yet. And Version 2.x* won't support jdk9. You will have to wait for v3 which will be available on a public beta soon.

**Comment by filipkemuel** [comment]
I had the same problem on a 4K display running Ubuntu 18.04 with OpenJDK 11. 
I solved the issue by setting GDK_SCALE=3 when running TMM
```
$ GDK_SCALE=3 ./tinyMediaManager.sh
```
