### ISSUE TITLE
automatic Subtitle download dont work

### ISSUE THREAD

**Issue by Draco105457** [tinyMediaManager/tinyMediaManager#157]
Version: 2.9.3.1
Build: 2017-04-04 17:09
OS: Mac OS X 10.12.5
JDK: 1.8.0_131 x86_64 Oracle Corporation

__What is the actual behaviour?__

if i want to download Subtitle automatic. The TinyMediaManager work but dont download anything.
If i do it Step by step (All file with "search and download from Internet"-Function) it works ... 

__What is the expected behaviour?__

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

[tmm_2.9.3.1_1db4ca3_mac.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1034410/tmm_2.9.3.1_1db4ca3_mac.zip)

**Comment by ProIcons** [comment]
You have attached the Application in a ZIP, rather than the log file its self. By the way the logfile is not even located on your package.

**Comment by Draco105457** [comment]
I attached the files what they are generate … but this makes no different …

Try it yourself .. 
First .. try to generate a Log file … the tinyMediaManager 2.9.3.1 don’t generate a Log file
Second … the generate for Subtitles don’t work automatic

You can see it in Video —> https://www.dropbox.com/s/xcnkifnlrbg28px/tinymediaManager.mp4?dl=0 <https://www.dropbox.com/s/xcnkifnlrbg28px/tinymediaManager.mp4?dl=0> 


Mit freundlichen Grüßen

Höllinger Marc-André
Salzburgerstrasse 26a
A-4020 Linz
+43 664 608888152
marc_hoellinger@icloud.com

**Comment by ProIcons** [comment]
I don't have a MacOS, to test it out, but in Linux, as Mac and Linux are both Unix based Operating Systems, there's a tmm.log located inside a Directory called "logs" on the application's folder.

I'm not sure where Mac stores the files, but you could open your terminal and try that:

```find / -name tmm.log```

If you find it attach it here.

**Comment by Draco105457** [comment]
In attachment you can find Log File … 
I have tested the late night Version … but there is the same 2 problems
 
Mit freundlichen Grüßen

Höllinger Marc-André
Salzburgerstrasse 26a
A-4020 Linz
+43 664 608888152
marc_hoellinger@icloud.com

**Comment by ProIcons** [comment]
As far of your issue, there are a few things i noticed.
First of all it seems that your movie file hash, doesn't match with any movie hash on the Subtitle Database, which means that you might find a Subtitle that will be out of sync with your movie.

In that case a subtitle won't be downloaded, to ensure the best experience you can get. 
Even if we search a movie by imdb id, it can return many results of different movie releases, which will definitely result to sync issues.  

Now the tolerance of matching alternatively imdb id, instead of a movie hash on the section of "Automatically Download Subtitles" is up to the main Developer of this project @mlaggner .

In any case there will be a suggestion patch to your issue. It's up to Manuel to decide.

**Comment by Draco105457** [comment]
Thanks for Help …
Please check the other problem …. That I can’t save any Log file … The Software don’t crate anything ….

Mit freundlichen Grüßen

Höllinger Marc-André
Salzburgerstrasse 26a
A-4020 Linz
+43 664 608888152
marc_hoellinger@icloud.com

> Am 05.06.2017 um 16:52 schrieb Nikolas Mavropoylos <notifications@github.com>:
> 
> As far of your issue, there are a few things i noticed.
> First of all it seems that your movie file hash, doesn't match with any movie hash on the Subtitle Database, which means that you might find a Subtitle that will be out of sync with your movie.
> 
> In that case a subtitle won't be downloaded, to ensure the best experience you can get.
> Even if we search a movie by imdb id, it can return many results of different movie releases, which will definitely result to sync issues.
> 
> Now the tolerance of matching alternatively imdb id, instead of a movie hash on the section of "Automatically Download Subtitles" is up to the main Developer of this project @mlaggner <https://github.com/mlaggner> .
> 
> In any case there will be a suggestion patch to your issue. It's up to Manuel to decide.
>

**Comment by mlaggner** [comment]
Well an automatic subtitle download only via IMDB id would result in false positives for movies where more editions are out (e.g. Lord of the Rings): you probably get the subtitle for another edition.

We may add an extra option in the settings for users which want activate this search

**Comment by ProIcons** [comment]
It's not only via IMDB id, As you noticed on the code, it is tolerating the imdb id method. With the highest user ranking. Which still can result with an out of sync subtitle

**Comment by beany31** [comment]
where can I find the subtitle downloads for TV Shows? works like a charm for movies...

**Comment by mlaggner** [comment]
at the same place where in movies: right click an episode and choose one of the subtitles actions

**Comment by beany31** [comment]
Thanks! Works perfectly
