### ISSUE TITLE
Feature Request Add Watched status column next to Subtitle Column In TV Shows

### ISSUE THREAD

**Issue by MrsAngelD** [tinyMediaManager/tinyMediaManager#159]
__What TMM version are you using?__
2.9.3.1

__release, pre-release, nightly, or directly from GitHub/branch?__

Not sure

__Your Operating system? (win/mac/linux? version?)__
Ubuntu 14.04

It would be nice to be able to see the watched/unwatched flag in a column next to where the info, artwork, and subtitle columns are in TV Shows. With a large library it's rather cumbersome to have to look through each movie/show/episode to see which is marked as watched/not watched.

Thank you for a great piece of software 👍

**Comment by mlaggner** [comment]
in the movie list there is already the watched in its own column

**Comment by MrsAngelD** [comment]
@mlaggner I was referring to tv shows, not movies, sorry I should have clarified.

**Comment by mlaggner** [comment]
the TV shows tree is not as flexible as the movie table.
I already have added the flag for version 3 (UI overhaul), but finalization will need more time.
meanwhile you could filter for watched/unwatched episodes?
