### ISSUE TITLE
Feature Request: Cast (Actor) Thumbnails for TV Shows

### ISSUE THREAD

**Issue by andrewtlong** [tinyMediaManager/tinyMediaManager#161]
__What TMM version are you using?__
2.9.3.1

Your Operating system? (win/mac/linux? version?)
Windows 10 Pro x64

Been using TMM for over a year now, and I love it. The only feature I wish it included would be the automatic downloading of cast (actor) thumbnails for TV shows. It works wonderfully for movies, but I have to manually create an ".actors" folder and download each thumbnail individually if I desire the same for TV shows, which can be time consuming.

**Comment by mlaggner** [comment]
has been done for v3
