### ISSUE TITLE
sup isn't recognized as a valid subtitle format

### ISSUE THREAD

**Issue by LeLobster** [tinyMediaManager/tinyMediaManager#162]
__What TMM version are you using?__
2.9.3.1

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
Subtitles in the .sup format are not recognized as subtitles by TMM.

__What is the expected behaviour?__
They should be.

__Steps to reproduce:__
Have 2 files.  
movie.mkv and movie.eng.sup  
Update the library with TMM

**Comment by myron0815** [comment]
will be added to our default list - thx.
Meanwhile, just add it for yourself - Settings>general>file types...

**Comment by mlaggner** [comment]
this fix will be in 2.9.4
