### ISSUE TITLE
Sort using multiple columns

### ISSUE THREAD

**Issue by dufferzafar** [tinyMediaManager/tinyMediaManager#163]
Using v2.9.3.1

TMM can only sort by a single column, but perhaps there should be a way to sort by multiple columns as well. So, we could first sort by year and for rows that have same year, we could sort by rating etc.

**Comment by mlaggner** [comment]
basically it would be possible, but this would break almost every interface for sorting we've implemented.
and since you can achieve almost the same result with a combination of filters and sorting, we won't use our limited time on this.

**Comment by dufferzafar** [comment]
@mlaggner Okay. Can you please explain how I'll be able to do this via filters?

**Comment by mlaggner** [comment]
To achieve almost the same result as sorting by year/rating, you can filter by the year you want to inspect and sort by rating afterwards
