### ISSUE TITLE
translations with mixed newline indicators

### ISSUE THREAD

**Issue by Gridluck** [tinyMediaManager/tinyMediaManager#164]
english translation strings for tmm contain not consistent and random newline indicators such as
\r\n or \n

all current 780+ strings need to be revirewed, and updated, so to contain only "\r\n" OR "\n" to indicate new line..

**Comment by mlaggner** [comment]
is there any problem here or is it just to be clean?

**Comment by Gridluck** [comment]
It's confusing and at times am not aware what to put when; also
why not dynamically align the text in a form vs hard coding new line
indicators all over? Some translations are longer than original and am not
sure where to place newline so to predict proper alignment

Thanks

**Comment by mlaggner** [comment]
I'll remove \r for v3 translations (since there will be much new translations if we switch th v3, the user have to check this too).
unfortunately swing cannot always know where to put linefeeds or not - this is why we (barely) put linefeeds in our literals to give it a hint
