### ISSUE TITLE
Rewrite/Cleanup nfo

### ISSUE THREAD

**Issue by Kiina** [tinyMediaManager/tinyMediaManager#166]
So I had some weird season stuff in some of my nfo and noticed it breaks emby. Created a new show and it isn't there so not sure if it's from tmm or some tool I used ages ago. I though easy fix, just choose "rewrite nfo for selected tv show" and I'm done. But it seems like this just rewrites the file as it currently is. There is no difference in the file with an before and after. Is this the intented behaviour? Is there any way to hard clean and rewrite your nfos without removing all of them first? 

Here's an example for the weird stuff in my nfo I wanted gone (maybe someone knows if this is from tmm or some other problem):

```
    <seasons xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <seasondetails>
            <season>0</season>
            <tvdb>626225</tvdb>
    </seasondetails>
        <seasondetails>
            <season>1</season>
            <tvdb>626226</tvdb>
    </seasondetails>
        <seasondetails>
            <season>999</season>
            <title>* All Seasons</title>
    </seasondetails>
  </seasons>
```

**Comment by myron0815** [comment]
What NFO file (name) is this?!?
Doesn't look like a TMM written one....

**Comment by Kiina** [comment]
It was part of my `tvshow.nfo`. I'm also kinda sure that that part was never written by tmm but there is no way to clean up an nfo with parts that are not from tmm

**Comment by myron0815** [comment]
hmm... yes, that might be :)
This is basically a feature:
We do not simply (over)write a new file; we just write the tags we know, so all unknown stay there.
Reason is, to not mistakenly overwrite needed/newer things from all other applications, which possibly touch the file... (think of a new Kodi version, writing additional tags)

But in your case, this is kinda suboptimal...
Guess, the only fix is to do a search & replace with regular expressions :| (never forget about backup first!)

**Comment by Kiina** [comment]
Yeah I understand why it doesn't do it on default but having the option would be nice

**Comment by mlaggner** [comment]
thanks for your idea - will be available in v3
