### ISSUE TITLE
New Movie Scan Behavior for Movies in Subdirectory

### ISSUE THREAD

**Issue by usableweb** [tinyMediaManager/tinyMediaManager#17]
Version: 2.7.3.1
Build: 2016-03-18 14:25
OS: Windows 7 6.1
JDK: 1.8.0_45 x86 Oracle Corporation

__What is the actual behaviour?__

A new movie scan of a drive which is organized:

M:/2015/Movie1/Movie1.mkv
M:/2015/Movie2/Movie2.mkv
.
.
M:/2015/MovieN/MovieN.mkv

Creates a single movie entry with all of the detected media files.  The movie entry is renamed (apparently randomly) after one of the detected movies.  The movie source is defined as M:\.  I have the 'allow multiple movies per folder' option unchecked.

__What is the expected behaviour?__

This used to work.  TMM used to correctly recurse all of the subdirs in the YYYY/Movie/ subdirectories, and create individual entries.

__Steps to reproduce:__

Above.

__Additional__
Have you attached the logfile from the day it happened?

I was unable to attach them to this report due to GitHub behavior I can't explain, but if you contact me at mark@the-howards.net, I would be happy to provide.

Thanks!

**Comment by mlaggner** [comment]
Do you have a video file inside the folder M:\2015 ?
Just did some tests at home and with having a video file in M:\2015 tmm detects M:\2015 as a movie directory and adds all subdirs/files to that movie

**Comment by usableweb** [comment]
No - that was the first thing I checked.  I will re-send logs associated 
with today's attempt with a text output of the 'dir' command 
before/after the scan.

**Comment by mlaggner** [comment]
Thanks for your logs and help. We have identified the problem and are working on a solution
