### ISSUE TITLE
Error refreshing list when add to viewed and viewed filter applied

### ISSUE THREAD

**Issue by andxet** [tinyMediaManager/tinyMediaManager#18]
Version: 2.7.3.1
Build: 2016-03-18 14:25
OS: Mac OS X 10.11.3
JDK: 1.8.0_51 x86_64 Oracle Corporation

**What is the actual behaviour?**
I usually use the "Not seen" filter to show only interesting episodes. When I set the "seen" flag to an episode, the view of the episodes list have a strange behaviour: the next episode come up to the viewed episode, the next position become blank. Sometimes it hide also not viewed episodes. It is possible to solve by toggle the filter then reactivate it.

**What is the expected behaviour?**
The expected behaviour is to hide the viewed episode.

**Steps to reproduce:**
In the TvSeries tab, add  filter "seen" and set it to "not seen". Only not seen episodes will be shown. Now select an episode, set the viewed flag.

**Additional**
Have you attached the logfile from the day it happened?
No, but I think it is easy to reproduce. If needed I will upload it.

**Comment by mlaggner** [comment]
I know that there are optical glitches in the tree when using filters.. Our implementation of a filtered JTree is not optimal. 
I already created a new implementation, but the changes are too heavy for v2 - this will be implemented in v3

**Comment by mlaggner** [comment]
have included that into the V3 branch
