### ISSUE TITLE
Report / Artwork Downloader / Start Program

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#183]
Hi
TMM Nightly 2.9.4 2017-08-04, laguage Polish, system Windows 7 64bit
1. Recently I have a problem with downloading graphics. Gets only fanart and actor photos (and not always), does not get posters, extrafanarts and extragraphics (logo etc.). I have set the download automatically. The poster can be downloaded manually but extragraphics does not search. (foto)
2. Function - Contact us / report a bug via GitHub - does not work. (foto).
3. Long running of the program (more than 1 min) - Every time the program starts, it appears - "upgrading database to new version". (foto)
Sorry - english - translator :)

![foto01](https://user-images.githubusercontent.com/23637884/29002703-b7d2f5aa-7aa8-11e7-95ec-a07cda698c8e.jpg)
![foto02](https://user-images.githubusercontent.com/23637884/29002707-cda805b4-7aa8-11e7-9c13-7edb1ef77121.jpg)
![foto03](https://user-images.githubusercontent.com/23637884/29002709-e1e83aee-7aa8-11e7-8ec9-e0a3526370dc.jpg)
![foto04](https://user-images.githubusercontent.com/23637884/29002710-e803459a-7aa8-11e7-988f-40e1db72b76a.jpg)

[tmm log.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/1203016/tmm.log.txt)

**Comment by ProIcons** [comment]
Please update your Java and try again.

**Comment by Zwanzig2** [comment]
It seems that it helped to get the graphics. (add 1.)
Did not help start the program (add 3.) - "upgrading database to new version" It takes about a minute.

**Comment by ProIcons** [comment]
It seems that Upgrading Database to new version issue occurs only on nightly builds please wait for the next release and you won't have this kind of issue.

**Comment by mlaggner** [comment]
yes, in the nightly build we have no release numbers - thus we do all database updates/migrations again and again..
just to ensure every run of the nightly build is "stable" ;)

**Comment by Zwanzig2** [comment]
OK :) great thanks
