### ISSUE TITLE
Feature Request: Define path where pictures and .nfo is stored

### ISSUE THREAD

**Issue by mxmehl** [tinyMediaManager/tinyMediaManager#185]
__What TMM version are you using?__

N/A

__release, pre-release, nightly, or directly from GitHub/branch?__

N/A

__What is the actual behaviour?__

TMM stores images and nfo files in the very same directory as the movie file. This makes folders with many TV show episodes extremely full.

__What is the expected behaviour?__

The user can define whether these files are stored in a subdirectory, e.g. ".moviedata". This would make the folders much cleaner for people who also browse their movies/shows in their file manager.

**Comment by mlaggner** [comment]
we had this feature request before, but since tinyMediaManager is designed to work FOR/WITH Kodi (and other media centers) where the nfo needs to be in the same folder, we won't change that

**Comment by mxmehl** [comment]
OK, I understand that. But what about the images, are these also important for Kodi? (I don't use Kodi)

**Comment by mlaggner** [comment]
yes, Kodi loads and displays them when showing the movie/episode
