### ISSUE TITLE
Newsfeed (RSS/Atom) for your blog

### ISSUE THREAD

**Issue by buhtz** [tinyMediaManager/tinyMediaManager#188]
It looks like that your Blog at http://www.tinymediamanager.org/blog/ doesn't offer a Newsfeed (RSS or Atom). Am I right?

**Correction**: There is a separate link in the bottom "Atom" http://www.tinymediamanager.org/atom.xml. This is working. But my Reader (Bamboo) doesn't recognize it by himself. Maybe there is missing metadata in your blog? Could this be improved? I don't know how other readers behave here. Not sure if this is up to you blog or to the reader. Usual my reader is very nice to recognize RSS/Atom-URLs by himself.

**Comment by myron0815** [comment]
You're right, these feeds are not well intregrated.
Will be changed....
Thx

**Comment by mlaggner** [comment]
thunderbird has no problems with this feed?

**Comment by mlaggner** [comment]
I've included the lines
```
<link rel="alternate" type="application/rss+xml" title="RSS" href=""{{ site.baseurl }}/feed.xml">
<link rel="alternate" type="application/atom+xml" title="Atom" href=""{{ site.baseurl }}/atom.xml">
```
into the header of the all pages - it should now work
