### ISSUE TITLE
Italian translation typo

### ISSUE THREAD

**Issue by bertof** [tinyMediaManager/tinyMediaManager#189]
Version: 2.9.3.1
Build: 2017-08-07 10:10
OS: Linux 4.12.4-1-ARCH
JDK: 1.8.0_144 amd64 Oracle Corporation

Selecting the root element a TV Serie from the tree menu (ex Game of Thrones in the tree of Game of Thrones) the label preview is misspelled in "Anteorima" instead of "Anteprima".

**Comment by ProIcons** [comment]
In Which Language

**Comment by bertof** [comment]
As from title it's in the italian locale. I already asked to join the translation team through transifex.com to apply the patch.

**Comment by myron0815** [comment]
added on Transifex :)
thx

**Comment by bertof** [comment]
Translation patch applied 😉
