### ISSUE TITLE
Rename TV shows episodes doesn't rename the episode number

### ISSUE THREAD

**Issue by estidiskyroamer** [tinyMediaManager/tinyMediaManager#19]
TMM v2.7.3.1
build date: 2016-03-18 14:25
Windows 10 64-bit version 1511
JDK: 1.8.0_45 x86 Oracle Corporation

__What is the actual behaviour?__
Every single episode has been scraped and nfo files updated. When I select rename/cleanup function, it moves all files to the correct directory according to titles and season, but incorrectly rename the files itself.
For the episodes title, I use this format: $N - $E - $T, but the $E (episode number) is not renamed.

__What is the expected behaviour?__
Using the format above, one example of episode title should be 'Flashpoint - 01 - Broken Peace.mp4', but instead it renames to 'Flashpoint - $E - Broken Peace.mp4'.

__Steps to reproduce:__
1. Scrape the new episodes.
2. Go to Settings > TV Shows > tab Renamer > change format of episode file name to $N - $E - $T.
3. Right click on the title of TV shows in TV shows list > rename/cleanup selected TV shows/episodes.

__Additional__
Have you attached the Logfile from the day it happened?

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/197864/tmm_logs.zip)

**Comment by mlaggner** [comment]
we've done a punch of renamer changes for TV show to make it more stable.
Could you try the latest nightly on test data? 
http://nightly.tinymediamanager.org
