### ISSUE TITLE
After marking and finding film sets no images will be loaded down for the film sets and film sets with 1 Film are shown (was not needed)

### ISSUE THREAD

**Issue by Sweetbeat** [tinyMediaManager/tinyMediaManager#190]
Version: 2.9.3.1
Build: 2017-04-04 17:09
OS: Windows 10 10.0
JDK: 1.8.0_121 amd64 Oracle Corporation

__What is the actual behaviour?__

Hi,
i wanted to update my film sets because of getting ne films which belongs to some sets.
After marking all my films and searching for film sets (right klicking-> finding film sets)
he founds a lot of new film sets.
But
1. he finds some film sets with only one film (i dont want that result, only need film sets with 2 or more films in my database
2. he didnt load the needed information (pictures and information concerning the film set)

__What is the expected behaviour?__

1. i want only shown film sets with 2 or more films in my database
filmsets with only 1 film in my database should not be shown as film set

2. after searching for film sets he directly should load down the pictures and the film set infos without doing that manually for each film set

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

**Comment by myron0815** [comment]
2) to download images or not, there is a setting. 
Check Settings->Movies->Pictures->Save MovieSet artwork in every movie directory.

1) there is no such setting (yet)
But what should happen, if you manually create a movie set, and scrape it? 
Should it not be filled? 
Should it be deleted again because you only have one movie? ...?
I'm not sure if we should do that...

**Comment by ProIcons** [comment]
I'm not sure hebis trying to create new film set. His goal is to display filmsets that contains greater or equal to 2. Which to i want to add here, every filmset contains 2.or more movies. So maybe he is trying to say to display the filmsets of the movies he has and if he only has a Single movie from a filmset to not display it.

**Comment by Sweetbeat** [comment]
@Prolcons yes that's correct. That was my Intention. 
When i mark all my Films in tmm and use the "find Film Sets" He creates Film Sets but i only want that He creates film sets with 2 or more Films in a Set (Films that i own) but not Film Sets from which i only got 1 Film. 
For example the Fast and the furious Set got normally 8 Films. If i only hot ONE of those in my  tmm data base He shouldnt create a Set out of this one Film. 

Hope that i now could explain it better

Regards

**Comment by ProIcons** [comment]
Could be paired with #191

**Comment by ProIcons** [comment]
Also about the pictures not getting downloaded, please update your java

**Comment by mlaggner** [comment]
@Sweetbeat well creating/finding movie sets is done movie per movie. We don't know if there will be another movie found for this set while analyzing the movie..
BUT I can offer you a filter, where movie sets with only one movie get hidden - would that be okay?

**Comment by Sweetbeat** [comment]
Hi,




Yes that would be great.




Regards sweetbeat 




Von: Manuel Laggner


Gesendet: Freitag, 8. September, 10:15


Betreff: Re: [tinyMediaManager/tinyMediaManager] After marking and finding film sets no images will be loaded down for the film sets and film sets with 1 Film are shown (was not needed) (#190)


An: tinyMediaManager/tinyMediaManager


Cc: Sweetbeat, Mention






@Sweetbeat well creating/finding movie sets is done movie per movie. We don't know if there will be another movie found for this set while analyzing the movie..


BUT I can offer you a filter, where movie sets with only one movie get hidden - would that be okay?
