### ISSUE TITLE
Feature Request - Search Movie Set

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#191]
Is it possible to add a filter by source or search panel to movie sets ? (In the panel movie sets).

**Comment by mlaggner** [comment]
I'll put this to the roadmap for v3 since in v2 filtering for movie sets is not planned or easy to implement

**Comment by Zwanzig2** [comment]
OK thank you for your answer.
When is any beta v3 planned?

**Comment by mlaggner** [comment]
in the near future

**Comment by Zwanzig2** [comment]
:)

**Comment by ProIcons** [comment]
v3 is currently on github, @Zwanzig2 . If you are aware of software engineering, and java, you can compile and run it. It's still under development.

**Comment by Zwanzig2** [comment]
Ok thank you, but unfortunately - I can not do it

**Comment by mlaggner** [comment]
a public alpha/beta will be release when all major things have been implemented (which should be soon)

**Comment by Zwanzig2** [comment]
OK thank you for the information.
By the way, is there a planned version 3 - actor editing (removal, reordering) with preview (Photo)?

**Comment by ProIcons** [comment]
Version 3 is already under development. This kind of feature is not planned, whatsoever all ideas are welcome and will be discussed

**Comment by Zwanzig2** [comment]
I think the topic can be closed THX

**Comment by mlaggner** [comment]
I will close it, when it is done ;)
