### ISSUE TITLE
add debug info about used mediainfolib and other third-party components

### ISSUE THREAD

**Issue by buhtz** [tinyMediaManager/tinyMediaManager#192]
Using TMM 2.94 snapshot from git.

It would be nice to have detailed informations in the debug output about used libs and their version. Currently I would need to know which version and files of mediainfo does my TMM uses. I need this for diagnostic on a maybe-bug.

**Comment by myron0815** [comment]
MediaInfo is the only third party lib we integrate.
You should at least see the version number in logfile after startup.
There are no plans to display such (and other) debug things in gui (yet)

**Comment by buhtz** [comment]
Ah sorry I haven't seen the line in the debug output.
