### ISSUE TITLE
2.94 snapshot offers a 2.93 update

### ISSUE THREAD

**Issue by buhtz** [tinyMediaManager/tinyMediaManager#193]
My 2.94 snapshot from git ofers me an update to version 2.93 when starting.

I think you see why this shouldn't happen.

**Comment by buhtz** [comment]
**git**!
I clone, I [build](https://github.com/tinyMediaManager/tinyMediaManager#how-to-build-tinymediamanager-yourself) and start from bash (on Debian GNU/Linux unstable).

**Comment by ProIcons** [comment]
The update system finds the latest release placed on the database, and when the latest version of update does not match with your version, offers you an update. Since this version is a snapshot version and not stable release, updater offers you update to the **latest stable version**

**Comment by myron0815** [comment]
ok, there is a flaw in our documentation.
the build process DOES build the correct version (the tmm.jar), but the distribution is always for release version (when not parametrized).
Either just copy the tmm.jar to your instance, or delete the "version" fil in root - should do the trick (for now)

we should change that ^^

**Comment by mlaggner** [comment]
I've put a hint in the README.md

**Comment by buhtz** [comment]
Please re-open the Issue.
This problem still occurse in the `v3` branch. v3-snapshot offers me an update to 2.9.4.

**Comment by ProIcons** [comment]
v3 is under development, and as we stated earlier updater offers you update to the latest stable version released.

**Comment by buhtz** [comment]
@mlaggner I am sorry for not being clear enough. I understand your explanation about the update check of TMM. And IMO this is the bug.

The current logic (if I understand you correct):
```
if ver_in_database != ver_running_instance:
    do_update()
```
But the logic should be a little bit more intelligent like this:
```
if ver_in_database > ver_running_instance:
    do_update()
```
