### ISSUE TITLE
Deactive "getting mediainfo"

### ISSUE THREAD

**Issue by buhtz** [tinyMediaManager/tinyMediaManager#194]
This is a wish for a future version.

I see no absolute need for the mediainfo's of an database entry. So shouldn't it be possible to deactive this ressource and time consuming part of the process?

**Comment by myron0815** [comment]
Depends.
We write such information into the generated NFOs, to give Kodi a kickstart on displaying correct icons...
And use that internally for different icons & filters too.
TMM will look quite empty without such information :p

On the other hand, this only runs once per file... so this shouldn't be a showstopper... (except when it doesn't finish / has bugs)

**Comment by ProIcons** [comment]
Beside the fact that it runs once per file, it also runs on separate thread dedicated only for mediainfo retrieval. This won't affect the other functions or the main functionality of the software, however you will see increased disk usage during this time. This library is written in pure C++, so running natively as fast as possible

**Comment by mlaggner** [comment]
I won't include that (disabling libmediainfo would cut half of the functionality of tmm and I cannot estimate the side effects)
