### ISSUE TITLE
No "okay" Button on Scrape & Select TV Show Dialog Box

### ISSUE THREAD

**Issue by nkb123** [tinyMediaManager/tinyMediaManager#196]
Version: 2.9.3.1
Build: 2017-04-04 17:09
OS: Windows 10 10.0
JDK: 1.8.0_144 amd64 Oracle Corporation

__What is the actual behaviour?__

When opening the "Scrape & search selected TV show(s)" dialog box, there should be an "accept" or "okay" button, usually placed in the bottom right corner. (There is usually also a cancel button.)

__What is the expected behaviour?__

No buttons appear in the bottom right corner of the dialog box and there is no option to "accept" or "update" scrape results. (I made sure the dialog box was enlarged as far as it would go.) As a result of this, the function is effectively broken.

__Steps to reproduce:__

In the TV Shows tab, right click on any TV show and click "Scrape & search selected TV show(s)."

__Additional__
Unable to provide logs. Logs aren't saving through the "Report a bug" option.

**Comment by ProIcons** [comment]
What screen resolution are you using. Under your installation's folder there's a tmm.log file, find it and attach it here

**Comment by nkb123** [comment]
1920 x 1080

**Comment by nkb123** [comment]
Had to change it to a txt file. GitHub doesn't seem to like .log files.
[tmm.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/1247437/tmm.txt)

**Comment by nkb123** [comment]
Figured it out. Sizing issue. Sorry to bother you.

**Comment by ProIcons** [comment]
By the logs the resolution you wete using was 1276x768
