### ISSUE TITLE
id TMDB not loaded

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#197]
Version: 2.9.4-SNAPSHOT - NIGHTLY
Build: 2017-08-24 23:02
OS: Windows 7 6.1
JDK: 1.8.0_144 x86 Oracle Corporation

I do not load my TMDB id in movies made earlier in Media Elch, I can not update the data. I previously updated some of the TMM videos and it was OK.
I can not also loaded log files in github. I can not create a log file from TMM

**Comment by ProIcons** [comment]
Rename tmm.log to .txt and you will be able to send the log here.

**Comment by Zwanzig2** [comment]
Hello
I am sending log and sample nfo
[tmm.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/1252321/tmm.txt)
[Celebrity [1998].txt](https://github.com/tinyMediaManager/tinyMediaManager/files/1252324/Celebrity.1998.txt)

**Comment by Zwanzig2** [comment]
Maybe something wrong and TMM never read exactly the nfo files created by Media Elch. I do now: I turn on the scrape metadata for the selected movie, I only select the year and start - shows the TMDB id. Maybe before I did the same :)

**Comment by ProIcons** [comment]
I can't understand what  part of the process is not working for you. 

All you have to do is to add a Media source folder that contains your movie's folder along with the nfo and then trigger an update to sources, your movie will get detected with the stored metadata from the nfo

**Comment by Zwanzig2** [comment]
Ok Film detects but does not read IdTMDB saved previously in nfo file (only nfo created by Media Elch).

**Comment by ProIcons** [comment]
Erase the film from TMM's database and update sources again. If the imdb entry is on the nfo file, it will be fetched.

**Comment by Zwanzig2** [comment]
This way, it does not load idTMDB. It only loads the imdb. But that does not matter.
"I do now: I turn on the scrape metadata for the selected movie, I only select the year and start - shows the TMDB id."
