### ISSUE TITLE
[Linux] Wrong permissions on downloaded /native/ libs.

### ISSUE THREAD

**Issue by Vallimar** [tinyMediaManager/tinyMediaManager#2]
I started using the nightly updater and kept seeing a problem with mediainfo issues. The files were being downloaded but the issue ended up being that they did not have the execute permission bit set so they were not able to be loaded. After manually using chmod, the errors went away and using the mediainfo function worked again.

There is also a discrepency with the 64bit reporting in that they are downloaded to /native/linux-amd64/  but the application says it is trying to load from /native/linux-x86-64/

Also, a request, would it be possible to have the application use the system libraries if they exist, perhaps with a config option on whether to prefer native over system? It would also be nice to print out the library version in the log when it loads it.

**Comment by mlaggner** [comment]
which linux distribution (and arch) do you have? I did not see any similar problem at home (using manjaro linux)

**Comment by Vallimar** [comment]
Using Fedora 23 x86_64. During my various tests, I had deleted the native folder a few times and each time it downloaded the files, they didn't have the execute bit set. I tried it again just now with the same result.

I'm not able to access the machine to launch the actual gui, but I expect it will give a load failure when lauching. I'll check in a few hours when I get home and update.

**Comment by Vallimar** [comment]
Tested, and fails to load the library on freshly download libzen and libmediainfo files.
>09:11:11.079 ERROR org.tinymediamanager.core.Settings - could not parse proxy port: null
>09:11:11.202 ERROR org.tinymediamanager.thirdparty.MediaInfo - Failed to load mediainfo
>java.lang.UnsatisfiedLinkError: Unable to load library 'mediainfo': Native library (linux-x86-64/libmediainfo.so) not found in resource path

Manually doing a chmod 755 on the files has it working as expected.

**Comment by mlaggner** [comment]
just checked it at home
a) we do not ship a linux-x86-64 folder inside native (only amd64; I did not even know that some linux distros name it as x86-64.. - will put in a patch for loading)
b) I definitely do not need the executable bits set for loading the native libs (644); please try to rename the native/linux-amd64 folder to native/linux-x86-64 and have a look if it is loading or not

**Comment by mlaggner** [comment]
ad loading native mediainfo:

try to create a file called `extra.txt` in the tmm dir with the following content:
`-Djna.nosys=false`

this _should_ force Java to load the native lib

**Comment by Vallimar** [comment]
This is already set in getdown.txt.  I tried adding it anwyays with the same result. The problem is the lack of executable bit. Fedora must be doing something different, or it could be some toggle in how I build my kernel, that prevents the library from loading if this isn't set. RedHat does apply a lot of extra security hardening bits to the packages they compile that nobody else does yet, so that could be the difference.

**Comment by Vallimar** [comment]
Maybe it's just something with my system. Did some more experiments and when using the bfd linker I can't get the libraries to load at all. When switching back to my default of the gold linker, they load, but only if executable.

Strange stuff, feel free to close since this only seems to be affecting me.

**Comment by Vallimar** [comment]
Definitely seems to be something wonky on my end. After trying lots of random things, it now works as expected. I don't get why it is acting so randomly, but will close this issue. Thanks for helping!

**Comment by mlaggner** [comment]
no need for closing it. I've just done some research and there are several sites on the net which suggest that the native libs should have the executable bit set (maybe that has something to do with SELinux or similar).
I will create a patch for it

**Comment by mlaggner** [comment]
a new build is up.
- libs under /native/linux-* will get +x at start up of tmm to make sure they are loadable
- unified loading paths of libmediainfo

during my tests I've recognized that jna loads the distribution installed mediainfo whenever the 
provided lib under /native/linux-* is not loadable (missing or incompatible).
We ship a mediainfo lib which has been built for ubuntu, but at my arch linux this was not loadable -  thus tmm loads the system library

**Comment by Vallimar** [comment]
I updated and did a bunch of testing and everything is working as you described, @mlaggner. Thanks for the updates and your patience!
