### ISSUE TITLE
[v3-branch]: Settings for subtitle

### ISSUE THREAD

**Issue by buhtz** [tinyMediaManager/tinyMediaManager#200]
Using the current `v3` branch from git today on Debian unstable.

When running TMM the first time it recoginze the system language and setup its GUI correct (to "German") without problems. But there are three aspects/problems.

_Settings -> Movie -> Subtitle -> Prefered Language_ is set to the first item in the drop-down-menu. It looks like arabia.

_Settings -> Movie_ There is no subtitle scraper in the list to select.

_Settings -> Series -> Subtitle -> Prefered Language_ is set to the 7th entrie "English".

**Comment by ProIcons** [comment]
The issue with the missing Subtitle Provider on Settings -> Movie -> Subtitle is confirmed.
