### ISSUE TITLE
[v3-branch]: genre filter should offer only existing genres

### ISSUE THREAD

**Issue by buhtz** [tinyMediaManager/tinyMediaManager#201]
I am using `v3` from git. The genre filter is great.
But it should only offer the genres that are realy existing in the database. Currently there are to much.

It is not only about an to big and confusing list of genres.

If the list would contain only the gernes that are really there it would be an extra information source. I would see at one view which genres are there. I could select the genres I don't want (e.g. "adventure") and edit the entires.

**Comment by mlaggner** [comment]
well, the list of genres is kinda fixed (except we allow additional custom genres in v3 now).
unlinke at tags we know at startup of tmm which genres exist and we display them in the list. observing all used genres (like tags) during runtime of tmm and alter the combobox if new genres are available would be an overkill here (and may have a bad influence in performance).
and on the other side: having all genres in the list shows you which genres exist and filtering for a genre which has no movies is a benefit in my eyes ;)

**Comment by buhtz** [comment]
> filtering for a genre which has no movies is a benefit in my eyes ;)

It's everytime interesting hearing about differnt use-cases.

In that case: The only way I see is to make this behaviour customizable. _Only display existing genres (yes/no)_

> observing all used genres (like tags) during runtime of tmm and alter the combobox
> if new genres are available would be an overkill here (and may have a bad influence
> in performance)

Of course I am absolutly not a Java developer. So maybe I miss some experience to value the needed ressources here. But I don't see performance problems. I am pretty sure you have kind of an Observer-Pattern implemented, or not? The combox is your Observer observing the scrapper (reading new movies), an open meta-data-dialog of a movie (where I can modify the genre).

If you don't see a benfit for TMM to have this feature I would recommend just to close this issue. What do you think?
