### ISSUE TITLE
[v3-branch]: bright theme

### ISSUE THREAD

**Issue by buhtz** [tinyMediaManager/tinyMediaManager#202]
The new `v3` looks great and offer nice new features which save a lot of time for me.

My wish would be that TMM offer a bright theme, too. I don't like the dark one.

**Comment by ProIcons** [comment]
Theming is not planned and probably won't be planned any time soon.

**Comment by mlaggner** [comment]
there is no bright theme planned at the moment - and there are no resources to do so
If you don't like it -> don't use it.

**Comment by buhtz** [comment]
There is no need to become unpolide @mlaggner . This was just a Feature Request.

**Comment by ProIcons** [comment]
GUI is hard-coded. While on a web page is easy to change the style with css etc, the case is different here. It needs a lot of work and it will throw back the timetable of v3

When we reach on a stable version of v3 we might consider it. Now it's out of the table

**Comment by Longri** [comment]
I work on it and send a PR soon!
![bildschirmfoto 2018-05-06 um 13 52 34](https://user-images.githubusercontent.com/2542295/39673039-5255ed9a-5135-11e8-84b6-d7fbb8dfe58c.png)
![bildschirmfoto 2018-05-06 um 13 53 27](https://user-images.githubusercontent.com/2542295/39673047-8b8d8da2-5135-11e8-9a85-9ed7f54ca374.png)

**Comment by mlaggner** [comment]
dark theme is already done in v3; v2 won't be touched for UI changes

**Comment by Longri** [comment]
With switching from light to dark?
And where is the source code of v3? I've checked out the Master and found nothing!

**Comment by mlaggner** [comment]
there is a v3 branch.
and the build is at http://v3-alpha.tinymediamanager.org

**Comment by Longri** [comment]
Thank you, I found it!
In my implementation, which I now reject again, I built in the theme switch so that does immediately  and not only with a new start. (Also when changing Font and FontSize)

Should I take this one in V3?

Which changes on theme of V3 are still planned? Not that double work is being done here.

**Comment by mlaggner** [comment]
could you create a new issue according the switch at runtime for font/theme?
lets discuss it there
