### ISSUE TITLE
"useTMDB" and movie titles

### ISSUE THREAD

**Issue by sp1ti** [tinyMediaManager/tinyMediaManager#205]
__What TMM version are you using?__
2.9.4

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
Scraping movies from IMDB without a translated title will net you the original title/transliteration from there. This is despite having "useTMDB" active.  
In the past this worked perfectly, now everything foreign and unpopular does not grab translations. Haven't been running the software in a while so I'm not sure when this changed.

Ex: http://www.imdb.com/title/tt1640144/ | https://www.themoviedb.org/movie/77696-le-masque-de-la-m-duse  
IMDB main = Le masque de la Méduse
TMDB original = Le Masque de la Méduse
TMDB translation = The Mask of Medusa

It only grabs "IMDB main".

__What is the expected behaviour?__
Either a fallback to use TMDBs translated title or both info from there (with "useTMDB").

__Steps to reproduce:__
Scrape any movie.

Logs:__
[tmm.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1272897/tmm.zip)

**Comment by ProIcons** [comment]
Please provide us your log file and we will check it shortly.

**Comment by sp1ti** [comment]
Logs attached.

**Comment by ProIcons** [comment]
I Downloaded and installed fresh the 2.9.4. 
After that i created a dummy folder named: "Le masque de la Méduse"

I scrapped it using IMDB Scraper with use TMDB Option, The result i got was the expected one, 
![Main](http://www.devian.gr/tmdb/test.PNG)
![Settings](http://www.devian.gr/tmdb/test2.PNG)

Since i can't reproduce your problem i would suggest you, to erase "scraper_imdb.conf" from your data folder, and then re enable the option "use tmdb". 

Whatsoever after looking yours logs, it seems that your software contacted with TMDb besides IMDb, and got the data. In any case if you think it can't be fixed, you can erase your "data" folder or backit up somewhere and start over. If you start over and you face more issues you can always come here for further help. 

Now i didn't quite understand what do you mean here:

> Not picking up but freshly scraped http://www.imdb.com/title/tt0055266/ | https://www.themoviedb.org/movie/107928-l-oro-di-roma
> persisting but an older scrape http://www.imdb.com/title/tt5111906/ | https://www.themoviedb.org/movie/444669-hinotama-bugy

**Comment by sp1ti** [comment]
Thanks for checking, should have done that first 😓 

Deleted the scraper config: "Medusa" ran fine now. Doing another one however does not change it once again.  
With a fresh install "Medusa" ran fine again, "L'oro di Roma" (http://www.imdb.com/title/tt0055266/ | https://www.themoviedb.org/movie/107928-l-oro-di-roma) not. 
(the two links were meant as additional examples but the "Magistrate" one isn't a good once since it has an EN aka on IMDB)

**Comment by ProIcons** [comment]
I've located the issue, whatsoever i would rather say is not a bug , but a feature. TMDb feature, is designed to work when plot is persistent. So if there's no plot, it won't get not even the title

https://github.com/tinyMediaManager/scraper-imdb/blob/master/src/main/java/org/tinymediamanager/scraper/imdb/ImdbMovieParser.java#L191

I will be adding a patch shortly but is up to the Project's founder to decide if he wants this operation to be changed.

**Comment by sp1ti** [comment]
Thanks for looking. I was browsing through not properly translated titles and found them all grabbing... looks like they all got a plot description meanwhile lol... At least I would know what to fix next time if it doesn't get implemented 😄

**Comment by ProIcons** [comment]
So there are movies that have a plot and you can't load tmdb data?

**Comment by sp1ti** [comment]
No, just all the movies I wanted to use to test this further were suddenly scraping 😄 . I did add a plot" to "L'oro di Roma" and it now also works today so it was definitly the`&& StringUtils.isNotBlank(tmdbMd.getPlot())` condition.

**Comment by ProIcons** [comment]
Works today... i haven't pushed any patch yet, and even if i had, it wouldn't be available to 2.9.4 version. It would be available on 2.9.4.1 version with many other hotfixes.
