### ISSUE TITLE
Feature request: TMDB & Adult movies

### ISSUE THREAD

**Issue by sp1ti** [tinyMediaManager/tinyMediaManager#206]
Unlike IMDB there is no "Adult" genre on TMDB but instead movies are set to "Adult: Yes". When scraping this doesn't get reflected in the NFO. There are also cases where the genre isn't present on IMDB (they're more strict) but it still gets flagged on TMDB. It would be great if the flag would result into the "Adult" genre being appended so that the information is present on Kodi, etc (in the scraper and when using the "useTmdb" flag).

Thanks for consideration.

**Comment by ProIcons** [comment]
The information on your request is very complicated, so i will try to break it down.

First of all you want on TMDb when there's an adult movie to be added as a genre.

After that you say that in some particular movies which are for adults, in IMDb there's nothing that indicating that, so you would like the information to be fetched from TMDb whether is for adults or not.

Is that correct?

**Comment by sp1ti** [comment]
I wanted to give some context in my request that is why it's so nested - sorry 😛 . Your take-away is correct.

- When only using the TMDB scraper add "Adult" if present in the response.
- When using "useTmdb" either include the "Adult" fallback as a feature or expand it to also scrape genres from TMDB instead of IMDB.

Ex. movie request
```
{
  "adult": true,
  "backdrop_path": "/8M3cEk8fGBxLLAA2e0famsMfOja.jpg",
  "belongs_to_collection": null,
  "budget": 0,
  "genres": [
    {
      "id": 27,
      "name": "Horror"
    },
    {
      "id": 18,
      "name": "Drama"
    }
  ],
  "homepage": "",
  "id": 30493,
  "imdb_id": "tt0165325",
  "original_language": "it",
  "original_title": "Immagini di un convento",
  "overview": "Locked behind the walls of a convent are an order of beautiful nuns whose vows force them to forget the pleasures of sexual contact. Crazed with lust and desire many of the nuns pleasure themselves and each other in fear of the Mother Superior. One night a wounded man is found on the grounds of the convent and is brought inside to be healed. He becomes the focus of the young nuns' desires as each one tries to visit this young man. But along with him has come the evil force of Satan. A local priest proceeds to exorcise the demon from within the holy building driving the nuns into a delirium of sexual madness.",
  "popularity": 0.001794,
  "poster_path": "/9l6Qqbj7qMCRURQxyuD2uiWFl6Z.jpg",
  "production_companies": [
    {
      "name": "Kristal Film",
      "id": 5052
    }
  ],
  "production_countries": [
    {
      "iso_3166_1": "IT",
      "name": "Italy"
    }
  ],
  "release_date": "1979-01-01",
  "revenue": 0,
  "runtime": 93,
  "spoken_languages": [
    {
      "iso_639_1": "it",
      "name": "Italiano"
    }
  ],
  "status": "Released",
  "tagline": "The Most Explicit Nunsploitation Film Ever Made",
  "title": "Images in a Convent",
  "video": false,
  "vote_average": 2.8,
  "vote_count": 4
}
```

**Comment by ProIcons** [comment]
I'm aware of TMDb's api. In fact i reworked the tmdb2-java by Uwetrottmann. Having said that, is not hard enhancement, whatsoever needs to be discussed with the project's founder. Thank you for your feedback.

**Comment by mlaggner** [comment]
creating an adult genre if the flag is set would be okay for us.
but overriding/influencing the genres by imdb via the tmdb scraper is not our goal. The source of the problem is that imdb has no correct meta data and we will not try to fix that

**Comment by myron0815** [comment]
added with https://github.com/tinyMediaManager/scraper-tmdb/commit/a654f1ddabf090667d2d0c084e4e1b8d794b25fb
