### ISSUE TITLE
relative path for data source

### ISSUE THREAD

**Issue by voxspox** [tinyMediaManager/tinyMediaManager#207]
__What TMM version are you using?__
2.9.4

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__

Not existing movies are not removed from database, p.ex. if a movie has moved to another folder.

It seems a relative filepath is resolved and stored in the database (movies.db). For example ../movies/good_movie is stored as /media/user/Drive/tmm/../movies/good_movie

__What is the expected behaviour?__

do not duplicate entries

__Steps to reproduce:__
- store movies and tmm on an external hard disk.
- start tmm from the disk and I have setup a relative path for the data source: Settings / Movies / Datasources / Source: ../movies
- move a movie to another folder
- button: update data sources

__Additional__
Your Operating system? (win/mac/linux? version?)
linux

**Comment by mlaggner** [comment]
don't use relative paths in the settings - it won't work for a reason!

**Comment by voxspox** [comment]
Could you tell us the reason?

Is it possible to use tmm as a "portable App"? i.e. install it on a external hard disk or flash drive.
