### ISSUE TITLE
file type checking seems to be case-sensitive

### ISSUE THREAD

**Issue by voxspox** [tinyMediaManager/tinyMediaManager#209]
__What TMM version are you using?__
2.9.4

I want to play DVDs with the player I have specified in the settings. But Globals.settings.getAllSupportedFileTypes().contains(fileType) in TmmUIHelper.openFile returns false.

Only after adding `.VOB` (beside `.vob`) to the "files types" my media player is used.

File type checking should be case insensitive.

**Comment by myron0815** [comment]
thx.
It worked most of the time, but some were missing...
