### ISSUE TITLE
command + delete to delete movies or tv shows from files

### ISSUE THREAD

**Issue by farhadarghavan** [tinyMediaManager/tinyMediaManager#21]
Version: 2.7.4
Build: 2016-04-01 19:01
OS: Mac OS X 10.11.4
JDK: 1.8.0_74 x86_64 Oracle Corporation

__What is the actual behaviour?__

Hi
i want use command + delete to delete movies or tv shows but only result is  remove these from list and database not file

__What is the expected behaviour?__

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
SHIFT + DELETE is already available for that function
