### ISSUE TITLE
Anidb scraper cannot work alone

### ISSUE THREAD

**Issue by utdrmac** [tinyMediaManager/tinyMediaManager#210]
__What TMM version are you using?__ 2.9.4
__What is the actual behaviour?__ Under 'Search and Scrape TV Show' -> Language -> Japanese is missing. I have many anime that are not showing up from anidb scraper, I'm assuming, because the language keeps defaulting to English. But there is no Japanese choice in this menu. Plenty of other languages, just no Japanese.

__What is the expected behaviour?__ For TMM to match the correct anime against animedb's list. My example anime is Cardcaptor Sakura; anidb=102, but TMM cannot seem to find this. Again, assuming because that title is Japanese-only.

__Steps to reproduce:__
Add an anime series to TMM.
Right-click -> Scrape -> Attempt to choose 'Japanese' as the language.

__Additional__
Your Operating system? macos sierra

**Comment by utdrmac** [comment]
Essentially any anime that only exists in anidb.net doesn't work in TMM. If it doesn't exist in tvdb, then it cannot be processed correctly by TMM.

**Comment by utdrmac** [comment]
thetvdb.com doesn't list, in this example, Cardcaptor Sakura for Japanese language. It has the English version, but those don't match up with the original Japanese ones.

**Comment by Kiina** [comment]
Yeah this is a problem for other missing languages too. There is no Korean/한국어 option. Try to add the following show:

https://www.thetvdb.com/?tab=series&id=332586&lid=32

It won't work without changing the tvdb entry to add an English title. Thought adding the language to the [api-scraper](https://github.com/tinyMediaManager/api-scraper/blob/master/src/main/java/org/tinymediamanager/scraper/entities/MediaLanguages.java#L54) would do the trick but seems like not. Or maybe there need to be more changes.

Also some minor inconsistency's. Most languages seem to be listed in their own language but Chinese is just "Chinese".

**Comment by ProIcons** [comment]
@utdrmac beside the missing language what exactly is the problem you are i can't understand this. Please give me an example. 

@Kiina about the Chinese language you are right. I've noticed it too and it will be fixed on next version.

If an entry is not localized in English then it would probably won't br scraped with an English title. A. Multi scraper which will scrape different metadata from different sources have been discussed and rejected several times. It doesn't mean that is out of the table, but certainly of it gets implemented it won't be implemented untill v3.

**Comment by utdrmac** [comment]
@ProIcons I gave an example above. I can provide others if necessary: Dragon Ball Super, Cowboy Bebop are two other series that I have that won't parse with aniDb alone. All of these do have english translated titles. anidb.net/perl-bin/animedb.pl?show=anime&aid=11210, http://anidb.net/perl-bin/animedb.pl?show=anime&aid=23

But when you attempt to scrape using aniDb, their matches are not found in the results box. Attempting to add manually, as exampled above, results in "cannot find" because there is no matching tvdb id.

Why can't the anidb scraper work independently and pull all the show, episode, metadata, etc directly from anidb? It's all there.

**Comment by ProIcons** [comment]
I will be checking this out

**Comment by myron0815** [comment]
Well, this is kinda historical :|
Our scraping always does a search first, and the ID is used to 100% identify the correct entry.
Unfortunately, only imdbid & tmdbid can be supplied to our search interface (yet).

This should be already fixed in v3; at least, we can make this work here....

**Comment by ProIcons** [comment]
Japanese and Korean languages added with: tinyMediaManager/api-scraper#5

**Comment by myron0815** [comment]
made some quickfixes to reactivate scraping. Did not work at all.
Now you should be able to search and scrape a complete show...

The standalone thingy will be done in v3... since this is a bigger change...

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
