### ISSUE TITLE
Does not update information from .nfo files

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#211]
Version: 2.9.4
Build: 2017-08-25 08:15
OS: Windows 7 6.1
JDK: 1.8.0_144 x86 Oracle Corporation

Hello
For some reason does not update information from .nfo files.
The information I changed in NIGHTLY is not shown in 2.9.4. Only after deleting movies from the base and reloading is OK.
Prior to updating the source, it loaded the correct information.
I also noticed some problems with downloading graphics. As I change the poster again, it only saves the file with the folder.jpg in the movie folder. (does not save <dynamic>-poster.jpg)
[tmm.log](https://github.com/tinyMediaManager/tinyMediaManager/files/1327679/tmm.log)

**Comment by ProIcons** [comment]
As far of your issue, that some of your graphics not getting downloaded, is not a tMM related issue. According to your log files, tMM had a hard time acquiring graphics due to a service error occurred in fanart.tv

As far of your first issue

I'm not sure what do you mean. Can you provide an example? What kind of information you changed in Nightly, what nightly edition were you using, and what information is not getting updated on 2.9.4.

**Comment by myron0815** [comment]
Found something in your logs, where we didn't catch the error correctly, letting the thread crash.
This might lead that no NFO or all subsequent functions are not executed...
let us know, if this solves your issue. thx.

**Comment by Zwanzig2** [comment]
Hello
When it comes to downloading graphics - it looks like it's OK.

As for updating movie info:
- I use two versions: TMM 2.9.4 and TMM last NIGHTLY from today, UI Language - Polish
- example - scrape movie info (TMM 2.9.4), then edit movie (TMM Nightly) - change plot, country (scrape Stany Zjednoczone Ameryki - change to USA)
I run TMM 2.9.4, I run Update data source and nothing changes in the edited video information (does not show changed information). To get them in 2.9.4 I have to remove the movie from the database and reload (then I see the changed information).
It looks like the information is saved in the NFO file correctly but TMM does not reload the information in the Update data source option (I thought it worked like - reloaded from the NFO file)
I may be wrong but it seems to me that it worked before.

**Comment by myron0815** [comment]
aparently it does not work in 2.9.4 - so any information of that version does not help here.
I cannot read from your text if this now works in nightly or not....?!

**Comment by Zwanzig2** [comment]
Ok reloading the graphics works fine :) - problem solved.

As for NFO files - thanks for the explanation, now I understand.

Thank you
