### ISSUE TITLE
Feature request: Ukrainian language for scrapping

### ISSUE THREAD

**Issue by Bzick-** [tinyMediaManager/tinyMediaManager#212]
Please add the Ukrainian language for TMDB and IMDB scrapping.

__What TMM version are you using?__
2.9.4

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__Additional__
Your Operating system? Mac 10.12

**Comment by ProIcons** [comment]
api-scraper@5

**Comment by Bzick-** [comment]
Awesome, thanks!
