### ISSUE TITLE
Plot is not scraped for movies from IMDB.

### ISSUE THREAD

**Issue by tritrek** [tinyMediaManager/tinyMediaManager#214]
Version: 2.9.4
Build: 2017-08-25 08:15
OS: Windows 7 6.1
JDK: 1.8.0_141 amd64 Oracle Corporation

__What is the actual behaviour?__
New movie is added, info is scraped (using IMDB scraper), everything is downloaded but the plot.

__What is the expected behaviour?__
...to have the plot as well

__Steps to reproduce:__
Add movie, scrape info, get angry.

__Additional__
Have you attached the logfile from the day it happened?
Oh yes, and that: I have tried to create it, chose location, hit SAVE, nothing happened. Tried different drives.

**Comment by ProIcons** [comment]
Issue already exists #208
