### ISSUE TITLE
Request - Animated posters automatically download if available

### ISSUE THREAD

**Issue by Sweetbeat** [tinyMediaManager/tinyMediaManager#215]
Right now, you need to do it manually for each film.
Would be great to do it automatically if wanted for the complete film database in tmm.
for example i got 500 films and i wanted for all films animate posters (fanarts) -> if they were available 
and
tmm sets them on position 1 so that kodi will show them 

will it be possible to set that on requests???

regards Kathrin

**Comment by myron0815** [comment]
Hi,
we might add some checkbox to settings...

As workaround:
Disable all picture plugins except the animated one.... and scrape without manual picture choosing ;)

**Comment by Sweetbeat** [comment]
well yes that would be great if you can implement this in a future version ..
that with the new scrape i will try...

Do i first need to delete all the existing images from the films or isnt that necessary?

**Comment by myron0815** [comment]
nah, not necessary.
We'll overwrite everything on scrape...

**Comment by Sweetbeat** [comment]
great.,.. thanks a lot for the fast and wonderful help :)

Regards
Kathrin

**Comment by Sweetbeat** [comment]
well ive tested it
but.. tmm doesnt add gif files...
when i select all films -> and click on "download all missing images" nothing happened (ive only mark Animatedposters 1.0 in the settings for the images under films
but for example world war z found gifs for poster and fanart if i do it manually (going directly in the film details and click on the image -> then he searches for an animated image and found it)(

**Comment by myron0815** [comment]
Have to check. 
It might be that we forgot the GIF workaround in this case :p

But: are the images really missing?
You said, you don't want to remove it first... so if there's already a poster, the "missing images" will not add anything...

**Comment by Sweetbeat** [comment]
well ive made the scraping a long time ago.. so tmmm found a lot of "normal" Posters..

therefore i asked if i need to delete the "normal" posters and images so that the animated ones would be shown.

1. now ive unchecked everything but the animatedposters 1.0 
2. ive marked 600 films (a lot of those must have animated posters-> ive checked it in internet and scraped then for test manually -> after found them, i deleted them manually in the film directory)
3.. i let tmm scrape them again automatically uncheck everything but the artwork)
4. after that i check if there were some gif files found -> windows explorer searching the film folders for *.gif

no hits

**Comment by Sweetbeat** [comment]
concrete film_
Kill bill Vol. 2
double click on film -> on the poster... -> tmm found an animated poster

i abort this
then i test it woth automatical scrape take the best hit (uncheck all but the artset)
nothing found..
So i prove that there exists an animated poster but tmm didnt find it with the automatical scrape way

**Comment by myron0815** [comment]
Puh - now you got me :)

please try following version:
https://tinymediamanager.ci.cloudbees.com/job/scraper-animated/ws/target/scraper-animated-1.1-SNAPSHOT.jar
download, rename, and overwrite in /plugins/ folder
will be in next release (no ETA yet)

Thanx for reporting - seems we need more testers :D

**Comment by Sweetbeat** [comment]
I like it to help a little bit in my Limits.
If you like und would test again if you are in need of.


Regards Kathrin

**Comment by ProIcons** [comment]
Thank you for your feedback. Everyone is more than welcome to help us in this effort to provide a free bug-free Media Manager for everyone. What you can do to assist us is downloading whenever you can the latest nightly build, and try it out. Nightly build as name suggests every day is different. On every bug you come across just come here open an issue, and we will be fixing that as soon as we can. [Nightly Builds](http://www.tinymediamanager.org/download/all-downloads#nightly-builds)
