### ISSUE TITLE
Failed to rename (but only for some files/directories)

### ISSUE THREAD

**Issue by dempers** [tinyMediaManager/tinyMediaManager#217]
Version: 2.9.5
Build: 2017-10-05 19:26
OS: Mac OS X 10.13
JDK: 1.8.0_141 x86_64 Oracle Corporation

__What is the actual behaviour?__
Some files/folders are not renaming (Failed to rename error) whereas others work as before the latest version

__What is the expected behaviour?__
Rename should work as usual

__Steps to reproduce:__
Right-click movie
Select Search & Scrape
Select correct Movie
Right-click movie
Select Clean up
Error occurs

__Additional__
Have you attached the logfile from the day it happened?
Yes
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1385081/tmm_logs.zip)

**Comment by dempers** [comment]
Yep that’s the problem. But it works just fine with some files and folders. It’s very inconsistent. Any ideas?

**Comment by myron0815** [comment]
Does it work right after restarting TMM?
The files might still be locked or something....

**Comment by dempers** [comment]
No, tried that. Also restarted the SAN (it’s a synology). Weirdly, it works for 80% of the files.

**Comment by ProIcons** [comment]
Renaming the folder manually to the very same. Name tmm was about to rename it, works?

**Comment by dempers** [comment]
Yep, that works just fine.

**Comment by ProIcons** [comment]
Is tmm running from the same user, that you manually renamed the folder?

**Comment by ProIcons** [comment]
Synology is using 2 filesystems, The ext4 and Btrfs. Make sure you are using ext4.
