### ISSUE TITLE
Rating: select source

### ISSUE THREAD

**Issue by voidzero** [tinyMediaManager/tinyMediaManager#218]
Greetings,

For TV series, and perhaps movies, I'd like to request the possibility to select a different source for ratings. In particular, I'd like the metadata to contain the ratings from Trakt. The reason is that the current ratings are pulled from somewhere (I'm not sure where?) that has just a few votes. For example: Fear The Walking Dead, Season 3, episode 16 has 4 votes from wherever the ratings are pulled now. But Trakt already has 693 votes. I think this is a far better representation.

So perhaps a user can select the source in the options. Where are they pulled from now?

**Comment by mlaggner** [comment]
until now, the ratings are scraped together with all other fields by the chosen metadata provider (scraper).
imho you could rescrape the episodes, only fetching ratings (untick all other options in the scraping window)

**Comment by tanrak** [comment]
> 
> 
> until now, the ratings are scraped together with all other fields by the chosen metadata provider (scraper).
> imho you could rescrape the episodes, only fetching ratings (untick all other options in the scraping window)

This does not realy work. First i make a full scrape from tvdb and then i scrape only the ratings from trakt.
If i tick only "rating" then only the tv show rating is updated but not the episodes rating. If i tick "rating" and "scrape season & episode data" (all others are untick) then all all entries at the episodes are overwritten. What am I doing wrong?

**Comment by mlaggner** [comment]
thanks for that hint - is now fixed in v3
