### ISSUE TITLE
Wiki: added info for people who get a blank window on startup

### ISSUE THREAD

**Issue by voidzero** [tinyMediaManager/tinyMediaManager#219]
I have added a section for this on the Installation page:

https://github.com/tinyMediaManager/tinyMediaManager/wiki/Installation#blank-window

And I added a link to it on the FAQ page.

Hope you like it. :smile:

**Comment by voidzero** [comment]
I've also fixed a markup issue with the FAQ. See the revision list for details.

**Comment by mlaggner** [comment]
Thanks!
