### ISSUE TITLE
The 'Search Episode' window that opens from the 'Scrape Episode metadata' window does not show the scroll bar like it used to.

### ISSUE THREAD

**Issue by darrennie** [tinyMediaManager/tinyMediaManager#22]
__What TMM version are you using?__
Version 2.7.4

__What is the actual behaviour?__
The 'Search Episode' window that opens from the 'Scrape Episode metadata' window does not show the scroll bar like it used to, the window must be manually resized before the scroll bar appears and has to be resized every time this function is needed. 

__What is the expected behaviour?__
On earlier versions (pre v2.7 if I remember correctly) when the window opened, the scroll bar and it's blue thumb were visible if needed, meaning if the amount of episodes did not fit in the window, the scroll bar would be available on the left of the panel (centre of main window).

__Steps to reproduce:__
1. After opening tmm, Select the 'TV Shows' tab on the left of screen.
2. Click on the + to open TV Show to select Season.
3. Click on the new + next to the Season you want opened.
4. Double Click on the Episode you want to edit, you may also Right Click then select 'Edit Selected TV Shows / Episodes'.
5. At the bottom of the 'Scrape Episode Metadata' window, Click the 'Search Episode' button which will open the 'Choose an Episode' window, which has the scroll bar problem.
.
__Additional__
Have you attached the Logfile from the day it happened?
Yes. logs.zip containing 
logs/tmm.log
launcher.log

Your Operating system? (win/mac/linux? version?)
OS X 10.8.5

**Comment by mlaggner** [comment]
the issue will be fixed in the next version.

**Comment by darrennie** [comment]
Most appreciated, thanks.
