### ISSUE TITLE
Feature Request: Needs an option/argument/switch to display DEBUG data when using the commandline version, not display this data by default.

### ISSUE THREAD

**Issue by timothymowens** [tinyMediaManager/tinyMediaManager#220]
__What TMM version are you using?__
2.95

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
Debugging information displays when using the commandline tool.

__What is the expected behaviour?__
This DEBUG information should only be displayed if a commandline option/argument is used, not by default.  If there's a way to hide this information currently, it's not in the documentation or FAQ that I have found (I could be wrong or just blind to this).  But I would like to see this tool only show the INFO, WARNING and ERROR data and not the DEBUG data by default and only show the DEBUG data if the tool is run with certain flags (to you know, debug an issue).

__Steps to reproduce:__
Run the commandline tool and see the output, example of the command I'm running:

`$ tinyMediaManagerCMD.sh -updateTv -scrapeNew -renameNew`

__Additional__
Have you attached the Logfile from the day it happened?
No, not needed.

Your Operating system? (win/mac/linux? version?)
Ubuntu 16.04.03 - Linux 4.10.0-37-generic

**Comment by ProIcons** [comment]
Please attach your log file to see the verbosity of the debugging on log file.

**Comment by timothymowens** [comment]
I would, but it would contain some things (names of files/content and quantity of content) that I don't want attached to my user id publicly, which is why I provided an example command.  I'm using the release build, no modifications, on Ubuntu 16.04 LTS.  You should see the same verbosity I'm seeing.  There should be flags to show or hide or manipulate the verbosity.  If these flags exist already, the documentation should be updated to show these options.

Bottomline, after executing the command I displayed in the OP, I get 5000 lines of output when only 2 files were added/scraped/updated/renamed.  As a user, I don't need to see the 4800 lines of DEBUG data, only the INFO, WARN, or ERROR data.  If I want to see the DEBUG data, then there should be a flag to show such data.

**Comment by myron0815** [comment]
well, can't you just add a ` | grep -v "[DEBUG]"` or something like?

We had already such an option a few years ago.
But since we mostly received logs without turned on debug, we decided to remove it...
