### ISSUE TITLE
My Scraper tmdb.org doesn't work anymore ..

### ISSUE THREAD

**Issue by Anakim** [tinyMediaManager/tinyMediaManager#221]
__What TMM version are you using?__
2.9.5

__release, pre-release, nightly, or directly from GitHub/branch?__

__What is the actual behaviour?__
Hi,
after a new installation on my Linux System i want to download with the tmdb scrap my movies. But it doesn't work anyomore. TMM says "nothing found" .. i do it on severel movies. the other scraper .. the same. 

i check my installation properties .. Java .. right version 8, Whats wrong ?

can someone help me ?

__What is the expected behaviour?__

__Steps to reproduce:__
- first
- second
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

**Comment by ProIcons** [comment]
Please provide us your log file,

**Comment by sanghviharshit** [comment]
Same for me, it looks like it's down today. It was working for me before. I tried to update, but I got an error message saying the Host is down

**Comment by ProIcons** [comment]
TMM's TMDb Scraper is working as intended. Are you using Kodi's TMDb Scraper?

**Comment by Anakim** [comment]
Hy
my logfile. 

I have a Mac by the way and it works from the beginning. Same Version. 
@ProIcons .. and yes i have Kodi TMDB Scraper and works .. 
it must be at the Installation on my Linux Mint

Thx

[tiny.log](https://github.com/tinyMediaManager/tinyMediaManager/files/1417061/tiny.log)

**Comment by mlaggner** [comment]
which java is installed by linux mint? (oracle or openjdk? which version?)
is the logs I see that there are problems creating a https connection - could be an outdated java version or missing certificates (iirc a fedora user had this once)

**Comment by ProIcons** [comment]
TLS Exception suggests outdated java version.

**Comment by Anakim** [comment]
@mlaggner 
i think its 1.8.0
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr4fp1-20170215_01(SR4 FP1))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20170209_336038 (JIT enabled, AOT enabled)
J9VM - R28_20170209_0201_B336038
JIT  - tr.r14.java.green_20170125_131456
GC   - R28_20170209_0201_B336038_CMPRSS
J9CL - 20170209_336038)
JCL - 20170215_01 based on Oracle jdk8u121-b13

**Comment by ProIcons** [comment]
Please install openjdk.

**Comment by Anakim** [comment]
ok .. @ProIcons 
now i have deinstalled all Java Files und reinstalled .. oracle jdk 8

```
sudo add-apt-repository ppa:webupd8team/jav
sudo apt-get update && sudo apt-get install oracle-java8-installer
```

```
java -version

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
and it works !! very nice support guys !!
Thx
