### ISSUE TITLE
Rename/Cleanup Option Does Not Skip "Extras" Folder

### ISSUE THREAD

**Issue by EarthBoundX5** [tinyMediaManager/tinyMediaManager#223]
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1443027/tmm_logs.zip)
Version: 2.9.5
Build: 2017-10-05 19:26
OS: Windows 10 10.0
JDK: 1.8.0_144 amd64 Oracle Corporation

__What is the actual behaviour?__
When selecting the Rename/Cleanup option, the "Extras" folder is not ignored.  This causes unexpected issues.  For example, if an alternative version of an episode resides in the "Extras" folder and has the original name and episode number of the original episode, the renaming routine will move said episode to the respective Season folder.

__What is the expected behaviour?__
Ignore "Extras" folder, as they are typically for non-scrapped items that generally are not expected to be handled by a scraping or renaming tool.

__Steps to reproduce:__
Example Situation:
1. Have Beavis and Butt-Head (1993)\Extras\Beavis and Butt-Head - S01E01 - Give Blood (Version B).mpg
2. Click Rename/Cleanup
3. Beavis and Butt-Head - S01E01 - Give Blood (Version B).mpg gets moved to Beavis and Butt-Head (1993)\Season 1

__Additional__
Have you attached the logfile from the day it happened?

**Comment by myron0815** [comment]
Thx for info.
Will be skipped in next version :)

**Comment by EarthBoundX5** [comment]
Thanks!  Will assumed closed for now then!

**Comment by EarthBoundX5** [comment]
Thanks!

 - EarthBoundX5
