### ISSUE TITLE
TMM will not open with Java 1.9

### ISSUE THREAD

**Issue by ruddj** [tinyMediaManager/tinyMediaManager#224]
Version: 2.9.5 Release
Build: 2017-10-05 19:26
OS: Windows 10  x64 Version 1709
JDK: 1.9.0_11 amd64 Oracle Corporation

When I open the tinyMediaManager.exe it shows a popup:
"This application requires a Java Runtime Environment 1.7 or higher 1.7.0"
Clicking OK launches the Java download website and quits the program.

Do you have any details when Java 1.9 will be supported?

**Comment by ProIcons** [comment]
As mentioned [here](https://github.com/tinyMediaManager/tinyMediaManager/issues/156#issuecomment-340534558) tMM 2.x versions will not support java 1.9. Install JRE 1.8 along with your 1.9, and run it through JRE 1.8.

Version 3 will support JRE 1.9, and soon there will be an Open Beta for all of you.

**Comment by mlaggner** [comment]
should work in 2.9.6
https://github.com/tinyMediaManager/tinyMediaManager/commit/7a35a4e51dbb0f52a6c4447b6e26ac38b68d985c

**Comment by ProIcons** [comment]
A Fast Workaround for tinyMediaManager project to work on java 9 is to add modify the 
`getdown.txt` file and append these lines at the end of the file

```
jvmarg = -XX:+IgnoreUnrecognizedVMOptions
jvmarg = --add-modules=java.xml.bind
```
