### ISSUE TITLE
Current version does not load for me on MacOS High Sierra

### ISSUE THREAD

**Issue by tolwin** [tinyMediaManager/tinyMediaManager#225]
__What TMM version are you using?__
Current release for MacOS.....Date Oct. 05 2017 8:30pm

__release, pre-release, nightly, or directly from GitHub/branch?__
Binary from http://www.tinymediamanager.org/download/

__What is the actual behaviour?__
TMM is not starting on MacOs High Sierra Version 10.13.1 (17B48). Icon of the app appears in doc, but nothing happens.

tail -f on launcher.log shows:

2017/11/10 19:36:00:053 INFORMATION n.a: ------------------ VM Info ------------------
2017/11/10 19:36:00:058 INFORMATION n.a: -- OS Name: Mac OS X
2017/11/10 19:36:00:058 INFORMATION n.a: -- OS Arch: x86_64
2017/11/10 19:36:00:058 INFORMATION n.a: -- OS Vers: 10.13.1
2017/11/10 19:36:00:058 INFORMATION n.a: -- Java Vers: 9.0.1
2017/11/10 19:36:00:059 INFORMATION n.a: -- Java Home: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
2017/11/10 19:36:00:059 INFORMATION n.a: -- User Name: mememe
2017/11/10 19:36:00:059 INFORMATION n.a: -- User Home: /Users/mememe
2017/11/10 19:36:00:059 INFORMATION n.a: -- Cur dir: /Applications/tinyMediaManager.app/Contents/Resources/Java
2017/11/10 19:36:00:059 INFORMATION n.a: ---------------------------------------------
2017/11/10 19:36:00:107 INFORMATION n.a: Checking whether we need to use a proxy...

And nothing else happens.

I do not have any proxy setup. Direct connection to Internet

java -version says:
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

__What is the expected behaviour?__
App should start :)

__Steps to reproduce:__
- Doubleclick on app
- Nothing else
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

**Comment by ProIcons** [comment]
https://github.com/tinyMediaManager/tinyMediaManager/issues/224

**Comment by ProIcons** [comment]
Install JRE 1.8
