### ISSUE TITLE
Movie List Extends Beyond the Bottom of the Window

### ISSUE THREAD

**Issue by nerdkid93** [tinyMediaManager/tinyMediaManager#23]
Version: 2.7.4
Build: 2016-04-01 19:01
OS: Windows 10 10.0
JDK: 1.8.0_73 amd64 Oracle Corporation

**What is the actual behaviour?**
The UI redraws the movie list to be larger than the window will allow. This creates a scrollbar that descends below the bottom edge of the window, and the bottom of the list cannot be viewed.

**What is the expected behaviour?**
The movie list should not be changed after updating a file.

**Steps to reproduce:**
Search and scrape data from an online source, and click update. If that didn't cause the issue, right click the altered movie, and select `Rename/Cleanup Selected Movie(s)`.

**Additional**
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/214414/tmm_logs.zip)
![image](https://cloud.githubusercontent.com/assets/6289786/14451190/0c45049c-0053-11e6-8d64-79a877f1a043.png)

**Comment by mlaggner** [comment]
Could you check all (sub)screens (also Movie set and TV show ones) which one is expanding the panel outside the screen? This is not visible in this screenshot

**Comment by myron0815** [comment]
try deleting the **data/tmm_ui.prop** which stores the GUI coordinates for every screen -> starting with defaults
