### ISSUE TITLE
Incorrectly Scraped Poster and FanArt

### ISSUE THREAD

**Issue by EarthBoundX5** [tinyMediaManager/tinyMediaManager#230]
Version: 2.9.5
Build: 2017-10-05 19:26
OS: Windows 10 10.0
JDK: 1.8.0_144 amd64 Oracle Corporation

__What is the actual behaviour?__
When scraping some shows, the incorrect poser and fanart will download.  Despite the TheTVDB id being right and the listing containing the correct artwork.  Replacing these with the correct images does not always update the local tmm db.

__What is the expected behaviour?__
Downloads the correct poster and fanart from the respective TheTVDB entry.

__Steps to reproduce:__
I've had this on 2x TV shows so far, but only noted the most recent.
1. Have RoboCop Prime Directives (2001) media/episodes as a show in a folder of the same name.
2. Scrape for media info and artwork
3. Get "The Story of Us with Morgan Freeman" as a result for poster and fanart.

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1497684/tmm_logs.zip)

**Comment by ProIcons** [comment]
With which fanart scraper are yoh scraping the fanart?

**Comment by EarthBoundX5** [comment]
I've left fanart scraping to the defaults.  So it should go AnimatedPosters, fanart.tv, then themoviedb.org.

**Comment by svaraej** [comment]
How is this an issue? TMM neither will or should download images from TheTVDB if it's not enabled in the settings.

**Comment by EarthBoundX5** [comment]
For random tv shows, specifically the one in my example, I would scrape the
correct TheTVDB ID...but when it would download the artwork, it would be
from a completely different show.  Like with my example, it would scrape
RoboCop Prime Directives correctly...but download artwork from The Story of
Us with Morgan Freeman...so completely wrong and odd...

What's stranger too, the actual show would have the artwork at the actual
page on TheTVDB.  So my work around when this happens was to manually
download the correct artwork and put it in the given folders.

 - EarthBoundX5

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
