### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by LeLobster** [tinyMediaManager/tinyMediaManager#232]
__What TMM version are you using?__
2.9.6-SNAPSHOT_a79d1db

__release, pre-release, nightly, or directly from GitHub/branch?__
Github

__What is the behaviour?__
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (dist) on project tinyMediaManager: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/lobster/Software/tinyMediaManager/ant-package.xml:228: net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/home/lobster/Software/tinyMediaManager/AppBundler/launch4j/bin/windres": error=2, No such file or directory
[ERROR] around Ant part ...<ant antfile="/home/lobster/Software/tinyMediaManager/ant-package.xml">... @ 8:72 in /home/lobster/Software/tinyMediaManager/target/antrun/build-main.xml

```

__Steps to reproduce:__
1. git clone https://github.com/tinyMediaManager/tinyMediaManager.git
2. mvn package

__Additional__
Debian Sid
`mvn -version` 
```
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-4-amd64", arch: "amd64", family: "unix"
```

**Comment by ProIcons** [comment]
Re clone your repository and try again. Or cross validate its integrity through the remote upstream

**Comment by LeLobster** [comment]
`git clone`
```
Cloning into 'tinyMediaManager'...
remote: Counting objects: 48877, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 48877 (delta 4), reused 8 (delta 4), pack-reused 48864
Receiving objects: 100% (48877/48877), 280.13 MiB | 4.25 MiB/s, done.
Resolving deltas: 100% (34444/34444), done.
```
`mvn package`
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (dist) on project tinyMediaManager: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/lobster/Software/tinyMediaManager/ant-package.xml:228: net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: java.io.IOException: Cannot run program "/home/lobster/Software/tinyMediaManager/AppBundler/launch4j/bin/windres": error=2, No such file or directory
[ERROR] around Ant part ...<ant antfile="/home/lobster/Software/tinyMediaManager/ant-package.xml">... @ 8:72 in /home/lobster/Software/tinyMediaManager/target/antrun/build-main.xml
```

Same error again.

Line 228 in ant-package is in the section `<!-- prepare build for Windows -->`


I'm pretty new to this stuff, just installed Debian 2 days ago.

**Comment by ProIcons** [comment]
I will try it on my wsl. And i will let you know

**Comment by ProIcons** [comment]
I found the problem. windres util by launch4j is built in 32bit architecture. Mine and your system is amd64 architecture.

```
windres: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.15, BuildID[sha1]=648677129832e944d54fa362bbb6e6e4b75015fd, stripped
```

Therefore you can't execute it. ant-build can't as well. 
Needs @mlaggner attention.

**Comment by ProIcons** [comment]
Issue will be resolved tomorrow, on nightly build. Thanks for reporting.

**Comment by LeLobster** [comment]
> Btw Debian SID is UNSTABLE.

I installed Debian via a `stable` release image but  I added the `testing` packages in the sources list because I was testing something.  
I removed it couple days ago but I guess in the mean time I managed to somehow upgrade my distro.
It's fine though, it seems to be running smooth, and when I run `apt-get dist-upgrade` there are 0 packages to resolve.

Anyhow thanks for the quick fix, do I just `git clone` again or do I have to point it at another branch?

**Comment by ProIcons** [comment]
Reclone or sync with remote updates. And switch to devel branch with git checkout

**Comment by ProIcons** [comment]
Also please read what SID version is all about on Debian's website

**Comment by LeLobster** [comment]
`[INFO] BUILD SUCCESS`

Confirm fixed.

> Also please read what SID version is all about on Debian's website

I roughly knew what it's about but someone recommend adding the sources to install Firefox Quantum, so I just did that.  
I don't think I ever ran a full `upgrade` for all my packages so it shouldn't have upgraded everything to packages from unstable.  

But anyway, now that I have only stable sources in `/etc/apt/sources.list` shouldn't it be fine?  
As I said; 'upgrade` and `dist-upgrade` both say 0 packages to resolve.

**Comment by ProIcons** [comment]
```
sudo apt-get install lsb-release
lsb_release -a
```

If it sais that you are running on SID then your system is completely unstable. It would be wise to install jessie.

**Comment by LeLobster** [comment]
`lsb_release -a`
```
Distributor ID:	Debian
Description:	Debian GNU/Linux stable-updates (sid)
Release:	stable-updates
Codename:	sid

```

**Comment by ProIcons** [comment]
You have your answer. Thank you for your feedback we appreciate every user feedback sinc
