### ISSUE TITLE
Unable to scrape using TVDB

### ISSUE THREAD

**Issue by gmac77** [tinyMediaManager/tinyMediaManager#234]
Version: 2.9.6
Build: 2017-12-10 17:25
OS: Windows 10 10.0 64bit
JDK: 9.0.1 amd64 Oracle Corporation

__What is the actual behaviour?__
Total failure of scraping when using TVDB to update new TV shows/episodes. 
Trying to scrape a new show brings up the search dialog with zero results.
Trying to scrape a new episode for an existing show brings up an error message (see logfile) The error message asks me to submit this bugreport.
Scraping using other sites works fine.

I have made sure I have updated to the latest version of Java.
I have closed and restarted the program. No change
I have "turned the computer off then on again". No change

__What is the expected behaviour?__
New shows and episodes should scrape correctly.

__Steps to reproduce:__

__Additional__
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1553923/tmm_logs.zip)

Have you attached the logfile from the day it happened?

**Comment by myron0815** [comment]
TMM is still not 100% Java 9 compatible (only with upcoming v3)
You could downgrade to v8... or try following:
careate (or edit) a file called `extra.txt` in TMM directory.
add `--add-modules java.xml.bind`
Save and restart TMM

We already added this workaround to 2.9.6, but it seems it is not always working....

**Comment by mlaggner** [comment]
please try this para instead (myrons param is already exisiting with 2.9.6)
`--add-modules=java.xml.ws`

**Comment by gmac77** [comment]
Thank you so much. That fix has worked and all is well.
