### ISSUE TITLE
Running tinyMediaManager.sh doesn't start the app, but copy/pasting the command does

### ISSUE THREAD

**Issue by LeLobster** [tinyMediaManager/tinyMediaManager#235]
__What TMM version are you using?__
Freshly built `tmm_2.9.7-SNAPSHOT_a1c3c7a_linux` using `Maven 3.3.9`

__What is the actual behaviour?__
Running `tinyMediaManager.sh` opens a new terminal widow and briefly flashes the TMM splash before closing.  
`java -jar tmm.jar` results in the following error
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: ch/qos/logback/core/filter/Filter
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.filter.Filter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

```

__Additional__
OS Name: Linux
OS Arch: amd64
OS Vers: 4.9.0-4-amd64
Java Vers: 1.8.0_151
Java Home: /usr/lib/jvm/java-8-openjdk-amd64/jre

**Comment by LeLobster** [comment]
I copy pasted the command found in `tinyMediaManager.sh`
`java -Djava.net.preferIPv4Stack=true -Dappbase=http://www.tinymediamanager.org/ -jar getdown.jar .` and ran it manually in the terminal and now it starts properly

**Comment by myron0815** [comment]
Building the jar and simply starting it with `java -jar tmm.jar` does not work.
Reason is, that you do not have the required libraries in correct place.
You need at least specify `-cp lib/*`

Unfortunately, we cannot fixate this in manifest, because when we dynamically extent this via getdown, it is not adhered.
So we always call our getdown.jar updater first, which then calls TMM correctly (and w/o actually updateing it)
Where did you find this shell script? the ones i checked, do not call TMM directly....

**Comment by ProIcons** [comment]
The real question here is how you unpacked tge tmm? Cause it seems it should run properly

**Comment by LeLobster** [comment]
> Where did you find this shell script? the ones i checked, do not call TMM directly...

First I thought the way to start tMM was by running `tmm.jar` but then I looked in the `sh` file what it was doing. So this was simply a wrong assumption on my part.
 
Double clicking the `sh` file opens a terminal window and flashes the tMM splash before closing again without starting, but I just ran the command `sh tinyMediaManager.sh` and now it does start properly.

edit: I also just figured out there is difference between choosing `Run in Terminal` and `Run` when double clicking an executable `sh` file.

> The real question here is how you unpacked tge tmm? Cause it seems it should run properly

I simply extracted the `tmm_2.9.7-SNAPSHOT_a1c3c7a_linux.tar.gz` created in the `dist` folder.  

---

I'm new to this whole linux thing and tmm is also the first piece of software I didn't just `apt install`  
So, thank you both for the quick replies but I think the only real issue here is on my part.

**Comment by ProIcons** [comment]
You can do the following
```
chmod +x tinyMediaManager.sh
```
and run it exactly like this

```
./tinyMediaManager.sh

**Comment by LeLobster** [comment]
It already has the execute permission and running the script from the terminal works fine.  
The only problem I had was double clicking prompted me for using the terminal or not and doing so doesn't start tMM, I just had to select `run`

I'm using Gnome as DE and want tMM in my favourites (I use it quite a lot), so I can create a custom icon which launches the `.sh` file from my launcher.

Anywhere I can find a somewhat high res version of your logo?
