### ISSUE TITLE
Renaming Filmset does not work properly

### ISSUE THREAD

**Issue by Scarecrow32168** [tinyMediaManager/tinyMediaManager#237]
Version: 2.9.7
Build: 2017-12-28 20:10
OS: Windows 7 6.1
JDK: 1.8.0_151 amd64 Oracle Corporation
UI Language: german

__What is the actual behaviour?__
Attempting to rename a movie set didn't work properly. 

Result: Movieset is renamed, but the directory on the hard disk is not renamed even after running "Cleanup/Rename", because I use the variable "$M" in the "Renamer" settings and not "$N" (complete placeholder string:"{$M}\\$E ($Y){ ($3)}"). 

Restarting TMM does not work either.

Problem: On the Edit Movieset page, there is no input/edit field for "Movieset Name (sort title)" and/or it was not automatically updated after editing the "Movieset Name" field.

__Workaround__
To give you the correct english field-labels, I have set the UI language from "german" to "english". After the (now needed) restart, to my big surprise the "Movieset Name (sort title)" was automatically updated to the correct value. So I can use this as a workaround, but it would nice to have a more comfortable solution (see below).

__What is the expected behaviour?__
a) Having an additional editable field for "Movieset Name (sort title)"
or
b) An automatism that updates the "Movieset Name (sort title)" field after editing the "Movieset Name" field

__Steps to reproduce:__
- Select the "Moviesets" tab
- Click on a Movieset
- Edit
   ONLY the "Movieset Name" can be changed here!
- Save

__Example__
- Renaming "Marvel's The Avenger's Collection" to "The Avenger's Collection"
- In TMM, the Movieset title now is (correct): "The Avenger's Collection"
 - Looking at "Settings->Movies"->Renamer" shows:
   - $M | Movieset title (sort title) | Marvel's The Avengers Filmreihe
   - $N | Movieset title | The Avengers Filmreihe

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
the title sortable is being built on access (it is not stored on the database), so it should be the right value after restarting tinyMediaManager

I found that manually altering the movie set title does not trigger the title sortable to be updated - will be fixed.

as a workaround: please re-check the values after restarting tinyMediaManager
