### ISSUE TITLE
[Feature Request] CountryCode api-scraper [withdrawn codes][conflicting]

### ISSUE THREAD

**Issue by RKaczmarek** [tinyMediaManager/tinyMediaManager#238]
__What TMM version are you using?__
2.9.7

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
CountryCode for for example germany only available for germany since 1990.

__What is the expected behaviour?__
In the following I will refer to the example of germany. The problem exists for other countries too.

For old movies, there should be germany available before 1990 and since 1990.

The following country codes should be available:

Code | Country Name | Alpha-2
--- | --- | ---
[276](https://en.wikipedia.org/wiki/ISO_3166-1_numeric) | [Germany](https://en.wikipedia.org/wiki/Germany) | __DE__
[278](https://en.wikipedia.org/wiki/ISO_3166-1_numeric) | [East Germany](https://en.wikipedia.org/wiki/East_Germany) | DD
[280](https://en.wikipedia.org/wiki/ISO_3166-1_numeric) | [West Germany](https://en.wikipedia.org/wiki/West_Germany) | __DE__

With the current enum CountryCode structure, it is not possible to add all of these country codes because they are conflicting in alpha-2 name which is the enum constant.

For example:
The scraper-imdb will never be able to scrape the correct release date for movies released before 1990. Best example here is Star Wars - Eposide IV. The release date in "west germany" was 1978-02-09.

To scrape the release date you have to request the realeaseinfo path of imdb for the movie. It contains the correct release date for "west germany" and later release dates for "germany".

Possible solutions:

Solution | Pros | Cons
--- | --- | ---
scraper-imdb uses it's own individual solution | possible to scrape correct release dates | would not help other scrapers
CountryCode contains a list of names | Alternative names. | Code and alpha-3 would be missing. Most CountryCodes would have a list with one item.
CountryCode uses name as enum constant | name is unique | getByAlpha2 would always return a list, even though most countries only have one name. Enum constants would be long.
e.g. west germany with enum constant e.g. XWG | easy to implement | dirty solution, but imdb uses this constant as region name.

__Steps to reproduce:__
Doesn't matter.

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
Doesn't matter.

**Comment by mlaggner** [comment]
just checking this and I think the approach number 1 would be the best solution here, since these excludes are IMDB-only (no valid ISO codes to match in IMDB)...

a list of the abandoned country codes over at imdb is here https://help.imdb.com/article/contribution/other-submission-guides/country-codes/G99K4LFRMSC37DCN# (although it is missing XWG). But what to do with countries which have been split (e.g. Czechoslovakia, Yugoslavia or Soviet Union)?

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
