### ISSUE TITLE
"watched" state is not synced back from movie.nfo file

### ISSUE THREAD

**Issue by voxspox** [tinyMediaManager/tinyMediaManager#239]
__What TMM version are you using?__
2.9.7 release

__What is the actual behaviour?__

The movie.nfo file has two fields: watched (bool) and playcount (int)
TMM offers a checkbox "watched" (edit movie). This state is stored in the field `playcount` in the `movie.nfo` file as 1 or 0.
Changing `playcount` in the file is not updated in TMM.

__What is the expected behaviour?__

1. Checking the "watched" checkbox (edit movie) should set the field `watched` in the `movie.nfo` file to `true`
2. The watched state (aka `watched`and `playcount`) should be read out from the `movie.nfo` while "update data sources"

__Steps to reproduce:__
- change playcount or watched field in movie.nfo file
- update data sources

**Comment by ProIcons** [comment]
We do not support 2 way binding between our data model and xml output. What I'm trying to say is that we don't read any kind of information from the movie xml file. We have an internal database and all of our data is stored there. The generation of this xml file is being done only for serving external media centers such as kodi plex etc. No info is being updated from xml to our internal database.

**Comment by voxspox** [comment]
ok.

I think the `watched` field should be set nevertheless.
