### ISSUE TITLE
Third party scrapers not working

### ISSUE THREAD

**Issue by Flobbes** [tinyMediaManager/tinyMediaManager#24]
When I try to scrape movies with third party scrapers I always get exceptions, independent of the used scraper. Tried current stable and nightly.

I wanted to debug it myself, but sadly I was not able to setup eclipse and tinymediamanager.

TinymediaManager complains about missing dependencies to its submodules and when I try to build the submodules, nearly all of them throw an uncountable number of errors.

Is there a way to checkout tmm + all dependencies? What is the suggested workflow to compile the source code?

**Comment by Flobbes** [comment]
Ok I managed to compile the source code. Eclipse somehow had modified some of the
package org.tinymediamanager.scraper.fanarttv;
lines.

Once I have found the issue with the scrapers, I will let you know.

**Comment by myron0815** [comment]
well, you only need the TMM repo (and optional the scraper you want to debug - but should work without cheking out)
Be sure to check it out as a "Maven" project (or use configure->maven project) - all dependencies are resolved automatically.
You will need to setup the snapshot repository as stated here: https://github.com/tinyMediaManager/tinyMediaManager/blob/master/README.md#developer-info, currently devel has all snapshots due to major refactoring of the API...

**Comment by Flobbes** [comment]
Ok got it running.
Had to switch to the old api.

The problem is that my scrapers don't return a year for the search results, but tmm expectes a field was that name and then crashs.

So I will modify my scrapers in this manner.

Thanks for the help.

**Comment by mlaggner** [comment]
with the new version of the API there is an explicit field for year to prevent such problems.
Your new scraper may work after migrating to API v2

**Comment by Flobbes** [comment]
Thank you very much for the help.
API v2 is that on the master or the devel branch?

Do you intend to support images for third party scrapers in the future?

**Comment by myron0815** [comment]
TMM is developed in the "devel" branch.
Currently with v2.0-SNAPSHOT API.
(Master is only for release)

For API (and all other plugins) there is only one master branch. (to keep it simple)

What do you mean with 3rd party scrapers?
Something like fanart.tv?

**Comment by mlaggner** [comment]
third party scrapers are supported - just build it against our api and place it in the plugins directory of tmm after building the jar

**Comment by Flobbes** [comment]
From within the software I understood, due to the fact that Scraper Meta data and images have seperate tabs. That the meta data and the images are obtained from different scrapers depending on the selection. And since the kodi scrapers are not available within the images selection, I thought the kodi scraper only extract the meta data.
But to be honest I haven't looked into the source code yet.
