### ISSUE TITLE
Error while clicking through cast members.

### ISSUE THREAD

**Issue by MikeyMouse** [tinyMediaManager/tinyMediaManager#240]
Version: 2.9.7
Build: 2017-12-28 20:10
OS: Windows 10 10.0
JDK: 1.8.0_151 x86 Oracle Corporation

__What is the actual behaviour?__
while clicking through the cast members an error pops up after about 8 selections

__What is the expected behaviour?__
just to display the current selections image

__Steps to reproduce:__
enter cast tab,
click a name,
click another name...
after about 8 selections it comes up with an error. This is not a regular amount of clicks
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1624086/tmm_logs.zip)

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
addressed with https://github.com/tinyMediaManager/tinyMediaManager/commit/b2dc4285d9d94dd397a9512b63e275d208f6b6ed
