### ISSUE TITLE
Renamer

### ISSUE THREAD

**Issue by OldMan100** [tinyMediaManager/tinyMediaManager#241]
Version: 3.0-SNAPSHOT
Build: 2018-01-13 01:21
OS: Windows 7 6.1
JDK: 9.0.1 amd64 Oracle Corporation

__What is the actual behaviour?__
Clicking Renamer Under TV Shows Under Settings Causes A Problem Detected Window To Pop Up.
It Takes At Least Three Clicks On The Close Button For The Window To Close.  Now You Makes Change To The Setting, The Setting Seems To Save.  I Also Found Out, If You Close Settings While Still Under Renamer And Open Setting Again, The Error Will Pop Back Up Since Settings Will Open Directly To Renamer Section, Being The Last Section I Was In Before Closing The Settings Window.

__What is the expected behaviour?__
After Clicking The Rename Button, I Should Be Able To Adjust The Settings For How The Video Files Are Renamed.
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1629068/tmm_logs.zip)

__Steps to reproduce:__
Click Setting, Move Down To Renamer Under TV Shows And Click. See The Error Window. Close The Error Window. While Still Under The Renamer Section, Close Settings. Reopen Settings.

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
the folder name: `24: Legacy` is unsupported in windows.
we may have to clean up that here

**Comment by OldMan100** [comment]
Thank you for the speedy fix. Will Continue to review v3.
