### ISSUE TITLE
Excluded Folders

### ISSUE THREAD

**Issue by OldMan100** [tinyMediaManager/tinyMediaManager#242]
Version: 3.0-SNAPSHOT
Build: 2018-01-13 01:21
OS: Windows 7 6.1
JDK: 9.0.1 amd64 Oracle Corporation

__What is the actual behaviour?__
Will Not Save Any Folders Selected For Exclude Folder(s) From Scan Under Source Under TV Shows.
Clicking The + Button Will A Window To Select The Folder To Exclude, But Will Not Save The Location Under Exclude Folder(s) From Scan.

__What is the expected behaviour?__
After Indicating The Folder To Exclude. The Location Should Be Listed In the Exclude Folder(s)
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1629075/tmm_logs.zip)
 From Scan Section, But Nothing Appears.

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
should work in the next build
