### ISSUE TITLE
Feature Request choise to get name from either folder or file

### ISSUE THREAD

**Issue by Tsunamijhoe** [tinyMediaManager/tinyMediaManager#243]
__What TMM version are you using?__
tmm_2.9.7_8513bee_win
__What is the actual behaviour?__
When importing TMM gets its name for the nfo from the files inside the movie folder,but this is not good for people who dont use iso format..
Mediainfo cant read inside image files,so all my dvd and blurays are stored in folder format,so TMM names the nfo BDMV.nfo for all blurays,and AUDIO_TS/VIDEO_TS.nfo for DVDs, while the artwork is named correctly as it appears to get those names from the folder name.

__What is the expected behaviour?__
With an option for chose either file or folder name for the nfo and artwork,everyone would be happy,and it would be the perfect manager for both older yamj setups like mine,and newer setups like Kodi

__Additional__
Your Operating system? (win/mac/linux? version?)
Windows 7 x64

**Comment by mlaggner** [comment]
As far as I can remember, this is one of the requirements of Kodi!
Otherwise Kodi (and probably other media centers) won't find the created NFO files

**Comment by Tsunamijhoe** [comment]
Find what nfo's? You don't seem to understand the feature request..
Tiny is supposed to MAKE the nfo. This is where the request comes in, tiny at present ONLY make the nfo from the filenames inside the movie folder which is why BDMV/VIDEO_TS format doesnt work with tiny, while EVERY other media manager either has profiles,or a setting to chose to get the movie title from either the movie folder,or the files inside. How would this break kodi compatability?

**Comment by myron0815** [comment]
Tiny works well with exploded discs ;)

But i'm also unsure what you really mean:
On one hand you talk about NFO file naming, then about getting the correct movie title?!?
For the first, the name and location of the nfo is kinda fixed for disc style movies;
Detecting a correct title is a completely different story....

**Comment by Tsunamijhoe** [comment]
What i am asking is a way to have the nfo saved as EITHER BDMV.nfo OR Aliens (1979).nfo,meaning the name of the nfo is taken from EITHER the folder Alien (1979) (folder name) OR like now Alien (1979)/BDMV (file name)
Do you understand now?

**Comment by myron0815** [comment]
Sure.
But since TMM was written with Kodi in mind, it's hardcoded to not bother the user.
And for Kodi, it is needed to be named like the filename... where video_ts would be correct for DVD - with no exception.

In v3 we already plan to support kinda profiles, which gives us more flexibility in presenting some advanced settings to the user... but for the time being, its fixed...

**Comment by Tsunamijhoe** [comment]
OK,i see.. Then maybe it should be called KODI media manager,and not tiny..Because tiny is recommended on forums for other xbmc based media players like popcorn hour and mede8er which is how i came to use it,as the media managers i used before no longer works or are developed,so scrapers dont have updated API and thus are useless
Any ETA on v3?
Thank you

**Comment by myron0815** [comment]
well, since they are xbmc based, they should have taken the same rules ;)

regarding v3:
no... not really.
We only have a very early alpha build on our Kodi forum... but this change is not yet in / specified....

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
