### ISSUE TITLE
Missing New Icon

### ISSUE THREAD

**Issue by OldMan100** [tinyMediaManager/tinyMediaManager#244]
Version: 3.0-SNAPSHOT
Build: 2018-01-15 01:21
OS: Windows 7 6.1
JDK: 1.8.0_152 amd64 Oracle Corporation

__What is the actual behaviour?__
The 'New'
[tmm_logs3.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1633970/tmm_logs3.zip)
 Icon Which Shows After The First Scan. Does Not Show On Update Scans. So, The User Does Not Know If Or Which File(s) Have Been Added To The Database. The File Is Added To The Left Under The Right Show, But No 'New" Icon To Tell You Theirs A New Listing.

__What is the expected behaviour?__
The 'New' Icon Should Show Up Whenever A New File Is Add To The Database. No Different Than V2.

__Steps to reproduce:__
Add A New File And Update The Disk Or Folder The File Is In.

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
thw new icon is there? https://imgur.com/F7llqwR

**Comment by OldMan100** [comment]
Half Way There. The Icon Shows Up Under Movies, But Not TVs. I Removed A Movie And TV Show.  During The Re-Scan Under Both Tabs, Only The Movie Was Stated As 'New. See Pics Attached.
![2 9 6 new](https://user-images.githubusercontent.com/35414666/35254708-52d499ba-ffa0-11e7-87a7-73de4e423837.JPG)
![3 0 snapshot new](https://user-images.githubusercontent.com/35414666/35254709-52eebad4-ffa0-11e7-9305-9fc418e06125.JPG)

**Comment by mlaggner** [comment]
you were absolutely right - missed that in the TV show section.
will be in the next build

**Comment by OldMan100** [comment]
The Problem Was Fixed 4 Days Ago.  But, In The Last 2 Builds, the Problem Has Partly Returned.
During Any Re-scans, The 'New' Icon Will Appear Along Side The Season # & Episode Name, But Not
The Show Name. See Below.

The Red Outline Should Have The 'New' Icon There.  Just Like The Two Blue Outlines.

![3 0 snapshot problem 2 5 modifed](https://user-images.githubusercontent.com/35414666/35487803-874f9b84-0434-11e8-82da-f71466d7ebce.jpg)
