### ISSUE TITLE
First Scan

### ISSUE THREAD

**Issue by OldMan100** [tinyMediaManager/tinyMediaManager#245]
Version: 3.0-SNAPSHOT
Build: 2018-01-15 01:21
OS: Windows 7 6.1
JDK: 1.8.0_152 amd64 Oracle Corporation

__What is the actual behaviour?__
After Indicating The Source Location(s) To Scan. The App Scans Before Anything Else.  This Should Not Be Done. A User Would Like To Fine Tune The Settings For A Scan Is Started. Also, The First Scan Of The Two Drives On My System Took Over 4 Hours And I Still Had Close The App, It Seems To Have Been Hanging During The 'Getting MediaInfo'.

__What is the expected behaviour?__
Install, Open Main Window, Even Better, Go Straight To Setting Window, To Change Any Settings.
Close. Then, The User Decisions Whether To Scan All Or Part Of The Library, Depending On The Size Video Collection.

__Steps to reproduce:__
On 2.5 TB Of Files, Open TMM For The First Time.  Add Source Location. Finish. See How Long The Scan Took And Whether Its Hanging Which Getting The Mediainfo.
[tmm_logs3.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1634150/tmm_logs3.zip)

__Additional__
Have you attached the logfile from the day it happened?

**Comment by myron0815** [comment]
Well, i see it as plus, to automatically start.
Why pressing a button?
We often had some bugreports, that the users added some folders in wizard, but nothing happens!

The scan only reads your files into database;
You cannot fine-tune or change anything of that behaviour.
This needs always be done with every datasource.
Yes, mediainfo takes its time, but it's worth waiting....
