### ISSUE TITLE
Renamer does not use sorttitle field in movie

### ISSUE THREAD

**Issue by wongvatanyu** [tinyMediaManager/tinyMediaManager#25]
__What TMM version are you using?__
2.7.4 (2016-04-01 19:01) on Linux Mint 17.3 (64-bit) Kernel 3.19.0-32-generic

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
TMM movie renamer was set to use folder name as "$2/$E ($Y)". The movie title, sorttitle, and original title are start with different characters. When use a rename function on tool bar. TMM replaces $2 with the first character from title (removing a/an/the) instead of using that of sorttitle. The behaviour also observed when rename movie files.

__What is the expected behaviour?__
When rename function is executed, TMM should:
1) check if sorttitle is not empty. If it's not empty, replace $2 with the first letter in sorttitle
2) if sorttitle is empty, read the title and create sorting title from title. and then replace $2 with the first character from generated sorting title.

__Steps to reproduce:__
1 In settings -> movies -> renamer, define folder name as "$2/$E ($Y)"
2 find a movie, and enter names of the title and sort title so that they start with different character. For example, Title="First Love" Sort Title = "A Little Thing Called Love"
3 click "rename" button to let TMM rename it.
4 read the folder name from media files tab. The topmost folder name will be "F", not "L" 
The issue can be reproduced every time. If the $2 variable is applied to file name, it will exhibit the same behaviour.

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
- No log files attached
- Operating system is Linux Mint 17.3 (based on Ubuntu 14.04 LTS) x86_64 Kernel 3.19.0-32-generic. The system is using KDE 4.x as desktop environment.

**Comment by mlaggner** [comment]
$2 is not for the sorttiltle but for the title sorting (I know - weird names, but how should we name it?)
* sorttitle is an extra field mainly using for sorting the movie inside Kodi (and also for movie sets)
* title sorting is the title without leading A, The, Der, Die, Das ...

So the logic is working as "designed", but not as expected by you..

Why would you need the first letter of the sorttitle in the renamer?

**Comment by wongvatanyu** [comment]
I have some odd naming films (non-english films) which don't started with English characters but I want them the be grouped using English pronunciation. At the moment, It use the first characters in whatever languages the files are named, which sometimes are not even alphabets.

My work around is to write the title the way I want file names to be first; then run renamer; and change it to the correct, non-english names.

Since this is a designed behaviour, I guess it is trivial issue. Let's move on and doing something more important like major bugs and raising kids, then. :)

And, if I forgot in my reply mail, thank you for making such  a great software.
