### ISSUE TITLE
Using movie length to help with search matching

### ISSUE THREAD

**Issue by LesKent** [tinyMediaManager/tinyMediaManager#250]
Thanks for the wonderful program that is very helpful. I have a large movie library and found that doing a search on all my movies resulted in a lot of manual search matching and often the first result was not the best. It's pretty time consuming to do manual matching. 

I was thinking that if you used the movie length from the media file to match up with the known movie lengths of possible matches and used that to help prioritize the results it would greatly speed matching. I know there are occasional variations with things like director's cuts, re-releases, extended versions, etc. but I suspect that it would match in 99% of the time or better. 

Once idea also is to add a column with the movie length of actual media  vs. matched movie length to help find mismatches quickly. Maybe add a filter option to only show length mismatches? 

Also another idea on search prioritization should no length available is to use IMDB user rating counts for best match. In my experience similar named movies for a year are often very obscure movies or shorts that seldom match.

**Comment by myron0815** [comment]
ok, can you give us an example, what your movie name was?

**Comment by LesKent** [comment]
Some examples:

The Boss (2016),mp4 search results in a list of 20 movies. The top two appear fairly relevant as The Boss (2016). But it turns out the first one is an obscure documentary called Gazda (tt7526686) with no IMDB alternative name and that TMDb has listed as The Boss but with an alternative name of Gazda.

Another:
To Live (1992).mp4 does not return any good results. In IMDB the correct movie is tt0099620 and has a title of "To Live (1992)" that is not being matched. In TMDB the movie has a title of To Liv(e). If I put the IMDB ID in the search it returns the correct "To Live (1992)" as the only result and if I put in "To Liv(e) (1992)" in the search box it also returns the correct "To Live (1992)" but not "To Liv(e) (1992)" title from TMDB. 

I can provide lots more examples.

**Comment by LesKent** [comment]
Another good example: Blind (2014) where the first result is Blind (2014) tt3821314 an obscure 10 minute short with 10 total user ratings on IMDB where the correct match is Blind (2014) tt2616810 which has 6,015 user ratings with correctly matching published movie length to the media length.  

There are another 15 results past the 2nd where the names are partial matches to the name "blind"

**Comment by myron0815** [comment]
The problem is, we only have a searchresult list.... and there's usually no movie legth in there.
Just common things like title, year, and - if we are lucky - some other things like votes & likes...

We do our best, to get the correct search result to the first entry, but if other sites name them differently, it does not work for 100%. At some cases the user must decide/check....

> Blind (2014)
yes, we are doomed here - both movies have the same name and the same year.

> To Live
has 2 english titles.
According to IMDB, "To Live" and "To Liv(e)" are both eligible.

> The Boss
Works for me (for my regional settings)
Best result always on top....

**Comment by LesKent** [comment]
Is it not possible that once you get the search results list to then look them up one-by-one for the details to get the length for each one that you can then use to prioritize the list?

**Comment by myron0815** [comment]
of course we could.
But this is considered as a bad habit.
DDOSing a site with complete scrape requests for the sake of sorting... no way....

TBDB would limit your requests, but any other sites (without API) like IMDB will not be amused with a 15 times increased traffic per IP...

For 99% of all the movies it is NO problem - for the rest... guess

**Comment by mlaggner** [comment]
totally agree myron.
by the way, you probably won't even get the right result for movies with different cuts/editions (see Lord of the Rings 1: Runtime: 178 min | 208 min (Special DVD Extended Edition) | 228 min (Blu Ray Extended Edition) | 171 min (DVD Widescreen Edition) )

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
