### ISSUE TITLE
tinyMediaManagerCMD.exe overwrites any changes to data/config.xml

### ISSUE THREAD

**Issue by rcollins98166** [tinyMediaManager/tinyMediaManager#251]
__What TMM version are you using?__
version=2.9.7
build=8513bee
date=2017-12-28 20\:10
Linux

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
I set a datasource in the config.xml, only to have my modification removed and the run then fail because there is no datasource.

__What is the expected behaviour?__
Accept the datasource I set in config.xml

__Steps to reproduce:__
1) Edit data/config.xml
2) Modify {movieDataSource/} to appear as (can't use angle brackets in this editor, so I am using curly braces):
 {movieDataSource}/Library/Downloads{movieDataSource/}
3)  Save config
4) "less" config to verify modification has been saved.
3) Start tmm with: ./tinyMediaManagerCMD.sh -updateMovies
4) Get Error: 
[headless-G2] o.t.c.m.tasks.MovieUpdateDatasourceTask2:137 - no datasource to update
5) Inspect config.xml to see that changes made are gone. Only {movieDataSource/} appears in the file.

__Additional__
Have you attached the Logfile from the day it happened?ll
Your Operating system? (win/mac/linux? version?)
Linux Fedora 27 server (No graphics) 64-bit x86

**Comment by mlaggner** [comment]
you need an additional `<path>` tag:

`<movieDataSource><path>/Library/Downloads</path></movieDataSource>`

**Comment by rcollins98166** [comment]
Added the additional <movieDataSource><path>/Library/Downloads</path></movieDataSource>
and get the same behavior. The tags are all removed and the program exits with "no data source to update."
