### ISSUE TITLE
Missing New Icon Returned

### ISSUE THREAD

**Issue by OldMan100** [tinyMediaManager/tinyMediaManager#253]
Version: 3.0-SNAPSHOT
Build: 2018-01-28 01:21
OS: Windows 7 6.1
JDK: 1.8.0_162 amd64 Oracle Corporation

__What is the actual behaviour?__
The Problem Was Fixed 4 Days Ago.  But, In The Last 2 Builds, the Problem Has Partly Returned.
During Any Re-scans, The 'New' Icon Will Appear Along Side The Season # & Episode Name, But Not
The Show Name. See Below.

The Red Outline Should Have The 'New' Icon There.  Just Like The Two Blue Outlines.

![3 0 snapshot problem 2 5 modifed](https://user-images.githubusercontent.com/35414666/35487803-874f9b84-0434-11e8-82da-f71466d7ebce.jpg)

__What is the expected behaviour?__
The Same As Version 2.

![2 9 6 re-scan](https://user-images.githubusercontent.com/35414666/35487880-de4ab954-0435-11e8-9eab-943aad3089e9.JPG)

__Steps to reproduce:__
Just Re-scan For New Videos.

__Additional__
[tmm_logs Re-scan.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1671675/tmm_logs.Re-scan.zip)

**Comment by ProIcons** [comment]
Well Version 3 is still unstable, so this is normal in a way. Thank you for reporting we will have a look at it while we try to come out with a more stable version of v3.

**Comment by OldMan100** [comment]
Thank You For The Quick Response.  I Just Found Out Something About The Problem That May Close In On The Correction.  If You Are Re-Scanning An Already Scanned  Show Listing, Then The Icon Will Only Appear Under Season # And Episode Names, But If You Are Scanning Or Re-scanning, Remove The Show Listing From The Database, An Entire New Show, The Icon Will Appear In All Three Places.

**Comment by mlaggner** [comment]
thanks, I've missed a piece.
is fixed in the next build
