### ISSUE TITLE
Scrap from TMDB failed caused by Java 

### ISSUE THREAD

**Issue by dov29** [tinyMediaManager/tinyMediaManager#254]
__What TMM version are you using?__
2.9.7 on Ubuntu 17.10 and openjdk9

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
scrap from TMDB failed with this java warning : "java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty"
No problem from others scrapers

Here attached the log
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1673221/tmm_logs.zip)

Thanks,

**Comment by ProIcons** [comment]
Update your Java to the latest version and try again.

**Comment by dov29** [comment]
I am already using the latest version

**Comment by ProIcons** [comment]
Please attach the tmm.log here.

**Comment by dov29** [comment]
Done

**Comment by ProIcons** [comment]
Your tmm instance is running with an old out-of-date jdk8 version.

```
=====================================================
org.tinymediamanager.TinyMediaManager:163 - tmm.version      : 2.9.7
org.tinymediamanager.TinyMediaManager:169 - os.name          : Linux
org.tinymediamanager.TinyMediaManager:173 - java.version     : 1.8.0_151
```

**Comment by dov29** [comment]
Thanks for your quick answer but I am running the latest version and still get the error 
 2018-01-29 12:18:11,565 INFO  [main] org.tinymediamanager.TinyMediaManager:173 - java.version     : 9-Ubuntu

**Comment by ProIcons** [comment]
Please open a terminal window , type the following commands and give me the output.
```
java -version
javac -version
lsb_release -a
```

**Comment by dov29** [comment]
- java -version
openjdk version "9-Ubuntu"
OpenJDK Runtime Environment (build 9-Ubuntu+0-9b181-4)
OpenJDK 64-Bit Server VM (build 9-Ubuntu+0-9b181-4, mixed mode)
- javac -version
javac 9-Ubuntu
- lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

**Comment by myron0815** [comment]
Has something to do with SSL and/or your JVM certs/truststore.
Please check https://stackoverflow.com/a/6788682 for possible solutions...

**Comment by dov29** [comment]
Ok guys, I fixed it by forcing to re-install Java certificates. Thanks for your help

sudo dpkg --purge --force-depends ca-certificates-java
followed by
sudo apt-get install ca-certificates-java
