### ISSUE TITLE
Conditional TV Show Naming Parts

### ISSUE THREAD

**Issue by MinchinWeb** [tinyMediaManager/tinyMediaManager#258]
__What TMM version are you using?__

2.9.7

__release, pre-release, nightly, or directly from GitHub/branch?__

release

__What is the actual behaviour?__

TV Show renaming template `[$F $A{ $S}]` results in `[480p AAC-2ch{ }]` (if no media source is defined)

__What is the expected behaviour?__

`[480p AAC-2ch]`

__Steps to reproduce:__
- adjust the 'Episode file name' field on the 'Renamer' tab under 'TV Show' settings...

__Additional__

Windows 10.

*It works as expected for Movies, just not for TV shows.* Is there another way to do conditional filenames?

**Comment by myron0815** [comment]
Well, conditionals didn't make it yet to TV shows :|
Since we changed our complete renamer in v3, and the 2.9.8 (in a few hours) might be the last version for v2, we won't change this here.

But i will remove such empty curly brackets... should be fine as workaround :)
