### ISSUE TITLE
4 Digit Seasons

### ISSUE THREAD

**Issue by OldMan100** [tinyMediaManager/tinyMediaManager#259]
Version: 3.0-SNAPSHOT
Build: 2018-02-06 01:21
OS: Windows 7 6.1
JDK: 1.8.0_162 amd64 Oracle Corporation

__What is the actual behaviour?__
TMM Scrapes A Shows With A 1 Or 2 Digit Season Number.  While Trying To Scrape On TVDB For The Show 'Mythbusters', You Get An Error 'Failed Getting Episode Metadata'. After A Few Attempts, I Pulled The Show Up In TVDB And Realize The Season Number Are Listed By The Year The Show Aired, Ex. Season 2003, Season 2004, Etc. After I Renamed The Folders And The Files To The Correct Year For Season Number, TMM Was Able To Scrape The Show.

__What is the expected behaviour?__
To Be Able To Scrape A Show, The Was TMM Was Designed. But I Know Of No Other Way To Do For This For A Show Like 'Myhtbusters', Without Renaming The Season Number, As Stated Before.

__Steps to reproduce:__
Try Scraping The Show 'Mythbusters', I Know Of No Other Shows Formatted Like This,  With A 1 Or 2 Digit Season Number. Then Change The Season Numbers On The Folders And Files To Reflect The Year The Episode Aired.

__Additional__
Have you attached the logfile from the day it happened?

**Comment by myron0815** [comment]
Our file system parser should be already aware of 4 numbers in seasons.
Have to check if there might be a problem on our scraper side...

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
