### ISSUE TITLE
Incorrect Guessing of Movie Title

### ISSUE THREAD

**Issue by the-solipsist** [tinyMediaManager/tinyMediaManager#26]
__What TMM version are you using?__
2.7.4

__release, pre-release, nightly, or directly from GitHub/branch?__
Release, using Linux.

__What is the actual behaviour?__
Title is guessed as 'moviename directorname'

__What is the expected behaviour?__
Title should be guessed as 'moviename', or at least when doing the search for scraping, "moviename" should be one of the searches done.

__Steps to reproduce:__
- Name a folder & its files using the naming pattern: The Apartment [Billy Wilder, 1960]
- Import that folder into TMM.
- Instead of guessing that [Billy Wilder, 1960] is not part of the movie title, TMM guesses the name as "The Apartment Billy Wilder", and when it searches on IMDB and tMDB, it finds no match.

Can this be changed to allow either for more intelligent guessing, or for custom naming patterns to be input?

**Comment by myron0815** [comment]
well, having actor names inside a filename is always problematic.
How should we know, what is a movie title, and some other information?

We already split a movie into it's parts, remove some stopwords, check positions, detect the year.... and reassemble the title; but unfortunately, this does not work with actor names.

After thinking a bit, the only thing a could commit to, is to remove everything between the squared brackets first, and then doing the title detection (might loose the year information in your example)

Custom naming patters have already put on our todo list - but not in near future...

**Comment by myron0815** [comment]
reworked our detection a bit.
Could you please check with latest nightly?
