### ISSUE TITLE
Cannot launch from MacOS Finder; Must use terminal

### ISSUE THREAD

**Issue by utdrmac** [tinyMediaManager/tinyMediaManager#263]
__What TMM version are you using?__
2.9.8 - Just downloaded 'release'

__release, pre-release, nightly, or directly from GitHub/branch?__
Release, http://release.tinymediamanager.org/dist/tmm_2.9.8_6644bb9_mac.zip

__What is the actual behavior?__
When you double-click on tinyMediaManager.app, nothing happens. The icon appears in Dock for 1-2 seconds then disappears with no error message.

__What is the expected behavior?__
For the app to actually launch when double-clicked

__Steps to reproduce:__
- Download using link above
- Extract archive
- option-right-click -> Open (to bypass unsigned app message)
- wait for nothing to happen

__Additional__
This launches the app:
```
$ cd ~/Downloads/tinyMediaManager.app/Contents/Resources/Java
$ ./tinyMediaManagerOSX.sh
```

**Comment by utdrmac** [comment]
macOS Sierra (10.12.6)

**Comment by mlaggner** [comment]
please try to disable gatekeeper, run tmm once an re-enable it:
https://www.tekrevue.com/tip/gatekeeper-macos-sierra/

**Comment by cokete** [comment]
The same here.

Same conditions, but I cannot start with terminal. Doesn't start.

**Comment by mlaggner** [comment]
do you use java 8 or java 9 to run tmm?
as analyzed in #272 the patcher we use won't run with java 9 on osx somehow..

**Comment by cokete** [comment]
Now I'm using Version 8 Update 161 and it works fine.

**Comment by devster31** [comment]
@mlaggner I believe a solution could be to change the start script.
In particular this line:
https://github.com/tinyMediaManager/tinyMediaManager/blob/0e6e9ae48af51057dfe6b8a0c276657dc5e9907c/AppBundler/dist-mac/Resources/Java/tinyMediaManagerOSX.sh#L17-L25
could be changed to:
```sh
elif [ -x /usr/libexec/java_home ]; then
    JAVA_HOME="`/usr/libexec/java_home -v 1.8`"
    export JAVA_HOME
fi
```
which in my case fixed the issue without changing the default `java` version on the system.

**Comment by mlaggner** [comment]
would that break java 7 compatibility?

**Comment by devster31** [comment]
I'm not sure but I believe it would only work with Java 8, since it specifies `-v 1.8`.
Using `java_home -V` would list all the `java` versions installed:
```
       -V or --verbose
              Prints the matching list of JVMs and architectures to stderr.
```
this could be parsed for other versions.
It's possible that `java_home -v 1.*` works and prefers `1.8` over `1.7`.

**Comment by mlaggner** [comment]
finally after some hours of research I found the source of the issue:
After you downloades tmm (into the downloads folder), you have to copy it to the applications folder, since executing an app from the downloads folder is being done in a sandbox for security reasons (and tmm won't run in a read only sandbox)!

also added this to the FAQ: https://github.com/tinyMediaManager/tinyMediaManager/wiki/FAQ#osx

**Comment by MindTooth** [comment]
The launch file clearly needs to be updated.  Now that we are on Java 11, this breaks.

```
$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home
```
One change that might work is to use `1.8+` instead.  Meaning we ask for all versions above Java 8.  The change fixed it for me.

I'll attempt a PR in the next few days.  Also found some issues of the script file via `shellcheck`.

**Comment by mlaggner** [comment]
Please provide a pr against devel branch 😏
