### ISSUE TITLE
Diacritical marks in "studio" field of .NFO

### ISSUE THREAD

**Issue by Geocacher** [tinyMediaManager/tinyMediaManager#264]
__What TMM version are you using?__
2.9.8

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
In the "studio" field of the .NFO file, characters employing diacritical marks are converted into symbols. An example is "Cubavisión" is converted to "Cubavisi�n".

__What is the expected behaviour?__
The expected behaviour should be to leave any previously displayed characters containing diacritics unchanged.

__Steps to reproduce:__
- Create a .NFO file
- Use Notepad to edit the  "studio" field of the .NFO to read "Cubavisión"
- In TMM, select the episode in question
- Tell TMM to "Rewrite NFO for selected episode(s)"
- Use Notepad to display the "studio" field of the .NFO, which will now read "Cubavisi�n"

__Additional__
Have you attached the Logfile from the day it happened?
[tmm.log](https://github.com/tinyMediaManager/tinyMediaManager/files/1738311/tmm.log)

Your Operating system? (win/mac/linux? version?)
Windows 10

**Comment by Geocacher** [comment]
Have investigated further and found that the "studio" field is copied from the one for the overall show upon an NFO update. Once the show "studio" field becomes "compromised", it will replicate to the episodes upon an NFO update. 

This may have just been a logic oversight. Episodes may be shot at different studios over the years. I've seen this on several ocassions.

It might be better to have a "studio" field added in the episode editing screens (in addition to the one in the editing screens for the show) and an NFO update rule that says TMM will only use the show "studio" field if the episode "studio" field is blank.

**Comment by mlaggner** [comment]
please try to open the NFO file with a real text editor (not notepad - this tool is awful) and check it again!. You can use Notepad++ or Atom Editor - these two test editors can handle unicode.

I've checked the two major metadata provider (tvdb & tmdb) and none of these support studios on episode level. It is only in the NFOs because the Kodi NFO specification points them out, but I am sure, Kodi won't use that either..

unless there is no good argument, we won't add studios on episode level

**Comment by Geocacher** [comment]
Thanks for the prompt reply. While Notepad is not the best editor, it does handle unicode characters. The issue, as noted in my second posting, was TMM uses the "studio" field in the show level to set the studio field in the episode level.

If Kodi actually doesn't use the "studio" tag, then your decision makes sense. Thank you again.
