### ISSUE TITLE
moviedb.org doesn't find any movie, no pictures and covered settings windows

### ISSUE THREAD

**Issue by Anakim** [tinyMediaManager/tinyMediaManager#265]
Version: 3.0-SNAPSHOT
Build: 2018-02-18 01:21
OS: Linux 4.13.0-32-generic
JDK: 1.8.0_161 amd64 Oracle Corporation

__What is the actual behaviour?__
The Scraper doesn't find any movies in german. The other scrappers sometimes but only english Descriptions. Also i can't downloading any picture. No search result

The second problem is. I want to change my settings to add a mac address for my Kodi. For this i must change with Alt-Tab to my Browser to copy the address. When i change back the open window with the settings is covered by the settings window and i can't save or exit tiny. Only kill process helps

__What is the expected behaviour?__

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

**Comment by Anakim** [comment]
i can explain that i find the solution for the moviedb.org error. I find in the logfile some hint's about java ssl certifacte error. It's a simple access problem with tiny and java. On my Linux Mint tiny starts in non root syntax. change it and run !! Happy.

But the other Problem with the covered windows still present. 
On every windows i open a subwindows it was covered by the root windows.

Is this a bug? or another Problem with my Linux ?

Thx

**Comment by mlaggner** [comment]
well, you should never run a program as admin (unless it really needs the rights). You may need to install/reinstall ca-certificates-java on your machine!

well alt-tabbing out of tmm and back in works in linux... I'll check this in v3 since v2 is kinda deprecated

**Comment by mlaggner** [comment]
as far as I could see that is already fixed in v3, but I've added this fix also to v2 (2.9.9)
