### ISSUE TITLE
Feature Request: Show missing episodes in TV Series for scraped shows

### ISSUE THREAD

**Issue by ziofat** [tinyMediaManager/tinyMediaManager#267]
__What TMM version are you using?__

v2.9.8

__release, pre-release, nightly, or directly from GitHub/branch?__

release version

__What is the actual behaviour?__

Only seasons/episodes I downloaded are shown in list

__What is the expected behaviour?__

Seasons/episodes aired but not downloaded are shown in list with grey colour

**Comment by mlaggner** [comment]
is already done for v3 and can not be implemented in v2
