### ISSUE TITLE
Exception during scraping + fix attached

### ISSUE THREAD

**Issue by Flobbes** [tinyMediaManager/tinyMediaManager#27]
__What TMM version are you using?__
Devel

__What is the actual behaviour?__
Null pointer exception

I appended a workaround. I guess you know better how to actually fix it.

[diff.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/232294/diff.txt)

**Comment by myron0815** [comment]
thx.
when does this happen?
which Kodi scraper XML?

**Comment by Flobbes** [comment]
Happens when the condition of a regex is empty.

The kodi tmdb produces this error for example.
