### ISSUE TITLE
Capitalize

### ISSUE THREAD

**Issue by Atomixo** [tinyMediaManager/tinyMediaManager#271]
Version: 3.0-SNAPSHOT
Build: 2018-03-18 00:21
OS: Windows 10 10.0
JDK: 1.8.0_161 amd64 Oracle Corporation

>Is it possible to make a feature so the "Title" and "Original Title" always is capitalize. (First Letter Is 
Capitalized In Every Word)

**Comment by myron0815** [comment]
nice idea.
Let's see, where we could integrate such checkbox...

**Comment by Atomixo** [comment]
>where do you expect this feature?
>at scraping, at renaming? only for GUI?

At scraping would be nice, maybe both. Its ok only for GUI for me.
Thanks.

**Comment by Atomixo** [comment]
Does capitalize coming soon???

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
