### ISSUE TITLE
Doesn't start on Mac OS X 

### ISSUE THREAD

**Issue by cokete** [tinyMediaManager/tinyMediaManager#272]
__What TMM version are you using?__
tinyMediaManager 2.9.8 for Mac OS X

__release, pre-release, nightly, or directly from GitHub/branch?__
Release --> http://release.tinymediamanager.org/dist/tmm_2.9.8_6644bb9_mac.zip

__What is the actual behaviour?__
When you double-click on tinyMediaManager.app, the icon appears in Dock for 20-30 seconds bouncing then when it finish there's no window, and if you make second click in the icon it says "The app is not responding"

__What is the expected behaviour?__
Launch the app when double-clicked

__Steps to reproduce:__
- Download
- Extract
- Move to Applications folder
- Double-click
- Wait

__Additional__
Mac OS X 10.12.6
Java 9.0.4
Gatekeeper is disabled always in my computer

**Comment by mlaggner** [comment]
could to go to the tinyMediaManager.app package contents and have a look for the logs files called `launcher.log` and `tmm.log` and upload them to pastebin?

**Comment by cokete** [comment]
I only have `launcher.log`
Pastebin url `launcher.log`: https://pastebin.com/cYTiuwwj

**Comment by mlaggner** [comment]
really weird - getdown (the patching engine we use) did not even finish loading..
I try to reproduce that on a test machine as soon as possible

**Comment by cokete** [comment]
Thank you.

If you need some more test, only tell me and I'll try it.

**Comment by mlaggner** [comment]
could you maybe try to install java 8 instead of java 9 and try again?
as far as I know getdown _should_ run on java 9 but I am not 100% sure about that :D

**Comment by cokete** [comment]
Now it works.

I've uninstalled java 9 and install java (Version 8 Update 161) and now it works!!

**Comment by mlaggner** [comment]
okay, really strange (have to analyze this).
is it ok to run tmm with java 8 until we find/fix the issue?

**Comment by cokete** [comment]
Yes, no problem. I use java 8 without problems!

Thank you for the support.

**Comment by MrJester** [comment]
I just started running into this issue today. I uploaded my tmm.log to pastebin here https://pastebin.com/hzK9duPZ

and here is the Java info I have
java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
