### ISSUE TITLE
Error Index 0 Size 0

### ISSUE THREAD

**Issue by Anakim** [tinyMediaManager/tinyMediaManager#275]
Version: 3.0-SNAPSHOT
Build: 2018-03-21 00:21
OS: Linux 4.13.0-37-generic
JDK: 1.8.0_161 amd64 Oracle Corporation

__What is the actual behaviour?__

Error occurs at each scrape on
see error above

__What is the expected behaviour?__

__Steps to reproduce:_
Error occurs at each scrape on

__Additional__
Have you attached the logfile from the day it happened?
[tmm.2018-03-26.0.log.gz](https://github.com/tinyMediaManager/tinyMediaManager/files/1853248/tmm.2018-03-26.0.log.gz)

**Comment by myron0815** [comment]
How did you click on scrape? 
Via top menu?

It looks like, you did not select any tv shows to scrape.
Try a right click on one, or multi select some...

**Comment by Anakim** [comment]
you are right. 
if i click on season before, the error comes

ok then this is a bug, this is not the case in version 2.9

but it helps me to click the show befor

**Comment by mlaggner** [comment]
should be fixed in the next build
