### ISSUE TITLE
Thumbnail locked

### ISSUE THREAD

**Issue by jimlynnjulian** [tinyMediaManager/tinyMediaManager#276]
__What TMM version are you using?__
2.9.8

__release, pre-release, nightly, or directly from GitHub/branch?__
Release.

__What is the actual behaviour?__
Unchangeable poster/thumbnail. Unchangeable data source, e.g. imdb, tmdb.

__What is the expected behaviour?__
Replacement of poster image

__Steps to reproduce:__
- first
Load 'Sex in the Comix' video manually, or automatically.
- second
   Try to change the default data source and poster image from tmdb to imdb.
ALL efforts including scrapes, edits and delete-load, fail. I can edit the entry and change the data source, but the image remains and is not updated. I can scrape the file and change the data source and the image remains.
   I even downloaded the image and image address I wanted, from IMDB. I matched the title of the new image and replaced the previous image. I edited the .nfo file and replaced the tmdb image link with the IMDB link.
   The program removed the changes, including the replaced poster image.
   At this point, there is no way to alter the poster image or data source that falls within reasonable expectations. What is the formula for changing the poster image?

film data:
Title: Sex in the Comix, 2012
IMDB #:  tt2403427
Poster image link:
https://ia.media-imdb.com/images/M/MV5BMjA1MjY1MTQ4NV5BMl5BanBnXkFtZTgwMzc5NjMwNzE@._V1_.jpg

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
Win 10 Pro x64

**Comment by jimlynnjulian** [comment]
I found a workaround. I used Media Companion, a related software, to make the change.

**Comment by mlaggner** [comment]
you can for example, scrape all movie meta data with TMDB;
after that, go into the movie editor (double click the movie entry in the table), click on the poster and insert the url into the text field on the bottom and click download image.
After that you get the image from the url in the upper area for being chosen as artwork. Select that and hit the OK button and everything is fine
