### ISSUE TITLE
Edit Movie For Collection Title

### ISSUE THREAD

**Issue by OldMan100** [tinyMediaManager/tinyMediaManager#277]
Version: 3.0-SNAPSHOT
Build: 2018-03-31 00:21
OS: Windows 7 6.1
JDK: 1.8.0_162 amd64 Oracle Corporation

__What is the actual behaviour?__

In Movieset, Clicking 'Edit Movie' Causes The Problem Detected Window To Pop Up. When You Right-Click On The The Collection Title, Ex. Babylon Collection, Star Wars Collection.

__What is the expected behaviour?__

Nothing Should Happen.  Right-Clicking 'Edit Movie' On The Collection Title Should Have The Same Effect As Right-Clicking 'Edit Movieset' On The Actual Movie Titles Under The Collection Title.

__Steps to reproduce:__

Go To MovieSet Section, Right-Click Any Collection Title, Click 'Edit Movie'.

__Additional__

Log Attached

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1865777/tmm_logs.zip)

**Comment by mlaggner** [comment]
should be fixed in the next build
