### ISSUE TITLE
Problem with scrape extrafanart

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#278]
Version: 2.9.8-SNAPSHOT - NIGHTLY
Build: 2018-04-02 23:03
OS: Windows 7 6.1
JDK: 1.8.0_161 amd64 Oracle Corporation

Hello
Two questions:
1. At the moment the fanart has the option to choose 1920 or 1280 or 300 and TMM 3 3840. Is it possible to add the option to download all graphics to the extrafanart folder, regardless of size? And options for downloading many posters to the extrafanart folder?
2. For a week I have a problem with downloading extrafanart, quite often it will download 1 or 2 or not at all. Then, to try again, I have to remove the movie from the database and load it again and again it does not react to downloading. I do not know if this is a TMM or FanartTV problem. With fanartTV pulls hard but manually from the site is OK.

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1889457/tmm_logs.zip)

description
It seems that the problem is with downloading from the site Fanart.TV. Graphics are loading slowly and from Movie.DB quickly. Then when downloading, if TMM encounters a download problem (probably Fanart.TV) - it stops downloading the next graphics. I tried to disable Fanart.TV in settings - from Movie.DB it downloads normally. However, it is a pity some fanarts from Fanart.TV :). It can make an option in the TMM settings to change the order in which the graphics are loaded. Now is the first FanartTV second the moviedb (reverse order)

**Comment by mlaggner** [comment]
1. why would you need the extrafanart in another dimension as you have chosen the main fanart? sounds inconsistent to me..

2. as far as I could see, fanart.tv has connect problems:

```
2018-04-09 11:36:50,121 INFO  [SwingWorker-pool-4-thread-3] org.tinymediamanager.scraper.http.Url:304 - aborted request: https://assets.fanart.tv/preview/movies/71859/moviebackground/we-need-to-talk-about-kevin-51ac996ab5eff.jpg ; connect timed out
```

I see the connect timed out several times here...
I could imagine that it looks like the download aborted, but tmm downloads images file by file; and if (for example) the first 10 files run into a timeout, it takes ages until urls get downloaded, where the servers react faster..
Changing the order would not make any difference since the other service may also fail sometimes ;)

**Comment by Zwanzig2** [comment]
1. some 720p (mainly in older movies) are simply of better quality and I can then increase the resolution. Some of them, despite the fact that 1080p is just a frame from the movie, is inefficiently enlarged. Main fanart - OK, it's about extrafanart. But no matter, I can handle it manually :)

2. the main problem. If I observed it correctly - it first downloads from fanarttv, if it has a problem - it does not download any more fanarts. Maybe it should skip those with download problems and download the next ones.

**Comment by mlaggner** [comment]
1. The problem here is that we act in an 1:n environment; if I get e.g. 1 fanart in 1080p and I will continue to get lower fanarts (just to get them), I probably will fetch the same fanart in 720p - this will create duplicates.
The only thing I can imagine is: just as for main fanarts, if there has no extra fanart been found for the desired size, just look in another size for extra fanarts.. 
would that be ok?

2. after looking at the code (and your logs) I have to say that I found no indicator that the queue is being aborted on error. In the MovieExtraImageDownloader and ImageChooser there is a loop over all found urls for fetching them. I do no see any constellation which can abort this queue...

**Comment by Zwanzig2** [comment]
ad1. OK, do not bother about it. This is not a problem, I can do it manually. I edit the movie, mark all fans and download, then remove duplicates and "good" 720p increase the resolution.

ad2. I do not know what the problem is? Turn on - find fanart - the preview will show me eg 20 images, I will select all - OK. The program works but sometimes (quite often) the extrafanart folder has 1-4 images + damaged image (ie .jpg file). When I want to download again to have them all - TMM does not download, I have to remove the video from the database and load it again. Sometimes it will be possible to download all the images.

Two more things:
I also use my own fanarts in the extrafanart folder. If I enable "find the missing graphics" it will actually clean my graphics (in extrafanart) and replace them with new ones (others like: logo, clerart and main fanart remain unchanged).

Function: auto close image chooser, when no image was found (= cancel action) - Super!, But how to choose your own graphics?

**Comment by Zwanzig2** [comment]
Downloading almost impossible graphics. I give logs and screenshots again
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1900445/tmm_logs.zip)
search result of fanarts in TMM:
![111](https://user-images.githubusercontent.com/23637884/38642098-50a8b1ae-3dd9-11e8-842f-006549a2a769.jpg)
result after downloading in extrafanart:
![2222](https://user-images.githubusercontent.com/23637884/38642139-6f1bba78-3dd9-11e8-99af-e372b9b41c5c.jpg)

**Comment by mlaggner** [comment]
okay, looks like a HTTP 500 from fanart.tv causes an exception which aborts the loop.
I'll rewrite the look to catch such errors

**Comment by Zwanzig2** [comment]
Ok, thanks for your patience :),
Occasionally I try TMM v3 there is also the same problem.

Function: auto close image chooser, when no image was found (= cancel action) - Super!, But how to choose your own graphics?"

**Comment by myron0815** [comment]
hmm.. ok, good point; never thought of that.
I usually do not download manual pictures, so there is a benefit to not need to abort 10 times per movie...
(Having many old movies where there's nothing beside poster)

But yes, we should further discuss that... or if the chaning then in movie edit might be enough... TBD

**Comment by myron0815** [comment]
reverted.
Thx for testing ^^
might find another way but for not it stays as-is.

**Comment by Zwanzig2** [comment]
Hello
I installed the latest TMM 2.9.8 build from 14/04/2018
1. "fix: downloading extrafanart / extrathumbs after network failures" has still not helped problems. I do not download graphics automatically anymore, because I can never be sure if I download. I need to control every folder with graphics and fanarttv. It seems to me that this will be Fanarttv plugin -
https://forum.kodi.tv/showthread.php?tid=330804
because he downloads without problems directly from the site. After turning off the fanarttv plugin - TMM works instantly.
2. "auto close image chooser, when no image was found" - I thought we would discuss it again :). The idea was good - you do not have to close each window manually - it makes work easier, but your own graphics can not be inserted. You can copy it manually to a folder and change its name. On the other hand, with a well-functioning graphics download, if you turn on the machine - there is no need to look around and close the windows. If there is nothing, I choose it manually.
I have set to automatically download and then manually correct - that is, I do not need "auto close".
However, at the moment with problems with downloading from fanarttv, I'm never sure if the graphics on the site is missing or only failed to download.

**Comment by mlaggner** [comment]
the API calls for fanart.tv contact an other host than the website. I suppose the API servers have connection problems or too much load..
We cannot do anything here - time will tell.
