### ISSUE TITLE
Update Data Sources

### ISSUE THREAD

**Issue by slacker247** [tinyMediaManager/tinyMediaManager#28]
__What TMM version are you using?__
2.7.5 Snapshot

__release, pre-release, nightly, or directly from GitHub/branch?__
direct from github / master

__What is the actual behaviour?__
Not adding new dvds in the defined source data dir

__What is the expected behaviour?__
should add the new dvds in the defined source data dir

__Steps to reproduce:__
- Check the below - it's the fix

__Additional__

Here's the fix:
file : \tinyMediaManager\src\main\java\org\tinymediamanager\core\movie\tasks\MovieUpdateDatasourceTask.java
line : 161
--- Change to:
                String ext = FilenameUtils.getExtension(file.getName());
              if (Globals.settings.getVideoFileType().contains("." + ext.toLowerCase())) {
// notice the extension is converted to lower case.

**Comment by myron0815** [comment]
Thx.
Could you please try the 2.8 "devel" branch (= nightly)?
We rewrote the update completely (MovieUpdateDatasoureTask**2**), it should be already fixed there...

**Comment by slacker247** [comment]
So it looks like it's missing these files.  Were they not checked in?  or am I missing a project that I need to include?

Missing Files:
org.tinymediamanager.scraper.util.PluginManager
org.tinymediamanager.scraper.util.StrgUtils
org.tinymediamanager.scraper.http.*
org.tinymediamanager.scraper.entities.*
org.tinymediamanager.scraper.MediaSearchOptions
org.tinymediamanager.scraper.MediaSearchResult
org.tinymediamanager.scraper.mediaprovider.*
org.tinymediamanager.scraper.MediaMetadata
org.tinymediamanager.scraper.MediaScrapeOptions
org.tinymediamanager.scraper.SubtitleSearchOptions
org.tinymediamanager.scraper.SubtitleSearchResult
org.tinymediamanager.scraper.util.ApiKey
org.tinymediamanager.scraper.MediaProviderInfo
org.tinymediamanager.scraper.util.UrlUtil
org.tinymediamanager.scraper.config.*

**Comment by myron0815** [comment]
ah well, maven could not resolve/download our API project :)

because current devel has all SNAPSHOTs set.
i guess, you need to setup our snapshot repo in Maven (see https://github.com/tinyMediaManager/tinyMediaManager/blob/master/README.md bottom page)
Then all the dependencies should be resolved...

**Comment by slacker247** [comment]
ok, tested it with the new build.  Looks to be working.  Is there a time frame in which you will be releasing this build?  or should I just use the source build as my current version for a while?

**Comment by mlaggner** [comment]
we need some more time for this version to be finished (a few weeks)
The source build may contain severe bugs und thus _should_ not be used with productive data ;)
