### ISSUE TITLE
(Enhancement) Kodi Krypton support for multiple IDs in NFO

### ISSUE THREAD

**Issue by sp1ti** [tinyMediaManager/tinyMediaManager#281]
Kodi added support for multiple identifiers for IDs in Krypton https://github.com/xbmc/xbmc/pull/10000. Can the movie NFOs be updated to include TMDB? Thank you!

```
<uniqueid type="imdb" default="true">(the ttid)</uniqueid>
<uniqueid type="tmdb" default="false">(the id)</uniqueid>
```

https://kodi.wiki/view/NFO_files/Movies

**Comment by mlaggner** [comment]
should already be possible in v3

**Comment by mlaggner** [comment]
this is a new style for ids which we do not support so far
we will include that in v3 since NFO parsing/writing is much more powerful there

**Comment by sp1ti** [comment]
Sound good, thank you!
