### ISSUE TITLE
Requests from TheTVDB.com no longer work

### ISSUE THREAD

**Issue by SPDurkee** [tinyMediaManager/tinyMediaManager#284]
__What TMM version are you using?__
2.9.8

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
lookups to TheTVDB.com no longer work

__What is the expected behaviour?__
TV images and data should be retrieved correctly.

__Steps to reproduce:__
- scrap any tv show with thetvdb as the source

__Additional__
TheTVDB.com updated their site on May 1st. So far all of the apps that connect to it, (even through the api) seem to be broken. TMM appears to have stopped working as well.

**Comment by mlaggner** [comment]
looks like everything from tvdb is down at the moment.
please also refer to the discussion at the kodi forums: https://forum.kodi.tv/showthread.php?tid=331535

**Comment by DocCaliban** [comment]
It appears they have switched off the 1.0 API with the update to the new web site
