### ISSUE TITLE
Not replacing non ASCII character

### ISSUE THREAD

**Issue by tosiek** [tinyMediaManager/tinyMediaManager#285]
__What TMM version are you using?__

2.9.10
__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
Does not replacing non ascii character: ł to l
UNICODE: U+0142
UTF-8 (hex) 	0xC5 0x82 (c582)
Windows 1250: 0xB3

__What is the expected behaviour?__
It should replace ł to l

__Steps to reproduce:__
Use in folder name ł and try to change name in dry run. Remember to check option in rename: Replace non ASCII

__Additional__
win

**Comment by mlaggner** [comment]
thanks for reporting..
looks like Java is not aware to normalize this character - I've included a workaround with https://github.com/tinyMediaManager/api-scraper/commit/2512f054eac0c3f05e60af583ba426dda0fce9dc

will be in the next version
