### ISSUE TITLE
[V3-branch] switch  font/theme at runtime

### ISSUE THREAD

**Issue by Longri** [tinyMediaManager/tinyMediaManager#289]
without restart!

**Comment by mlaggner** [comment]
how did you implement this?
Imho there is some sort of buffering somewhere - did changing that at runtime work? (also with re-layouting, ..)

**Comment by Longri** [comment]
Call UIManager.setLookAndFeel(?) again and at some Controls re layout on:
```
    @Override
    public void updateUI() {
      super.updateUI();
       ......
      }
```

**Comment by ProIcons** [comment]
This has been already discussed in backlog, and is a great addition. We lack the implementation details but We can try various things, to achieve this functionality. 

Having said that we also need to implement whats left of our backlog to finally release an open beta for v3, which is coming soon. This is a feature that we certainly want, and we will try to achieve on the following cycles. 
If you already have some sort of experience on the UI, you can always make a Pull Request with a working code on https://github.com/tinyMediaManager/tinyMediaManager-LaF . We are always happy receiving community contributions.

**Comment by mlaggner** [comment]
@Longri could you create a PR with the needed patched to achieve that?

**Comment by Longri** [comment]
I'll do it next week.

**Comment by mlaggner** [comment]
just had a look at this and the fact is:
a) changing the font is doable with a few changes
b) changing the theme would also be doable, BUT I found no way to refresh the icons (some icons for the dark theme do have other colors than the ones for the light theme). thus changing not the whole theme will create a inconsistency which I will avoid.

**Comment by mlaggner** [comment]
I am sorry to say, that the icons also depend on the font size - thus we cannot change either fonts or theme at runtime without heavily redesign the UI code (and breaking standard swing patterns) just for preventing the user to restart once after changing..
such a small benefit for the huge amount of work to be done :(
