### ISSUE TITLE
Unable to scrape episode info

### ISSUE THREAD

**Issue by akyag** [tinyMediaManager/tinyMediaManager#29]
Version: 2.8-SNAPSHOT - NIGHTLY
Build: 2016-04-25 23:03
OS: Linux 4.4.7-300.fc23.x86_64
JDK: 1.8.0_91 amd64 Oracle Corporation

__What is the actual behaviour?__
Unable to scrape episodes of most of shows. some shows can be scraped and some can't.
Unable to connect to trakt yesterday so tried starting with clean installation. Unable to verify donator email

__What is the expected behaviour?__
scraping of all episodes done correctly

__Steps to reproduce:__
try scraping That '70s show

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/235933/tmm_logs.zip)

**Comment by myron0815** [comment]
We see a SSL Exception when connecting to google's app servers.
Our donation-license-generation-and-mailing is currently hosted there (will be changed!)
(You can copy the tmm.lic from another instance on same PC you have)
The only thing i found about it, was to install/update the "nss" packet? (although for J7)
http://blog.backslasher.net/java-ssl-crash.html
Does this happen with release version too?

For the scraping error - there is nothing in the logs; just updating, but no scraping.
Have no clue (yet), why you get the unknown_error... it works here...

**Comment by akyag** [comment]
Found the license file, so thats sorted. I generally have issues when starting up TMM. It get's stuck on loading GUI. I have to kill it a few times before it starts. I think I posted about that in forums before. Issue related openJDK.

About the scraping error, it's baffling actually. I have 140 shows in list. It works for some and nothing happens when I scrape certain shows. If the error was failing to reach tvdb, then all shows should be affected right?

**Comment by mlaggner** [comment]
you may have two different problems:
a) the problem with donating points to invalid/outdated SSL certificates on your system. I've tried it on a windows machine and a linux machine (arch linux) and both work
b) I've analyzed the logs and src code for your scraping problem: everything points to a (temparory) problem with thetvdb (no HTTP return code). Scraping works fine here for several different shows (and also the shows from your log). I've added some more logging in the actual nightly build - maybe they give us a hint what is the cause of this problem

**Comment by akyag** [comment]
I can visit the xml file of all episodes in browser. (*/series/73787/all/en.xml) But TMM still won't scrape it :(

**Comment by mlaggner** [comment]
please delete all your logs in the logs folder and start tmm again, and do only a scrape (please no update data sources) and attach the new logs again

**Comment by akyag** [comment]
Here you go..
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/246366/tmm_logs.zip)

**Comment by mlaggner** [comment]
please check/review your proxy settings

`2016-05-03 11:33:32,845 ERROR [main] org.tinymediamanager.core.Settings:831 - could not parse proxy port: For input string: ""`

**Comment by akyag** [comment]
![settings_111](https://cloud.githubusercontent.com/assets/7376589/14978052/c3d4a7f4-1136-11e6-8325-e687f4d61b5a.png)
Proxy settings are blank. Although I have tried to use some proxies in past to test internet connection. But after that I removed the proxies and saved the settings.

**Comment by mlaggner** [comment]
maybe you have one single space in the proxy host?

**Comment by akyag** [comment]
Haha, nope. I checked for it as soon as I saw the empty settings too. I removed proxy strings from config.xml to be sure and then generated this log.
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/246551/tmm_logs.zip)

**Comment by mlaggner** [comment]
please also try to delete to cache/url folder inside your tmm dir and try again (I think your old request is cached)

**Comment by akyag** [comment]
There was no cache/url directory. So I deleted cache directory. No luck yet :/

**Comment by mlaggner** [comment]
I've just created a new build containing a fix for the proxy settings and more logging.
Could you retry with this build?

**Comment by akyag** [comment]
Thanks, sorry for the late reply and all this trouble.. This is with new build - 
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/246888/tmm_logs.zip)

**Comment by mlaggner** [comment]
okay, now I have a clue where to look for. 
Looks like the issue described at https://github.com/square/okhttp/issues/2193

I've added the Accept-Encoding and started a new build (will be online in a few minutes).

But I am pretty clueless why everything worked for me but not for you..

**Comment by akyag** [comment]
it works for most show except this damn show! Check this - 
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/247140/tmm_logs.zip)

**Comment by mlaggner** [comment]
just for your information: I am migrating to the new TheTVDB API right now and these problems should not occur any more with the new implementation.

**Comment by akyag** [comment]
Great.. I am going to use "tmm_2.8-SNAPSHOT_8b73824_linux" till then. That's the build that works for me for rest of the shows..

**Comment by mlaggner** [comment]
I've started migrating to the new API but that seems to be much weaker than API v1...
Until TheTVDb changes some things in the API v2, I cannot switch without losing functionality we already have with v1.
But I've upgraded the http library we use - could you try again with the latest nightly build?

**Comment by akyag** [comment]
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/256424/tmm_logs.zip)
Tried, but no luck yet.

**Comment by mlaggner** [comment]
I've created a new build - could you try again please?

**Comment by akyag** [comment]
Yessss... It's working! Thanks so much :) I will test some more before closing the issue.

**Comment by akyag** [comment]
Tried by importing another season of That '70s show.. Working as expected. Closing...
