### ISSUE TITLE
Bulk editing not working

### ISSUE THREAD

**Issue by Celid** [tinyMediaManager/tinyMediaManager#290]
__What TMM version are you using?__
2.9.11 on Windows 64 (wasn't working for many months before though)

__release, pre-release, nightly, or directly from GitHub/branch?__

__What is the actual behaviour?__
When I select several movies and choose bulk editing, the modal appear and I can add a genre or a tag. I then click on close. But when I go on edit movie for one of those previous movie, I see no changes. 

__What is the expected behaviour?__
The tags and genres should be added in the infos of the selected movies

__Steps to reproduce:__
- select movies
- bulk editing
- add tag or genre
- close
- open edit movie
- see no change

**Comment by mlaggner** [comment]
working as expected here.. did you click the green plus button to actually assign the genre to the selected movies?

**Comment by Celid** [comment]
I have no plus button... So the bug might be a visual one. Is there a way to validate without clicking ? 

![sans titre](https://user-images.githubusercontent.com/24714954/39814033-1c238e34-5393-11e8-9729-359b8d580474.png)

**Comment by mlaggner** [comment]
omg - you must have an entry in some of the dropdowns which is expanding the whole dialog..
it should look like:

![image](https://user-images.githubusercontent.com/1523778/39814890-6fa8f26c-5396-11e8-8254-e4937de47390.png)

I'll try to find out how I can prevent the dialog to expand this far

**Comment by Celid** [comment]
Oh yeah, I've deleted some bad movie sets that were far too long because of bad copy paste, and now I see them. Thanks for your help !

**Comment by mlaggner** [comment]
I'd still making some changes here to prevent such a behavior

**Comment by Celid** [comment]
Thanks ! Do you want me to close the issue ?

**Comment by mlaggner** [comment]
has been fixed with https://github.com/tinyMediaManager/tinyMediaManager/commit/1a26ba41826b2a79eb0de1000f12817fa848225d
