### ISSUE TITLE
Watched flag in TMM is not updated from NFO file?

### ISSUE THREAD

**Issue by igormu** [tinyMediaManager/tinyMediaManager#291]
__What TMM version are you using?__
2.9.11

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
Watched state in TMM does not get updated from NFO file edit.

__What is the expected behaviour?__
Watched state in TMM is updated to new value if the NFO file was updated.

__Steps to reproduce:__
- Add TV show or movie to TMM
- Scrape it to produce NFO file for it
- Edit NFO file , set <watched>true</watched>, save file
- (Optional) Restart TMM
- Look at TMM entry again, it is still not marked as "Watched"

--------
Right now toggling "Watched" state will update NFO file which is great. However if done in opposite direction, the TMM state itself is not updated.

This means if using "Kodi" export library functionality (which updates the NFO files on the disk to be the latest) then the watched state will be out-of-sync with TMM.

**Comment by mlaggner** [comment]
should aready be solved in v3 - won't be implemented in v2

**Comment by igormu** [comment]
Thanks!
