### ISSUE TITLE
Scraping Episode Information Bug

### ISSUE THREAD

**Issue by Xgox** [tinyMediaManager/tinyMediaManager#292]
Version: 2.9.11
Build: 2018-05-05 08:12
OS: Windows 10 10.0
JDK: 1.8.0_171 x86 Oracle Corporation

__What is the actual behaviour?__

"Problem detected" pops up when trying to scrape episode metadata

__What is the expected behaviour?__

To scrape the information properly

__Steps to reproduce:__

Try scraping episode metadata for a new episode?

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/1999975/tmm_logs.zip)

__Additional__
Have you attached the logfile from the day it happened?

**Comment by myron0815** [comment]
Thx.
Seems, TVDB is having some issues... and when it is not available on startup, it crashes.
Try restarting TMM, currently it is working.

And we try to be more gracefully to this specific case...
