### ISSUE TITLE
Movie rename functionality

### ISSUE THREAD

**Issue by thwaller** [tinyMediaManager/tinyMediaManager#293]
Version: 2.9.11-SNAPSHOT - PRE-RELEASE
Build: 2018-05-05 07:24
OS: Linux 4.15.0-17-generic
JDK: 10.0.1 amd64 Oracle Corporation

When I use the rename feature for movies (shows untested), it does not seem to accommodate subfolders. For example, I have a large collection, so I have the "movies" folder mapped into tMM. Now, inside that folder, I have subfolders like A, B, C-D, E, etc. Inside of those folders, I have movie folders, which all contain their respective movie.

Now... when I use the rename functionality, if I have a movie such as /movies/D/Dracula/dracula.mp4, when I rename it using the feature, it is changed to /movies/Dracula/dracula.mp4. So it appears to only be able to use the 'home' folder as the mapped folder, then a subfolder for each movie. What I am trying to find is an option for the rename feature to respect the containing directory and only change the movie directory.

I did not attach logs or the specific questions asked as I do not believe they apply. This is not really a bug as it is doing what I believe it is programmed to, and my issue here is more of an oversight in functionality, or even a feature request. The only solution I can think of at this time is to map in each letter subfolder individually, which seems silly. Hope this makes sense, I will provide anything further you may want.

**Comment by myron0815** [comment]
check renamer settings and play around with our variables....
https://www.tinymediamanager.org/blog/reworked-renamer-settingscapabitilies/

**Comment by thwaller** [comment]
Unless I am completely missing it, I see nothing that tells it to remain in the folder that it is in, aside from a rename (potentially) of its own containing folder.

**Comment by myron0815** [comment]
ah... you want to keep the folder?
Didn't read that out of your text....

Just empty the folder pattern should imho keep it as-is...

**Comment by thwaller** [comment]
That may work, but then it will not do the rename I want. Here is an example of desired bahaviour:
/movies/D/Dracula/dracula movie.mp4 --> /movies/D/Dracula (1992)/dracula movie.mp4
not what it does now:
/movies/D/Dracula/dracula movie.mp4 --> /movies/Dracula (1992)/dracula movie.mp4

**Comment by myron0815** [comment]
so you do not want to keep the folder as-is.
alright :|

Try "$1\$T ($Y)" as folder?
check example afterwards?

**Comment by thwaller** [comment]
I use the renaming function to keep the movie folders proper as shown above. I leave the movie file names as-is. I did look at the option you now suggest, and it will work only somewhat. The issue is movies that start with a period, # or a foreign character, as well as ones like stated above where the folder is C-D and not just C and D folders....

If there is no other option, I can work with what you suggest using the first letter variable, I currently just store all those (numbers, symbols, etc) starting character movies in a single folder.

**Comment by mlaggner** [comment]
tmm is designed to organize your library, so you have two options:

a) let tmm organize your folder structure
b) don't let tmm organize your folder structure

anything in between will be a half baked solution (beside that handling will be almost impossible)

**Comment by thwaller** [comment]
I think we are all good with the above notes. I really do not see using the same 'home' folder as a "half baked solution", nor is it hard to handle as I do audio tagging / organizing all the time with such functionality without any issues. But I can see it as out of scope a bit as tMM is intended to be small/simplistic/etc. And I do agree that just letting tMM do the organizing as it wants (or with few options) is simplistic, which is in scope, and as said above, it seems to suite well enough.

**Comment by mlaggner** [comment]
sorry, didn't want to sound rude..

you have a _clean_ folder structure where such a logic would work. But we have to respect also really messy set ups (as we've often seen before), which will probably cause problems here..

the problem here is, that the renamer is extremely complex (because we respect every setup like multi movie folder, nested folders, ...) and generating the _whole_ folder name is one of our restrictions to work clean..

But I will still think about that in a free minute because you are the second one which requested this feature..

**Comment by mlaggner** [comment]
and what about multi movie dirs?

* H \
  * Upload \
    * by me \
      * Movie1.avi
      * Movie2.avi

the existing logic would create

* H \
  * Movie 1 \
    * Movie1.avi
  * Movie 2 \
    * Movie2.avi

with your setting ticket, what would you expect here? the folder _by me_ to be renamed to movie1/2?
a folder Movie 1 to be created beneath _Upload_ ?

these are the things we need to consider :D

**Comment by thwaller** [comment]
What I mean is the option would be a checkbox to
1) retain the full path directory structure
2) do not retain the full path directory structure.

So, the result from above:
1) H \ Upload \ by me \
Movie 1 \ Movie1.avi
Movie 2 \ Movie2.avi

2) this is as you stated above with existing logic.

**Comment by mlaggner** [comment]
with your example, you changed the path structure!
Movie 1: **H\Upload\by me\** changed to **H\Upload\by me\Movie 1\**

with your dracula example above that would result in:
**/movies/D/Dracula/**dracula movie.mp4 --> **/movies/D/Dracula/Dracula/**dracula movie.mp4

so to be consistent we must make sure

a) within a single movie the folder must only change the name of the last subfolder
/movies/D/**Dracula**/dracula movie.mp4 --> /movies/D/**Dracula (1992)**/dracula movie.mp4

b) within a multi movie folder we create a subfolder for each movie?
/movies/Upload/by me/Movie1.avi --> /movies/Upload/by me/**Movie 1**/Movie1.avi

do you aggree?

**Comment by myron0815** [comment]
what about normalizing movies like ".45", "0815", "11:22" into a "0-9" folder when specifying $1
And/or "Æon Flux" to A (currently we take the first ASCII character -> O)
And maybe others which could not be normalized to some "#" folder?

Keeping the current movie folder, and just rename with folder/file is imho not doable.
Try renaming a pattern with subfolder (like "$1\$T") multiple times.
We would always move the movie again on $1 subfolder deeper.
And i'm against of stripping all the possible subfolders from folder pattern - this always makes things unpredicable to the end user!

**Comment by thwaller** [comment]
> what about normalizing movies like ".45", "0815", "11:22" into a "0-9" folder when specifying $1?
And/or "Æon Flux" to A (currently we take the first alpha character -> O)
And maybe others which could not be normalized to some "#" folder?

All of that above is very close to what I had to start with. Sticking with your description, only difference I would have is ".45" would go in the # folder, since the period is not a number to fit into 0-9. The "Æ"would also be in the # folder (for me), but I see a strong case for its equiv to take over and use "A".

To use a more real explanation... if I write a script to search for movies, and the name of the movie is "Æon Flux"", that is what I am searching for, and Æ is a valid character, just not ASCII. So my personal logic is that the name, as-is, is a valid name, so I would have no thoughts on changing it in special character handling.

But as I said before though, using the method above that myron0815 and I ended with does work, and it does keep it simple. When I do this organizing audio (on a much larger volume), I always open the directory I want to consider 'root' and rename from there. Meaning that I can only rename the directories within that folder. This cannot apply here though... there is not directory tree browsing in tMM, and I am not so sure there would need to be.

**Comment by myron0815** [comment]
did a small change for v2 with https://github.com/tinyMediaManager/tinyMediaManager/commit/91e586c97b96fab544a732e904eb9ae3d0274f83
If you have set the "replace ascii characters" in settings, the $1 now adheares this.
We now would get the "Æon Flux" to A, or to first latin char O.
Would not change more in v2, since this might break many existing installations...

But needs to be rethinked/changed in v3

**Comment by thwaller** [comment]
I was thinking (on my own personal use) that another sort of solution would be to be able to have a separate rename profile for different data sources. Or maybe easier, to be able to have different rename profiles, and when you select to rename, you select which profile to use.

Example of this would be in audio taggers... you can select the format to use when auto-renaming the audio files for example.

I am only trying to think on how to get a nice improvement while still keeping it simple and easy. I am not aware of the other request for such a thing, but maybe that may help there too?

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
