### ISSUE TITLE
can you add douban  scrape ？

### ISSUE THREAD

**Issue by SelfEnough** [tinyMediaManager/tinyMediaManager#295]
__What TMM version are you using?__
ALPHA 3  （2.9.11 also）

some info still scraped incomplete with IMDB or TMDB 
can you add douban  scrape ？
Chinese users will very happy to see that

**Comment by mlaggner** [comment]
I am sorry - writing a scraper for a site where we cannot read any character will be impossible for us...
If there is a Chinese developer which does that for us we will accept a pull request
