### ISSUE TITLE
Can't scrap The Expanse S03E06

### ISSUE THREAD

**Issue by mostm** [tinyMediaManager/tinyMediaManager#296]
Version: 2.9.11
Build: 2018-05-05 08:12
OS: Windows 10 10.0
JDK: 1.8.0_161 amd64 Oracle Corporation

__What is the expected behaviour?__

Properly scrap episode

__What is the actual behaviour?__

It doesn't edit/add any metainformation, so, it doesn't scrap

__Steps to reproduce:__

1. Download episode
2. Add in Data Source
3. Try to scrap

__Additional__
Have you attached the logfile from the day it happened?
Yeah, here they are: [tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2018466/tmm_logs.zip)

**Comment by mostm** [comment]
Also, i scrapped it successfully yesterday without latest episode

**Comment by mostm** [comment]
Seems like Kodi addons don't work as expected, switched to The TVDB and everything scrapped successfully

**Comment by mlaggner** [comment]
we cannot give support for the kodi addons, but the tmm scrapers should work as expected

**Comment by myron0815** [comment]
The errors in your logfile look interesting enough, to have a closer look.
Did some changes to our Kodi scraper
You might want to try v3 or nightly tomorrow...
Always good to have some testers before release ;)
