### ISSUE TITLE
Trying to add genre and tag to movie does nothing.

### ISSUE THREAD

**Issue by J4bber** [tinyMediaManager/tinyMediaManager#298]
Version: 2.9.11
Build: 2018-05-05 08:12
OS: Windows 10 10.0
JDK: 1.8.0_161 x86 Oracle Corporation

__What is the actual behaviour?__
Nothing happens

__What is the expected behaviour?__
Update Tags and Genre

__Steps to reproduce:__
Editing a movie.  Clicked the details 2, then the + to add Genres, nothing happens.  Tried same with Tags, nothing happens
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2043182/tmm_logs.zip)

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
did you enter/choose a genre/tag from the dropdown below the list?
works here..

**Comment by J4bber** [comment]
Completely missed the dropdown :(   Thanks!
