### ISSUE TITLE
[Feature Request] Music scraper for MP3 and FLAC Albums

### ISSUE THREAD

**Issue by juanrodgil** [tinyMediaManager/tinyMediaManager#300]
With the better support of Plex for albums (PlexAmp and Android Auto support), i think is a good idea to support a new category of multimedia files.

__What is the expected behaviour?__

Use the musicbrainz API to scrape mp3, ogg and flac files.

https://musicbrainz.org/doc/Development/XML_Web_Service/Version_2
https://musicbrainz.org/doc/Other_Databases

**Comment by myron0815** [comment]
Well, although i do like the idea to scrape my mp3s with TMM, this would be a loooong way :|
Focus is still on movies & TV shows... and i guess for a longer term...

**Comment by Lonerider2010** [comment]
Using KODI, I also would like to support the request for a music scraper.
Maybe it will take not that long time, as MusicBrainz provides also a well documented library for accessing their data, see [https://musicbrainz.org/doc/libmusicbrainz](url).
They also deliver Picard, an open source music tagger using this library, see [https://github.com/metabrainz/picard](url).
