### ISSUE TITLE
[V3] Weblate incorrectly displays Settings.mediaplayer in Russian

### ISSUE THREAD

**Issue by mostm** [tinyMediaManager/tinyMediaManager#303]
__What is the actual behaviour?__
Weblate squished `Settings.mediaplayer` into `Settings.languagehint` in Russian

__What is the expected behaviour?__
Weblate should have separate `Settings.mediaplayer` and `Settings.languagehint`

__Steps to reproduce:__
- Open Russian/translate in Weblate
- Search for Context: Settings.languagehint
- Watch at Source string

__Screenshot__
![image](https://user-images.githubusercontent.com/23155159/40769551-b3b47ba6-64d1-11e8-9b0c-2aeecb634c4b.png)

**Comment by mlaggner** [comment]
you are right - there has been a copy&paste error in the messages.properties.
will be fixed in weblate (for all languages!) as soon as I push this file the next time
