### ISSUE TITLE
[3.0-SNAPSHOT] Automatic Rename not working or saved

### ISSUE THREAD

**Issue by rastarr** [tinyMediaManager/tinyMediaManager#307]
Version: 3.0-SNAPSHOT
Build: 2018-06-06 00:21
OS: Mac OS X 10.13.4
JDK: 1.8.0_131 x86_64 Oracle Corporation

__What is the actual behaviour?__
Under 'Settings' > Movies
Automatic tasks for 'Automatic rename' does not appear to work
nor does the setting get saved out to reload on the next open of the application

![settings-1](https://user-images.githubusercontent.com/2160922/41144154-2631cb2a-6b26-11e8-9ab5-b397c2c366d1.jpg)

__What is the expected behaviour?__
umm, well, automatic rename should rename the folder and files as well as the setting to be saved for persistant reloading

__Steps to reproduce:__
refer above and screenshot

**Comment by mlaggner** [comment]
should be fixed with https://github.com/tinyMediaManager/tinyMediaManager/commit/ee782fbe2b19b6fb3b51c3cb6caa29488065d7aa
