### ISSUE TITLE
Build of tinyMediaManager v3.0

### ISSUE THREAD

**Issue by Lonerider2010** [tinyMediaManager/tinyMediaManager#308]
__What TMM version are you using?__
V3.0

__release, pre-release, nightly, or directly from GitHub/branch?__
directly from GitHub branch v3

__What is the actual behaviour?__
When built according to README.md, got the following messages:
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/tinymediamanager/tmm-parent/1.0/tmm-parent-1.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.tinymediamanager:tinyMediaManager:2.9.13-SNAPSHOT: Could not transfer artifact org.tinymediamanager:tmm-parent:pom:1.0 from/to central (https://repo.maven.apache.org/maven2): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and 'parent.relativePath' points at wrong local POM @ line 18, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.tinymediamanager:tinyMediaManager:2.9.13-SNAPSHOT (/home/dietmar/test/tinyMediaManager/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.tinymediamanager:tinyMediaManager:2.9.13-SNAPSHOT: Could not transfer artifact org.tinymediamanager:tmm-parent:pom:1.0 from/to central (https://repo.maven.apache.org/maven2): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and 'parent.relativePath' points at wrong local POM @ line 18, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

__What is the expected behaviour?__
an error-free build

__Steps to reproduce:__
- first:              $ git clone https://github.com/tinyMediaManager/tinyMediaManager.git
- second         $ mvn package
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
OS: 
       Xubuntu 18.04
mvn: 
       mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-22-generic", arch: "amd64", family: "unix"

**Comment by mlaggner** [comment]
a) looks like you want to build the master branch.. you may need a `git checkout v3` before running maven
b) weird exception - but I think you find a solution at: https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty

btw: there are finished builds for v3 at http://v3-alpha.tinymediamanager.org

**Comment by Lonerider2010** [comment]
Thanks for these hints. That helped me a lot.
