### ISSUE TITLE
no splashscreen in java.library.path

### ISSUE THREAD

**Issue by stooj** [tinyMediaManager/tinyMediaManager#309]
__What TMM version are you using?__

version=2.9.12
build=597414a
date=2018-05-29 18\:55

__release, pre-release, nightly, or directly from GitHub/branch?__

release

__What is the actual behaviour?__

tinyMediaManager crashes on launch with the following error message:

`no splashscreen in java.library.path`

__What is the expected behaviour?__

tinyMediaManager should launch.

__Steps to reproduce:__

- Run `./tinyMediaManager.sh` from a bash terminal

__Additional__

Log file is here: [tmm.log](https://github.com/tinyMediaManager/tinyMediaManager/files/2086794/tmm.log)

The launcher log is here: [launcher.log](https://github.com/tinyMediaManager/tinyMediaManager/files/2086802/launcher.log)

```bash
cat /etc/issue.net

Ubuntu 18.04 LTS
```

```bash
java --version

openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)
```

The splashscreen file does exist in my directory - here's the directory listing:

```
tree -L 1

.
├── cache
├── changelog.txt
├── data
├── digest2.txt
├── digest.txt
├── env.txt
├── getdown.jar
├── getdown-new.jar
├── getdown.txt
├── gettingdown.lock
├── jspf.cache
├── launcher.log
├── lib
├── LICENSE
├── locale
├── logs
├── native
├── plugins
├── proxy.txt
├── splashscreen.png
├── templates
├── tinyMediaManagerCMD.sh
├── tinyMediaManager.desktop
├── tinyMediaManager.sh
├── tinyMediaManagerUpdater.sh
├── tmm.jar
├── tmm.png
└── version

8 directories, 20 files
```

Thanks :)

**Comment by mlaggner** [comment]
please use Java 8 for tmm - Java 9+ broke many things (that's why Java 8 is still the _stable_ JRE)

**Comment by mlaggner** [comment]
if only java headleass is installed this error may also occur..
nevertheless I am closing this issue
