### ISSUE TITLE
Problem with add data origen and save button.

### ISSUE THREAD

**Issue by rabtron** [tinyMediaManager/tinyMediaManager#31]
Version: 2.7.4
Build: 2016-04-01 19:01
OS: Mac OS X 10.11.4
JDK: 1.8.0_91 x86_64 Oracle Corporation

__What is the actual behaviour?__
It hangs when I try to add data source

__What is the expected behaviour?__
to add data source

__Steps to reproduce:__
Go to Menu
Tinymediamanager
Settings
add data origen

__Additional__
I can´t add log because when I try to save the log the progam also is crashes.
I have OSX El Capitan
Have you attached the logfile from the day it happened?
I put on here the log that my computer reports for apple.

Date/Time:       2016-05-10 11:21:52 +0200
OS Version:      Mac OS X 10.11.4 (Build 15E65)
Architecture:    x86_64h
Report Version:  22

Command:         org.tinymediamanager.TinyMediaManager
Path:            /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
Version:         ??? (???)
Parent:          launchd [1]
PID:             5489

Event:           hang
Duration:        3.00s (process was unresponsive for 13 seconds before sampling)
Steps:           30 (100ms sampling interval)

Hardware model:  MacBookAir6,2
Active cpus:     4

Fan speed:       1223 rpm

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------

Heaviest stack for the main thread of the target process:
  30  start + 52 (java + 6660) [0x10caada04]
  30  main + 101 (java + 33984) [0x10cab44c0]
  30  JLI_Launch + 1952 (java + 8620) [0x10caae1ac]
  30  CreateExecutionEnvironment + 871 (java + 25699) [0x10cab2463]
  30  CFRunLoopRunSpecific + 296 (CoreFoundation + 560856) [0x7fff81e3ded8]
  30  __CFRunLoopRun + 927 (CoreFoundation + 562399) [0x7fff81e3e4df]
  30  __CFRunLoopDoSources0 + 556 (CoreFoundation + 565180) [0x7fff81e3efbc]
  30  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17 (CoreFoundation + 698497) [0x7fff81e5f881]
  30  __NSThreadPerformPerform + 279 (Foundation + 487262) [0x7fff8a3a5f5e]
  30  ??? (<CA27E60D-3E7D-3B94-BA0F-2E7DBD5255C7> + 28000) [0x120687d60]
  30  ??? (<2E591401-2665-37E3-BEB7-799D7C5E4BA4> + 226776) [0x1220145d8]
  30  ??? (<915C0924-3D8D-3838-BC54-C581FB1083A0> + 8525) [0x12203814d]
  30  -[NSApplication run] + 682 (AppKit + 249476) [0x7fff8d6d9e84]
  30  ??? (<915C0924-3D8D-3838-BC54-C581FB1083A0> + 9130) [0x1220383aa]
  30  -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454 (AppKit + 295722) [0x7fff8d6e532a]
  30  _DPSNextEvent + 1067 (AppKit + 298746) [0x7fff8d6e5efa]
  30  _BlockUntilNextEventMatchingListInModeWithFilter + 71 (HIToolbox + 198063) [0x7fff92dd35af]
  30  ReceiveNextEventCommon + 184 (HIToolbox + 198263) [0x7fff92dd3677]
  30  RunCurrentEventLoopInMode + 235 (HIToolbox + 198965) [0x7fff92dd3935]
  30  CFRunLoopRunSpecific + 296 (CoreFoundation + 560856) [0x7fff81e3ded8]
  30  __CFRunLoopRun + 927 (CoreFoundation + 562399) [0x7fff81e3e4df]
  30  __CFRunLoopDoSources0 + 556 (CoreFoundation + 565180) [0x7fff81e3efbc]
  30  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17 (CoreFoundation + 698497) [0x7fff81e5f881]
  30  __NSThreadPerformPerform + 279 (Foundation + 487262) [0x7fff8a3a5f5e]
  30  ??? (<1FAB41FC-372C-389F-BBE9-AB6B71611B6B> + 196881) [0x1254ec111]
  30  -[NSWindow(NSWindowAccessibility) accessibilityFocusedUIElement] + 118 (AppKit + 8559927) [0x7fff8dec6d37]
  30  ??? (<1FAB41FC-372C-389F-BBE9-AB6B71611B6B> + 22201) [0x1254c16b9]
  30  ??? (<1FAB41FC-372C-389F-BBE9-AB6B71611B6B> + 197471) [0x1254ec35f]
  30  ??? (<CA27E60D-3E7D-3B94-BA0F-2E7DBD5255C7> + 16326) [0x120684fc6]
  30  ??? (<3F27CF0D-DD51-34FE-93D6-DED02BC69CFE> + 3250295) [0x10d919877]
  30  ??? (<3F27CF0D-DD51-34FE-93D6-DED02BC69CFE> + 3289022) [0x10d922fbe]
  30  ??? (<3F27CF0D-DD51-34FE-93D6-DED02BC69CFE> + 3064294) [0x10d8ec1e6]
  30  ??? (<3F27CF0D-DD51-34FE-93D6-DED02BC69CFE> + 16336807) [0x10e5947a7]
  30  ??? (<3F27CF0D-DD51-34FE-93D6-DED02BC69CFE> + 16367680) [0x10e59c040]
  30  ??? (<3F27CF0D-DD51-34FE-93D6-DED02BC69CFE> + 16367680) [0x10e59c040]
  30  ??? (<3F27CF0D-DD51-34FE-93D6-DED02BC69CFE> + 16368317) [0x10e59c2bd]
  30  ??? (<3F27CF0D-DD51-34FE-93D6-DED02BC69CFE> + 16368317) [0x10e59c2bd]
  30  ??? (<3F27CF0D-DD51-34FE-93D6-DED02BC69CFE> + 16368317) [0x10e59c2bd]
  30  ??? (<3F27CF0D-DD51-34FE-93D6-DED02BC69CFE> + 16431572) [0x10e5ab9d4]
  30  ??? (<1FAB41FC-372C-389F-BBE9-AB6B71611B6B> + 214993) [0x1254f07d1]
  30  -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 270 (Foundation + 151001) [0x7fff8a353dd9]
  30  CFRunLoopRunSpecific + 296 (CoreFoundation + 560856) [0x7fff81e3ded8]
  29  __CFRunLoopRun + 1356 (CoreFoundation + 562828) [0x7fff81e3e68c]
  29  __CFRunLoopServiceMachPort + 212 (CoreFoundation + 565700) [0x7fff81e3f1c4]
  29  mach_msg_trap + 10 (libsystem_kernel.dylib + 69490) [0x7fff85661f72]
 *29  ipc_mqueue_receive_continue + 0 (kernel + 812624) [0xffffff80002c6650]

Process:         org.tinymediamanager.TinyMediaManager [5489]
Path:            /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
Architecture:    x86_64
Parent:          launchd [1]
UID:             501
Task size:       57752 pages (+46)
CPU Time:        0.196s
Note:            Unresponsive for 13 seconds before sampling
Note:            5 idle work queue threads omitted

**Comment by mlaggner** [comment]
this happens on some osx machines and I could not find any hint what is causing this.
You can use the workaround from the issue https://github.com/tinyMediaManager/tinyMediaManager/issues/14 to deactivate the JavaFX folder chooser meanwhile

**Comment by rabtron** [comment]
The file extra.txt isn´t in any directory in Tinymediamanager, so I have
created it, but now the app can´t open.

Another solution please?

Thank you in advance.

**Comment by rabtron** [comment]
I'm desperate .. I can not use TinymediaManager and I can not catalog
and organize my movies ... Do you know your any program to do the same
and can be used while this bug is fixed?

Thanks.

**Comment by mlaggner** [comment]
did you insert the right string into the extra.txt?
`-Dtmm.legacy.filechooser=true`

I did a typo in the first response of #14

**Comment by mlaggner** [comment]
could you also try the latest build from http://nightly.tinymediamanager.org ?

**Comment by rabtron** [comment]
yes but the archive extra.txt isn´t. I created it. Then when I try to
open Tinymediamanager it doesn´t open.

**Comment by rabtron** [comment]
Thanks, thanks you very much. it seems to work well and so far has not
given me any bug.

Thanks again.
