### ISSUE TITLE
imdb keywords are not being imported as tags

### ISSUE THREAD

**Issue by levander051** [tinyMediaManager/tinyMediaManager#312]
__What TMM version are you using?__

2.9.12 OSX

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

**Comment by myron0815** [comment]
Well, yes, this is intentional.
We never found a good way for the user to filter them.
No one would like ~400 tags/keywords like seen on "Avatar"...

**Comment by levander051** [comment]
Well, is there any way that could be an option... to enable that intentionally from user side if wanted? 
(MediaElch has that enabled but is limited to 10 keywords unfortunately)

**Comment by myron0815** [comment]
Not yet, but we can discuss that for v3.
Reference: https://www.imdb.com/title/tt0499549/keywords

But IMHO, the tags are not usable in any way... even with the first 10 i'm unsure if they're useful for anyone; Tags should be something, what is in common between some movies, to find similar ones. "breakfast" doesn't really describe Avatar for me...
And your Kodi instance gets flooded with senseless tags which you won't be able to filter in a useful manner...

**Comment by levander051** [comment]
I agree that keywords are mainly useful to make connection to other movies that have common keywords and I also agree there is too much of useless, crap keywords that I would like to eliminate but we wouldn't have this discussion if there is working Allmovie.com scraper for example witch has all these, more or less, thoughtful "keywords" as movies' Themes, Moods etc. At the moment nfo metadata use "tags" and I don't see change of that in near or not so near future. But I hope for changes in software that use it and how they use tags depends on their development and I'm not really satisfied with any in that matter. At least I can hope to be able to select movies by tags, make collections out of them or to watch playlist etc.

Anyway, I think it is easier to import all the tags so I can easily find "desert island" films in my library than finding letterboxd or mubi lists and manually tagging them. Also tinyMM can also improve managing tags (filters feature in tMM is really useful and could be improved for that purpose!) so it can be easily grouped and bulk editable for purpose of eliminating un-useful tags.

I think there are more ways to make this work, for example it would be great to have an option to import only those keywords that already exists in scraped nfos. That way you could import only keywords of some importance to you and avoid those "breakfasts" or "male frontal nudities"

**Comment by mlaggner** [comment]
I've re-added this for v3 and the TMDB scraper only, since IMDB produces too much noise here..
