### ISSUE TITLE
v3: some movies are missing

### ISSUE THREAD

**Issue by Lonerider2010** [tinyMediaManager/tinyMediaManager#313]
[tmm_logs_2018-06-12.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2094823/tmm_logs_2018-06-12.zip)
Version: 3.0-SNAPSHOT
Build: 2018-06-12 00:21
OS: Linux 4.15.0-22-generic
JDK: 1.8.0_171 amd64 Oracle Corporation

__What is the actual behaviour?__
After setting up a new installation, I defined the directories containing my movies.
tMM listed 57 of them and provided the attached error message.
![error_message_2018-06-12](https://user-images.githubusercontent.com/4317444/41302864-e80bffc0-6e6b-11e8-87e5-6af4074e4874.png)
Just for comparison: tMM v2.9.12 listed 170 movies with the same sources.

__What is the expected behaviour?__
To list the same number of movies as v2.9.12.

__Steps to reproduce:__
Sorry, but can't provide all 170 movies to reproduce.
One of the movies that were not listed is 2001: A Space Odysey.

__Additional__
Have you attached the logfile from the day it happened?
Yes.

**Comment by Lonerider2010** [comment]
Just for the protocol: now I did the same comparison for the tv shows: 
in both versions (v2.9.12 and v3.0) the same number of tv shows and episodes are listed.

**Comment by mlaggner** [comment]
I've found some design problems in your log - maybe these problems are the source of your problems. I'll have a look at them the next days

**Comment by Lonerider2010** [comment]
Btw that didn't happen with previous snapshots of v3.0. 
Unfortunately I cannot restore the old snapshots, so I cannot say, which one was ok.

**Comment by mlaggner** [comment]
I do not see any other hint in the logs or commit history - but did you active automatic trailer download recently?

**Comment by mlaggner** [comment]
a new build is on the way - please report back if the issue has been addressed with that build!

**Comment by Lonerider2010** [comment]
Great: just updated - and all movies are there! Thanks a lot :-)
