### ISSUE TITLE
v3.0: Scraping TV Shows

### ISSUE THREAD

**Issue by Lonerider2010** [tinyMediaManager/tinyMediaManager#314]
Version: 3.0-SNAPSHOT
Build: 2018-06-13 17:32
OS: Linux 4.15.0-22-generic
JDK: 1.8.0_171 amd64 Oracle Corporation

__What is the actual behaviour?__
When scraping a tv show, the (possible) results are shown together with the banner of the show.
Btw. with the snapshot of issue #313 no scraping happened at all.

__What is the expected behaviour?__
With previous snapshots (before that of Issue #313) the poster of the tv show was shown instead of the banner.
Personally I would prefer to see the poster, which give much more visual information.

__Steps to reproduce:__
Scrape a tv show.

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs_2018-06-13.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2099111/tmm_logs_2018-06-13.zip)

**Comment by mlaggner** [comment]
if you use TheTVDb for scraping, then only the banner is available (since they switched off their API v1 about a month ago, we are unable to show posters along with the search result)

just tested the scraper and it is returning results with the latest v3 build

**Comment by Lonerider2010** [comment]
According to the TheTVDb API v2 the request URL for the poster of a series would be:
https://api.thetvdb.com/series/{id}/images/query?keyType=poster
Tested it with their API web interface and it works fine.

**Comment by mlaggner** [comment]
well, that is an extra call! we use the results from the search to display them;
TheTVDb decided to provide the banner while others provide a poster - we won't do many unnecessary extra calls here just because one scraper offers a different artwork for a search result..

**Comment by Lonerider2010** [comment]
Ok, accepted. So I will try to convince the TVDb people to change that.

**Comment by Lonerider2010** [comment]
Sorry, but I need to reopen this issue:
Now I added a new tv show, scraped it with The TVDB, and as described, the banner is shown.
But what's definitively wrong: this banner is stored as poster. It should be stored as banner.
Otherwise that's very confusing.

**Comment by Lonerider2010** [comment]
Just for information: the issue for the TVDB API is here:
https://gitlab.thetvdb.com/site/thetvdb_api/issues/42

**Comment by mlaggner** [comment]
unfortunately I cannot register there (something does not work..)
but I've added the extra call to fetch the poster for the search results.. but the example from #315 do not here either, because the api responses sometimes with 404 on the poster call :(

is in v3 in the next build

**Comment by Lonerider2010** [comment]
[tmm_logs_2018-06-19.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2116278/tmm_logs_2018-06-19.zip)
When I try to edit the scraped series, and want to select a poster, I still get a Java nullPointerException, see log.

**Comment by mlaggner** [comment]
tvdb did not respond with data - I've changed this to "swallow" the exception and display nothing if the data source does not respond with data

**Comment by Lonerider2010** [comment]
Something is strange now: I got the answer from the TVDB API developers, and they say that nothing has changed with the API concerning the returned image link.
So I kindly ask you to get in direct contact with the API developers, e.g. on base of the issue I created,
and clarify with them what you need for the tMM, and what they can deliver.
Thanks in advance.

**Comment by myron0815** [comment]
aparently it was our fault.
For every scraper, we always filled the poster from search result.
To have something nice to present to the user.

But TVDB was sending only a banner, which we (falsely) set as such.
Has been changed...

**Comment by Lonerider2010** [comment]
Thanks for that. It's ok now.
