### ISSUE TITLE
v3: "Poster wählen" crashes

### ISSUE THREAD

**Issue by Lonerider2010** [tinyMediaManager/tinyMediaManager#315]
[tmm_logs_2018-06-15.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2105002/tmm_logs_2018-06-15.zip)
Version: 3.0-SNAPSHOT
Build: 2018-06-15 00:22
OS: Linux 4.15.0-22-generic
JDK: 1.8.0_171 amd64 Oracle Corporation

__What is the actual behaviour?__
After adding a new tv show and scraping it with The TVDB, I tried to get the artwork for that tv show.
The dialog "Poster wählen" leads to a NullPointerException.

__What is the expected behaviour?__
The dialog should work.

__Steps to reproduce:__
- Add a new tv show
- Scrape it with The TVDB
- Edit the show (top level)
- Double-click the poster(banner)
- The error occurs

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
this is an error in the TVDB api: they tell us they have a poster, but when getting the poster, they respond with a HTTP 404...
the funny thing is, that the same url work in my browser.. have to have a deeper look at this

**Comment by mlaggner** [comment]
closed this here because it should crash in tmm, but the source problem must be handled by tvdb
