### ISSUE TITLE
Connection to external KODI device does not work

### ISSUE THREAD

**Issue by Lonerider2010** [tinyMediaManager/tinyMediaManager#316]
[tmm_logs_2018-06-22_2.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2126505/tmm_logs_2018-06-22_2.zip)
Version: 3.0-SNAPSHOT
Build: 2018-06-22 00:22
OS: Linux 4.15.0-22-generic
JDK: 1.8.0_171 amd64 Oracle Corporation

__What is the actual behaviour?__
When I try to connect tMM to a running KODI machine, the connection crashes. After that I even can't start tMM any more.

__What is the expected behaviour?__
A working connection to the KODI machine.

__Steps to reproduce:__
- Go to Settings -> General -> External devices.
- At section KODI / XBMC enter IP address, Username and Password.
- Click 'Connect'.
- The error occurs.
- After that a new start of tMM is not possible anymore. A new installation is necessary.

__Additional__
Have you attached the logfile from the day it happened? Yes.

**Comment by myron0815** [comment]
Thanks for having such a good tester - much appreciated :)

It crashes after connect.
Which means, when activated in settings, it always crashes on startup :|
Meanwhile it should be sufficent to delete the TMM settings (data/tmm.json), or to edit and empty the "kodiHost".
Will be fixed on weekend i guess...

**Comment by Lonerider2010** [comment]
It's a pleasure for me that I can make a small contribution to this project.

**Comment by Lonerider2010** [comment]
Version: 3.0-SNAPSHOT
Build: 2018-07-01 00:21
OS: Linux 4.15.0-22-generic
JDK: 1.8.0_171 amd64 Oracle Corporation

[tmm_logs_2018-07-02.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2153849/tmm_logs_2018-07-02.zip)

With the current version, a NullPointerException occurs.

**Comment by myron0815** [comment]
thx, missed a few spots.

Another Q:
Inside Kodi, do you have the remote connection from OTHER and LOCAL devices enabled?
I see some connected and at the same time connection refused messages...

**Comment by Lonerider2010** [comment]
Yes, with KODI I have LOCAL and OTHER devices enabled.
Btw, when using the KODI JSON-RPC browser (https://github.com/robnewton/JSON-RPC-Browser),
everything works fine.

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
