### ISSUE TITLE
Get missing episodes data for selected TV show(s)

### ISSUE THREAD

**Issue by Lonerider2010** [tinyMediaManager/tinyMediaManager#317]
[tmm_logs_2018-06-22_3.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2126552/tmm_logs_2018-06-22_3.zip)
Version: 3.0-SNAPSHOT
Build: 2018-06-22 00:22
OS: Linux 4.15.0-22-generic
JDK: 1.8.0_171 amd64 Oracle Corporation

__What is the actual behaviour?__
When I select all TV shows (more that 70) and execute the command 'Get missing episodes data for selected TV show(s)', it tells me:
Episodes: 3489 of 2164.

__What is the expected behaviour?__
The numbers should be in reverted order: a smaller number is a part of a greater number, not the other way round. So it should be:
Episodes: 2164 of 3489.

__Steps to reproduce:__
- Go to TV shows.
- Select all entries.
- Right click and select 'Get missing episodes data for selected TV show(s)'.
- After the command has been finished, at the bottom of the TV shows list you see the number of episodes.

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
well, depends on the definition ;)
you may have 2164 episode physically on your disc - with getting missing episodes, we mix "virtual" episodes into the tree and now, you have 3489 episode in sum (virtual + physical).
this indicator is meant to show how much episodes are actually in the view (depends on filters). mixin in virtual ones resulted in a wrong calculation..

in my mind 2164/3489 would be false too..
what about to display  something like
2000 (3000) of 2164 (3489) **IF** you have mixed in virtual episodes?

the first number pair (physical - (virtual)) indicates how much episodes are in the view according to your filters, the second number pair indicates the sum

**Comment by Lonerider2010** [comment]
Ok, agreed.

**Comment by mlaggner** [comment]
I've included that in the next build
