### ISSUE TITLE
TV shows: mark which are complete/incomplete

### ISSUE THREAD

**Issue by Lonerider2010** [tinyMediaManager/tinyMediaManager#318]
Version: 3.0-SNAPSHOT
Build: 2018-06-22 00:22
OS: Linux 4.15.0-22-generic
JDK: 1.8.0_171 amd64 Oracle Corporation

__What is the actual behaviour?__
When I look for the missing episodes of my TV shows (see #317), I have to open each TV show in order to find out if it is complete or not.

__What is the expected behaviour?__
The list of TV shows has an additional column, 
- either to show the complete number of episodes, which I then can compare with the existing ones,
- or to have a mark like with the images, to show complete or incomplete,
- or both columns to select.

__Additional__
Have you attached the logfile from the day it happened? See #317.

**Comment by mlaggner** [comment]
you should be able to filter the missing episodes with the next build

**Comment by Lonerider2010** [comment]
It's fine for me now.
