### ISSUE TITLE
Fimset Renaming

### ISSUE THREAD

**Issue by kleinerflo** [tinyMediaManager/tinyMediaManager#319]
Version: 3.0-SNAPSHOT
Build: 2018-06-21 00:22
OS: Windows 10
The renaming MovieSet doesn't seem to be going here. If you
The layout is set to ${movieSet.title}\${title} ${- ,edition,} (${year})  for example,
y:\Movies\Jump Street Filmreihe${movie.title} (2012)\21  Jump Street (2012) 480p AC3.avi
![unbenannt](https://user-images.githubusercontent.com/40491964/41774816-8aef7192-7621-11e8-97a3-4450e0c7b527.png)

**Comment by mlaggner** [comment]
this should be already fixed with https://github.com/tinyMediaManager/tinyMediaManager/commit/53c9f6ac183ac7596b9d1897c88b22df08236e6a
