### ISSUE TITLE
Support for TV Show - characterart

### ISSUE THREAD

**Issue by mgonzales71** [tinyMediaManager/tinyMediaManager#320]
__What TMM version are you using?__

Version: 3.0-SNAPSHOT
Build: 2018-06-23 00:22
OS: Windows 10 10.0
JDK: 10.0.1 amd64 Oracle Corporation

__release, pre-release, nightly, or directly from GitHub/branch?__

pre-release snapshots

__What is the actual behaviour?__

### **characterart is recognized:**

![honeyview_2018-06-23_02-23-22](https://user-images.githubusercontent.com/6510026/41808149-49129e1c-768e-11e8-8cbf-7615d97e69f6.png)
### 
**but you can't change / add or see the URL referenced for that artwork:**

![honeyview_javaw_2018-06-23_02-23-36](https://user-images.githubusercontent.com/6510026/41808150-493ed626-768e-11e8-882b-8b645cdb8812.png)
![honeyview_javaw_2018-06-23_02-23-45](https://user-images.githubusercontent.com/6510026/41808151-496e2bc4-768e-11e8-93e9-1685f0b87a78.png)

__What is the expected behaviour?__

would be nice if characterart was fully supported for tv shows

__Steps to reproduce:__
- first
- second
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

Windows 10 x64bit

Thanks for the consideration

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
