### ISSUE TITLE
filter for "new episodes" for tv shows in 3.0 snapshots does not behave like 2.x 

### ISSUE THREAD

**Issue by mgonzales71** [tinyMediaManager/tinyMediaManager#321]
__What TMM version are you using?__

Version: 3.0-SNAPSHOT
Build: 2018-06-23 00:22
OS: Windows 10 10.0
JDK: 10.0.1 amd64 Oracle Corporation

__release, pre-release, nightly, or directly from GitHub/branch?__

pre-release snapshots

__What is the actual behaviour?__

as you can see when new episodes enabled as a filter it still shows you seasons/episodes that are not new

![2018-06-23_02-44-29](https://user-images.githubusercontent.com/6510026/41808261-cb324022-768f-11e8-901f-418b60cfae39.png)

__What is the expected behaviour?__

in this example... only the highlighted episode (and seasons) should be shown like it did in 2.x

I don't have 2.x installed otherwise I would provide a screenshot but I am pretty sure you know what I mean if not ask and I will provide more info.

__Steps to reproduce:__
- first enable filter for new episodes using 3.x
- second
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

Windows 10 x64bit

Thanks

**Comment by mlaggner** [comment]
will be fixed in the next build

**Comment by mgonzales71** [comment]
thanks - working great
