### ISSUE TITLE
Support for keyart artwork type for movies and tv shows

### ISSUE THREAD

**Issue by mgonzales71** [tinyMediaManager/tinyMediaManager#322]
__What TMM version are you using?__

Version: 3.0-SNAPSHOT
Build: 2018-06-23 00:22
OS: Windows 10 10.0
JDK: 10.0.1 amd64 Oracle Corporation

__release, pre-release, nightly, or directly from GitHub/branch?__

pre-release / snapshots

__What is the actual behaviour?__

no support for movie or tv show keyart

__What is the expected behaviour?__

requesting support for both movie and tv show keyart artwork type

SEE:

https://kodi.wiki/view/Movie_artwork#Keyart

https://kodi.wiki/view/TV-Show_artwork#Keyart

__Steps to reproduce:__

NA

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

Windows 10 x64

Thank you for the consideration to add this support.

**Comment by mlaggner** [comment]
IIRC there is no artwork provider which offers this kind of artwork (at least when I checked it the last time).
Without proper support from artwork providers this feature makes no sense?!

**Comment by mgonzales71** [comment]
check out Artwork Beef:
https://github.com/rmrector/script.artwork.beef
https://rmrector.github.io/script.artwork.beef/

his script handles the new artwork type at fanart.tv  and themoviedb.com

While not the most elegant solution... I do think it probably won't been long after Kodi 18 is released that you will see API updates follow with support for Keyart searching (hopefully). 

But until then - they way he does it is working around the missing API calls the only logical way one could (no language).  Maybe that is just how it will be and never see an API call added.

But I do thank you for the consideration for this feature being added.

Mario

**Comment by mgonzales71** [comment]
btw Artwork Beef is now the "De facto" artwork handling script for Kodi.  They requested skin / addon devs to remove script.artwork.downloader as a dependency and instead use artwork beef which has been quickly evolving to be more then Artwork Downloader ever was.

Maybe you can utilize Artwork Beef for handling artwork the same way you do with meta info scrapper scripts?

soon to come are changes for artwork handling in Kodi
see:

https://github.com/xbmc/xbmc/pull/13859

and the discussion of cleaning up the naming of all the artwork (finally)
https://forum.kodi.tv/showthread.php?tid=331822&pid=2734211

if you want to give any input do post in the above forum post.

Thanks again - Mario

**Comment by mlaggner** [comment]
just had a look at this issue again - well the keyart is nothing else than a poster without text!
as long as there is no viable marker for keyart in the artwork providers (imho no provider does that good!) we won't be able to distinguish between "normal" poster and "textless" poster..
I've had a look at the Kodi plugin and this only uses the language tag of the artwork from fanart.tv - but history has shown us, that this information is not available all the time..
so I will wait for the artwork provider to create a clean keyart type before implementing it (to avoid false positives)

**Comment by mgonzales71** [comment]
Fanart TV strictly requires the none language tag to be applied to Key Art I know you say history has shown but they are very strict about that for any approved poster images that contain no text.

For instance look at the poster artwork for 
https://fanart.tv/series/311790/lethal-weapon/

The poster artwork that has language none is keyart.

I guess if I were to explain the best way of looking at adding keyart support is any poster images that are approved at FanArt with the language set to none is verified to contain no text.
 
The incorrect way to look at this is that an image could have been uploaded that contained no text but was incorrectly marked as English.  

But I’m pretty sure that if you search for posters with language set the none you’re always going to find  keyart images.

If you are apprehensive  about it you could always market it as an experimental feature or as part of testing version 3 snapshots

Thanks for the consideration

Kodi will be officially supporting keyart with the upcoming Leia version 18.

And right now fanart TV is the only site that does this Support as far as I know.

TMDB might.

Thanks

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
