### ISSUE TITLE
no search results for specific series

### ISSUE THREAD

**Issue by b1n4ryj4n** [tinyMediaManager/tinyMediaManager#323]
__What TMM version are you using?__
tmm_3.0-SNAPSHOT_bf170ff_win

__release, pre-release, nightly, or directly from GitHub/branch?__
NIGHTLY

__What is the actual behaviour?__
Can not find series with ";" e.g. "ChäoS;Child" or "Steins;Gate"
I need to remove all ; in the search textbox to get a result.

__What is the expected behaviour?__
A search result because it's in the database https://www.thetvdb.com/series/chaos-child

__Steps to reproduce:__
Rightclick scrap a serie, enter in search "ChäoS;Child".
No Result found.

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
Windows 10 x64

**Comment by myron0815** [comment]
Well, yes, but there's nothing we can do about :| (at least, if we don't need to)

We pass the title/searchbox 1:1 to the API.... and they find something or not.
Usually, we do not want to compensate their lack of searchability. (other sites do not have such problems)

Ok, removing a ; from searchrequest ist not hard (done for next build), but where does it end?
What other special handlings does the TVDB have?
Anyway.. thx for reporting :)
