### ISSUE TITLE
tinyMediaManager contains incorrect version information on macOS

### ISSUE THREAD

**Issue by core-code** [tinyMediaManager/tinyMediaManager#326]
if you select tinyMediaManager and "Get Info" using the finder, the version of the app is displayed as "$version" which obviously makes no sense

this is causes by the following entry in your Info.plist file:
  	<key>CFBundleShortVersionString</key> <string>$version</string>

this should probably be "2.9.12" instead of "$version" ;)

also, the CFBundleVersion entry also looks kind of wrong:
   	<key>CFBundleVersion</key>
  		<string>2.9.12 597414a</string>

this is a strange concatenation of the version string and the build number (?). since the "CFBundleVersion" entry is supposed to contain the build-number, it should probably only be 597414a (if this really is a monotically increasing number)

**Comment by myron0815** [comment]
thx

**Comment by core-code** [comment]
thanks!
