### ISSUE TITLE
datasource for series are not updating

### ISSUE THREAD

**Issue by b1n4ryj4n** [tinyMediaManager/tinyMediaManager#327]
__What TMM version are you using?__
tmm_3.0-SNAPSHOT_4fd66bc_win.zip

__release, pre-release, nightly, or directly from GitHub/branch?__
nightly

__What is the actual behaviour?__
After add a new datasource folder for series the filter datasources don't update their available datasources.

__What is the expected behaviour?__
Update datasource folders in filter for series without restart tmm to force an update.

__Steps to reproduce:__
- add a new datasource folder for series
- update sources
- add a second new datasource folder for series
- update sources
- in filter -> datasources are not present

__Additional__
Your Operating system? (win/mac/linux? version?)
Windows 10 x64

**Comment by mlaggner** [comment]
should be working again in the next build
