### ISSUE TITLE
request: populate / support ` <runtime>##</runtime> ` tag tv shows / episodes nfo files

### ISSUE THREAD

**Issue by mgonzales71** [tinyMediaManager/tinyMediaManager#328]
__What TMM version are you using?__

Version: 3.0-SNAPSHOT
Build: 2018-06-28 
OS: Windows 10 10.0
JDK: 10.0.1 amd64 Oracle Corporation

__release, pre-release, nightly, or directly from GitHub/branch?__

__What is the actual behaviour?__

runtime seems to always be set to 0

![notepad _2018-06-29_17-36-15](https://user-images.githubusercontent.com/6510026/42119944-8cd1d4c2-7bc7-11e8-9263-3d915cbd1957.png)

the data is available (example is tvdb):

![firefox_2018-06-29_17-35-10](https://user-images.githubusercontent.com/6510026/42119960-cb8a99ce-7bc7-11e8-9e36-474e139efa1f.png)

__What is the expected behaviour?__

could you populate the ` <runtime>##</runtime> ` tag?

according to https://kodi.wiki/view/NFO_files/TV_shows it supports minutes only
  
so if you would please consider it for tvshow.nfo and episode.nfo files in the future.

it would be very much appreciated and thank I you considering this request

**Comment by mlaggner** [comment]
runtime from tmdb/imdb is being imported in the next build
