### ISSUE TITLE
request: support <episodeguide></episodeguide> URL tag for tv show nfo files

### ISSUE THREAD

**Issue by mgonzales71** [tinyMediaManager/tinyMediaManager#329]
__What TMM version are you using?__

Version: 3.0-SNAPSHOT
Build: 2018-06-28 
OS: Windows 10 10.0
JDK: 10.0.1 amd64 Oracle Corporation

__release, pre-release, nightly, or directly from GitHub/branch?__

snapshot

__What is the actual behaviour?__

not included

recently I have been seeing errors like this in Kodi:

`VideoInfoScanner: Asked to lookup episode N:\TVShows\12 Monkeys (2015)\Season 4\12.Monkeys.S04E07.mp4 online, but we have no episode guide. Check your tvshow.nfo and make sure the <episodeguide> tag is in place.`

I am not sure if the kodi scrapper for tvdb will no longer try to look up / scrape online info when an existing tvshow.nfo file is present for the show but the corresponding episode.nfo file is missing for a new tv show video file added to the media library source.

__What is the expected behaviour?__

request for addition  and support of the 
`<episodeguide></episodeguide>` (URL tag)

not sure where the episode list in obtained from and format as the KODI wiki is not clear but this could be the schema for the URL  via the TVDB API

http://www.thetvdb.com/api/1D62F2F90030C444/series/71361/all/en.zip

other possible sources:

http://api.tvmaze.com/lookup/shows?thetvdb=295515 gives you this URL

http://api.tvmaze.com/shows/2114

and then you can snag this CVS formatted episode list via this URL scheme:
http://epguides.com/common/exportToCSVmaze.asp?maze=2114
or in JSON format via
http://api.tvmaze.com/shows/2114/episodes URL scheme

Sorry I don't know more about that tag and what is expected.

But if you would please consider it for tvshow.nfo file in the future it would be very much appreciated and I thank you in advance for considering this request.

**Comment by mgonzales71** [comment]
I did find a little more info regarding the URL and tag:

```
/** Kodi requires an <episodeguide> element with TheTVDB API Series Record XML URL **/

episodeguide {url(cache:"${i.id}.xml", "http://www.thetvdb.com/api/1D62F2F90030C444/series/${i.id}/all/${locale.language}.zip")

```
**Kodi Wiki:**

```
<episodeguide>
  <url cache=""></url>
</episodeguide>
```

**and a formatted example:**

```
<episodeguide>
<url cache="71361.xml">http://www.thetvdb.com/api/1D62F2F90030C444/series/71361/all/en.zip</url>
</episodeguide>
```

**Comment by mlaggner** [comment]
this is the api v1 endpoint of tvdb which has been shut down to my knowledge..
furthermore I won't publish our internal api kex in NFO files...

**Comment by mgonzales71** [comment]
Found more info..

If you first let Kodi scrape a show it adds this to the MyVideo DB under TVshow:

(Example is DC's Legends of Tomorrow) and I assume using Kodi's API key

![db browser for sqlite_2018-07-02_22-49-03](https://user-images.githubusercontent.com/6510026/42201016-e68f61a2-7e4a-11e8-9c2f-b705d1dd4174.png)

**Comment by myron0815** [comment]
will check the scraping error.

Regarding the episodenguide:
Only the program which does the scraping needs this.
So when scraping with TMM, we have the URL, and when scraping the show inside Kodi, you have the Url in NFO as well.
But we cannot export this URL, since it contains our private API key.
So you either need to scrape and prepare your updated shows with TMM, or complete rescrape this with Kodi, to be able to scrape a single episode.

Adding personal API keys would be another story.
This might be the best out of this solution....

**Comment by mgonzales71** [comment]
actually I was testing to see if that made any difference but not my normal scrapper

**Comment by mgonzales71** [comment]
Ok - I painstaking added the episode guide to my nfo files and then your program REMOVED them all!!!  😞 why?!

FYI: MediaElch, MediaCompanion etc all add episode guide tags to the NFO files for TV Shows and they sure as hell don't remove them if they are there.

and I turned off the write "clean" nfo - even though that is a recognized and recommneded tag if you actually read the Kodi Wiki on nfo files for TV Shows.

So I again suggest you write it (and use a personal API key if that bugs you to use the Kodi one or your own) and to at least keep ALL tags that Kodi recognizes and uses even if your app doesn't.

![javaw_2018-11-26_19-03-38](https://user-images.githubusercontent.com/6510026/49055974-7be4dd00-f1ae-11e8-9e96-bfe080df0a7e.png)

**Comment by mlaggner** [comment]
thanks for reporting - found a bug where exactly episodeguide from a previous NFO has not been written

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
