### ISSUE TITLE
Movie sets are not resetting

### ISSUE THREAD

**Issue by b1n4ryj4n** [tinyMediaManager/tinyMediaManager#330]
__What TMM version are you using?__
tmm_3.0-SNAPSHOT_be9d92f_win.zip

__release, pre-release, nightly, or directly from GitHub/branch?__
nightly

__What is the actual behaviour?__
If you delete all datasources of movies the movie sets are still there.

__What is the expected behaviour?__
Also delete the associated movie sets from the database after deleting the movie datasources. Unless the films in the collection no longer exist.

Your Operating system? (win/mac/linux? version?)
Windown 10 x64

**Comment by mlaggner** [comment]
at the moment the movie sets exist independently of the data sources (theoretically you could assign movies from different data sources to a movie set).
your idea is to remove ALL movie sets only if ALL data sources are removed?

**Comment by b1n4ryj4n** [comment]
Yeah sounds good to me.
