### ISSUE TITLE
Search for episodes in TV shows

### ISSUE THREAD

**Issue by Lonerider2010** [tinyMediaManager/tinyMediaManager#331]
Version: 3.0-SNAPSHOT
Build: 2018-07-01 00:21
OS: Linux 4.15.0-22-generic
JDK: 1.8.0_171 amd64 Oracle Corporation

__What is the actual behaviour?__
Within the TV shows, I search for an episode. The results are shown on TV show level.

__What is the expected behaviour?__
When I get the results, they should be unfolded down to the episode level. If I get several results, this would help me to get an overview at once, and avoid many clicks.

In the search field I should be able to clear the field with one click.

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

**Comment by myron0815** [comment]
ok, so an auto expand to current search result.
Seems reasonable to do so, dunno how hard this might be on technical side ;)
thx for reporting

**Comment by Lonerider2010** [comment]
So I wish you good success with this :-)

**Comment by mlaggner** [comment]
I've implemented the enhancements for the search field, but I have problems with the automatic expansion..
the filter does not actually know, _where_ the search result was in the tree path:
if you search for **24**, you probably get the hit on the show level - expanding all seasons and episodes of this season would not be right..
what about to implement the _expand all_ feature to a more prominent place then the popup menu?

btw: If I do a search in my development software, the search results do not get expanded either..

**Comment by Lonerider2010** [comment]
If you expand some tv shows before the search, the results will be expanded as well. So a way to expand all tv shows with one command would be helpful.

**Comment by Lonerider2010** [comment]
After a search the tv shows should not be collapsed automatically. So the expanded tv shows would be available for another search.

**Comment by mlaggner** [comment]
expand all/collapse all is already available (context menu)

**Comment by mlaggner** [comment]
expand all/collapse all is already available (context menu)
