### ISSUE TITLE
tMM error

### ISSUE THREAD

**Issue by docpauluk** [tinyMediaManager/tinyMediaManager#332]
Version: 2.9.12
Build: 2018-05-29 18:55
OS: Windows 10 10.0
JDK: 1.8.0_171 x86 Oracle Corporation

__What is the actual behaviour?__
Tried to rename a .mkv file originally named in Russian

__What is the expected behaviour?__
file name would be modified with data from IMDB

__Steps to reproduce:__
1) refresh downloads directory
2) search for the movie
3) movie correctly identified
4) click OK - "Problem detected"

__Additional__
Have you attached the logfile from the day it happened?

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2153956/tmm_logs.zip)
![tmm error](https://user-images.githubusercontent.com/28462047/42147846-cd2b8f5a-7e23-11e8-803b-3d2f37d3f406.jpg)

**Comment by docpauluk** [comment]
OK - so all renaming was broken - seems to be due to the Movie Re-namer Folder name.
If I leave the field blank, it's OK...
Also OK if I use relative folders..

**Comment by mlaggner** [comment]
you have `O:\Torrents\finished` in your renamer path expression.. this expression is always relative to your data source (otherwise you'd have problems with multiple data sources).

**Comment by docpauluk** [comment]
thanks for the reply - user error... :)
