### ISSUE TITLE
Duplicate NFO Files

### ISSUE THREAD

**Issue by EarthBoundX5** [tinyMediaManager/tinyMediaManager#333]
Version: 2.9.12
Build: 2018-05-29 18:55
OS: Windows 10 10.0
JDK: 1.8.0_171 amd64 Oracle Corporation

__What is the actual behaviour?__
NFO files are being created before the video files are renamed or moved into folders, then they are recreated in the new folder, but with the new name of the video file.

__What is the expected behaviour?__
NFO file follows video file like normal or redundant NFO files are not left behind.

__Steps to reproduce:__
1. Put video file in data source
2. Update data source
3. Scrape Movie (and have auto rename options enabled)
4. Find old NFO files left in data source with old video file name

__Additional__
Have you attached the logfile from the day it happened?
Attached log file after opening TMM and scraping 3x videos.
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2168924/tmm_logs.zip)

**Comment by mlaggner** [comment]
the change for https://github.com/tinyMediaManager/tinyMediaManager/commit/a65f64facd1a7424dbaa882637dd28f83bc31933 has broken this kind of cleanup.. we have to find a way to detect files for each constellation in each OS...

**Comment by EarthBoundX5** [comment]
Thanks for the specifics, glad it's a known issue.

It's too bad, Java being machine agnostic still doesn't hold true in
certain cases.  I remember having a few issues with handling fd's back in
college between Debian and Windows with Java 5.

Thanks again,
EarthBoundX5

**Comment by mlaggner** [comment]
well the problem is not java itself - it is the native implementation of the file system access...
the BIG problem is, that macOS supports both case sensitive and case insensitive file systems, so it is problematic to implement such checks in code ;) 
But I hope we could cover all cases now...
