### ISSUE TITLE
idea: exclude folder from trakt sync

### ISSUE THREAD

**Issue by b1n4ryj4n** [tinyMediaManager/tinyMediaManager#334]
__What TMM version are you using?__
tmm_3.0-SNAPSHOT_6bac590_win.zip

__release, pre-release, nightly, or directly from GitHub/branch?__
nightly

__Idea__
A new setting for trakt so that certain folders / data sources should not be synced. Similar to exclude folder (s) from scan.

**Comment by mlaggner** [comment]
trakt.tv support is only available globally (if you use automatic sync) or for selected entities (manual sync).
This integration does not work on folder level and special settings for data sources (such as enable/disable trakt, different renamer settings, ...) would be too huge - so there is no such feature nor planned. If you want to not sync some entities to trakt, you may have to do it manually..
