### ISSUE TITLE
Improvement on KODI connection needed

### ISSUE THREAD

**Issue by Lonerider2010** [tinyMediaManager/tinyMediaManager#335]
[tmm_logs_2018-07-07.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2173106/tmm_logs_2018-07-07.zip)
Version: 3.0-SNAPSHOT
Build: 2018-07-03 00:22
OS: Linux 4.15.0-22-generic
JDK: 1.8.0_171 amd64 Oracle Corporation

__What is the actual behaviour?__

1. Settings - External Devices - Data of KODI machine - Connect: nothing happens,
    no feedback, so I don't know if the connection is established.
2. Tools - KODI (Unknown): what does 'Unknown' mean? The name of the KODI machine?
    Does not work.
3. Tools - KODI (Unknown) - Application - Quit: Does not work.
4. Tools - KODI (Unknown) - Application - Mute / UnMute: leads to a NullPointerException, 
    see attachment.
5. Tools - KODI (Unknown) - Application - Volume different levels: Does not work.
6. Tools - KODI (Unknown) - System - all submenus: Do not work.
7. Tools - KODI (Unknown) - Video Library - Scan for new content - Scan ALL Datasources: 
    Last level not activated
8. Tools - KODI (Unknown) - Audio Library - Scan for new content - Scan ALL Datasources: 
    Last level not activated
    This entry is very interesting, see #300!
9. None of the entries above is translated to German.

__What is the expected behaviour?__
Make the KODI connection transparent (with feedback) and working.

__Steps to reproduce:__
See description above.

__Additional__
Have you attached the logfile from the day it happened? Yes

**Comment by myron0815** [comment]
Well, yes, there needs much work to get this going :|
First we need to have an idea, what we want to solve with this connection... and then we need time...
Current methods are just there to play a bit...

"Unknown" comes from that fact, that TMM is still not able to connect to your Kodi instance.
I still see "Error calling Kodi: Verbindungsaufbau abgelehnt (Connection refused)" in your logs.
Which Kodi version do you have?
Are your ports correct?
...?

**Comment by myron0815** [comment]
ok, seems not to work with Kodi 18 Leia at all :|

**Comment by myron0815** [comment]
fixed some issues, at least my latest Kodi 18 Leia works...

**Comment by Lonerider2010** [comment]
The KODI version I'm running is 17.6. By default, the HTTP port is set to 8080. Changed that to 9090, but that didn't help with the newest tMM build (2018-07-09 12:33). Tried the RPC interface with the KODI JSON-RPC Browser [(Link)](https://github.com/robnewton/JSON-RPC-Browser), and that works. There is one strange thing: I have to login twice to get the connection.

Concerning ideas about the RPC connection, I would like to support you. Can we have a chat or so, because I think the issues is not the right platform to exchange ideas, it should be more interactive.

**Comment by Lonerider2010** [comment]
In addition: I'm running Kodi 17.6 on a Raspberry Pi, based on OSMC 2018-06-07.

**Comment by myron0815** [comment]
http should be 80/8080 per default, and TCP defaults to 9090 
(cannot even be changed inside Kodi, only in webinterface)

Well, we have a (unannounced) public Discord channel you might want to join:
https://discord.gg/gb6V9TZ 
But bear with us if we don't respond immediately - we have all day jobs & family, and barely time beside...

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
