### ISSUE TITLE
idea: hide specials

### ISSUE THREAD

**Issue by b1n4ryj4n** [tinyMediaManager/tinyMediaManager#336]
__What TMM version are you using?__
tmm_3.0-SNAPSHOT_a3a682e_win.zip

__release, pre-release, nightly, or directly from GitHub/branch?__
nightly

__What is the actual behaviour?__
Pls implement a setting, so that specials are hidden from filtering missing episodes, metadata, images...

**Comment by myron0815** [comment]
hmm.. why would someone want this?
Can you tell us your intention behind?
Or, at least a show, where this might be useful?

**Comment by b1n4ryj4n** [comment]
I'm not a collector of specials and therefore it is annoying that always all shows which i already collected are nevertheless displayed in filters. 

In particular, there are almost every anime that has specials episodes. 
But also many tv series like Supernatural, 24, The Mentalist...

**Comment by OldMan100** [comment]
myron0815,

b1n4ry4n idea is something I was thinking about some time ago.  I have a lot of animes, but not the specials. So any updating, scraping,  of a show would produce a listing for specials in blue. Specials I will most likely never get. Which means anytime a user, like myself,  opens the listing to a show, a folder for special would there with the titles of all the specials the app could find, most likely in blue. It's great to know there specials out there, if I was looking for them, but am not, then the folder and the listing inside are of no use.  Even better, is the ability to toggle the special folder on a per show basic inside maybe the Detail section.  But I know this would be a great of work on your part.  Just wishful thinking.

**Comment by mlaggner** [comment]
added this option (default = hide specials).
for now you need to restart tmm once after activating this setting to show specials.
