### ISSUE TITLE
Odd renaming

### ISSUE THREAD

**Issue by DaemonPhoenix42** [tinyMediaManager/tinyMediaManager#337]
2.9.12
Release

Example: (Outcome)
Ajin - -1x01 - OAD 01 The Nakamura Shinya Incident
Example: (Desire)
Ajin - 0x01 - OAD The Nakamura Shinya Incident

My apologies if this is not considered an issue or is even a product of the database but why is this particular series marked as "Season -1" as opposed to "Season 0"

**Comment by myron0815** [comment]
If we could not detect a valid season pattern out of filename, it will become -1, and you should manually correct it - else we couldn't scrape anything.

What was your original filename?

**Comment by myron0815** [comment]
any chance of telling that weird name, so we might get a change to improve our parser? ;)

**Comment by DaemonPhoenix42** [comment]
ahh yes.
Ajin OAD - 01 - The Nakamura Shinya Incident

It was treated as if it was the same series in the manager, even though its an OVA/Special the name makes it appear as if its a different series with no season.

I haven't gone through my media in a bit so I don't know if there are any other offenders. will update if I find some.

**Comment by myron0815** [comment]
ok, we can't do anything about it anyway.
01 is the episode... and there is no season number... so all good from our side :)
