### ISSUE TITLE
External HardDrive

### ISSUE THREAD

**Issue by Furycom** [tinyMediaManager/tinyMediaManager#339]
tmm_2.9.12_597414a_win

hi!

i have 5000 movie on 18 external unplugged Harddrive
so i need a ''scan external hardrive functionnality''
i want to tell the program to : scan this directory for movie and label it SATA18
the way it is now dont work at all whit my collection

after it i will nedd a ''find duplicate'' option to see if i have duplicate movie accros multiple drive

theese modification will be very appreciate until the programe is not working for me now

p.s i am french , excuse my english

thanks a lot :)

**Comment by myron0815** [comment]
Puh... i think that does not work that way.
TMM was designed to maintain an online catalog of live movies, to be prepared for Kodi et all.
So mounting different harddrives as same datasource does not work here.
What could works, is, to put all the movies in a subdir like M:\movies18\blabla, so every hard drive has its own datasource. (but this seems only be a workaround)

Of how many GBs are we talking about? Sometimes it's just easier to buy a cheap 8TB harddrive (like a seagate archive or similar) and reduce the HDD count...

**Comment by myron0815** [comment]
The french - always polite as we know them...

**Comment by Furycom** [comment]
im sorry for my rudeness
i simply dont understand how to hell you can figure
that a software intended for movie collection purpose dont need functionnality for
more than 1 hard drive

i am frustrated because your soft is great , but just dont work because of that
and you seem to think that is not an issue so....
this soft simply dont work

**Comment by Furycom** [comment]
i search for a movie i want to watch in my actual software
the movie i want is in the sata14
so i plug my sata14 in my networkdock

in kodi , i go play the movie from sata14 from network

adding a multi harddrive functionnality to your software is from my perspective a basic thing
if you dont have multiple harddrive , you are not a true collector
if you are not a true collector , you dont need a soft to catalogue movie

**Comment by b1n4ryj4n** [comment]
Sorry for interfering but I see no benefit. If you have a large amount of data (movies or series or whatever) a NAS with a large amount of memory would be worth it. They are not that expensive anymore. 50TB+ NAS's are already available for $ 3000. I can recommend you Synology. So you just have to add a network path. 

--
And a real collector in my point of view does not have multiple hard drives (10+). just everything in one place so it can be accessed from anywhere at anytime. The ones that use the hard disks are just data compulsive hoarder. They spend a lot of money for films and series but do not want to invest money to neatly archive this. Shame on you!

greetz

**Comment by Furycom** [comment]
you are stupid as hell
other real software make what i want
its okay for me , i already have an alternative
shame on you , and your lack of functionnality software
im out of here
