### ISSUE TITLE
Air dates in May of any year not being scraped from IMDb

### ISSUE THREAD

**Issue by raffishtenant** [tinyMediaManager/tinyMediaManager#340]
Version: 2.9.12
Build: 2018-05-29 18:55
OS: Mac OS X 10.13.1
JDK: 1.8.0_161 x86_64 Oracle Corporation

__What is the actual behaviour?__

When scraping IMDb for TV episodes, air dates are not always scraped, even when other information from the episode is. I think I've figured out the pattern: the missed dates always appear to be from May. Is the fact that this is the only month that is not abbreviated with a period in the scraped data messing things up?

__What is the expected behaviour?__

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2195970/tmm_logs.zip)

**Comment by myron0815** [comment]
nice catch!
It is indeed the missing dot in the date format we try to parse.
Should be fixed with next version.
Thx :)
