### ISSUE TITLE
Use lang (2 letter codes) from audio streams to Rename. 

### ISSUE THREAD

**Issue by CarlosMC** [tinyMediaManager/tinyMediaManager#341]
Hi All,
Thanks for all the great work done here, i just starting to use tmm.

I would like to  organice my movies in the following way (special case: dual audio):
Movies/The Movie Collection/The Movie (year) - EXTENDED [1080p] **[EN+ES]**/The movie [...] .mkv

Currently what i have is:
**Folder:** Movies/{$N/}$T ($Y){ - $U}{ [$F]}
**File name:** $T ($Y){ - $U} $V $A

I couldn't find any variable to get the LANG info of the audio streaming.
Is this possible at the moment? or If not, could this be an enhancement request?

Thanks in advance!
Cheers,

**Comment by thwaller** [comment]
Ahh, that makes sense. The reason I do not have that problem is I only use the renamer for the folders and not the files. So for me, anything I have in the movie file name is always there.

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
