### ISSUE TITLE
Node duplicates arise

### ISSUE THREAD

**Issue by b1n4ryj4n** [tinyMediaManager/tinyMediaManager#342]
__What TMM version are you using?__
tmm_3.0-SNAPSHOT_a358a45_win.zip

__release, pre-release, nightly, or directly from GitHub/branch?__
NIGHTLY

__What is the actual behaviour?__
If I move a series folder to another directory, the directory will still remain in tMM when I update the data sources for series. And so unfortunately Node duplicate arise. Although the series directories no longer exist.

![node_duplicates](https://user-images.githubusercontent.com/3122325/42900331-eea4e116-8ac8-11e8-8378-5cb115e1ce2b.png)

__What is the expected behaviour?__
tMM must check when update datasources whether the directories are still there and if not delete them from the database, or add a funktion to re read all datasources from zero.

greetz

**Comment by mlaggner** [comment]
well, that works here...
did the nodes disappear after a restart? 
was the old datasource empty after removing the tv show?

**Comment by b1n4ryj4n** [comment]
Ah found the problem.
It was a PEBKAC error 🤦‍♂️

The empty folder with the  series name was still in the datasource folder.
