### ISSUE TITLE
Multiple subs in same language

### ISSUE THREAD

**Issue by thwaller** [tinyMediaManager/tinyMediaManager#343]
Version: 2.9.13-SNAPSHOT - PRE-RELEASE
Build: 2018-07-18 06:53
OS: Linux 4.15.0-23-generic
JDK: 1.8.0_181 amd64 Oracle Corporation

I have some movies with external subs. In some cases, I have an English subs file and a foreign parts only sub file. Currently, tMM finds error in this during the rename function, since it renames (tries to) both of the subtitle files to the same new name. It would be nice to have the ability in the GUI to differentiate those files, so tMM knows they are different and renames them appropriately. Something like:
1) <movie_name>.eng_foreign_only.sub -- Foreign parts only
2) <movie_name>.eng.sub -- Full English subs
3) <movie_name>.eng_hi.sub -- Full English subs with Hearing Impaired subs

Is this something that maybe can already be done and I just miss it, or is this something that might be considered?

**Comment by thwaller** [comment]
HI is in fact a standard, but calling it "HI" is not. It is also common as "SDH".

I can solve it manually, but should others have the issue, I would want them to use your product without this issue. You have a strange database to me :)

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
