### ISSUE TITLE
Changing data sources

### ISSUE THREAD

**Issue by thwaller** [tinyMediaManager/tinyMediaManager#344]
Version: 2.9.13-SNAPSHOT - PRE-RELEASE
Build: 2018-07-18 06:53
OS: Linux 4.15.0-23-generic
JDK: 1.8.0_181 amd64 Oracle Corporation

I have noticed, since I am using tMM for many more things recently, that if I change the data source for a movie, some information that was entered is lost. For example, if I go to Edit Movie -> Media Files and add in a subtitle specification for the media file, that information is no longer there when changing data sources. I assume this is because that information is stored in the tMM database and not in the NFO file.

So my question is ... is there a way to have a feature where you can change the data source without having to scan the new source for the movies as "new", then remove the old data source? Or, a way to write this "extra" information, if not to the NFO, but to an extra information NFO file?

Here is the logic and reasoning behind this... when I acquire a new movie for my collection, I typically save it local or to a USB connected drive which seconds as an extension to a NAS when connected there. I also have the NAS I referenced. So, I have a data source for my local HD, the external USB and the NAS. All that works fine, but when I move a movie from local to the NAS or external USB, this is where data gets lost. New things which will get watched in short time frame are usually local, ones that will get watched by others on the other TVs will likely go to the external USB, and the NAS is more of an archive holding all the older movies or ones we have seen and have no immediate plans to watch again. That is why the data sources are changing.

**Comment by myron0815** [comment]
good point - some information is not stored in NFO, and will be lost...

**Comment by thwaller** [comment]
That would work. So I could select one-to-many entities and migrate them from one data source to another... if I understand that correctly, that would address this perfectly.

**Comment by mlaggner** [comment]
is available in the next build
