### ISSUE TITLE
[Feature Request] Allow to create SubMovieSet

### ISSUE THREAD

**Issue by Mannshoch** [tinyMediaManager/tinyMediaManager#345]
In my opinion some MovieSet are also Part of a greater MovieSet. Like all Marvel based Movies belongs together also the "The Lord of the Rings" and "The Hobbit" MovieSet belongs into a Tolkien MovieSet

- Tolkien MovieSet
  - The Hobbit MovieSet
  - The Lord of the Rings MovieSet

**Comment by mlaggner** [comment]
I thonk think the benefit for creating such a structure is worth the complexity to introduce..
This would result in a multi level structure like in TV shows, but without the need for every movie set.
Since movie sets are kinda deprecated (also in Kodi!) we won't add this!

**Comment by myron0815** [comment]
As a side note:
A movie in Kodi can only be part of EXACTLY ONE movieset.
This is the major drawback, which makes this cool feature quite unusable.
So better start tagging them with a movieset... Kodi can filter/search by tags quite well...

**Comment by Mannshoch** [comment]
I have no problem with that that Kodi is not able to use a SubMovieSet. After you have it implemented I would try to write a Feature Request on kodi to support it. Until than, It's a nice tool to sort it Better. The next idea would be to use it also with TV-Series because some Movie get also a TV-Serie. Or TV-Series get a Spin-off which pla in the same World.
I don't need it immediately in Kodi, but I allow me to hope it would follow in Kodi because People say "Woow. cool feature!".

@myron0815  seems interesting. Is it really possible to tag a video file like the EXIF in a Picture or mp3 with additional information? I never crossed any Applicaton that is able to do such kind of things.

**Comment by myron0815** [comment]
Haha, great idea.
So we have the work, and Kodi won't do it...
It always should be the other way round!

Nevertheless, feel free to ask in forum if they will implement that.
(But i'm kinda sure, they would answer similar)

With tagging i meant to set tags within TMM, which are saved into NFO, and then filterable by Kodi...

**Comment by Mannshoch** [comment]
In My opinion This tool is not an add-on for Kodi. It's his own Full Program to catalog and categorize Movies. Also there is no need to focus only on Kodi. I personally use more the the function to Play on VLC Button.
>   It always should be the other way round!
That's the point where evolution ends. 

I for my self don't see any improvement in Kodi since a while. As an e.g. A tools like to configure and setup a remote control with their key as easy as it a RetroPi project do is missing. I never had a proper working remote control. So I use at home the Tablet for that, hey if you would have aa nice Webservice I would use tMM to choose a Movie, I also never found any Proper working Web-skin for Kodi. And since last Update my visualization for my radio and music in Kodi are missing. 

If you follow only Kodis steps you would not be able to overtake them and you have to break if they do.

**Comment by myron0815** [comment]
k, i see your point.
The problem is, we barely have time to maintain TMM in it's core features.

Introducing complexity is not what we currently have planned, nor have the manpower to do so.
It might be great, to better visualize things inside TMM, but when no other application profits, it has currently no priority.

TMM was always designed for usage with a mediacentre, and not as standalone app.
But yes, since it matures, people start using it as standalone management tool.
Which is great, but it needs some more rework to evolve....
