### ISSUE TITLE
[Feature Request] AniDB TV-Show title option

### ISSUE THREAD

**Issue by WorldEntityGravity** [tinyMediaManager/tinyMediaManager#346]
__What TMM version are you using?__
2.9.12

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
When scraping a TV-Show using AniDB, you always get the translated show title in the language you have selected if one exist.

__What is the expected behaviour?__
There should be a option for the AniDB scraper to always scrape the "Main Title" of the shows or when manually scraping. The reason being that since alot of shows has different names for different seasons it quickly gets anoying when one season has a translated title and the others dont.

**Comment by mlaggner** [comment]
could you give us an example please?
the show title is being fetched once and not per season..

**Comment by WorldEntityGravity** [comment]
I guess I was a bit unclear, what I meant was that alot of anime shows have each season listed as a separate show on AniDB. 
So if the first season has the title translated to english but the following seasons do not, it can get confusing fast.

For example the first season of "Nanatsu no Taizai" gets named "The Seven Deadly Sins" by tMM (https://anidb.net/perl-bin/animedb.pl?show=anime&aid=10596) but the following season gets named  "Nanatsu no Taizai: Imashime no Fukkatsu" (https://anidb.net/perl-bin/animedb.pl?show=anime&aid=11646).

The easiest way to fix this in my opinion would be to have an option to always use the "Main Title" regardless of any translated titles.

**Comment by mlaggner** [comment]
in v3 we've introduced a original title field like in the movies section - would that be enough for you?
