### ISSUE TITLE
Enhancement: Embedded Subtitles

### ISSUE THREAD

**Issue by DaemonPhoenix42** [tinyMediaManager/tinyMediaManager#348]
2.9.13 Release

Most of my library is in MKV format and comes with embedded subtitles, is it possible to monitor already existing subtitles in such a format?

**Comment by myron0815** [comment]
We should already detect them (listed on mediaInformation tab), and should add them already into the NFO. IMHO.

What do you mean with "monitor" ?!

**Comment by DaemonPhoenix42** [comment]
Ohh my mistake, It does seem to be picking them up. Jumped the gun on bringin' my perceived issue to your attention.
I do however have some files that now have multiple subtitles (One local thanks to TMM scraping, and the original embedded ones).
I'll remove the extras and let you know if it persists.

though another idea would be converting file types and automatically embedding subtitles for MKV, I don't see that being too trivial of a implementation though. so, for now, I'll continue using MKVMerge

**Comment by myron0815** [comment]
Well, it would be not hard... but we decided to not touch/alter the user's video file.
Mainly to keep the file hash consistent, to not trigger any sync scripts...
