### ISSUE TITLE
Rare movie rename issue

### ISSUE THREAD

**Issue by thwaller** [tinyMediaManager/tinyMediaManager#349]
Version: 2.9.13-SNAPSHOT - PRE-RELEASE
Build: 2018-07-23 18:36
OS: Linux 4.15.0-29-generic
JDK: 1.8.0_181 amd64 Oracle Corporation

I have encountered what I believe to be a rare issue. I have 2 movies with the same title and the same year of release. Given this, when I use the renamer, I get an error as the folder names as generated using the style "Movie Name (Year)" is in fact a duplicate. This has also created other issues not related to tMM but with many other sites and searches for this/these movies. Now, I can easily fix this manually, but I wonder as an enhancement there would be some sort of error handling for such things? I understand that is a lot of work for such a small thing, and likely quite rare. But I thought I would share in the case that there are similar or related issues that come up for something to also consider should/when a fix become worth the efforts.

For reference, these are the two movies I am referencing in this report:
1) https://trakt.tv/movies/fireball-2009
2) https://trakt.tv/movies/fireball-2009-01-02

Please also note that while this is already likely to be a rare issue, both of the movies referenced here are also more rare movies on their own. So I am not really expecting a fix, but more to identify a known issue that may have not been considered prior.

**Comment by ProIcons** [comment]
Thing is, that the only possible solution of doing this is adding something more on the Folder's Name, which it will probably generate issues with some Media Centers such as Kodi. Most of media centers even though there's a ".nfo" File that describes the movie, tends to scrape it again for good measure, to ensure the validity of the ".nfo" and Movie's data in general. Now if we append a random string or a unique id that corresponds to one of our scraping services, that could generate issues on these media centers by not being able to detect the movie them selves. Having said that, this is a rare issue worth taking a look into it, but it is certainly on a low priority.

Thank you for this report. You will be notified about it's process by this page.

**Comment by mlaggner** [comment]
the only way to _fix_ this would be that the user adds some sort of id (imdb/tmdb) to the renamer token..
nevertheless - the renamer would not rename/movie the files from one movie into the other, so we are some sort of safe here.
since there is no fix we can provide (only the _suggestion_ above), I will close this issue
