### ISSUE TITLE
Cannot choose country at preferred language setting (at movies/scraper)

### ISSUE THREAD

**Issue by adrianosantanna** [tinyMediaManager/tinyMediaManager#35]
Version: 2.7.4
Build: 2016-04-01 19:01
OS: Linux 4.5.0-2-amd64
JDK: 1.8.0_91 amd64 Oracle Corporation

__What is the actual behavior?__

It's not available to choose country at preferred language setting, at movie/scraper settings.

When I choose Portuguese it works as pt-PT.

__What is the expected behavior?__

Choose pt-BR (Brazilian Portuguese) or pt-PT (Portuguese of Portugal), instead of only Portuguese. 

Movies names are not always the same in Brazil and in Portugal.

__Steps to reproduce:__

Choose Portuguese as preferred language (movie/scraper) and scrape the movie 'Divergent'. tmm will scrape 'A Série Divergente: Divergente', which is the movie name in Portugal, but would be desirable to scrape 'Divergente', the movie name in Brazil, also available at themoviedb.org.

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
which scraper do you use?

With tmdb we can only pass the ISO 639-1 code to their web service (see http://docs.themoviedb.apiary.io/#reference/movies) - which is pt for both.
With imdb it _could_ work (imdb has a strange internal ruleset which translation to respond)

**Comment by adrianosantanna** [comment]
I'm using The Movie Database (TMDb). 

    Em Sexta-feira, 27 de Maio de 2016 2:31, Manuel Laggner <notifications@github.com> escreveu:
 

 which scraper do you use?With tmdb we can only pass the ISO 639-1 code to their web service (see http://docs.themoviedb.apiary.io/#reference/movies) - which is pt for both.
With imdb it could work (imdb has a strange internal ruleset which translation to respond)—

**Comment by pablobs** [comment]
I was looking at the code just to see this question.
In fact the theMovieDB accepts BCP47 language tag. So if you query through pt-BR, it returns the results in Brazilian Portuguese correctly.
Ex.:
http://api.themoviedb.org/3/movie/10890?api_key=<apiKey>&language=pt-BR
returns
{..."title":"Recrutas da Pesada"...}

http://api.themoviedb.org/3/movie/10890?api_key=<apiKey>&language=pt
returns
{..."title":"O Pelotão Chanfrado"...}

I saw a while back about this issue about iso 639-1 in TMDB ... although no update in the documentation, they have changed this more than a year ago....

**Comment by mlaggner** [comment]
thanks for the hint, I'll have a look what we need to change for this request

**Comment by mlaggner** [comment]
with the latest changes (actual nightly build) you should be able to scrape pt-BR from tmdb
