### ISSUE TITLE
Variable for disc/part number missing - rename not working correctly

### ISSUE THREAD

**Issue by mouth4war** [tinyMediaManager/tinyMediaManager#350]
__What TMM version are you using?__
latest

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
Multiple disc moves (cd1, cd2) are not renamed properly since there is no variable for disc number available to add to the rename string

__What is the expected behaviour?__
Multiple disc moves (cd1, cd2) are renamed properly using disc/part number variable

__Steps to reproduce:__
- first
- second
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

**Comment by mlaggner** [comment]
IIRC the renamer takes the multi disk part from the old filename and attaches it to the new one..
but without a real example / log I am unable to analyze that further

**Comment by mouth4war** [comment]
I renamed from CD1/2 to Part1/2 and it worked
