### ISSUE TITLE
Directors/writers not being scraped from any DB (for movies only)

### ISSUE THREAD

**Issue by raffishtenant** [tinyMediaManager/tinyMediaManager#351]
Version: 2.9.13
Build: 2018-07-23 18:42
OS: Mac OS X 10.13.1
JDK: 1.8.0_161 x86_64 Oracle Corporation

__What is the actual behaviour?__

I may be losing my mind, but I can't seem to get directors or writers to scrape at all anymore for movies, as of the latest version. I did a search and found that there was an earlier issue with this for IMDb, with OMDB recommended as an alternative, but it doesn't work for me regardless of which scraper I use. Curiously, it still seems to work fine for for TV episodes.

__What is the expected behaviour?__

Self-evident.

__Steps to reproduce:__

Create a dummy file named "Coco.mp4" and scrape it as a Movie with any scraper, selecting the 2017 film. Obviously, this major release has director and writer metadata in every DB, but I find that it does not show up in the info panels or .nfo files.

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2243704/tmm_logs.zip)

**Comment by mlaggner** [comment]
works here, bu I've seen that you **DISABLED** cast scraping in the settings - and this is the default value for scrapes...

**Comment by raffishtenant** [comment]
Gah, my bad...didn't realize that cast and major crew both fell under that setting, but it makes plenty of sense. Thanks for the amazingly response.
