### ISSUE TITLE
country and originaltitle for TV series as well?

### ISSUE THREAD

**Issue by raffishtenant** [tinyMediaManager/tinyMediaManager#352]
Version: 2.9.13
Build: 2018-07-23 18:42
OS: Mac OS X 10.13.1
JDK: 1.8.0_161 x86_64 Oracle Corporation

__What is the actual behaviour?__

Though often present for TV as well, country and originaltitle are only scraped for movies ATM.

__What is the expected behaviour?__

Perhaps not a high priority, but it would be terrific if these fields could make it into the .nfo for TV. IMDb in particular has a standard of using the English title as the primary, though even most English speakers often don't know the work by that title...so while IMDb is arguably still the "reference standard," having the originaltitle in the metadata is extremely useful for searching purposes.

And country is just nice to have in general, regardless of medium.

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
original title for shows and episodes is already done in v3, but for now we have barely sources for that data..
I hope you understand that imdb is our lowest prio for tv shows because that site is awful for scraping (no official API, endless site changes which needs work on our scrapers, inperformant site, ..), but I will add this to our v3 todo list

**Comment by raffishtenant** [comment]
Thanks. I definitely understand the frustrations with IMDb. I also realized that their legacy flat files (the final versions with integrated IDs) are actually a pretty good fallback for some of this information, so for my application I'm planning to leverage their title.basics.tsv file for primary and original titles whenever I have an IMDb ID to work with. Of course, it's no longer being updated post-2017, but it's not bad in a pinch.

**Comment by mlaggner** [comment]
I've added both in v3
the TV show country is only available from TMDB and IMDB
