### ISSUE TITLE
folder stacking dvds not working (multiple entries in TMM)

### ISSUE THREAD

**Issue by mouth4war** [tinyMediaManager/tinyMediaManager#355]
__What TMM version are you using?__
latest

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
Cannot get multiple folders of same release (2 DVDs) to detect as single entry in TMM
eg:
Title Part1/Video_TS/
Title Part2/Video_TS/

I have tried with Pt1/2 and DVD1/2 with same result (two entries in TMM)
__What is the expected behaviour?__
TMM folder stacking should detect a single release/entry and stack both DVD folders into one

__Steps to reproduce:__
- first
- second
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
