### ISSUE TITLE
[Feature Request] In shows : a way to affect a media to and episode by drag & drop

### ISSUE THREAD

**Issue by schmurtzm** [tinyMediaManager/tinyMediaManager#356]
At the moment when the episodes of a season are not in the right order you've got to rename each media file name with the right episode number and then update data source.
This process works perfectly but it can be very long the rename each file.

I imagine a list UI like this to reaffect episodes in a faster way :

![tinymediamanager association mangaer](https://user-images.githubusercontent.com/7110113/43804920-54807256-9a8d-11e8-95d9-1f9abb83e851.jpg)

- The 2 first columns ("scrapped") are not editable : it comes from the scraping, you can just order the scrapped list by episode number or episode name.
- On the third ("assignment") and fourth columns ("available media file") you can drag and drop the files from a column to another one :

At the beginning all the files are in the "available media file" column. 
You can drag and drop the file in the "assignment" column to the corresponding scrapped media.
You can also use one of the 2 buttons that will try to make it automatically on the basis of the episod name or the episode number contained in the filename.

What do you think about it ?

**Comment by mlaggner** [comment]
we have one very similar.. go to edit tv show and the last tab

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
