### ISSUE TITLE
Provide a way to verify installer

### ISSUE THREAD

**Issue by WPFilmmaker** [tinyMediaManager/tinyMediaManager#358]
I would like to request a way to verify the download of the file from the website. A Sha256sum or GPG would be great.

**Comment by mlaggner** [comment]
thanks for the suggestion.
should be live now!

**Comment by WPFilmmaker** [comment]
@mlaggner Thank you for the add!

I am no expert and don't want to sound like a pain in the bum, but apparently SHA-1 is not considered extremely solid anymore (check https://en.wikipedia.org/wiki/SHA-1 ), depending on the attack case you think tMM might face you might want to think whether to switch to SHA-2 or 3 or keep SHA-1.

Again thank you for adding a security feature!

**Comment by mlaggner** [comment]
Tmm is a media manager and no encryption software or os.. Who the hell should attack tmm??
