### ISSUE TITLE
Vote count still not being grabbed by IMDB Scraper for TV Episodes

### ISSUE THREAD

**Issue by tr0nllam** [tinyMediaManager/tinyMediaManager#36]
Version: Latest nightly Windows build

The IMDB Scraper is still not recording the vote count for TV Episodes. The previous fix does not seem to have worked.

SInce the fix, if I scrape an episode with less than 1000 votes, the program will display the vote count. However, if you look at the NFO, it still shows up as 0 votes. Also, episodes with votes above 1000 are neither displayed, nor recorded in the NFO file.

**Comment by mlaggner** [comment]
thanks for reporting. fixed this and the fixes will be in the next nightly build

**Comment by tr0nllam** [comment]
I just checked the latest nightly and you've fixed the vote count for episodes with votes less than 1000. However, if an episode has more than 1000 votes, it's still not recording it to NFO or displaying it in the program.

**Comment by mlaggner** [comment]
the imdb scraper will be build tomorrow morning (for the fix with vote count > 1000)
