### ISSUE TITLE
scraping is very slow, performance issue?

### ISSUE THREAD

**Issue by b1n4ryj4n** [tinyMediaManager/tinyMediaManager#361]
__What TMM version are you using?__
tmm_3.0-SNAPSHOT_074c6f3_win.zip

__release, pre-release, nightly, or directly from GitHub/branch?__
nightly

__What is the actual behaviour?__
I need greater than 10 minutes to scrap a tv show with 168 episodes (e.g: "Ein Käfig voller Helden").
-- I allocated already, max memory -> 2560 MiB and it is still very slow.

__What is the expected behaviour?__
scrap a tv show lesser than 1 minute

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
Windows 10 x64, VDSL 100k

**Comment by mlaggner** [comment]
What scraper do you use?
Tvdb is sometimes very slow with their new api...

**Comment by b1n4ryj4n** [comment]
tvdb, but i do not think it's a tvdb problem because i tested it with an other tool and it works fast there.

I think it's a problem with collecting and  transfering the thumbnail images, mayby it is better to collect all thumbnails urls first, download the thumbnails all together at the end (e.g. with multi download options so that two or more images are downloaded at the same time) and then move the thumbs from the tmp folder to the specific series folder?

**Comment by mlaggner** [comment]
works here like a charm?
images are collected AFTER everything else has been done (async) - so there should be no problem with images

**Comment by mlaggner** [comment]
well I finally found the issue.. 
tvdb offers a single web service endpoint for all episodes now so we do not need to call 1 endpoint for every episode..
but the internal cache did not get fired, so we still needed to fetch every episode for its own.. should be fixed with the build tomorrow

**Comment by b1n4ryj4n** [comment]
The season images being downloaded very fast, but the thumbnails not. Look all sequential for me. Need over 1 Minute to scrap 24 Episodes. Here a video, that shows what i mean,

https://youtu.be/d5w4FtPzgLg
