### ISSUE TITLE
Cannot remove thumb location in edit (TV Episode for sure)

### ISSUE THREAD

**Issue by NobahdiAtoll** [tinyMediaManager/tinyMediaManager#365]
__What TMM version are you using?__ SNAPSHOT-3,0

__release, pre-release, nightly, or directly from GitHub/branch?__ nightly

__What is the actual behaviour?__ Clearing thumb field does not clear the set thumb location set for the episode

__What is the expected behaviour?__ Clearing thumb field clears the set thumb location set for the episode

__Steps to reproduce:__
- open the TV Episode edit window
  - Go to 'Details 2' tab
  - Clear any set value for the field "Thumb"
  - Click OK on the edit window
- Open the edit window again 
  - Go to 'Details 2' tab 
  - Note the Thumb field has still retained the previously set value

__Additional__
 Just a note this is related to the problems I was having with 3.0-SNAPSHOT and my previous issue about image not changing... (yes on Linux with 2.xx.xx the problem was file acess, but when i ran SNAPSHOT-3.0 on Windows i found the problem was also persisted by the fact that I was recycling temp thumbnail location (just to get it to copy the image edited to the folder next to the file (I reopened that issue and illustrated how to reproduce that....) Now I find it's impossible to clear whatever location is already set, so me using a single file location where i edit and save my files is apparently exposing that issue, and not being able to clear the set location makes me have to use a different edit and save location every time.

**Comment by NobahdiAtoll** [comment]
No not the file just the link to the file.

Currently when you select a file it sets the Thumb field to "file:/path/to/file" and copies the image. I use the same file for editing images. So I want to clear that after the image is copies to location so if I ever edit and change the image it doesn't register as not being changed (since the link will be the same) and the edited file is copied next to video file

**Comment by mlaggner** [comment]
okay, that has been fixed by my changes. please review tomorrow (v3)
