### ISSUE TITLE
A button to clear/remove image

### ISSUE THREAD

**Issue by thwaller** [tinyMediaManager/tinyMediaManager#367]
Version: 2.9.13-SNAPSHOT - PRE-RELEASE
Build: 2018-07-23 18:36
OS: Linux 4.15.0-30-generic
JDK: 1.8.0_181 amd64 Oracle Corporation

I found there is no way to clear or remove an image, like the poster and fanart, from the tMM GUI. I am aware I can just go to the folder and manually remove it. Is there an option I might be missing, or could one be added?

The reason for this is I have a movie that I put into collection, and the only image for fanart that is there is inappropriate. I speak not of pornograpthy, just an R rated movie with a scene that is not suitable for general viewing in a line up of movies. As it is the only image available, I cannot change to another, and selecting nothing and clicking ok produces error.

This is not a high priority thing, but something that maybe can be worked on if you are there making other changes sort of thing.

**Comment by akovia** [comment]
I'd like to request this as well for different reasons, but I've been wishing for this for a while.

Maybe deleting them to the .deletedByTMM folder on a R-click menu, or delete button while selected, or both?

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
