### ISSUE TITLE
Rename option incorrectly setting language of subtitle when it's a composite language code

### ISSUE THREAD

**Issue by msdos** [tinyMediaManager/tinyMediaManager#368]
__What TMM version are you using?__
2.9.13

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
When using the rename feature, a subtitle named movie.pt-br.srt is renamed to movie.br.srt or movie.bre.srt or movie.breton.srt.

__What is the expected behaviour?__
pt-br is "Brazilian Portuguese": so the renaming should br movie.pt.srt, movie.por.srt or movie.portuguese.srt.

When having movie.pt.srt, "Portuguese" instead of "Breton" is correctly chosen.

__Steps to reproduce:__
- Video file with movie.pt-br.srt subtitle.
- Try to rename.

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
Ubuntu 18.04.1

**Comment by mlaggner** [comment]
thanks for reporting. 
I've just added a fix for v3 - we may decide if we also change the v2 api once more to fix this corner case..

**Comment by msdos** [comment]
There are some really rare situations that we can have `pt_br`, `pt-BR` and `pt_BR` as well, but I think this should be another issue since this can be happening to all composite language codes.
