### ISSUE TITLE
Crash when trying to use file chooser

### ISSUE THREAD

**Issue by plguidez** [tinyMediaManager/tinyMediaManager#37]
__What TMM version are you using?__
2.7.4

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
any attempt to access the Mac file chooser results in a crash, whether when trying to add a folder to the list of sources, or saving logs. the app crashes the moment a button which opens the file chooser is pressed.

Your Operating system? 
Mac OS 10.11.5 (latest)

**Comment by mlaggner** [comment]
this is a known bug and already fixed for version 2.8
meanwhile you can look at https://github.com/tinyMediaManager/tinyMediaManager/issues/14 for a workaround
