### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by msdos** [tinyMediaManager/tinyMediaManager#374]
We're in https://github.com/tinyMediaManager/tinyMediaManager/releases/tag/tinyMediaManager-2.9.13 but https://github.com/tinyMediaManager/tinyMediaManager/blob/9825b570421e46fdb9b5d60a4e8c52459225738a/changelog.txt last entry is pointing to 2.9.9.

**Comment by mlaggner** [comment]
I do not know which tree you got, but the actual changelog is https://github.com/tinyMediaManager/tinyMediaManager/blob/master/changelog.txt and this points to 2.9.13

**Comment by msdos** [comment]
I think it was in a previous github source code search. My bad.
