### ISSUE TITLE
config request for filter dupplicates

### ISSUE THREAD

**Issue by b1n4ryj4n** [tinyMediaManager/tinyMediaManager#376]
Hi there,

i would like to have the ability to not list different film versions as duplicate films.

e.g. Terminator 2 has a "Theatrical" and a "Director's Cut" version but  it is listed as a duplicate movie.

**Comment by ProIcons** [comment]
The case is that no Movie Source lists movies differently, and there's no such system to identify a Cut from another. Title is our only source, but then again it's still the same movie. We could maybe add on parenthesis the Movie's edition but it's definitely not on our priority list.

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
