### ISSUE TITLE
TMMv3 A few "inconveniences"

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#377]
Version: 3.0-SNAPSHOT
Build: 2018-08-24 00:35
OS: Windows 7 6.1 Polish
JDK: 1.8.0_181 amd64 Oracle Corporation

I think I can change to TMM3 :) - I have beautifully imported all information from NFO files created with TMM2.
Thank you for the last corrections I asked for (including certification, tmdbSet)

A few "inconveniences" that I encountered in use:

1. when setting the folder name:
$ {genres [0] .name} \ $ {movieSet.title} \ $ {title} ($ {year}) ($ {edition})
- after changing the name, the genre is in English. Non-standard species that I will create myself are OK.
![1](https://user-images.githubusercontent.com/23637884/44620447-b6c83380-a894-11e8-8a8c-4efc26da5b68.jpg)

2. when previewing downloaded graphics - the image is displayed in the original size, it does not adjust to the resolution of the monitor (it comes out pretty much behind the screen of the monitor). To close the image, I have to move the window.

3. With the active TAG filter - selecting the tag does not change the view (it does not filter) immediately - you need to deactivate and then activate the filter.

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2320858/tmm_logs.zip)

**Comment by mlaggner** [comment]
for the first issue - please leave out the .name afert genres[0] and you will get the localized value
the second one should be fixed with the next build 

for the third one I have to investigate something more..

**Comment by mlaggner** [comment]
everything should be fixed in the build tomorrow

**Comment by Zwanzig2** [comment]
thank you very much
1 and 3 work great
2 - nothing has changed (at my place). This may be due to my monitor. Resolution is set to 1680x1050 but I have probably damaged EDID in the monitor.
