### ISSUE TITLE
Rename With An Apostrophe

### ISSUE THREAD

**Issue by OldMan100** [tinyMediaManager/tinyMediaManager#378]
__What TMM version are you using?__
 TMM 3.0

__release, pre-release, nightly, or directly from GitHub/branch?__
Nightly

__What is the actual behaviour?__

Clicking 'Rename/cleanup selected TV Episode' Under A Listing With An Apostrophe In The Episode's Name Produces The Following Characters , &#39;s, Instead Of The Apostrophe.

__What is the expected behaviour?__

Clicking 'Rename/cleanup selected TV Episode' Under A Listing With A Apostrophe Or Any Other Non-Aphanumeric In The Episode's Name Should Replace The Code, Ex. &#39;s, With The Actual Single Character.

__Steps to reproduce:__

Just Rename An Episode With A Apostrophe In The Title. Since The Renaming Is Done Using The Title In The Edit Selected Episode Section And This Is Provided During Scraping Of An Episode'. 

I've Attached Three Pics.

Pic 1 Shows The Title After Scraping.
Pic 2 Shows The Listing After Renaming Episode.
Pic 3 Show The Episode Listing Under Windows Explorer.

Pic 1
![pic 1](https://user-images.githubusercontent.com/35414666/44950502-f7c4c880-adfd-11e8-839d-485db9a9d9a6.PNG)

Pic 2
![pic 2](https://user-images.githubusercontent.com/35414666/44950411-f0042480-adfb-11e8-8831-e13811e47d5f.PNG)

Pic 3
![pic 3](https://user-images.githubusercontent.com/35414666/44950412-f0042480-adfb-11e8-9048-9bee97141893.PNG)

This Can Be Corrected By Going Into Edit Episode Section. Replace &#39;s With ' And Renaming The Episode Regain. Now the Listing In TMM Is Correct, Also The Listing Under Windows Explorer.

But, This Would Mean Manually Correcting Episodes Everytime An Episode Has A Apostrophe Or Any Other Non-Aphanumeric In The Episode's Name.

P.S. Apostrophe Is The Only So Far I've Come Across With This Problem.  So I Don't Know If Other Non-Aphanumeric Characters Would Cause The Same Problem.

__Additional__
Have you attached the Logfile from the day it happened?

This Does Not Produce An Error In The App, Just A Bug In The Renaming.

Your Operating system? (win/mac/linux? version?)
Windows 10

**Comment by mlaggner** [comment]
which scraper did you use?
as you see in the episode editor, the renamer just does what it should do: renames the episode according to the data in tmm.
We should find the source - where did the &#39; come from

**Comment by OldMan100** [comment]
TVDB is where all my scraping is done.  Tried to reproduce the problem.  This time, the episode was  scraped  and renamed correctly.  Maybe, there was a problem on TVDB side and now the problem is corrected.
