### ISSUE TITLE
TV Shows and Trakt

### ISSUE THREAD

**Issue by thwaller** [tinyMediaManager/tinyMediaManager#379]
Version: 2.9.13-SNAPSHOT - PRE-RELEASE
Build: 2018-07-23 18:36
OS: Linux 4.15.0-33-generic
JDK: 1.8.0_181 amd64 Oracle Corporation

It appears there are problems syncing TV shows with Trakt. I suspect it is due to the changes at TheMovieDB, but I cannot verify that.

What happens is you sync to Trakt and it does not sync. Trakt does not show in collection, and tMM does not pull in the Trakt ID. I had to scrape it with TMDB vs TVDB as at first, it did not even pull in the TMDB ID. IMDB ID has pulled fine.

I see nothing in the tMM logs regarding this.Trying to perform a sync to Trakt adds nothing to the log. I refer to Tools -> Show Error Log.

Previously, this had been working fine. I have a small TV show collection only, but the other 3 shows I have entities for in my collection all sync'd fine. Those were added and sync'd in July of this year, around the 14th or 15th. So I would assume it is due to something that has changed between then and now.

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
