### ISSUE TITLE
Unable to scrape episodes

### ISSUE THREAD

**Issue by estidiskyroamer** [tinyMediaManager/tinyMediaManager#38]
I'm using TMM 2.7.4 updated from the download page at website.
Operating system is Windows 10 build 10586.318

Usually when I scrape for a TV show, it will also scrape the episodes (I'm using thetvdb.com scraper). Now when I try to scrape, it just scrapes the TV show's main data (title, rating, status, certification, etc.) but not the episodes, even if I select 'scrape episode metadata'.

I can't upload the logs file. It's generated using the 'contact us' menu from TMM, but when I upload it, it shows error "Unfortunately, we don’t support that file type."

**Comment by myron0815** [comment]
just tested - works fine here?
Can you try again and/or upload the log somewhere else? (pastbin etc)

**Comment by estidiskyroamer** [comment]
I've tried again, still doesn't work.
Is it okay to upload to mediafire?
http://www.mediafire.com/download/9kr97p3d8odjwaw/tmm_logs.zip

**Comment by mlaggner** [comment]
we changed some things in the underlying HTTP library.
Could you try again with version 2.8?

**Comment by estidiskyroamer** [comment]
Alright, looks like it works fine now. Thanks!
