### ISSUE TITLE
Font sizing pushes some controls outside of Dialog bounds 

### ISSUE THREAD

**Issue by NobahdiAtoll** [tinyMediaManager/tinyMediaManager#380]
__What TMM version are you using?__ 3.0-SNAPSHOT

__release, pre-release, nightly, or directly from GitHub/branch?__  Nightly

__What is the actual behaviour?__ Font-scaling makes some controls inaccessible

__What is the expected behaviour?__ Scaling windows does not push controls out of dialog

__Steps to reproduce:__
- first: Set TMM to use a larger scale font (I use 18)
- second  try using the bulk edit dialog, the Accept buttons for all items are not visible and will not become visible by resizing dialog as resizing window is limited to screen resolution and the accept buttons are 300 light years away from their associated labels and editable controls (at least in a 1080p resolution)
![this](https://user-images.githubusercontent.com/20236010/44955243-d56e9180-ae75-11e8-8270-7110cd7eb5a6.png)

__Suggestion__ grid layout is perhaps not the best layout otion to use here unless somehow the grid column bounds can be made resizable by user. I find grid layout tends to be incompatible with scaling if its mixed controls in the grid.

__Additional__ I am using this on a 1920x1080 TV and because of visual issues I have to use a larger font in order to see, this wreaks havoc on all the scaling on Dialog Windows (save for the edir window)
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?) Debian 9 (stretch)

**Comment by mlaggner** [comment]
could you give me more examples, where a large font size do not fit?

**Comment by NobahdiAtoll** [comment]
bulk editor and filter are the two that I've noticed

**Comment by NobahdiAtoll** [comment]
Found it. TV Show/Details 2/Add ID

**Comment by mlaggner** [comment]
thanks - so I will close this issue, since I've fixed the bulk editor yesterday
