### ISSUE TITLE
[enhancement] make custom ids visible in info panel's

### ISSUE THREAD

**Issue by b1n4ryj4n** [tinyMediaManager/tinyMediaManager#381]
__What TMM version are you using?__
3.0
__release, pre-release, nightly, or directly from GitHub/branch?__
NIGHTLY

__What is the actual behaviour?__
Currently only IMDB, TMDb and Trakt are always displayed in the info panel.

__What is the expected behaviour?__
It would be nice if own IDs could be displayed there as well. Otherwise you always have to open the movie editing and go to detail 2 to see all id's.

**Comment by mlaggner** [comment]
well having a dynamic list is not easily at design time.. you have to reserve some space, don't know how much minimal space you should give that list and how much maximum space..
maybe I find a space somewhere to put that list..

**Comment by ProIcons** [comment]
That would be easier and makes much more sense. 
Or we could do it vertically, same story.

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
