### ISSUE TITLE
Movie Rename Variables Feature Request.

### ISSUE THREAD

**Issue by Rappleby28** [tinyMediaManager/tinyMediaManager#382]
Greetings,

I am a registered user of tMM 2.9.13 (Excellent Program BTW) on Windows 7 Pro.  I have my movies organized as M:\Movies\\[Genre Folder]\\[Movie Folder]\The Actual Movie.mkv.  (the M: drive is a 32 TB Raid 6 Array)

I tried to use "M:\Movies" as part of the rename but it was not accepted because of the colon.  I could place the movies in the root directory before scraping to achieve the result that I want but I don't like using the root directory to store individual files.  Is there a way to include the drive letter in the renaming process?

If not, is it possible to create a variable for the drive letter in the Rename Tab?  This would allow the flexibility to move the movie to any folder on any drive after scraping and renaming. 

Thank you for any suggestions and/or consideration of my feature request.

**Comment by mlaggner** [comment]
I am sorry, there is no such function.
the renamer works only inside one data source (to avoid time consuming move/copy operation while renaming).
in v3 we plan an action to move a movie to another datasource - this could be what you want

btw: I have a similar workflow - I have the folder _upload_ in my datasource where I put all new movies and rename them from there. Kodi is configured to ignore the _upload_ folder -> everything works fine ;)

**Comment by henkall** [comment]
> I am sorry, there is no such function.
> the renamer works only inside one data source (to avoid time consuming move/copy operation while renaming).
> in v3 we plan an action to move a movie to another datasource - this could be what you want
> 
> btw: I have a similar workflow - I have the folder _upload_ in my datasource where I put all new movies and rename them from there. Kodi is configured to ignore the _upload_ folder -> everything works fine ;)

The feature to move a movie to another datasource would be nice. 👍

**Comment by mlaggner** [comment]
the feature to move a movie/TV show to another data source has been implemented in v3
