### ISSUE TITLE
New TV Show: Artwork of Specials not shown

### ISSUE THREAD

**Issue by Lonerider2010** [tinyMediaManager/tinyMediaManager#383]
Version: 3.0-SNAPSHOT
Build: 2018-09-05 00:36
OS: Linux 4.15.0-33-generic
JDK: 1.8.0_181 amd64 Oracle Corporation

__What is the actual behaviour?__
When I created a new tv show (no data available from tvdb), I added artwork (poster, fanart, banner) to the specials, which was shown in tmm and also stored as season-specials-*.jpg.
When I started tmm again, the artwork of the specials is not shown anymore.

__What is the expected behaviour?__
tmm should show the artwork of the specials after each restart.

__Steps to reproduce:__
1. Create a new tv show.
2. Add a specials directory and insert the videos
3. Edit the tv show in tmm.
4. Add artwork (local files: poster, fanart, banner) to the tv show.
5. Edit the artwork for the specials. Use the artwork from the tv show.
6. The specials artwork is stored as season-specials-*.jpg.
7. Restart tmm.
8. The tv show's artwork is still shown.
9. The specials artwork is not shown anymore, but still existing in the tv show's directory.

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs_2018-09-05.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2351482/tmm_logs_2018-09-05.zip)

**Comment by mlaggner** [comment]
will be fixed in the next build
