### ISSUE TITLE
Feature Request: Bulk Editor Additions

### ISSUE THREAD

**Issue by NobahdiAtoll** [tinyMediaManager/tinyMediaManager#384]
I think I may be becoming a bother, but I just wonder if it would be possible to add studio and country to the bulk editor for TV Shows?

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
