### ISSUE TITLE
[enhancement] make tree nodes collapsible / expandable using arrow keys

### ISSUE THREAD

**Issue by b1n4ryj4n** [tinyMediaManager/tinyMediaManager#385]
__What TMM version are you using?__
3.0

__release, pre-release, nightly, or directly from GitHub/branch?__
NIGHTLY

__What is the actual behaviour?__
The tree nodes can not be expanded or collapsed with the arrow keys.

__What is the expected behaviour?__
The tree nodes can be expanded or collapsed with the arrow keys. Because this functionality I am used to from other programs and I am always annoyed that I have to serve the mouse here. 🙈

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
