### ISSUE TITLE
[Feature Request] Renaming across drive letters

### ISSUE THREAD

**Issue by henkall** [tinyMediaManager/tinyMediaManager#386]
Using TMM on Windows.

I could really need the option so actually be able to rename to another drive.

If I have a movie at D:\Movie\movie_name\
Then renaming it would be moving it to E:\Movie\movie_renamed

It is maybe possible to do in Linux because Linux is not using drive letters but how to do it in Windows?

**Comment by mlaggner** [comment]
we will only rename inside an data source - but with v3 you are able to change the data source of a movie/tv show, so it gets moved.

**Comment by henkall** [comment]
Hi. I have just looked at this feature in v3 and it seems fine but if I have a tv-show split between two sources I can't move them to only one source because it is telling me the folder already exist on the source.

Would it possible to make it then only move the episode file?

**Comment by myron0815** [comment]
No, we try to not correct such things.
If the show (folder) is already existent, then we do not move it.

This could be a complete other show, and since the user's files are most important to us, you need to correct such things on your own...
