### ISSUE TITLE
Does not run on Ubuntu Bionic

### ISSUE THREAD

**Issue by mabushey** [tinyMediaManager/tinyMediaManager#387]
__What TMM version are you using?__
tmm_2.9.13_5cfe5d1_linux.tar.gz

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
```
michael@corwin ~/source/tmm$ ./tinyMediaManager.sh
michael@corwin ~/source/tmm$ echo $?
0
```

__What is the expected behaviour?__
tmm to run

__Steps to reproduce:__
```
mkdir tmm
cd tmm
tar -xvzf ../tmm_2.9.13_5cfe5d1_linux.tar.gz  (by the way the archive not being in a dir is really disrespectful)
./tinyMediaManager.sh
```
__Additional__
Have you attached the Logfile from the day it happened?
[launcher.log](https://github.com/tinyMediaManager/tinyMediaManager/files/2364514/launcher.log)

Your Operating system? (win/mac/linux? version?)
Ubuntu Bionic

**Comment by mabushey** [comment]
There used to be a Docker container for tmm which would  be awesome, but it hasn't been touched in years. It would be awesome if there a supported dockerfile to keep all the delicate java dependencies in line. I was able to fix it via:
```
sudo dpkg --purge openjdk-11-jre-headless default-jre-headless 
sudo dpkg --purge openjdk-11-jre default-jre
```

**Comment by mlaggner** [comment]
well, creating a docker instance is not in our interest, but we will try to adopt the code so that it will run with java 11..
We still do not know what exactly is broken with java 11
