### ISSUE TITLE
Exporting order of xml is different when running from CLI and GUI

### ISSUE THREAD

**Issue by msdos** [tinyMediaManager/tinyMediaManager#389]
__What TMM version are you using?__
2.9.13 and v3.

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
Exporting movielist in GUI keeps the GUI order in the xml nodes. Exporting with `export` CMD option gives a random order.

__What is the expected behaviour?__
Both export options should give the same order.

__Steps to reproduce:__
- Run the commandline script `./tinyMediaManagerCMD.sh -export ListExampleXml ~/Downloads/export/`. Move the file to movielistcli..xml. Then, select all movies in GUI and select the export option, using the same template.

__Additional__
Have you attached the Logfile from the day it happened?

They're are not meaningful, they all give `INFO  [main] o.t.core.movie.MovieExporter:113 - movie list generated: /home/user/Downloads/export/movielist.xml`

__Your Operating system? (win/mac/linux? version?)__

CLI
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK Client VM (build 25.181-b13, mixed mode)

openjdk-8-jdk-headless/stable,now 8u181-b13-1~deb9u1 armhf [installed]
  OpenJDK Development Kit (JDK) (headless)

openjdk-8-jre-headless/stable,now 8u181-b13-1~deb9u1 armhf [installed]
  OpenJDK Java runtime, using Hotspot JIT (headless)

Debian 9.4

GUI
Ubuntu 18.04. Just exported the db from the CLI machine to test.

**Comment by mlaggner** [comment]
the GUI sorts the movie list on every output.. if you do a special sorting (i.e. by rating), this will reflect directly into the exported list.
I will add a standard sorting (by title - default in the GUI) for the command line option (v2 & v3)

**Comment by mlaggner** [comment]
just changed it for v3 - could you test it tomorrow with the new build?
If it was successful, I will backport it to v2

**Comment by msdos** [comment]
I updated running the .sh updater on commandline... is that correct? I exported in GUI and in CMD and now they have the same order, the GUI (this means that it's not alphabetically ordering, so movies that begins with "The" will follow the default GUI order that doesn't take it into consideration).

**Comment by msdos** [comment]
> I will add a standard sorting (by title - default in the GUI) for the command line option (v2 & v3)

Please don't forget to add this information in Command Line documentation, so users will know this limitation in advance.

Thanks for the fix.

**Comment by mlaggner** [comment]
should be in the next release/nightly build
