### ISSUE TITLE
scraper-animated gives a o.t.s.animated.AnimatedMetadataProvider:197 - Error reading json/cache 11188 2018-09-15 15:12:37 java.nio.file.FileAlreadyExistsException: cache if the cache folder is a symbolic link

### ISSUE THREAD

**Issue by msdos** [tinyMediaManager/tinyMediaManager#390]
If `cache` is a symbolic link, this exception is thrown in https://github.com/tinyMediaManager/scraper-animated/blob/738d02a7b52fba1e0afc231f468b7b4715a17917/src/main/java/org/tinymediamanager/scraper/animated/AnimatedMetadataProvider.java#L188.

This seems to be correct from a Java perspective (https://bugs.openjdk.java.net/browse/JDK-8130464), but not from an usability standpoint.

My suggestion is to either encapsulate `Files.createDirectories(JSON_FILE.getParent());` in  try catch itself or check if it's a symbolic link too.

**Comment by mlaggner** [comment]
well, you are messing around with tmms internal folder structure and report a bug where no one is in a standard installation..
if we have to respect all internal folder to be symlinks too, we have to change a bunch of code.. for what benefit?

**Comment by msdos** [comment]
t's no uncommon to use symbolic links in headless devices that use sd cards (for example, a raspberrypi), for folders that receive too many writings, pointing to a normal HD for example. I know in your documentation you say to use the $HOME folder since it can grow a lot, but defeats the mentioned purpose to avoid sd wearing out too fast. Usually, SD cards are smaller than HD and it makes sense as well to put media files in an external HD.

I'm not asking to all folders to be symlinks, but specifically the `cache` one since it seems you always try to create it, in the specific line I showed. This is the only folder that gives the problem. All the others (logs, data, backups) work just fine.

I'm not calling it a bug: I'm asking if something can be done to avoid this error in this scenario. For example, if in the code, before calling `Files.createDirectories(JSON_FILE.getParent());`, you check if a folder or a symlink with the same name exists.

**Comment by mlaggner** [comment]
just fixed it for v3..
don't think I will create a new branch & release for v2
