### ISSUE TITLE
Typo: whitch instead of which

### ISSUE THREAD

**Issue by msdos** [tinyMediaManager/tinyMediaManager#391]
https://github.com/tinyMediaManager/tinyMediaManager/blob/c6c1a4025a16ebce3ffec4cef16856089e19a440/src/main/java/org/tinymediamanager/core/tvshow/tasks/TvShowScrapeTask.java#L129

https://github.com/tinyMediaManager/tinyMediaManager/blob/c6c1a4025a16ebce3ffec4cef16856089e19a440/src/main/java/org/tinymediamanager/core/movie/tasks/MovieScrapeTask.java#L231

**Comment by msdos** [comment]
hahahaha, I made myself a typo when posting the issue

**Comment by mlaggner** [comment]
fixed for v3.
