### ISSUE TITLE
Art not staying when set.

### ISSUE THREAD

**Issue by akovia** [tinyMediaManager/tinyMediaManager#394]
__What TMM version are you using?__
3.0-SNAPSHOT

__release, pre-release, nightly, or directly from GitHub/branch?__
Build date: 2018-09-20 00:35

__What is the actual behaviour?__
Not able to set artwork and have it stay after closing program. I changed series poster and fanart as well as season posters and thumbs. I also made sure to rewrite the nfo when done.

__What is the expected behaviour?__
Have artwork stay after setting it.

__Steps to reproduce:__
- Select local art for poster.
- If it takes it, close the program and open it back up.
- The artwork is gone.

__Additional__
[tmm.2018-09-19.5.log.gz](https://github.com/tinyMediaManager/tinyMediaManager/files/2403214/tmm.2018-09-19.5.log.gz)
[tmm-1.mkv.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2403220/tmm-1.mkv.zip)

Have you attached the Logfile from the day it happened?
Yes. I also uploaded a video to better explain what is happening.

Your Operating system? (win/mac/linux? version?)
Arch Linux: 4.18.7-arch1-1-ARCH

**Comment by akovia** [comment]
After some more testing I think it might be related to my art folder being hidden.
`.art_bu`

I'm able to browse to and pick the art I want without any trouble, and the correct path is listed in the artwork URL, but it just won't load it. If I move the art to a non hidden folder, I can select it without any trouble.

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
