### ISSUE TITLE
User set art overwritten 

### ISSUE THREAD

**Issue by akovia** [tinyMediaManager/tinyMediaManager#395]
__What TMM version are you using?__
3.0-SNAPSHOT

__release, pre-release, nightly, or directly from GitHub/branch?__
Build date: 2018-09-20 07:02

__What is the actual behaviour?__
Artwork set from local source is being overwritten when using "**Download Missing Artwork ...**"

__What is the expected behaviour?__
Only download art that is missing

__Steps to reproduce:__
- Select local sources for artwork
- Use the "Download Missing Artwork for selected TV Show..."
- tmm downloads new artwork to replace artwork set by user.

__Additional__
Have you attached the Logfile from the day it happened?
Yes
[tmm.log](https://github.com/tinyMediaManager/tinyMediaManager/files/2403240/tmm.log)
Your Operating system? (win/mac/linux? version?)
Arch Linux: 4.18.7-arch1-1-ARCH

Just wanted to say I am a doner and a fan. I really like the new program and look forward to having the bugs worked out. Thanks for the scraper fix! I did want to add that when it finishes scraping now, it will select the first item in the show list. Then you have to scroll back to the show you just scraped.

**Comment by akovia** [comment]
Just wanted to add this just happened when using "Update Selected TV show(s)" All of my set art reverted to defaults.

**Comment by mlaggner** [comment]
in this logs I saw that you have a bunch of _strange_ images in your TV show folder (and subfolders)...
I suppose we might set the right one (TV show/poster.jpg) but update data source finds other ones (TV show/extrafanart/...)
since parsing TV shows is extremely more complicated than parsing movies, we might find wrong items here

**Comment by mlaggner** [comment]
could now reproduce the isse from #397 and here (update TV show) - this was driven by your extrafanart folder.
but could not reproduce the issue with _download missing artwork_ - maybe this was also a side effect?
I'll push my changes for there and #397 and please you to test again with the new build

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
