### ISSUE TITLE
Artwork getting overwritten on 2.9

### ISSUE THREAD

**Issue by akovia** [tinyMediaManager/tinyMediaManager#397]
Version: 2.9.13
Build: 2018-07-29 13:41
OS: Linux 4.18.7-arch1-1-ARCH
JDK: 1.8.0_181 amd64 Oracle Corporation

__What is the actual behaviour?__
Assigned artwork is overwritten when Updating Show.

__What is the expected behaviour?__
User set artwork should not be overwritten.

__Steps to reproduce:__
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2408146/tmm_logs.zip)

1. Select a local poster, banner, fanart, etc...
2. Run command "Update Selected TV show(s)"
3. Artwork reverts to previously assigned artwork

__Additional__
Have you attached the logfile from the day it happened?
Yes

**Comment by mlaggner** [comment]
sorry, cannot reproduce that problem nor there is any hint in the logs..
just tested it with replacing the TV show banner with a local file and after _update selected TV shows_ everything was the same
