### ISSUE TITLE
Feature Request: separate scraping of cast from country & studio

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#400]
Version: 3.0-SNAPSHOT
Build: 2018-09-26 00:35
OS: Windows 7 6.1 Polish
JDK: 1.8.0_181 amd64 Oracle Corporation

1. Is it possible to separate the scraping of the cast from the country and the studio?
I have quite a lot of movies and I've worked hard to adjust the data manually to my needs. In TMMv3, the actors' graphics are scratched with better quality as in TMMv2, I would like to re-download them (of course I must first remove old ones because they do not replace them) but when downloading the cast - it also downloads country and studio and replaces which I already have edited.

2. Function - download the missing graphics - just like above. It's about separating extra graphics from fanarts. Fanarts also have edited - removed poor quality, new manually added, etc. After using the function - download the missing graphics - deletes all my fanarts from the extrafanart folder and downloads new ones.

If it is complicated to do it or only I'm interested in it - you can not worry about it, somehow I'm tired of re-editing :)
thx

**Comment by myron0815** [comment]
1) well, yes, ticking actors, and updating contries is not where we should go ;)

2) Withing scrape dialog, we only have "artwork" - everything else would be too much.
On the other hand, in setting you are able to choose the file naming for each type.
If you untick everything unneeded, we might not download them (but might only be a preference, and actually not (yet) a chooser what to download - havent tried)

DownloadMissingGraphics should only download missing ones - and never touch existing.
(At least, if they are known to TMM and havent just been added on filesystem)
Have to check...

**Comment by Zwanzig2** [comment]
ad.1 If I understood correctly, this separation of actors' scraping from the country and the studio is possible? It would be great.
If I do not delete folder .actors, it will not download new graphics for me. At the moment (for trial) I am removing folder .actors and scrape again. In the folder I have new graphics but in TMMv3 it still displays old ones (even if I clear the graphics cache).

ad. 2 - it means that I clean in preferences, for example, all Fanart names, then after calling the function "download missing graphics" fanarts will not start and download only those with selected names?
Existing graphics do not overwrite, the problem I have is only with extrafanart. There, it happens that there is no downloadable fanarts or are of poor quality. I download them manually and save in sequence fanart1, fanart2 ... .  If I call "download the missing graphics" TMM downloads as it is in TMDB and FanartTV. eg I have 10 extrafanarts / on TMDB it is 5 / after calling the function ... ... in extrafanart I have 5 fanarts.
But we do not have to worry about it, that's my problem :) I will try to uncheck the fanart names in the settings. On the other hand, I do not use it that often.

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
