### ISSUE TITLE
Scraping overwrites any existing .nfo file without checking type or honoring NFO naming settings.

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [tinyMediaManager/tinyMediaManager#401]
__What TMM version are you using?__
2018 July 23rd one

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
When TMM scrapes (I believe this is the term? This is my first time using the app), it automatically overwrites any existing .nfo files without warning or checking the type of the file (is it a "scene" NFO, i.e. ASCII art text file), and without adhering to any settings about NFO file naming.

__What is the expected behaviour?__
Well, first of all, I wouldn't expect an analysis run to write *anything* to the targets being analysed without prior warning and consent. Be that as it may, choosing to do so regardless would at worst be an annoying nuisance, unless it also chose to *change* data, which is what is happening here.

In my particular situation, I protect the integrity of my media files by adding PAR2 parity data to each folder. Mutating any file in such a folder damages integrity, and will need a repair operation to run, in order to repair the destroyed data, which is a time and resource consuming effort.

But, at least I *have* the PAR2 data. Had I not, the damage would have been irreversible. I thank my lucky stars that the app is at least not also automatically renaming files, as I see that this is also an option.

I know it's not comme il faut to bitch about FOSS software -- and I really don't mean to -- but I do think that mutating *anything* without user consent is a terrifically bad thing to do. 

__Additional__
Your Operating system? (win/mac/linux? version?)
Ubuntu 18.04.1.

**Comment by DanielSmedegaardBuus** [comment]
Okay, mucking around a bit more, I realise it is not the scraping step that does this, it's actually when I use the "Rewrite NFOs ..." action in the list.

So, it's pretty much on me :) However, it would really be nice if TMM could ignore existing .nfo files altogether (or perhaps just those that won't parse as XML?), and be configured to just create its own, rather than assuming that anything named .nfo is an XML file and then take ownership of it.

**Comment by minikN** [comment]
@DanielSmedegaardBuus Could you possible elaborate on this a bit more? Because I believe I have the same issue. I've never used the "Rewrite NFOs" option. Yet, after a new installation of TMM - and after adding the files, it will automatically scrape new metadata and overwrite my existing NFO files.
