### ISSUE TITLE
Non-Standard genre in Polish - Fantasy

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#402]
Version: 3.0-SNAPSHOT
Build: 2018-09-27 00:35
OS: Windows 7 6.1 Polish
JDK: 1.8.0_181 amd64 Oracle Corporation

How to add an non-stander genre - Fantasy ?.
TMM translates the term Fantasy into Polish - Fantastyka. However, it is not unambiguous in Polish. Fantasy is a general term (eg Jurassic World, The Twilight Saga, The League of Extraordinary Gentlemen, etc.), but they are not S-F and Fantasy is commonly referred to as medieval films (Lord of the Rings, Conan, The Huntsman: Winter's War, etc.)
If I try to enter exactly Fantasy - it automatically saves as Fantastyka.

**Comment by myron0815** [comment]
Well, internally, the genre _IS_ already called Fantasy- therefor you cannot enter it twice ;)
But it mainly depends upon the scraper source, how they define the genres... we're just taking them 1:1 and translating...

Feel free, to add own genres in TMM, and tag them accordingly....

**Comment by Zwanzig2** [comment]
OK understands. Of course, I can handle it differently, I will try eg Fantasy (Fantasy) :) or I will use Tag.
