### ISSUE TITLE
TheTVDB ID is displayed even though anidb is chosen

### ISSUE THREAD

**Issue by utdrmac** [tinyMediaManager/tinyMediaManager#404]
__What TMM version are you using?__
2.9.13

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
See screenshot. The TV show is anime. AniDB is set with appropriate ID in show settings. On the show overview, you can see under "IMDB ID" it says "TVDB ID" with the same ID for anidb. This is obviously incorrect.

__What is the expected behaviour?__
The expected behavior is to not show TVDBID when AniDB is the chosen scraper.

__Steps to reproduce:__
- add an anime
- select anidb as the scraper
- see that TVDB ID is displayed

__Additional__
Your Operating system? Mac OS High Sierra

<img width="540" alt="screen shot 2018-10-02 at 9 52 57 pm" src="https://user-images.githubusercontent.com/4413670/46387788-0b2db280-c68e-11e8-9d1d-998386a86c39.png">

**Comment by myron0815** [comment]
puh - can you reproduce this?
and send me the logfile?

I'm unable to - it works correct here (scraping exact that anime)

**Comment by utdrmac** [comment]
If it's a graphical glitch (ie: a bug), why did you close this bug report?

**Comment by mlaggner** [comment]
just fixed it in v3 - see the commit message above
