### ISSUE TITLE
Fanart.TV not working for TV Artwork Images?

### ISSUE THREAD

**Issue by mgonzales71** [tinyMediaManager/tinyMediaManager#405]
Version: 3.0-SNAPSHOT
Build: 2018-09-27 00:35
OS: Windows 10 10.0
JDK: 10.0.2 amd64 Oracle Corporation

using latest 3.0 snapshot as of this issue posting date

__What is the actual behaviour?__

fanart.tv artwork not showing available / scraping to tv shows

__What is the expected behaviour?__

i entered my personal api key
go to choose a new artwork for tv show (say for example logo)
nothing from fanart.tv shows up as available but if you go to fanart.tv they have logo artwork available

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2445300/tmm_logs.zip)

**Comment by myron0815** [comment]
Have you tried without API key?
I have none, and it works.

If i enter a wrong one, the error response is silently ignored :(
I've changed that for next build, so we might see, what Fanart.tv is answering :)

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
