### ISSUE TITLE
Registration info is lost between system reboots

### ISSUE THREAD

**Issue by b1azk0** [tinyMediaManager/tinyMediaManager#408]
Version: 2.9.13
Build: 2018-07-23 18:42
OS: Linux 4.14.74-1-MANJARO
JDK: 1.8.0_181 amd64 Oracle Corporation

__What is the actual behaviour?__
After each reboot TMM loses registration info and I need to re-enter it in order to use kodi plugin again

__What is the expected behaviour?__
:)
I'd like to keep registration details from boot to boot.

__Steps to reproduce:__
Can't say as it happend from day one on manjaro (was OK under windows7)

__Additional__
Have you attached the logfile from the day it happened?
I saved it. Should I send it somehow here?

**Comment by myron0815** [comment]
License is stored in a file called "tmm.lic"
Usually directly inside TMM directory (assuming write rights)
Can also be in ~/.tmm/ or in ~./ folder....

Do you have that file?

**Comment by b1azk0** [comment]
Hi,
yes, I have the file "tmm.lic" located in where I extracted all tmm files `/home/username/progs/tmm/`

**Comment by mlaggner** [comment]
do you have multiple network interfaces or changing mac addresses? (the license is bound to your mac address)

**Comment by b1azk0** [comment]
ahhh... I was using `nordnm` script with mac address randomization. Turned that off now, and see if problem is solved.
Thanks for your support
