### ISSUE TITLE
TMDB does not find a graphic

### ISSUE THREAD

**Issue by Zwanzig2** [tinyMediaManager/tinyMediaManager#409]
Version: 3.0-SNAPSHOT
Build: 2018-10-20 00:35
OS: Windows 7 6.1
JDK: 1.8.0_181 amd64 Oracle Corporation

As in the title - TMMv3 after the last update stopped searching for graphics from Tmdb. The site Tmdb works.

It also seems that Movieset does not load extra graphics. Graphics (logo, clearart, banner) have been saved in movie folders but you can not see them in the edit window. Poster and fanart reads normally.

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2498013/tmm_logs.zip)

I checked in TMMv2 - and it's all right.

edit:
I just noticed that the movieset does not work in editing - "find tmdbid"
edit2:
In Movies from the queue does not scrape graphics from the site fanartTV

**Comment by mlaggner** [comment]
well there has been an issue with movie set renaming (artwork did net get renamed too).. this has been fixed the last days

**Comment by Zwanzig2** [comment]
OK, I did not notice that they are under the changed name.
But it looks like there is no way to get them back to the names you know.
I need to download Movieset graphics again ??

**Comment by Zwanzig2** [comment]
I have graphics in the format movieset-poster, movieset-fanart, .... - it's probably a good name. And yet it does not display.

**Comment by Zwanzig2** [comment]
Now I deduce that maybe after changing the source (or changing the name), TMM loses contact with Movieset graphics.
I just changed the source of the collection (I moved to a different location using TMM). Before changing - the graphics were visible in the Movieset tab. After the change - they are gone (they are physically in folders with movies).

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
