### ISSUE TITLE
Removed files do not disappear from movies view

### ISSUE THREAD

**Issue by metivier** [tinyMediaManager/tinyMediaManager#41]
__What TMM version are you using?__
2.8

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
Files added then removed do not disappear on refresh action.

__What is the expected behaviour?__
Files removed must be removed from movies view

__Steps to reproduce:__
- add a movie to the movie folder
- refresh movies list by clicking refresh button (the movie appears)
- remove (or move) the movie
- the movie stay in the list of movies view.

__Additional__
Your Operating system : windows 10

**Comment by mlaggner** [comment]
should be improved in the next version
