### ISSUE TITLE
Tmm abends trying to save

### ISSUE THREAD

**Issue by phildtmm** [tinyMediaManager/tinyMediaManager#411]
[tmm20181026.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2519135/tmm20181026.zip)
Version: 3.0-SNAPSHOT
Build: 2018-10-25 00:35
OS: Linux 4.18.16-pclos1
JDK: 1.8.0_162 amd64 Oracle Corporation

__What is the actual behaviour?__
After entering information on the video and selecting save, an error message is generated

__What is the expected behaviour?__
Information is saved and .nfo is updated

__Steps to reproduce:__
Select a video, enter information for the video - in my case it was plot, year, release date, production, genre and actors and then "save"

__Additional__
Have you attached the logfile from the day it happened?
Yes - See above

**Comment by mlaggner** [comment]
thanks for the info. will be fixed in a few minutes (when the new build is done)

**Comment by Zwanzig2** [comment]
unfortunately, you still can not save edited movies. ):

**Comment by mlaggner** [comment]
Did you update? Any useful logs?

**Comment by mlaggner** [comment]
you are right - I've missed one bracket.. new build is up in a few minutes

**Comment by Zwanzig2** [comment]
OK, it seems to be working well.
Thank you
