### ISSUE TITLE
AniDB not filling in several series

### ISSUE THREAD

**Issue by rgooler** [tinyMediaManager/tinyMediaManager#413]
__What TMM version are you using?__
Tried the following versions:

Release: 2.9.13
Prerelease: 2.9.13-PRERELEASE
Nightly: 2.9.14 downloaded 10/29/2018

__What is the actual behaviour?__
When trying to scrape several shows, no data shows up in the scraper preview, nor is the nfo filled out.

__What is the expected behaviour?__
Shows would be scraped

__Steps to reproduce:__
Try to scrape the TV show "Ai No Katachi Ecchi Na Onnanoko Wa Kirai Desuka"

Warning - this is an 18+ show and contains adult content.

__Additional__
Have you attached the Logfile from the day it happened?
Yes

Your Operating system? (win/mac/linux? version?)

Windows 10

**Comment by rgooler** [comment]
[tmm.log](https://github.com/tinyMediaManager/tinyMediaManager/files/2527947/tmm.log)

**Comment by myron0815** [comment]
hmm... i've tried the show, and it worked for me.
But i can see from your log, it doesn't for you. 
(not being able to parse the IDs and others from response)
Have no idea so far....

Does this happen when you try it again?
I can see, that you were quite fast in searching after TMM startup, whilst AniDB was still downloading it cached titles.... it might have interfered...

If you click on this url (as in logs),
http://api.anidb.net:9001/httpapi?request=anime&client=tinymediamanager&clientver=2&protover=1&aid=5638
do you get a quite readable XML back?
