### ISSUE TITLE
TMM3: Trakt ratings are not rounded

### ISSUE THREAD

**Issue by tanrak** [tinyMediaManager/tinyMediaManager#414]
__What TMM version are you using?__
TMM3

__release, pre-release, nightly, or directly from GitHub/branch?__
Nightly

__What is the actual behaviour?__
Trakt ratings are not rounded.

__What is the expected behaviour?__
The rating shows five digits after the decimal point instead of one.

__Steps to reproduce:__
Scrape Infos from Trakt.

**Comment by mlaggner** [comment]
thanks - will be fixed in the next build

**Comment by tanrak** [comment]
Sorry for this questions but any news about this problem?

**Comment by mlaggner** [comment]
should already work on v3 with the actual build

**Comment by tanrak** [comment]
Hm, in version=3.0-SNAPSHOT, build=d79e59a, date=2018-12-07 01\:35 it doesn't work.

https://i.imgur.com/j5mL7ax.png

**Comment by mlaggner** [comment]
you need to re-fetch the data..

**Comment by tanrak** [comment]
Of course, I did it. Re-fetch with tvdb the rating is rounded. Then re-fetch with trakt, the ratings has 5 digits after the decimal point.
