### ISSUE TITLE
Displaying IMDB number of votes in column and allow sorting

### ISSUE THREAD

**Issue by electrifyings** [tinyMediaManager/tinyMediaManager#415]
__What TMM version are you using?__ 2.9.13

__release, pre-release, nightly, or directly from GitHub/branch?__ Release

__What is the actual behaviour?__ TMM does not show the option to display number of IMDB votes in visible columns. Since it is not a column, there is no functionality to sort the movies by number of votes.

__What is the expected behaviour?__ TMM should allow to display number of IMDB votes as one of the columns and additionally should allow us to sort movies by number of votes. 

__Additional__
It is a feature request and not a bug. Since most of us sort movies by rating to watch in those order, some of the movies with votes less than 100 with rating > 8 also comes at the top. I would like to instead watch movies which are popular as indicated by number of votes in IMDB rather than the ones which are highest rated.

Your Operating system? All operating systems since it is feature request.

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
