### ISSUE TITLE
Movies Area Stuck in Getting Mediainfo

### ISSUE THREAD

**Issue by josenightbreed** [tinyMediaManager/tinyMediaManager#419]
Version: 2.9.13
Build: 2018-07-23 18:42
OS: Windows 10 10.0
JDK: 1.8.0_191 amd64 Oracle Corporation

__What is the actual behaviour?__
In the Movies section the program is getting stuck in getting mediainfo, i have around 1900 movies and don't know if that might be the issue. but everytime i hit update sourses in the movie section, this happens. No issues on the tv shows section unless i use the movie section first then it won't do anything because it's stuck in the movies section getting mediainfo.
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2604991/tmm_logs.zip)

__What is the expected behaviour?__

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
you log looks a bit confusing (it might be that you do several things at the same time?)
the last entry is from getting mediainfo of artwork - but I cannot remember if an artwork ever caused errors..
do you have iso files in your library?

**Comment by myron0815** [comment]
since it hung both times on `I:\Movies\Frozen (2010)-poster.jpg` can you please upload that file?

**Comment by josenightbreed** [comment]
Happy Thanksgiving to everyone



> 
> 
> you log looks a bit confusing (it might be that you do several things at the same time?)
> the last entry is from getting mediainfo of artwork - but I cannot remember if an artwork ever caused errors..
> do you have iso files in your library?

"There is always a first time hehehehe"

No, i don't have any iso files just MP4, MKV and AVI files, the only other formats in the library is because of the trailers that the app downloaded.



> 
> 
> since it hung both times on `I:\Movies\Frozen (2010)-poster.jpg` can you please upload that file?

That fixed the issue, i removed the file (but windows was able to see it just fine) and scraped it again and by some obscure elven sorcery everything works as intended again XD.
The app saw the file as having 0MB but i opened it in different programs and it was just fine ..... shit happens XD

Thank you for your time

**Comment by mlaggner** [comment]
nice to hear.. So I will close this issue
