### ISSUE TITLE
Shows not updating if show dir has only symlinks

### ISSUE THREAD

**Issue by voidzero** [tinyMediaManager/tinyMediaManager#42]
__What TMM version are you using?__
2.8 on Linux

__release, pre-release, nightly, or directly from GitHub/branch?__
In-app updater (ie. release channel)

__What is the actual behaviour?__
I have a directory with all of my TV shows, and (because it is quite large) I also have a directory that contains symlinks to just the TV shows that are currently active. Before 2.8, this used to work fine: TMM would follow the links and update the shows. But now it no longer does this. With a newly initialized DB, the shows display as having 0 episodes.

__What is the expected behaviour?__
The shows should display as normal (so, TMM should follow the symlinks as if they are normal directories). As said, to me this seems to be a new bug, introduced with v2.8.

__Steps to reproduce:__
- 1. determine what your TV show directory is (`/mnt/shows`)
- 2. create a normal directory `/mnt/shows/tmm`
- 3. `cd /mnt/shows/tmm`
- 4. `ln -sr "../My Funky Show (2016)"`
- 5. Reload TMM's directory
- 6. See that no episodes are added.

__Additional__
Have you attached the Logfile from the day it happened?
No. It does not contain revelant information.

Your Operating system? (win/mac/linux? version?)
Linux x64, Java oracle-jdk-bin-1.8.

**Comment by mlaggner** [comment]
thanks for the hint. Never had such a use case and it looks like our implementation of Java NIO does not follow symlinks - will investigate
