### ISSUE TITLE
Update TMM

### ISSUE THREAD

**Issue by minikN** [tinyMediaManager/tinyMediaManager#420]
Unfortunately, no one responded [here](https://github.com/tinyMediaManager/tinyMediaManager/issues/417)

I'm not quite sure how to pull in the changes to use it. I cloned the repo and compiled it, but it's still not working.

Thanks.

**Comment by myron0815** [comment]
You can always use our precompiled nightly builds from here:
http://nightly.tinymediamanager.org/

And yes, clicking on Season level has no effect; TBD if feature or bug- will reopen...

**Comment by minikN** [comment]
You got me confused now. What do you mean by "has no effect"? It worked before, it just scraped the wrong language / didn't back up to the fall back language if the main language wasn't available. But it did scrape data.

**Comment by mlaggner** [comment]
well myron was false here: when firing the action we will search for all episodes beneath the selected node and this still works on the nightly..
please make sure that there are valid IDs on TV show level - otherwise tmm is not able to scrape episode meta data..

and a log is still helpful ;)

**Comment by minikN** [comment]
Yes you may.
