### ISSUE TITLE
Search and Scrape Media Confirmation Dialog Scales to Full Monitor Width

### ISSUE THREAD

**Issue by istoff** [tinyMediaManager/tinyMediaManager#421]
Version: 2.9.13
Build: 2018-07-23 18:42
OS: Windows 10 10.0
JDK: 1.8.0_191 x86 Oracle Corporation

__What is the actual behaviour?__
When scraping metadata/images using the force best match, the dialog boxes are nearly full monitor width.  On a 2560x1080 display it appears to be resized to about 10 pixels on either side of the monitor edge.
It doesn't matter if hte parent TMM window is scaled beforehand to about 800x600 beforehand.

__What is the expected behaviour?__
I wouls suggest that the scrape metadata window would be located centre aligned with the parent window, perhaps 1280x1024?

__Steps to reproduce:__
Open TMM 2.9.13.  
Click scraper (force best match option).  window opens full width.
Click scrape (scrape selected movies) window resizes ok

__Additional__
Have you attached the logfile from the day it happened?
No logs, I can do screenshots if required.

**Comment by mlaggner** [comment]
tmm remembers the window settings..
just delete the file data/tmm.prop in your tmm folder and everything should be resetted

**Comment by istoff** [comment]
Confirmed.  I'm an idiot.

Thank you.
