### ISSUE TITLE
Provide option to disable image downloading

### ISSUE THREAD

**Issue by movedoa** [tinyMediaManager/tinyMediaManager#424]
__What TMM version are you using?__
2.9.13

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
There is no way to disable image downloading. Afaik you can only choose between automatic and manual selection. 

__What is the expected behaviour?__
I don't want to download posters and artwork i only want to create the nfo files.

**Comment by myron0815** [comment]
does unticking the "artwork" checkbox globally in settings, or selective on scrape not work?

**Comment by movedoa** [comment]
I disabled all scapers for images, but that doesn't seem to work.
Manual does work but scraping a huge fresh library with this produces thousads of clicks on cancel.
Also the thumbnail generation also has no option it seems.

**Comment by movedoa** [comment]
Ok so this problem only seems to exist for tv-series. Movies have the option to disable thumbnails, artwork and so on. And when i disable all scrapers and untick all the additional artwork boxes no images are generated/downloaded.

The options for additional artwork seem to be missing in the tv-series settings.
I disabled all scapers for images, but that doesn't seem to work.
Manual does work but scraping a huge fresh library with this produces thousands of clicks on cancel. But i believe even with manual it would still create thumbs?

**Comment by mlaggner** [comment]
Already added options for this in v3..
Won't change that in v2 since this is too much work

**Comment by movedoa** [comment]
Great news, i close this issue then

**Comment by GiacomoLaw** [comment]
@mlaggner Hi - hate to dig up an old issue, but where can I find this option? Thanks!
