### ISSUE TITLE
Extra Images cannot be fetched from fanart.tv

### ISSUE THREAD

**Issue by robzombie91** [tinyMediaManager/tinyMediaManager#426]
__What TMM version are you using?__
2.9.14 (also doesnt work on 2.9.13)

__release, pre-release, nightly, or directly from GitHub/branch?__
pre-release (also affects release)

__What is the actual behaviour?__
Throws out internal server error when searching for extra images (clearlogo, banner, clearart, etc), most likely due to ssl

__What is the expected behaviour?__
Bring up images into the fields above

__Steps to reproduce:__
1. Right click media and click edit movie
2. Click extra artwork
3. click any field
4, Nothing shows up unless you paste in a link to an image

__Additional__
Have you attached the Logfile from the day it happened? - Yes
Your Operating system? (win/mac/linux? version?) - Windows

**Comment by robzombie91** [comment]
[tmm.log](https://github.com/tinyMediaManager/tinyMediaManager/files/2657535/tmm.log)

**Comment by mlaggner** [comment]
well, what should we do if fanart.tv servers throw a HTTP 500 error?

**Comment by robzombie91** [comment]
I'm guessing it was just on their end since it wasnt working yesterday and just this-morning it just started working mysteriously
