### ISSUE TITLE
Broken Image fetching

### ISSUE THREAD

**Issue by cj2tech** [tinyMediaManager/tinyMediaManager#428]
Version: 3.0-SNAPSHOT
Build: 2018-12-07 01:35
OS: Windows 10 10.0
JDK: 1.8.0_191 x86 Oracle Corporation

__What is the actual behaviour?__
01:22:59.142 WARN  org.tinymediamanager.core.tasks.MediaEntityImageFetcherTask - Error accessing url: 
01:22:59.142 WARN  org.tinymediamanager.core.tasks.MediaEntityImageFetcherTask - Error accessing url: 
01:22:59.142 WARN  org.tinymediamanager.core.tasks.MediaEntityImageFetcherTask - Error accessing url: 
01:23:38.248 WARN  org.tinymediamanager.core.tasks.MediaEntityImageFetcherTask - Error accessing url: 
01:23:38.250 WARN  org.tinymediamanager.core.tasks.MediaEntityImageFetcherTask - Error accessing url: 
01:23:38.265 WARN  org.tinymediamanager.core.tasks.MediaEntityImageFetcherTask - Error accessing url: 
01:23:48.250 WARN  org.tinymediamanager.core.tasks.MediaEntityImageFetcherTask - Error accessing url: 

__What is the expected behaviour?__
To fetch image files

__Steps to reproduce:__
?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2660294/tmm_logs.zip)

__Additional__
Have you attached the logfile from the day it happened?yes

**Comment by mlaggner** [comment]
fanart.tv servers have some serious problems at the moment (see #426)

nothing we can do..

**Comment by cj2tech** [comment]
https://fanart.tv/2016/10/big-increase-traffic-way/

**Comment by mlaggner** [comment]
Thanks! will announce this in the forums
