### ISSUE TITLE
Extra Thumbnail

### ISSUE THREAD

**Issue by OldMan100** [tinyMediaManager/tinyMediaManager#429]
Version: 3.0-SNAPSHOT
Build: 2018-12-10 01:36
OS: Windows 10 10.0
JDK: 1.8.0_192 x86 Oracle Corporation

__What is the actual behaviour?__

A copy of the thumbnail for each episode is created during the renaming and the original thumbnail is still with the rest of the files. 
 Here is what happen when you rename a episode:

This is what the file looks like before scraping.

The file is named Doctor Who S11E10 for the scraping portion.
![image](https://user-images.githubusercontent.com/35414666/49773184-e0bb2f80-fca4-11e8-8de2-29a7c3382b3f.png)
This is what a file looks like after scraping.

Doctor Who S11E10 now has the nfo file and both jpgs. 
![image](https://user-images.githubusercontent.com/35414666/49773437-f67d2480-fca5-11e8-816c-c7d48dd2b048.png)
This is what a file looks like after renaming.

![image](https://user-images.githubusercontent.com/35414666/49773510-4825af00-fca6-11e8-8b6c-dca014ea23f4.png)
The app renamed the files for S11E10, just like episode S11E09.  But, the original thumbnail for S11E10 is also there.  See above pic. This is only happening on thumbnails, landscapes are good.

__What is the expected behaviour?__

Rename the original thumbnail created or create a copy of the original thumbnail renamed, which seems to be what the app is doing, and delete the original.

Go from this,
![image](https://user-images.githubusercontent.com/35414666/49774162-a94e8200-fca8-11e8-9de0-a04804c6943e.png)
To this, without the extra thumbnail.
![image](https://user-images.githubusercontent.com/35414666/49774212-dd29a780-fca8-11e8-91a4-4631edb336aa.png)

P.S.
Just before I was going to sent this, I has an idea.  I uncheck the landscape from episode thumb in Artwork file name and left only thumbnail checked. Reset the file and TMM to before the file was scraped.
Re-scraped the file, only getting the thumbnail, then renamed the episode. Now everything came out, the way it should, no extra thumbnail.  The problem seems to occur when both thumbnail and the landscape are set in the Artwork file name for Episode thumb.
__Steps to reproduce:__
Set both thumbnail and landscape under Artwork file names under Settings.
Rename a file you just scraped.

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2665734/tmm_logs.zip)

**Comment by mlaggner** [comment]
we've migrated v3 to GitLab (https://gitlab.com/tinyMediaManager/tinyMediaManager) along with all issues. The issues for v2 at GitHub will be closed - we will respond to the corresponding issue in GitLab in the future

br
Manuel
