### ISSUE TITLE
Crash when attempting to rename a file with a movie title containing a colon

### ISSUE THREAD

**Issue by GaloyerF** [tinyMediaManager/tinyMediaManager#43]
Version: 2.8-SNAPSHOT - PRE-RELEASE
Build: 2016-06-13 16:28
OS: Windows 10 10.0
JDK: 1.8.0_91 amd64 Oracle Corporation

__What is the actual behaviour?__

The application raise an error and does not update the movie when the movie scrapped contain a colon.

__What is the expected behaviour?__

The movie should be updated and proceed to next movie to scrap.

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

**Comment by myron0815** [comment]
thx

**Comment by GaloyerF** [comment]
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/314596/tmm_logs.zip)

Sorry i forgot this...
