### ISSUE TITLE
Issue to write NFO-files

### ISSUE THREAD

**Issue by mr2web** [tinyMediaManager/tinyMediaManager#432]
Version: 2.9.14
Build: 2018-12-08 13:27
OS: Linux 4.4.0-140-generic
JDK: 1.8.0_191 amd64 Oracle Corporation

__What is the actual behaviour?__
Unable to write NFO-files to NFS-share. Dono it it would write to local though. This has not been an issue until I recently updated TMM to current version.
The issue is after scraping new movies. Have not tried to update an existing NFO-file.

__What is the expected behaviour?__
NFO-file to be created on NFS-share. This has not been an issue until recently after updating TMM.

__Steps to reproduce:__
Scrape a new movie that does not have a NFO-file already. 

__Additional__
Have you attached the logfile from the day it happened? Yes
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2707808/tmm_logs.zip)

**Comment by mr2web** [comment]
It turns out that relaunching the TMM updater got it to work again. :-D  Why, I have no idea.

**Comment by mlaggner** [comment]
Java itself does only use the file system via native system calls (kernel)...
there must be a problem with your NFS share (mount options, permissions, ...?)
