### ISSUE TITLE
datasource as input for cmd 

### ISSUE THREAD

**Issue by k6Q28k5w5eWuRuuzTg9j7GrKCbjt7** [tinyMediaManager/tinyMediaManager#433]
Hi, 

Is there any way to pass along datasource for the CMD without using a predefined path in settings? On the form: "tmmCMD --path xyz -update -rename" 

Usecase / scenario: want to process + rename on host A, before it syncs to host B. If a preset of directory is set, race conditions arise. 

Why do the work on Host a?: -> Avoid API ban / minimize connections. Doing the work on host A ensures that minimal connections / work is needed towards host B (lib is 200 tb).

**Comment by mlaggner** [comment]
no sorry, the datasource is tied/queried many times inside tmm and such a feature would break many other features inside tmm.. (the path is also stored in the internal database - so you would get problems with the DB entries if you switch the path)

my advice is: mount the lib in the same way on both machines and it will work
