### ISSUE TITLE
Movies "Replace colons with" Not Saving

### ISSUE THREAD

**Issue by EarthBoundX5** [tinyMediaManager/tinyMediaManager#434]
Version: 2.9.14
Build: 2018-12-08 13:27
OS: Windows Server 2008 R2 6.1
JDK: 1.8.0_191 amd64 Oracle Corporation

__What is the actual behaviour?__
"Replace colons with" option, under Movies -> Renamer, does not save.

__What is the expected behaviour?__
This setting should save with each close of the program.  Really, it should also default to -, as that's the previous default behavior before the feature was implemented.

__Steps to reproduce:__
Open TMM
Change from Space to Dash
Close TMM
Open TMM
Find that setting is back to Space

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2716540/tmm_logs.zip)

**Comment by subagon** [comment]
Having the save issue

**Comment by EarthBoundX5** [comment]
Per this forum post: https://forum.kodi.tv/showthread.php?tid=338182&pid=2803492#pid2803492

I believe mlaggner is addressing the issue?

**Comment by mlaggner** [comment]
has been fixed with https://github.com/tinyMediaManager/tinyMediaManager/commit/fcc41cb9c9a941df9a5939500ba16d7828dfd213

**Comment by Clark-Wayne** [comment]
Thanks for resolving this. Just a note though, this bug also applies to tvsettings as well.

**Comment by mlaggner** [comment]
thanks - has been addressed with  c4ef78f
