### ISSUE TITLE
Invalid argument on writing artwork

### ISSUE THREAD

**Issue by mdiesing** [tinyMediaManager/tinyMediaManager#435]
__What TMM version are you using?__
2.9.15-SNAPSHOT and 2.9.14

__release, pre-release, nightly, or directly from GitHub/branch?__
Github/master, GitHub/devel, release

__What is the actual behaviour?__
When I try to change the artwork (poster, fanart) there is an error "Invalid Argument" and the artwork is not written.

__What is the expected behaviour?__
There should be a file in the directory of the movie.

__Steps to reproduce:__
- edit movie
- click on poster
- select poster
- ok
- ok

__Additional__
I think that the mounted directory is the problem, but I'm sure, it worked some time before. Renaming the directory on the smb share works. The movie.nfo file is also written on the share.

OS: Ubuntu
Java: 1.8.0_191-b12

Error message: Downloading artwork failed: /run/user/1000/gvfs/smb-share:server=192.168.1.105,share=myvideo/mkv/Films/Angel of the Night (1998)/poster.jpg.1546176828159.part (Invalid argument)

My own stack trace:
`
14:23:37.626 WARN  org.tinymediamanager.core.MediaEntityImageFetcherTask - /run/user/1000/gvfs/smb-share:server=192.168.1.105,share=myvideo/mkv/Films/Angel of the Night (1998)/poster.jpg.1546176217564.part (Invalid argument)
java.io.FileNotFoundException: /run/user/1000/gvfs/smb-share:server=192.168.1.105,share=myvideo/mkv/Films/Angel of the Night (1998)/poster.jpg.1546176217564.part (Invalid argument)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.tinymediamanager.core.MediaEntityImageFetcherTask.run(MediaEntityImageFetcherTask.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by mlaggner** [comment]
Please do not use gvfs since that only brings problems..
I am sure it will work if you mount the share via /etc/fstab

**Comment by mlaggner** [comment]
The problem are the gvfs arguments in the path. See https://stackoverflow.com/a/23961074

**Comment by mdiesing** [comment]
> Please do not use gvfs since that only brings problems..
> I am sure it will work if you mount the share via /etc/fstab

Thank you, that works. But it's odd that some functions (like creating the nfo file) have no problem with the colon.

**Comment by mlaggner** [comment]
maybe these functions use any other internal ways to write a file..
but gvfs is really bad for massive access from/to a cifs share (tested it on my NAS and I got a really bad network performance). After I've switched to /etc/fstab everything works like a charm
