### ISSUE TITLE
Don't add duplicate years when renaming shows

### ISSUE THREAD

**Issue by MindTooth** [tinyMediaManager/tinyMediaManager#436]
__What TMM version are you using?__
2.9.14 - Homebrew - (Jave 11 - after I fixed the script)

__What is the actual behaviour?__
Renaming a show with a year in the shows name, the year is duplicated.

__What is the expected behaviour?__
If year it the same, or differ minimally, one is omitted somehow.  Thoughts?

__Steps to reproduce:__
- Find **Tokyo Ghoul:re (2018)** (AniDB)
- Rename folder
- Get `Tokyo GhoulRe (2018) (2018)` as the filename

__Additional__
Your Operating system? (win/mac/linux? version?) - **macOS**

**Comment by mlaggner** [comment]
if the year is part of the title, it will be hard to detect that and do not add the year via tmm..
are that much tv shows affected?

**Comment by MindTooth** [comment]
Don't believe there is a bunch.  Guess that it's more of an issue with AniDB that splits the seasons into separate shows.
