### ISSUE TITLE
[Feature Request] TV Shows Trailers

### ISSUE THREAD

**Issue by benkap** [tinyMediaManager/tinyMediaManager#439]
Today there are trailers for TV Shows while it's very difficult to find a tool to scrap and add to NFOs trailers URL (even from youtube) this would have been a great addition to this awesome tool.

There are many scrappers that support this, Is this in the road-map for future releases?

Thank you

**Comment by mlaggner** [comment]
do you only want to get the trailer URLs or combine that with trailer donwload?
first would be rather easy (_IF_ the scraper sources can provide trailer urls - did not check that yet).
second one would be a pain in the ass and not solvable at the moment

**Comment by benkap** [comment]
While the download is cool feature i don't see much use of it while getting the URL and adding it to the NFO will have great benefit. If you look around - there is still not many tools (if any at all) that support this.

One issue that i do think about the different implantation of TV shows then Movies is that for TV show there can be a "global" trailer for the entire show and a seasonal trailer.
1. The global trailer NFO - I assume it should be located in the main NFO file in the 'TV Show Directory' main directory
2. The seasonal trailer NFO - I assume should go to the  'TV Show Directory\Season X\season.nfo).

I don't know how hard this is to implement but even adding only 1. (the global trailer to the main NFO) is a great feature to have and hard to find alternatives today.

**Comment by Stele77** [comment]
Hi, I just started using TMM for my libary. I am still a newbie, and TMM makes things so much easier and accessible. 
Having the option to download trailers is already on of the main points why i prefer TMM over other tools like MediaElch, but why not for TV Shows? It is just as useful IMHO as movie trailers. Grabbing the trailers from YouTube (Where most trailers would be available) would be great, but automating the integration into the NFO etc. is even more crucial, as to do this manually is pretty much a closed book for most newbies like me (and i guess even more advanced users).
Thanks for any consideration!
