### ISSUE TITLE
Crash when attempting to rename a file with a movie title containing a colon

### ISSUE THREAD

**Issue by GaloyerF** [tinyMediaManager/tinyMediaManager#44]
Version: 2.8-SNAPSHOT - PRE-RELEASE
Build: 2016-06-13 16:28
OS: Windows 10 10.0
JDK: 1.8.0_91 amd64 Oracle Corporation

What is the actual behaviour?

The application raise an error and does not update the movie when the movie scrapped contain a colon.

What is the expected behaviour?

The movie should be updated and proceed to next movie to scrap.

Steps to reproduce:

Additional
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/314627/tmm_logs.zip)

**Comment by myron0815** [comment]
Are you sure you have the latest pre-release?
i fixed it with issue #43 2 hours ago...

(Version should be already 2.8.1-SNAPSHOT)

**Comment by GaloyerF** [comment]
Cool then, i'll download it now...
I'll open a second case for shows renaming ... TMM does not recognize serie and episode in "Smallville - S02E01 - Dans l'œil du cyclone (22).avi"
when it work perfectly **until** "Smallville - S01E21 - Avis de tempête (21).avi"
previous episode are parsed and the remaining undreds of episodes fails... 
But I don't have crash reports, it just stops while updating after 21 episodes...

**Comment by myron0815** [comment]
don't you get a "new version" popup when starting?
anyway... we fixed some annoying things there... and hopefully your second issue too :)
Meanwhile i close this, since this topic is fixed...
