### ISSUE TITLE
tvshow.nfo file managled tags: episodeguide, watched, and playcount

### ISSUE THREAD

**Issue by mgonzales71** [tinyMediaManager/tinyMediaManager#441]
__What TMM version are you using?__

Snapshot 3 build 09-Jan-2019 (latest as of opening this issue)

__release, pre-release, nightly, or directly from GitHub/branch?__

snapshot

__What is the actual behaviour?__

- read data from .nfo files for a tvshow
- immediately re-write .nfo file for same tvshow

```
  <episodeguide>
    <url post="yes" cache="auth.json">https://api.thetvdb.com/login?{&quot;apikey&quot;:&quot;439DFEBA9D3059C6&quot;,&quot;id&quot;:328552}|Content-Type=application/json</url>
  </episodeguide>

```

changes to 

```
  <episodeguide>
    <url cache="auth.json" post="yes">https://api.thetvdb.com/login?{&amp;quot;apikey&amp;quot;:&amp;quot;439DFEBA9D3059C6&amp;quot;,&amp;quot;id&amp;quot;:328552}|Content-Type=application/json</url>
  </episodeguide>
```

and

```
  <watched>true</watched>
  <playcount>1</playcount>
```

changes to

```
  <watched>false</watched>
  <playcount/>
```

__What is the expected behaviour?__

not to re-write the episodeguide to something that isn't compatible and to drop/change the watched / playcount tags.

### The re-written item doen't work if you re-import into Kodi (I am using Leia nightly (09-Jan-2019) for Windows 10 x64.

also not sure why the watched Boolean gets set to **false** and the playcount is dropped.

__Steps to reproduce:__
- first import tv show using Kodi scrapper (TVDB was used), export DB
- second read exported nfo file into TMM - write nfo file out
- see above issues

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

Win 10 64bit

Sorry for opening issue on here, I don't yet have an account on GitLab.

Hopefully you see this.

Thanks!

**Comment by mgonzales71** [comment]
note the subtle changes in episode guide tag - they are hard to see at first beyond the post= and cache= being swapped.  the changes are significant in that if they get placed in the Kodi DB Kodi will give the following errors in the log when trying to add new episodes because the episiodeguide tag is malformed:

```
T:11904  NOTICE: VideoInfoScanner: Starting scan ..
T:11904   ERROR: CCurlFile::Open failed with code 401 for https://api.thetvdb.com/login:
                               {"Error":"Not authorized"}
T:11904   ERROR: ADDON::CScraper::Run: Unable to parse web site
T:11904 WARNING: No information found for item 'N:\TV Shows\Cops (1989)\', it won't be added to the library.
```

**Comment by mgonzales71** [comment]
additional note: I think the Kodi devs may have made changes (or fixed a bug) from previous nightly builds with respect the the new URL scheme for episodeguide tags.  So that may be the root of this issue possibly?  I just keep thinking even though it does not work it does look familiar.    Thanks again for you hard work on this program and your assistance!

**Comment by myron0815** [comment]
fixed the encoding for next build.

The ordering of attributes does not matter in XML (and neither should in Kodi).
Not being able to login (401) is a more reasonable error...

**Comment by mlaggner** [comment]
according to the watched state:
we do write the watched state after the following logic:

**a TV show is only watched if ALL episodes inside this show have been watched!**

if a playcount is in the previous NFO, we take that (only if the logic above results in TRUE), otherwise we write playcount = 1

please review your data!

**Comment by mgonzales71** [comment]
ok - I actually was more focused on what was changing in the nfo file data unexpectedly vs the logic of the change - but maybe dropping any data is to be avoided for some future addition to what Kodi supports vs what an app supports?  will test - thanks!

**Comment by mgonzales71** [comment]
and yes if a show is all watched and caught up that maybe does make sense - not aure if it was saved via Kodi video db backup or another app - I try to revisit other apps (MediaElch, etc from time to time) but don't recall anything recent for that in particular
