### ISSUE TITLE
fanart.jpg and poster.jpg always contain movie name

### ISSUE THREAD

**Issue by nicholashead** [tinyMediaManager/tinyMediaManager#442]
__What TMM version are you using?__
2.9.14
__release, pre-release, nightly, or directly from GitHub/branch?__
release
__What is the actual behaviour?__
When saving fanart and poster art, the filenames always seem to contain the movie name - such as `My Movie - 2018-fanart.jpg` and `My Movie - 2018-poster.jpg` - even though the TMM settings (Movies -> Images) has poster file name set to just `poster.ext` and fanart file naming set to `fanart.ext`
__What is the expected behaviour?__
That the fanart and poster would be named `fanart.jpg` and `poster.jpg`

__Steps to reproduce:__
- Change your poster/fanart rename settings in TMM.
- Right click on a movie and choose "Rename/cleanup selected movies"
- Filename is not correct.

__Additional__
Windows 10.

**Comment by myron0815** [comment]
depends.
Are more than one movie(file) in this directory?
Please upload logifle (after a fresh "update datasource") to some pastebin site...

**Comment by nicholashead** [comment]
@myron0815 	yes, actually, that wound up to be it. And I think TMM doesn't handle that scenario according to #134 

I wound up just separating my qualities in prefix folders, like `720p/Movie Name (year)/Movie Name - Year - 720p.mkv` and that seems to work better, and make Plex happy. 

Thanks, closing.

**Comment by myron0815** [comment]
Kinda.
Problem is, that Kodi does not support that scenario.
(and barely any other MediaCentre)
We have to keep a minimum convergence which suits them all, and this is somewhat completely special in every aspect. (although it reads quite simple)

"one movie (variant) per folder" is an easy enough workaround... and since most people collect only one variant per movie, this seems to have less priority... sorry

**Comment by nicholashead** [comment]
@myron0815 	No worries, totally makes sense. It is logical for something like Plex, which would need to transcode sometimes - so you'd want it to just pull from 1080p instead of 4k, for example. But for Kodi you'd just play back whatever's best. 👍

**Comment by myron0815** [comment]
ok, with transcoding in mind, it makes perfectly sense.
Never understood, why someone would keep xx variants of same movie :D
(That, or i'm not a movie enthusiast collector at all :p)
