### ISSUE TITLE
Texts on settings are not showing properly

### ISSUE THREAD

**Issue by Adyel** [tinyMediaManager/tinyMediaManager#443]
__What TMM version are you using?__
Version 2.9.14

__release, pre-release, nightly, or directly from GitHub/branch?__
From the official website. Release probably.

__What is the actual behavior?__
Texts are not showing fully in the setting.
![screenshot_2019-01-11_12-27-23](https://user-images.githubusercontent.com/4653623/51017101-f3bf6900-159c-11e9-8005-bbaca1c65167.png)

__What is the expected behavior?__
The text should show properly.

__Steps to reproduce:__
- Click Settings
- Goto Movies Tab (General)

__Additional__
No log needed.
Operating System: Manjaro Linux (Arch)

**Comment by mlaggner** [comment]
has been fixed for the next release
