### ISSUE TITLE
macOS: Homebrew installation did not open with Java 11

### ISSUE THREAD

**Issue by spl** [tinyMediaManager/tinyMediaManager#445]
__What TMM version are you using?__

2.9.14 (096b083)

__release, pre-release, nightly, or directly from GitHub/branch?__

Homebrew [formula](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/tinymediamanager.rb)

__What is the actual behaviour?__

`tinyMediaManager.app` says I do not have Java installed, even though I installed it with Homebrew:

```sh
$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
```

See https://github.com/Homebrew/homebrew-cask/issues/57762 for details.

__What is the expected behaviour?__

`tinyMediaManager.app` opens as expected. The [version 2.9.14 release notes](http://www.tinymediamanager.org/blog/version-2-9-14/) claim “Java 9 / 10 / 11 compatibility,” and I have Java 11 installed.

__Steps to reproduce:__
- `brew cask install java` (Java not already installed)
- `brew cask install tinymediamanager`
- `open -a tinyMediaManager`

__Additional__

OS: macOS 10.14.2 (Mojave)

If I install Java 8 via Homebrew, then it works. After the above, I did:

- `brew cask install java8`
- `open -a tinyMediaManager`

And tinyMediaManager opened successfully.

**Comment by myron0815** [comment]
do you have some logfile?
like launcher.log (and tmm.log if any)

are you able to start the tinyMediaManagerOSX.sh manually?
(sorry, no mac user :p)

**Comment by spl** [comment]
I'm looking now. This is the only thing from `system.log`:

```
Jan 22 08:56:19 <host> com.apple.xpc.launchd[1] (org.tinyMediaManager.tinymediamanager.3208[98207]): Service exited with abnormal code: 127
```

**Comment by spl** [comment]
```sh
$ /usr/libexec/java_home -v 1.8 -F
Unable to find any JVMs matching version "1.8".
$ echo $?
2
```

**Comment by myron0815** [comment]
yes, this has been found recently, and is already changed:
https://github.com/tinyMediaManager/tinyMediaManager/commit/b4c13a9303b85ea60fbde26dd2ac07ff14f4db6f#diff-89b548e9112d0dcb4859d2042698b62a

we were explicitely searching for Java 8, and not 8+ ;)
will be in next version... or already in prerelease.
Thanx for reporting.

**Comment by spl** [comment]
Great! Thanks!
