### ISSUE TITLE
Store movieset artwork in a separate folder not working

### ISSUE THREAD

**Issue by rvernica** [tinyMediaManager/tinyMediaManager#447]
__What TMM version are you using?__

Version: `2.9.14`
Build date: `2018-12-08 13:27`

__release, pre-release, nightly, or directly from GitHub/branch?__

Release

__What is the actual behaviour?__

I checked _Store movieset artwork in a separate folder_ and provided a _Folder name_ using _Select folder_. I see that the artwork is still downloaded in the movie folder.

__What is the expected behaviour?__

I expect the movie artwork to be downloaded in the specified folder.

__Steps to reproduce:__
1. Run tutorial to specify movie path
1. Right-click on a movie and select _Search and scrape selected movie(s)_, select movie
1. Artwork is downloaded and displayed
1. On the disk the artwork files are in the movie folder (`banner.jpg`, `clearart.png`, `logo.jpg`, `poster.jpg`...)
1. Go to _tinyMediaManager_ menu, select _Settings_
1. Select _Movies_ and then the _Images_ tab
1. In the _Enable extra artwork_ section, select _Store movieset artwork in a separate folder_ and provided a _Folder name_ using _Select folder_
1. Restart tinyMediaManager
1. Pick another movie and run steps (2)-(4) the artwork files are still downloaded in the movie folder and not the separate folder.

__Additional__

I tried restarting tinyMediaManager after adjusting the settings, but it did not help. If I go back in settings, I can see the settings I set are as expected.

Fedora Linux `29`

**Comment by mlaggner** [comment]
we only store movie set artwork in the artwork folder, NOT the movie artwork!

**Comment by rvernica** [comment]
Got it, I confused _movie_ with _movieset_. Sorry about that.
