### ISSUE TITLE
Typo in DataTablesHTML.jar template

### ISSUE THREAD

**Issue by rvernica** [tinyMediaManager/tinyMediaManager#448]
__What TMM version are you using?__

Version: `2.9.14`
Build date: `2018-12-08 13:27`

The page headers should be:

* _Titel_ -> _Title_
* _Original Titel_ -> _Original Title_
* Also in the _Search ..._ input field titles

![template](https://user-images.githubusercontent.com/241185/51795204-4c455780-2194-11e9-9633-9f9056d30195.png)

**Comment by mlaggner** [comment]
thanks - will be changed in v3
