### ISSUE TITLE
Search with 'Title + (Year)'.

### ISSUE THREAD

**Issue by luizoti** [tinyMediaManager/tinyMediaManager#449]
__What TMM version are you using? __
2.9.15

__release, pre-release, nightly, or directly from GitHub / branch? __

__What is the actual behavior? __
Does not use the year to perform searches.

__What is the expected behavior? __
Who can use the year to do the research.

__Steps to play: __
- 1. When searching, via CMD or manually.
- 2. Placing the year the search identifies the correct content in the manual search bar, but Tiny itself can not filter the year and use it in the search.

Example: Dororo Anime of 2019 and 1969, both are found, but placing the year the search correctly returns only the correct version.
- ...
I looked for some configuration to force the use of the year, but I did not find it.

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win / mac / linux? version?)
Windows

**Comment by luizoti** [comment]
After some tests I found out what Tiny does searches using the year only if the year is inside the tvshow.nfo file, using flexget I created a script in Powershell that generates an .nfo and captures the anime name direct from TVDB, and with this Tiny can find the information of the anime with ease, it is a big turn, but it works, if possible I would ask you to add the search by using the year, I think it would be useful.

**Comment by myron0815** [comment]
Well, on update, we try to parse the year out of filename.
This more or less works fine.
If we have it, we would use it in the scraper...

How are your files named, btw?
Anime mostly has weird filenames, where this might not work so well...
