### ISSUE TITLE
Rename/Cleanup of movies does not move/rename .idx files 

### ISSUE THREAD

**Issue by akuntsch** [tinyMediaManager/tinyMediaManager#45]
__What TMM version are you using?__
2.8.1

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
Renaming / cleanup of movies with a subdirectory with external subtitles (.sub and .idx files) does not move/rename the .idx files to the movie directory, but moves the .sub files and renames them.

__What is the expected behaviour?__
Both .idx and .sub files are moved/renamed.

__Steps to reproduce:__
- Add a movie with external subtitles (.sub and .idx) in a subdirectory
- Scrape and rename/cleanup

__Additional__
Your Operating system? Windows 10

**Comment by mlaggner** [comment]
did the subtitles (sub/idx in the subfolder) got detected by tmm? (you can see this in the media files tab)
do you have any log files to provide?

**Comment by mlaggner** [comment]
that fix will be in the next version

**Comment by CyberC123** [comment]
The same issue with series.
