### ISSUE TITLE
BBC iPlayer files confuse TMM

### ISSUE THREAD

**Issue by ArgDave** [tinyMediaManager/tinyMediaManager#452]
__What TMM version are you using?__
Version: 2.9.14 build date: 2018-12-08 13:27

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
![bbc iplayer tmm](https://user-images.githubusercontent.com/25934691/52706938-72ce0580-2f7e-11e9-8ec1-3b97eea66b09.JPG)
I am based in the UK and save files from BBC iPlayer but their names confuse TMM and need renaming before they can be searched by TMM. It would be great if they could just read straight in, especially as I often forget and then it takes a fair bit of untangling!

I have attached an image of the three latest files that created confusion.

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
Windows 7

**Comment by myron0815** [comment]
What exactly does TMM confuse?
Can you provide a logfile?
I'm not gonna type such names....

I (kinda) tried first name, and it was correctly identified as Season1 Episode 2

**Comment by Xstar97** [comment]
i use this method....
Inside Europe Ten Years of Turmoil (folder)
S1(folder)
Inside Europe Ten Years of Turmoil - S01E001 - Going for Broke.xxx
Or
Inside_Europe_Ten_Years_of_Turmoil_-_S01E001_-_Going_for_Broke.xxx

idk what that garble is at the end of yours but its throwing it off....
