### ISSUE TITLE
Req: Possible to change background color of "New" 

### ISSUE THREAD

**Issue by SanityClause** [tinyMediaManager/tinyMediaManager#453]
__What TMM version are you using?__
2.9.16

__release, pre-release, nightly, or directly from GitHub/branch?__
regular release

__What is the actual behaviour?__
When updating db and it finds new material, the "New" with its dark gray background is almost impossible for my old eyes to see. Can you tell me how to make it something a little different (green, red, blue)

__What is the expected behaviour?__ 
Works as intended

__Steps to reproduce:__
- first: add new material to tv or movies
- second: update db
third : find "new" with 70 yr old eyes
- ...

__Additional__
Have you attached the Logfile from the day it happened? no
Your Operating system? (win/mac/linux? version?) linux

**Comment by myron0815** [comment]
Hi,
sorry, not (yet) and not easily possible.
But you can sort your list with the date, when it was added, so all the new items are on top...

**Comment by mlaggner** [comment]
You can also put a filter on new items..

**Comment by SanityClause** [comment]
Thanks for the responses. Ill try both and see which one works best

Don't get old... you wont like it  :-(

**Comment by mlaggner** [comment]
I'll make that indicator a bit more concise in v3..
won't touch v2 any more for nice to have's (need all the time I can get for finishing v3)
