### ISSUE TITLE
Req: Regex to identify tv shows organised by iTunes

### ISSUE THREAD

**Issue by davecarrr** [tinyMediaManager/tinyMediaManager#454]
__What TMM version are you using?__
2.9.16

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
TV shows stored in the format "\Season 1\01 Episode 1.m4v are being imported inconsistently, it would appear the scraper is getting confused by the numbers in the rest of the filename.

__What is the expected behaviour?__
The regex scraper could be updated to the following 
<For season folders> - Season[\._ ]([0-9]+)[\\/]([0-9]+)([^\\/]*)$
<For specials or no season folders> - (0)([0-9]+)([^\\/]*)$

__Steps to reproduce:__
The format iTunes uses is "Season <Season Number>\<2 digit Episode Number> <Episode Title>

__Additional__
No Log files, but any numbers in the episode name seem to confuse it so particularly a problem for "01 Episode 1.m4v", not a problem for "01 Pilot.m4v"

**Comment by myron0815** [comment]
well, it's not that easy :)
But you're right, within TMMv2, i'll get duplicate Episode 1
This is working correctly in v3...

**Comment by davecarrr** [comment]
i thought i would check the prerelease of v3 and still having problems, an example in point is

Broadchurch\Season 1\01 Episode 1.m4v - not recognised
Broadchurch\Season 1\02 Episode 2.m4v - Recognised
Broadchurch\Season 1\03 Episode 3.m4v - not recognised
Broadchurch\Season 1\04 Episode 4.m4v - not recognised

really odd behaviour as i use the regex above in advancedsettings.xml and everything is fine, but tiny only seems to recognise odd files.

**Comment by myron0815** [comment]
are we talking about TMM?
Advancedsettings.xml is something used by Kodi....

Nevertheless, once i import your structure with v3, it gets correctly identiefied as S1, E1-4
![grafik](https://user-images.githubusercontent.com/1846737/53286384-f2718680-376d-11e9-9be7-91e998666369.png)

Be sure to scrape, create NFO files, and rename them - else Kodi won't import it!

**Comment by davecarrr** [comment]
Hi , sorry i only mentioned Kodi to demonstrate that the regex worked, i'm definitely talking about TMM. strange that you are getting such a different output from me, I will try the latest nightly and see if it has the same issue.

D
