### ISSUE TITLE
Feature Request: No Language Code Subtitles

### ISSUE THREAD

**Issue by Fr33dan** [tinyMediaManager/tinyMediaManager#457]
My media server seems to have issues with detecting subtitle files if they have a language code. There are several option for how to format the language code. Could an option be added to that list for no code to be added? So instead of [filename].[language].srt I could have files that are just [filename].srt.

**Comment by myron0815** [comment]
How does your unnamed media server deal with 2 or more subtitles?

**Comment by Fr33dan** [comment]
No idea. The program in questions is serviio but I didn't think it was relevant. According to its documentation it should support the codes but they are not detected. That said I only speak one language and only need subtitles in that language in my collection. With that in mind I would prefer them to have the exact same file name as the media regardless of my media server.

**Comment by myron0815** [comment]
serviio perfectly supports the filenames with language codes. (according to their doc)
https://serviio.org/index.php?option=com_content&view=article&id=33
They seem to understand 2 or 3 char language codes - you did try that?

So... if it does not work, what about creating a bug for... them...?

Although we could discuss the naming, when having EXACT ONE subtitle...

**Comment by Fr33dan** [comment]
I am aware they are supposed to support it but their subtitle support has always been a bit buggy. I was planning on playing with the filenames manually and seeing what if anything I could get to work with codes. I also can't rule out the possibility that it's something strange with my playback device, like it only likes subtitles that don't have an specified language or something of the like. I don't know maybe that doesn't make sense but I've had some weird behavior with files I have that have embedded subtitles. They're great over there and I'm sure they'd help me get it working but I've got to sort some stuff out to get the full details before I go to them. 

So I considered all that and decided I would just really prefer them to have the same name as the media files. Not just because it works around this issue but because I think it looks neater.

**Comment by jesusrivas89** [comment]
Hi. I'll join you at the request. I would also like the subtitles to have the same name as the video file, and several friends I taught to use the program complain about that function, there should be an option that says that the rename of files is exactly the same as the video file, without adding any kind of language code.

**Comment by mlaggner** [comment]
copied this issue over to gitlab:
https://gitlab.com/tinyMediaManager/tinyMediaManager/issues/621
