### ISSUE TITLE
Search and Scrape TV Shows Buttons Missing

### ISSUE THREAD

**Issue by heyfrank** [tinyMediaManager/tinyMediaManager#458]
Version: 2.9.16
Build: 2019-02-18 20:35
OS: Windows 10 10.0
JDK: 1.8.0_181 x86 Oracle Corporation

__What is the actual behaviour?__

If you right click on a tv show and click "Search & scrape selected TV Show" the prompt comes up to select the show, but the buttons to continue are not there. The only way around it is to force shows to scrape.

__What is the expected behaviour?__

Buttons to be able to select the tv show to continue to scrape.

__Steps to reproduce:__

right click on a tv show and click "Search & scrape selected TV Show" the prompt comes up to select the show, but the buttons to continue are not there.

__Additional__
Have you attached the logfile from the day it happened?

Yes
![tmm-impjoker](https://user-images.githubusercontent.com/1498086/53701302-4230fd00-3dc1-11e9-9c8d-bb622a394483.PNG)
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2923645/tmm_logs.zip)

**Comment by mlaggner** [comment]
resize the dialog - tmm tries to remember your dialog settings and if you resized it once under the minimum size, tmm will remember it.
otherwise delete the file tmm_ui.prop in your tmm/data folder
