### ISSUE TITLE
Edit path to files - Movies

### ISSUE THREAD

**Issue by BladeCZ** [tinyMediaManager/tinyMediaManager#460]
__What TMM version are you using?__ 2.9.16 (Lastes)

__release, pre-release, nightly, or directly from GitHub/branch?__ Auto-update

__What is the actual behaviour?__ I do not have the ability to modify the file path without having to delete the database even though the structure of the file has remained preserved.

__What is the expected behaviour?__Allow file paths to be edited.
In "\data\config.xml" I found the setup file, but after editing file paths, and subsequent scanning, all the movies in the database were duplicated.

__Additional__
Your Operating system? Windows 10

Ps. sorry for my bad english. i use google translator :D

**Comment by mlaggner** [comment]
tmm is designed to manage your video/artwork files - so there should be no need to modify the path.
We store internally all paths to all objects which prevents us from offering a simple "edit path" mechanism..

so either do:

a) let tmm move all files (renamer)

or

b) move the files by your own and let tmm re-scan the structure (update data sources)
