### ISSUE TITLE
File rename/cleanups are getting cached somewhere!

### ISSUE THREAD

**Issue by najinsky** [tinyMediaManager/tinyMediaManager#461]
__What TMM version are you using?__

tmm.version      : 2.9.16
os.name          : Mac OS X
os.version       : 10.14.3
os.arch          : x86_64
java.version     : 1.8.0_131
default encoding : UTF-8 | UTF8 | UTF-8
set encoding to  : UTF-8 | UTF8 | UTF-8
System language  : en_GB
GUI language     : en_US
Scraper language : English
TV Scraper lang  : English

__release, pre-release, nightly, or directly from GitHub/branch?__

Release version downloaded from https://www.tinymediamanager.org/download/
Happened in previous version and still happens after software update. 

__What is the actual behaviour?__

Intermittent - not always repeatable. TV Show Files are on external drive connected by USB 3. The volume is formatted as ExFAT.

After successfully scraping TV show metadata, chose the rename/cleanup option for the selected show to get 'clean' file file names.

Most of the time it works.
Occasionally it has the issue.
No pattern is observed as to when the issue does/doesn't happen.
No error is reported either way.

The issue is observed in Finder, when returning to the folder where the media files are stored it appears as though the files still have their original name, not the new 'clean' name.

Initially it appears as though the rename had failed.
However if the computer is shut down and rebooted, returning back to the media folders shows the files now have their new clean names.

Further, any attempt to use the files with the old name (before rebooting) causes various stability issues in finder/macOS.

__What is the expected behaviour?__

New clean file names to be applied without having to reboot the computer.

__Steps to reproduce:__

It's intermittent and occasional - no guaranteed way to reproduce.

1. Update TV show media files to bring new files into the database.
2. Scrape TV show metadata - wait for finished.
3 Chose rename / cleanup selected TV show(s) / Episode(s)
4 Check in finder to see if the files have been renamed.

Sometimes they have, sometimes not.

__Additional__
> Have you attached the Logfile from the day it happened?

Log files not uploaded as they contain personal information. However log file always indicates that the rename (move) was successful and no error is reported:

From tmm.log:

2019-03-16 19:38:09,262 INFO  [tmmpool-rename-T1] org.tinymediamanager.core.Utils:701 - Successfully moved file from ....

2019-03-16 19:38:09,266 INFO  [tmmpool-main-task-T2-G55] o.t.core.tvshow.tasks.TvShowRenameTask:114 - Done renaming TV shows)

> Your Operating system? (win/mac/linux? version?)

Given above

**Comment by mlaggner** [comment]
If finder does not show the updated files, but tmm shows no error I suppose finder does some sort of caching?
you could open a terminal an have a look with the command `ls` in the folder to see the "real and uncached" files

**Comment by najinsky** [comment]
Hi Manuel,

It’s a good thought, but I already tried the ls at the command line and it too shows the old file name.

I checked the javadocs for the File class (I assume the code uses File.renameTo(File dest)) to see if there was any reference to caching but didn’t notice anything that could explain this behaviour.

My suspicion is that it may be some deep issue with the interaction between the JVM, macOS Mojave and the ExFAT file system.

I doubt there is anything that can be done in tmm to resolve it, however, if it is isn’t already being done, it might be useful to add an extra step to the rename process that gets a new reference to the destination file and checks File.exists() after the rename. If so, a “Move/Rename Verified” entry could be written to the log. Just a thought, and it might tease out some logic issue if a trapped exception is not being handled.

**Comment by myron0815** [comment]
Well, when we do some filesystem operations, and Java with it's native OS implementation does not throw an error, we HAVE to assume, everything is fine.  
We simply cannot question every action we do, and recheck.   

You could try upgrading your Java version.
(your sub-version 131 is already 2 years old)
Maybe this fixes your issues...
