### ISSUE TITLE
Only scrap video information

### ISSUE THREAD

**Issue by mooooonbaby** [tinyMediaManager/tinyMediaManager#462]
__What TMM version are you using?__
2.9.16

__What is the actual behaviour?__
TMM can't scrap information when the content isn't in thetvdb.com

__What is the expected behaviour?__
ONly scrap the video information (resolution, ...)

__Additional__
Your Operating system? (win/mac/linux? version?): Xubuntu 18.04

I have some content that isn't a series or movie (documentries or content from youtube). for that i have added an extra home button in kodi. i don't need more information except the name of the content and some video information in the xml. so far i made this by manually creating the xml files. but thats awkward when there are more than 100 episodes. what i want is only to scrap basic information about video and audio streams and write the file name without the extention to the <title>-tag. 

can this be done with tinymediamanager?

**Comment by mooooonbaby** [comment]
i found out that this works when i double click on an episode and then click on ok. the xml is created. but i have to do this for each episode individually.

**Comment by myron0815** [comment]
XML is written when you scrape or manually edit the entry.
So, when you cannot scrape such information online, you have to enter it manually?

If you are fine with the already shown / parsed title out of filename:
There should be a "rewrite NFO for episodes" function available in right click menu (for all marked shows)
