### ISSUE TITLE
cannot contact website to scrape metadata

### ISSUE THREAD

**Issue by dvdblueray** [tinyMediaManager/tinyMediaManager#463]
Version: 2.9.16
Build: 2019-02-18 20:35
OS: Windows 10 10.0
JDK: 1.8.0_201 amd64 Oracle Corporation

__What is the actual behaviour?__
Not being able to scrape metadata from websites

__What is the expected behaviour?__
To be able to scrape data to video file 

__Steps to reproduce:__
Unknown

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/2990136/tmm_logs.zip)

**Comment by myron0815** [comment]
according to logs, you did nothing - just start TMM.
No update, no scrape, nothing.
Please attach logfile after something does not work...

**Comment by Networms007** [comment]
i have the same issue... you will need some log file, where can i found it that i can send it to you

**Comment by Networms007** [comment]
23:48:57.193 WARN  org.tinymediamanager.scraper.tmdb.TmdbMovieMetadataProvider - problem getting data from tmdb: Remote host closed connection during handshake
23:48:58.733 WARN  org.tinymediamanager.scraper.tmdb.TmdbMovieMetadataProvider - problem getting data from tmdb: Remote host closed connection during handshake
23:49:00.275 WARN  org.tinymediamanager.scraper.tmdb.TmdbMovieMetadataProvider - problem getting data from tmdb: Remote host closed connection during handshake
23:49:01.832 WARN  org.tinymediamanager.scraper.tmdb.TmdbMovieMetadataProvider - problem getting data from tmdb: Remote host closed connection during handshake
23:49:03.366 WARN  org.tinymediamanager.scraper.tmdb.TmdbMovieMetadataProvider - problem getting data from tmdb: Remote host closed connection during handshake

**Comment by myron0815** [comment]
please upload the full logfile after reproducing the issue!
In the BugReport dialog you can export all needed files to a zip...
Just attach it here
