### ISSUE TITLE
Search by tag and genres?

### ISSUE THREAD

**Issue by WPFilmmaker** [tinyMediaManager/tinyMediaManager#464]
I would like to request a feature for finding movies by tag or genre, when your list is very long this would be very useful to find films according to your mood.

I tried adding tags to films, but when i searched such tag in the search bar the tagged movie did not show up, so I think this features does not exist and would like to request it.

Same thing for search by genre, there should be a quick way to delve into only a specific category.

Version 2.9.16 Linux

**Comment by mlaggner** [comment]
Try to press the filter button right to the search bar 🙄
