### ISSUE TITLE
[Feature Request] Rename Hi10p / 10-Bits in video codec.

### ISSUE THREAD

**Issue by luizoti** [tinyMediaManager/tinyMediaManager#465]
__What TMM version are you using? __
2.9.16

__release, pre-release, nightly, or directly from GitHub / branch? __
no

__What is the actual behavior? __
Do not insert bit depth into the name.

__What is the expected behavior? __
Insert Bit Depth into video codec when renaming.

__Steps to play: __

All situations where where files are renamed.

**Comment by myron0815** [comment]
has been added to V3.  
As own renamer token, which can be freely used...
(Will not be added to v2)

**Comment by luizoti** [comment]
Thanks, this will be very useful.
