### ISSUE TITLE
[Possible Bug] Use year and .nfo in searches.

### ISSUE THREAD

**Issue by luizoti** [tinyMediaManager/tinyMediaManager#466]
__What TMM version are you using? __
3.0 SNAPSHOT - 2019-03-26

__release, pre-release, nightly, or directly from GitHub / branch? __
nightly

__What is the actual behavior? __
Does not use the year and .nfo to perform searches.

Use the year of the folder or file and nfo information as a filter form in the search.

__Steps to play: __

I know if this is in fact a bug or a function removed for any reason, so I did not put it as feature request and yes "possible bug".

I had opened another post talking about it in version 2.9.15, it reported that the program n uses the year as a filter if the folder or file has.

With some tests I noticed that the program can read an already existing .nfo file to do the scrape, using this together with flexget, I was able to make a script to generate .nfo.

The problem is that I moved to the last version v3 and it stopped reading the existing .nfo to search the series.

Have you attached the Logfile from the day it happened?
Your Operating system? (win / mac / linux? version?)
Linux

**Comment by myron0815** [comment]
It depends on the scraper.
Some APIs have the ability to additionally add a year;
Some allow the year appended in to searchtext,
and some do not even find anything with year.

On scrape, we usually try several variants to find only one result, but not always possible.
Which scraper did you do your tests with?

And where/when do we not read the year?
Can you give me an example?

**Comment by luizoti** [comment]
I'll try to be clear and quick.

I tried to report what seems to me wrong, but I do not know if it's a bug or just not implemented, thanks for the patience.

For movies I use themoviedb.org.

> The Void (2016)> Year and recognized in tmm v2 and v3, but returns 3 results (normal).
> The Void (2016) .mkv> Year seems to be ignored in v2 and v3.

For movies I use .nfo to not have errors with tmmCMD the program will nfo.

For series use thetvdb.

> Dororo (2019)> The tmm ignores the year in v2 and v3.
Season 1
> Dororo (2019) - S01E01.mkv> tmm ignores the year in v2 and v3.

In v2 I used the .nfo to have n errors in tmmCMD, it worked just like the movies, but in V3 it stopped working.

For series, if I put Dororo (2019) in the search bar, I have a correct result for this series, regardless of the name of the folder or .mkv.

**Comment by myron0815** [comment]
> The Void (2016) .mkv - Year seems to be ignored in v2 and v3.
what do you mean by that???
Are you entering the coplete filename with extension in search field?! or what?!
Any if yes... WHY?


Re "Dororo":
It seems, there are some translation faults on TMDB.
While searching in english, the title and year is filled correct.
When searchin gin my localized language, the title has the year appended with brackets.


But since you did not provide any logs, i cannot help you more.
In fact, i do not even understand what you were doing or trying...

**Comment by luizoti** [comment]
No, in no situation did I put the extension, the idea was to exemplify that both the year of the folder and the year of the file were ignored, for tv series (unless it is manually typed in the search bar) I imagine that the anode should be used as a way to filter better results, out behavior where for movies the program can read .nfo, but stop series looks like they do not read.

I did not get to post the log file because the program does not generate an error message, but as soon as possible I can post here.

**Comment by luizoti** [comment]
I do not know how I can be clearer about it.

LOGS: https://filebin.ca/4bdXof71hgZw

Examples in pictures:
![4](https://user-images.githubusercontent.com/29931919/55086140-a7a5a000-5086-11e9-9da9-83da3a8f3eea.png)
![3](https://user-images.githubusercontent.com/29931919/55086142-a7a5a000-5086-11e9-8449-e4be448b37fd.png)
![2](https://user-images.githubusercontent.com/29931919/55086143-a7a5a000-5086-11e9-8904-718ce4861287.png)
![1](https://user-images.githubusercontent.com/29931919/55086144-a7a5a000-5086-11e9-9258-d6040e8c3b54.png)

**Comment by myron0815** [comment]
I still dont get it.
In all your 4 screens, the TOP # 1 search result is the one you want!
**What else should we do better???**

---  

Another thing to consider; this might explain your question:
Opening the search window for the first time - or entering a word and click search BEHAVE DIFFERENT!

The former takes ALL information it has to scrape (year, title, IDs, ...)
(This is the default behaviour, when doing automated/cmd search & scrapes)
This usually results in only one result

And if you enter something into the searchbox, ONLY this will be sent as search query!
(else you could not search at all, when taking the known values)
But this depends heavily on the used scraper, IF an appended year as searchtext will return something... or not.

**Comment by luizoti** [comment]
> Another thing to consider; this might explain your question:
Opening the search window for the first time - or entering a word and click search BEHAVE DIFFERENT!

I did another test, with the option (force best math), and he can not find information with thetvdb, BUT with themoviedb yes, this is the main problem, but he had never noticed since using themoviedb for series had no meaning for me.

>And if you enter something into the searchbox, ONLY this will be sent as search query!
(else you could not search at all, when taking the known values)
But this depends heavily on the used scraper, IF an appended year as searchtext will return something... or not.

Ok, if I understand, the textbox takes only the inserted text, I understand.

> What else should we do better???

Based on what I understand, perhaps the answer to this question is:

Make the program use the full folder name in thetvdb search, if the folder is Dororo (2019), it will ALSO try to find exactly that information.

I can be quite mistaken, but if the folder has described the year and tmm can display the year in the details tab, but at the time of searching with the CMD / force best match, it does not get results, so it is not using the year as a filter (I do not know it's part of how thetvdb works, but it sounds weird to me.)

**Forget completely the problem I mentioned about .nfo, it seems that the way tmm reads nfo has changed with respect to tvshows.**

**Comment by luizoti** [comment]
If you want you can close this topic, the problem is basically how ThetvDb works, it does not provide the year for your tvshows, but dororo in particular has the year in the title, so when searching the search box for "Dororo ( 2019) "I get one the right result, but that seems to be exclusive to Dororo.

For this reason, probably searching for Dororo (2019) with the "force best match" option using themoviedb, gets the right result.

The solution was to configure flexget to save all series without a year, and to remove special characters like ":" with this tmm recognizes everything with much less problems.

**Comment by myron0815** [comment]
Dororo has some metadata problems on TvDB; not filling the firstAired date.

But having a folder with date is always preferred.
On updating, we already have some year :)

But it does not help on TvDB - we cannot search with year; there's just a text field...

But:
how often do you NOT find a show?
I mean, searching the right show is done once, and when having all the IDs & co, you never come to this problem again....
