### ISSUE TITLE
[Feature Request] Folder Merge

### ISSUE THREAD

**Issue by luizoti** [tinyMediaManager/tinyMediaManager#467]
__What TMM version are you using?__
3.0 SNAPSHOT - 2019-03-26

__release, pre-release, nightly, or directly from GitHub/branch?__
nightly

__What is the actual behaviour?__
Scraping and renaming keep two different folders for the same series.

__What is the expected behaviour?__
If for some reason a series has episodes in two different folders and both are already properly scraped the program merges those folders.

If it is possible to include this function maybe better as something optional.

Dororo > Season 1 > Ep1.mkv 
Dororo (2019) > Season 1 > Ep2 to Ep4.mkv

__Steps to reproduce:__
- first
- second
- ...
__Additional__
Have you attached the Logfile from the day it happened?

Your Operating system? (win/mac/linux? version?)
linux

**Comment by myron0815** [comment]
sorry, too much work for too less benefit.
Moving this in explorer takes seconds, 
but changing TMM renamer, cleanup et all is much much work....

And:
We never can be 100% sure, if it is not another show with same name... so we would mix/destroy the users files! No way...

**Comment by luizoti** [comment]
ok I understand.
