### ISSUE TITLE
Movieset name sometimes not available in Renamer

### ISSUE THREAD

**Issue by eelco1** [tinyMediaManager/tinyMediaManager#468]
Version: 2.9.16
Build: 2019-02-18 20:35
OS: Windows 8.1 6.3
JDK: 1.8.0_45 x86 Oracle Corporation

__What is the actual behaviour?__

For some movies, the movie Renamer Example frame does not display the movieset that is defined in the movies' properties.
See also attached screenprints below.
The value ($M or $N) is also not used in the rename pattern.

__What is the expected behaviour?__
The movieset title should be displayed in the Example frame in the Settings dialog, and be available for the rename.

__Steps to reproduce:__
Unknown, it works with earlier defined movies, for those the movieset is displayed in the Renamer Example frame, see screenshot below.

__Additional__
Have you attached the logfile from the day it happened?
![tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/3018608/tmm_logs.zip)

Movie properties:
![2019-03-28 16_04_54-tinyMediaManager _ 2 9 16](https://user-images.githubusercontent.com/1716264/55168724-a7370300-5173-11e9-88cd-107959011099.png)

Also shown in the Moviesets list:
![image](https://user-images.githubusercontent.com/1716264/55170589-1bbf7100-5177-11e9-9b6e-d99529b26363.png)

Value missing in the Renamer example frame
![2019-03-28 16_06_07-tinyMediaManager_Settings](https://user-images.githubusercontent.com/1716264/55170420-ce430400-5176-11e9-80bb-b849186bd8e5.png)

Value is available for other movie, and is used in the Rename pattern (here shown with an explicitly defined underscore before it in the path):
![2019-03-28 16_06_07-tinyMediaManager_Settings_OK](https://user-images.githubusercontent.com/1716264/55169512-31cc3200-5175-11e9-93dc-ecea2e51234c.png)

**Comment by myron0815** [comment]
There's a setting in TMM, wether to create a MovieSet when there's only ONE movie in it.
This is not ticket in your case.

**Comment by eelco1** [comment]
Hi,
Thanks, you pointed me in the right way: It is indeed happening with all movie sets with only one movie in them. Movie sets with multiple movies in them do not have the "problem".
However, I was unaware of and unable to find the setting.
I now found it and it indeed was switched off:
![image](https://user-images.githubusercontent.com/1716264/55217529-08a4b380-5200-11e9-902e-c79fd994fa5d.png)

Enabling the option indeed solves the issue:
![image](https://user-images.githubusercontent.com/1716264/55217630-40abf680-5200-11e9-8dbe-feee6ed1d359.png)

Many thanks for your response.

I will close the ticket, as this is obviously not a bug.
