### ISSUE TITLE
[NOT A BUG BUT A SUGGESTION] Video Tutorials

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [tinyMediaManager/tinyMediaManager#469]
__What TMM version are you using?__

version=3.0-SNAPSHOT
build=552aacb1
date=2019-03-18 19\:35

__release, pre-release, nightly, or directly from GitHub/branch?__
pre-release

Dear TMM Team,
I'm just thinking since you are releasing a new version of TMM (v3) soon,
Won't it be a good idea to make a video tutorial on TMM?

**Comment by mlaggner** [comment]
would you create one? :)
we have more than enough to do with writing the code...

**Comment by Ashutosh-Kukreti** [comment]
Yup will do,
Once I understand how it works and how to customize it according to my needs.
