### ISSUE TITLE
crashing when scraping

### ISSUE THREAD

**Issue by CarnitasFries** [tinyMediaManager/tinyMediaManager#47]
Version: 2.8.1
Build: 2016-06-15 19:06
OS: Windows 7 6.1
JDK: 1.8.0_91 x86 Oracle Corporation

__What is the actual behaviour?__

I had no problem indexing 
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/325720/tmm_logs.zip)
and managing 188 movies in my PC, yesterday. Today it is crashing pretty much after every movie where I need to Search and Scrape. The biggest difference today is that I am trying to index a USB connected external drive. This could be causing the problem...

__What is the expected behaviour?__

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?

**Comment by mlaggner** [comment]
this is a random hiccup - please try again.
I'll increase stability of multithreading soon
