### ISSUE TITLE
Movies are not displayed

### ISSUE THREAD

**Issue by RonPil** [tinyMediaManager/tinyMediaManager#470]
Version: 2.9.16
Build: 2019-02-18 20:35
OS: Windows 10 10.0
JDK: 1.8.0_201 x86 Oracle Corporation

__What is the actual behaviour?__
Movies are not displayed in TMM

__What is the expected behaviour?__
Movie directories are not read completely. There are always missing movies that are not displayed in TMM even though they are in the directory structure.

__Steps to reproduce:__
Data source to add, re-read directories

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/3072544/tmm_logs.zip)

**Comment by myron0815** [comment]
Good to have logs.  
Better would be a NAME or FOLDER to look for, which has not been added....
(Maybe it is just an wrong NFO, so the movie you are expecting has a wrong name...)

**Comment by RonPil** [comment]
A picture says more than 1000 words;)
You will see the folder list / movie list on the left and on the right the movies that were imported.
The movie files have the same names as the folders, there are no NFO files in the folders.
I hope you can start with the picture a little more than with the log.
![Anmerkung 2019-04-12 130130](https://user-images.githubusercontent.com/49553868/56033105-05dbaf80-5d24-11e9-8a4e-062ee7619f9f.jpg)

**Comment by myron0815** [comment]
Starting with the first - what's the contents of "Ant Man" folder?

**Comment by RonPil** [comment]
only the Movie File with the same name as the folder "Ant Man and the Wasp {3D} [2018] [HD] BD.mk3d"
Ah i think i see the mk3d is the problem. Testing? Yes thats it. 
I'm sorry for the uproar :( then the whole thing can be closed.
Thanks for the food for thought

**Comment by myron0815** [comment]
Yep, this is a yet unknown video file extension.  
Just add it inside TMM settings...
