### ISSUE TITLE
Reqest - scraper for blu-ray.com

### ISSUE THREAD

**Issue by postmanpaul** [tinyMediaManager/tinyMediaManager#471]
i really wanna see scraper for blu-ray.com, i whould also wanna sponsor that project..
i collect alot of blu-ray movies, and imdb and more dont have that info,photos or nothing.
think it whould be awsome to see that scraper into tiny as i love that program, i found a nother program that works for blu-ray.com, its not as perfect as tiny!

Greets.
PostmanPaul.

**Comment by mlaggner** [comment]
sadly no, since there is no official API for blu-ray.com
