### ISSUE TITLE
how to get access to csfd scraper?

### ISSUE THREAD

**Issue by alfonz19** [tinyMediaManager/tinyMediaManager#472]
__What TMM version are you using?__
2.9.16

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
all ok

__What is the expected behaviour?__
have csfd scraper available

__Additional__
I've been told, that donor version have csfd enabled, but that did not happen to me. What can I do to get access to get access to that?

Thanks!

**Comment by mlaggner** [comment]
you need to have kodi installed on the same system along with this scraper.
tmm can find this scraper from kodi and use it

**Comment by alfonz19** [comment]
Still no light at the end of tunnel.
I installed kodi. No csfd among plugins, at least I cannot find it. I found some web page about this scraper, download zip file and tried to add it using this file (metadata.csfd.cz-3.3a.zip resp metadata.csfd.cz.3.4b.zip) but cannot be added.

so the one from official (dead) site, the version 3.3a prints:
The dependency on metadata.common.hdtrailers.net version 1.0.4 couldn't be satisfied

I also found some fan base (hopefully not hacker based) version 3.4b, which prints:
The dependency on metadata.common.hdtrailers.net version 2.0.5 couldn't be satisfied

the version of dependency in question seems  to be 1.2.2. And finally I'm on archaic fedora 26 and running kodi from repositories. I will upgrade at the end of the month when newest fedora is out, so maybe this will improve, but considering the versions, it should be working, right? 1.2.2 should be sufficient for 1.0.4, no?

**Comment by myron0815** [comment]
Sorry, we cannot give support for Kodi plugin - try Kodi forums, or the forum/site where you've downloaded the plugin.

in TMM, we _just try_ to execute it, which works to some intent, but not 100%  
Try to get this scraper running inside Kodi first....

**Comment by myron0815** [comment]
https://github.com/ekarorgit/metadata.csfd.cz
has version 3.11, updated within last year.
Did you try that?

**Comment by alfonz19** [comment]
That one could be installed and work (seems that only nfo is generated, but better than nothing).
Thank you very much, I understand(now) that this is completely unrelated to your area, but you helped anyways. I really appreciate that. Thank you again.
