### ISSUE TITLE
 create movie sets/collections based on my own criteria

### ISSUE THREAD

**Issue by MariusCC** [tinyMediaManager/tinyMediaManager#474]
__What TMM version are you using?__
TMM 2.9.16 release

__What is the actual behaviour?__
No way to group the movies in "movie sets" except by getting already defined sets from TMDB.

__What is the expected behaviour?__
I want to be able to create movie sets/collections based on my own criteria (ie - children movies or martial arts movies).

__Additional__
Manjaro Linux latest.

**Comment by myron0815** [comment]
Oo the MovieSet page, click the "+" icon to manually create a MovieSet.
Once done, you can edit it, to add the (sparse) metadata, and to assign it now to movies...

**Comment by Suddow** [comment]
Is there a way to do sequential numbering for moviesets?

**Comment by mlaggner** [comment]
movie sets are sorted (inside tmm) by their name; you could put the numbering into the movie set name if you want to

```
01. Movieset 1
02. Movieset 2
...
12. Movieset 12
```
