### ISSUE TITLE
Any way to remove the word 'rated' from mpaa rating?

### ISSUE THREAD

**Issue by Viswanth1038** [tinyMediaManager/tinyMediaManager#476]
Is there any way to remove the word 'rated' from mpaa rating to just only show pg-13 or r and not like rated pg-13, rated r?

**Comment by mlaggner** [comment]
where exactly do you want to remove it? in the UI or NFO?

for the NFO we should already have a setting to let you choose the right certification

**Comment by Viswanth1038** [comment]
Not certification tag. mpaa tag in NFO

**Comment by mlaggner** [comment]
no sorry, we've fixated this style for the MPAA tag for Kodi compatibility (this has been verified and changed in 2017/01)

why would you need another form here?

**Comment by Viswanth1038** [comment]
I'm using these nfo files for Emby and the ratings show up like 'rated pg-13'. It's okay though. I'll remove certification from metadata and Emby fetches it.
