### ISSUE TITLE
Laserdisc not listed as a Source type

### ISSUE THREAD

**Issue by HunterZ** [tinyMediaManager/tinyMediaManager#477]
Version: 2.9.16
Build: 2019-02-18 20:35
OS: Windows 10 10.0
JDK: 1.8.0_211 amd64 Oracle Corporation

__What is the actual behaviour?__
Movies with LDRip in their names are not recognized as a source of Laserdisc, nor is Laserdisc an option for the Source dropdown in the Edit movie -> Details menu.

__What is the expected behaviour?__
Laserdisc is included in Edit movie -> Details menu, and Laserdisc/LDRip recognized in filenames.

__Steps to reproduce:__
Scrape a movie with LDRip in its filename, or examine the Edit movie -> Details -> Source dropdown.

__Additional__
No log file, as it's obvious from looking at the UI that this is not currently supported.

**Comment by mlaggner** [comment]
this has already been added for v2 and won't be backported to v2
