### ISSUE TITLE
Error Exporting Movies in ANY format after upgrading to 2.8.1

### ISSUE THREAD

**Issue by jrgigliotti** [tinyMediaManager/tinyMediaManager#48]
Version: 2.8.1
Build: 2016-06-15 19:06
OS: Windows 10 10.0
JDK: 1.8.0_73 amd64 Oracle Corporation

__What is the actual behaviour?__
Go to export movies, folder is created if needed, but no files are actually created.

__What is the expected behaviour?__
Exporting of movies adds index.html and other files based on the template.

__Steps to reproduce:__
Open up TMM, make sure movies are up to date, add movies if needed.  Select all movies to Export, right click and "Export selected movie(s)".  Select any template and output folder and click "Export".  No files are created, log displays 

2016-06-23 10:49:12,373 ERROR [main] o.t.u.movies.dialogs.MovieExporterDialog:181 - Error exporting movies: illegal template

__Additional__
Have you attached the logfile from the day it happened? Yep
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/330208/tmm_logs.zip)

FYI, In addition, I'm hoping to submit a new export that I've been working on for awhile here and there for your review.

**Comment by mlaggner** [comment]
thanks for reporting. 
We're already aware of this bug and that will be fixed for the next version.

you can send us the export template to support@tinymediamanager.org for review when it is finished

**Comment by jrgigliotti** [comment]
Great!  Thanks!

**Comment by jrgigliotti** [comment]
FYI - I have now upgraded to 2.8.3.1 and still having this same issue?

Thanks,
Jen

**Comment by mlaggner** [comment]
Do you have any actual log?

**Comment by jrgigliotti** [comment]
Here are all of the logs.

**Comment by mlaggner** [comment]
sorry, no attachments were in your response..
you can also upload it to something like pastebin (only tmm.log is interesting here)

**Comment by jrgigliotti** [comment]
hm, ok.  here is just the tmm.log

**Comment by jrgigliotti** [comment]
Sorry, I was simply responding via my gmail instead of actually logging into github, so try this.
[tmm.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/428069/tmm.zip)

**Comment by mlaggner** [comment]
do you have sufficient permissions to write the export to C:\inetpub\wwwroot\ ?
could you also send me your export template to support@tinymediamanager.org for further analysis?

**Comment by jrgigliotti** [comment]
Ok,  thanks for that.  I had tried setting up the local server and didn't even think about that.  I've now got it back to working again, BUT when I go to export, it doesn't create the include folder and the images folder and all the files that belong in there export to the main directory.  I went ahead and attached the zip of the Mobile Movie Search template I've been working on over the last few years to see if you can duplicate, but I've also experienced similar problems with the other templates like SimpleConfluence.  I have moved away from using the wwwroot and just using a random folder in the c:\drive
Thanks,
Jen
[MobileMovieSearch.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/428949/MobileMovieSearch.zip)

**Comment by mlaggner** [comment]
Copying is working here (MobileMovieSearch and SimpleConfluence).
Please check 
* all source files are available in your template folder 
* you have sufficient write permissions at your target folder

otherwise I need to create a special tmm version with enhanced debugging infos..
