### ISSUE TITLE
[SUGGESTION] In the tv series renamer, be able to use episode tags

### ISSUE THREAD

**Issue by rurikk94** [tinyMediaManager/tinyMediaManager#480]
__What TMM version are you using?__

tinyMediaManager 3.0 

__release, pre-release, nightly, or directly from GitHub/branch?__

Date Compilation 2019-05-31 16:05

__What is the actual behaviour?__

it is possible to add tag to the tv episodes or to the tv show itself.

__What is the expected behaviour?__

Be able to use the added tag in the tv show renamer.

PD: i' don't speak english very well, sorry if you dont understand me

**Comment by mlaggner** [comment]
in the renamer of v3 you can do basically everything:

https://gitlab.com/tinyMediaManager/tinyMediaManager/wikis/TV-Show-Settings#renamer
https://gitlab.com/tinyMediaManager/tinyMediaManager/wikis/JMTE
