### ISSUE TITLE
How do I uninstall version 3 and go back to my previous version AND restore my original settings before they were messed up by the version 3 install?

### ISSUE THREAD

**Issue by Rappleby28** [tinyMediaManager/tinyMediaManager#481]
__What TMM version are you using?__

__release, pre-release, nightly, or directly from GitHub/branch?__

__What is the actual behaviour?__

__What is the expected behaviour?__

__Steps to reproduce:__
- first
- second
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

**Comment by myron0815** [comment]
- download and extract v2 to some folder
- copy folder "data_old_v2" from v3 and rename to "data"

May i ask what we've messed up?
Maybe we can change/fix it?

**Comment by Rappleby28** [comment]
Thanks for your prompt response. The problem related to the renaming area. I had ver 2 set up to create a genre folder and put the movie folder inside that and the movie into the movie folder with NFO, extended art, etc. In the Kodi format. Then I would merge it with my existing folders. When I upgraded, that renaming system disappeared.  I finally figured out how to do it in ver 3. Sorry for the panic. You can close (or delete) the thread. 
--
Best Regards,
Ray Appleby
403-852-0582
From my iPhone
