### ISSUE TITLE
Korean/Japanese characters not encoded properly in NFO file

### ISSUE THREAD

**Issue by bmeriwether** [tinyMediaManager/tinyMediaManager#482]
Version 3.0
Build date: 2019-05-31 16:05

**Problem:**
After scraping a Japanese or Korean film, TMM writes the original title field as bad characters. E.g. a bunch of square boxes. It shows this in both the UI as well as improperly displayed when the actual NFO file is opened. After opening the corresponding title on TMDB, the original title is shown as expected. If I copy & paste the Japanese text into the NFO, it's fine. But regardless of that, TMM still won't display the title correctly in that field. My system otherwise has no issues rendering or saving these names.

**Expected behavior:**
TMM would fetch Japanese/Korean original title names from TMDB and display them properly in the original title field in the UI. It would then save them properly encoded into the NFO file.

**Repro:**
- Add foreign language film (e.g. "3-Iron (2004)" or "Zatoichi and the Chest of Gold (1964)".
- R-click and select scrape this title.
- In the Search movie dialog that comes up, below the english name of the movie matched will be a series of boxes instead of the correct Korean or Japanese title.
- Open the corresponding nfo file it wrote - there is bad information written here as well.

**Additional:**
As run on Windows 10

![Capture](https://user-images.githubusercontent.com/51335104/58821436-494eed80-85f2-11e9-9a64-3a677bf3e334.PNG)

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/3248724/tmm_logs.zip)

**Comment by bmeriwether** [comment]
Example of NFO with bad title written.

[Kamikaze Girls (2004).zip](https://github.com/tinyMediaManager/tinyMediaManager/files/3248741/Kamikaze.Girls.2004.zip)

**Comment by myron0815** [comment]
works for me...?
![grafik](https://user-images.githubusercontent.com/1846737/58825130-061a6c00-863e-11e9-9e1c-841adf367eb4.png)

Scraped the show from tmdb;   
and also imported your NFO.  
Both worked....  hmmmm....

**Comment by bmeriwether** [comment]
@myron0815 Thanks. I am using Notepad++, but apparently it doesn't auto-select UTF8 encoding. With it selected, I can see that it is saving it off OK. What font are you using in TMM for display? I have tried several, but it doesn't make a difference.

**Comment by mlaggner** [comment]
the font is the default windows font for Java (Dialog which should be the physical font Lucidia).
If you need a font which supports also Japanese/Korean Glyphs you have to choose that font in the font settings inside tmm..

**Comment by zpengcom** [comment]
Font list cannot display the source-han-sans font
https://github.com/adobe-fonts/source-han-sans

**Comment by mlaggner** [comment]
Java can only use ttf fonts - not otf fonts
