### ISSUE TITLE
Feature Request: Scraping 3D movies.

### ISSUE THREAD

**Issue by Rappleby28** [tinyMediaManager/tinyMediaManager#483]
Version 3.0 has a file type of mk3d but the renamer has no token to rename the movie to include the 3D format such as HSBS or TAB or indicate in any way that the movie is 3D.  It would be nice if we could rename the movie in a format which would be recognized by KODI as a 3D movie.

**Comment by mlaggner** [comment]
there is a token for the 3D format:
![image](https://user-images.githubusercontent.com/1523778/59017320-8c53cf80-8843-11e9-9bf0-801690f8f913.png)
