### ISSUE TITLE
Error while renaiming artwork files

### ISSUE THREAD

**Issue by TuxMaus** [tinyMediaManager/tinyMediaManager#485]
__What TMM version are you using?__
3.0.1 on linux 4.15.0-50-generic with openjdk-11-jre

__release, pre-release, nightly, or directly from GitHub/branch?__
Release

__What is the actual behaviour?__
During scraping the artwork files are downloaded to tmp directory as expected but afterwards they are deleted but not moved to destination folder -> renaiming error (see log file)

With TMM version 2.9.x I had no problems with renaiming artwork files. 

Video file is renamed and moved to subfolder as expected.
NFO file is created in subfolder as expected.

Files are stored on a CIFS mounted device.

__What is the expected behaviour?__
Artwork files are expeced to be saved.

__Steps to reproduce:__
force new scraping "Strg+Shift+S"

__Additional__
Logfile: [tmm.log](https://github.com/tinyMediaManager/tinyMediaManager/files/3317264/tmm.log)

**Comment by mlaggner** [comment]
should be fixed with v3.0.3
