### ISSUE TITLE
Configuration deleted when upgrade.

### ISSUE THREAD

**Issue by raistlin2912** [tinyMediaManager/tinyMediaManager#488]
__What TMM version are you using?__
3.0.2

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
The configuration is overwriten

__What is the expected behaviour?__
Mantain configuration untouched

__Steps to reproduce:__
- Replace the app with new version

__Additional__
OS: MacOS Mojave

I use Homebrew cask to install and update your app. The problem is that application stores its configuration files inside the APP file, when you replaces the app for update (like homebrew does) the configuration are deleted.

Solution: Store configuration on "Application Support" folder, like all apps in MacOs.

**Comment by mlaggner** [comment]
tmm is designed to be portable (to have multiple instances side by side) and thus it needs to store all information inside the app itself
furthermore we also offer an upgrade mechanism - so there is no need to a homebrew task.

**Comment by raistlin2912** [comment]
@mlaggner Hello, All apps in MacOS stores his configuration in the user folder inside Application Support. If you stores the configuration inside APP file you can't use the app in multi-user environment, because the APP file is the same for all users if you installs in /Applications.

**Comment by raistlin2912** [comment]
The "portable" term used for windows apps not is applicable to macOS apps.
