### ISSUE TITLE
[Feature] Renamer+Clean Safety Prompt or Disable Option

### ISSUE THREAD

**Issue by xInsertx** [tinyMediaManager/tinyMediaManager#489]
__What TMM version are you using?__
Using TMM 3.0.2 (release) on Windows 10

Can we please get a safety prompt for the rename+clean button at the top? At some stage, while using v3 today I must have misclicked or something because when I checked my folders they were all messed up. TMM had gone through and destroyed my directory structure and filenames and **DELETED a heap of custom files** in each folder.

I consider this a hazard that never once happened in all the time I've been using v2. A simple "Are you sure?" prompt will prevent any further accidental changes.

Ideally, I would like this to be something globally disabled, but a prompt will suffice.

Note: Luckily I use ZFS Snapshots, so it only costed me about an hours worth of work to rollback and reconfigure a few things, but this could be devastating to someone.

**Comment by myron0815** [comment]
What files did we delete?  
Are your (renamer|image) settings the same as in v2 (with new syntax of course)?  
Usually, you find them in a hidden ".deletedByTMM" folder in each datasource (since we do not delete anything)

Even if you forcefully clicked on that button - with "yes" the same would have happened.  
If we start adding such dialog to rename & cleanup, we must add this to 10 other methods as well...

**Comment by xInsertx** [comment]
I'll see if I can grab the logs tonight once I'm back. I didn't know about the hidden deletebytmm folder, but as mentioned a snapshot rollback fixed this much quicker.

regarding rename settings, there left as default because I do not use TMM to do renaming in my workflow (I let radarr/sonarr handle this). I use TMM as a pure library/metadata management tool, which is doing quite well.

What I'm looking for is a prompt to prevent someone from accidentally clicking the button (on the top menu) and having it rename/clean there folders/data sources. A simple prompt beforehand would allow them to click NO preventing accidents from happening.

**Comment by myron0815** [comment]
hmm.. i c.  
You could remove the file naming patterns in renamer settings.  
If they are empty, we _shouldn't_ rename... (never tried)

**Comment by xInsertx** [comment]
@myron0815 
Sorry for the late reply.

Well, that works, but I wonder if that should be more treated as a bug, or display an error. Maybe an option under each Renamer tab to just enable/disable it will be cleaner.

For now, I'm quite happy to make the patterns empty fields, But I would be worried about the future.

**Comment by mlaggner** [comment]
will be added to 3.0.4
