### ISSUE TITLE
[BUG?] Warning Displayed about missing NFO files when not expected.

### ISSUE THREAD

**Issue by xInsertx** [tinyMediaManager/tinyMediaManager#490]
**What TMM version are you using?**
Using TMM 3.0.2 (release) on Windows 10

**What is the actual behaviour?**
Under "TvShows " > "Scrapper" > "NFO settings" I only have tvshow-nfo ticked. (Not episode nfos)

When viewing the library, it displays a warning saying nex to series title "The nfo for one or missing episodes is missing".

__What is the expected behaviour?__
I think this should not be displayed. If tvshows is ticked only, only check for the series nfo. This appears to be how images already work. The warning should still be displayed below it though.

OFC this could be by design but seems counter-intuitive (when doing library maintenance) if you have disabled the option yourself.

See Attached.
![image](https://user-images.githubusercontent.com/10349764/61167185-16e3c900-a57e-11e9-9ebc-fbaefbaa9864.png)

**Comment by myron0815** [comment]
ok, i c.  
removed the need for this warning, if you have unticked the episode NFOs.  
thx.
