### ISSUE TITLE
[TEMPLATE] mobilemovie with details

### ISSUE THREAD

**Issue by dp-site** [tinyMediaManager/tinyMediaManager#491]
Hi, I modified the mobilemovie search template by Jennifer Gigliotti.
It display some info if you click on the image and the imdb page if you click the title.

You must click because mobile haven't :hover :(
There is a demo here :
http://dp-site.fr/VideoExpansionList/tmmExpansionVideos/movielist.html
It keep the Jennifer 's functions.

[MyMobileMovieSearch.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/3390148/MyMobileMovieSearch.zip)

**Comment by mlaggner** [comment]
sorry for the late reply - I did not watch the github issues since we migrated to gitlab

what exactly did you modify? Do you think we can merge that into the original template?

**Comment by mlaggner** [comment]
okay, just compared them and they are different; I'll add this as a separate template -> thanks
