### ISSUE TITLE
I want to use the featurettes folder name like video_extras

### ISSUE THREAD

**Issue by diarmate** [tinyMediaManager/tinyMediaManager#493]
__What TMM version are you using?__

3.0.2
__release, pre-release, nightly, or directly from GitHub/branch?__

release
__What is the actual behaviour?__
when i renamed,
"fearturettes" folder files in the movie folder are distributed

__What is the expected behaviour?__

I want to use the featurettes folder name like video_extras.
Where can I fix it?I can't make template.conf..sorry
I want to modify only that part

__Steps to reproduce:__
- first
- second
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

**Comment by mlaggner** [comment]
try to only name that folder extras
