### ISSUE TITLE
Trakt doesn't have an API key anymore, but client ID and secret.

### ISSUE THREAD

**Issue by SyRaza** [tinyMediaManager/tinyMediaManager#495]
__What TMM version are you using?__
3.0.2

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
TMM asks for Trakt Api Key but trakt only client ID and secret now. At least I can't find a way to get a single api key. 

How do I connect TMM with Trakt?

__Additional__

Your Operating system? (win/mac/linux? version?)
Linux

**Comment by mlaggner** [comment]
for connecting your lib with trakt, you need to use the settings page "General -> external Services"

entering an API key for trakt is only provided, if you don't want to scrape with the tmm api key..

**Comment by mlaggner** [comment]
in fact the Client ID is the only thing you need to use here;
notation will be changed in 3.0.4
