### ISSUE TITLE
Feature request: Generate .nomedia files for ended series and optionally single movie folders

### ISSUE THREAD

**Issue by FrankEBailey** [tinyMediaManager/tinyMediaManager#496]
It would be immensely useful to me if TMM was able to generate .nomedia files for series that have ended. Kodi takes a long time (upwards of 10 minutes at times) to scan my entire library for new items, and I've discovered that strategically placing .nomedia files in the folders of shows that have come to an end has allowed me to speed up the Kodi library scans quite a bit. The same goes for movies, but as I store my movies in single folders with the movie name, it means a lot of copy-pasting. If TMM could create these files automatically it'd be a massive time saver.

**Comment by mlaggner** [comment]
copied this issue to gitlab: https://gitlab.com/tinyMediaManager/tinyMediaManager/issues/622
