### ISSUE TITLE
Genres 'Marvel' is transformed to Holiday

### ISSUE THREAD

**Issue by francoisgagnon** [tinyMediaManager/tinyMediaManager#497]
Hi,

I tested this situation on version 3.0.0 (release) and 3.0.4.
Into Movie Edit (tabs Details2), when I enter Genres (custom) it is transformed to other word.
(I tested that with language French and English, same situation), OS : Windows
like :
'Marvel' -> 'Holiday',
'Dead' -> 'Documentary'

but 'Marvels' -> 'Marvels' (not changed)

I checked on all files 'messages_xx' any languages use this word.
Do you have idea why?

**Comment by francoisgagnon** [comment]
Hi, 

I tested this situation on version 3.0.0 (release) and 3.0.4.
Into Movie Edit (tabs Details2), when I enter Genres (custom) it is transformed to other word.
(I tested that with language French and English, same situation)
like : 
'Marvel' -> 'Holiday', 
'Dead' -> 'Documentary'

but 'Marvels' -> 'Marvels' (not changed)

I checked on all files 'messages_xx' any languages use this word.
Do you have idea why?

**Comment by mlaggner** [comment]
yes, this is a side effect of our "we try to detect all different notations" logic..
we may have to tweak this a bit - stay tuned

and please open issues at gitlab, since v3 is hosted there!
