### ISSUE TITLE
Error On Scrape & Artwork Will Not Download

### ISSUE THREAD

**Issue by whwgh** [tinyMediaManager/tinyMediaManager#50]
Version: 2.8.1
Build: 2016-06-15 19:06
OS: Windows 10 10.0
JDK: 1.8.0_91 amd64 Oracle Corporation

__What is the actual behaviour?__
When I scrape a movie I get the error log (attached) it appears all text based info is downloaded but artwork will not.  When I manually choose artwork and click OK in the Edit Movie selection it also will not download the artwork.

__What is the expected behaviour?__
That text data and artwork should download.

__Steps to reproduce:__
right click title and select Search & Scrape Selected Movies (1 at a time).

__Additional__
Have you attached the logfile from the day it happened?
Yes
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/333822/tmm_logs.zip)

**Comment by akyag** [comment]
I have problem scarping episode thumb. This maybe related to the problem above. Attaching logs
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/340001/tmm_logs.zip)

**Comment by mlaggner** [comment]
@whwgh you have some sort of access problem to the file system (many NoSuchFileException or FileNotFoundException). Looks like you have an USB drive or Network share connected. Please be sure that the drive is accessible while scraping!

@akyag you have some HTTP 403 (forbidden) responses from TMDB. The same urls work for me.. Could it be possible that you have been (temporarily) blocked from TMDB?
