### ISSUE TITLE
 Feature request: some tokens for the file renamer

### ISSUE THREAD

**Issue by enigmans** [tinyMediaManager/tinyMediaManager#51]
Hi

Can  you please add new tokens in the file renamer? Like for TV shows I want to keep the "origin", like HDTV or Web-DL, and also the release group if possible. Because this is very important stuff when searching for subtitles manually, makes everything easier!

If possible, you can scan the file name for "origin" and "release group" and maybe save it the NFO. Users can for example keep track of their own releasegroups in a list box, like the 'bad words' box in settings -> movies -> general. I'm just thinking out loud, I hope it's not too much I ask of you. :sweat_smile:

**Comment by mlaggner** [comment]
I could add the field "media source" to the renamer for episodes too if that would be enough.
release group handling is a different part - at the moment we are not able to extract the release group out of the file name and we have no field for release groups either..
But with hash searches you should be able to find the right subs for your episodes?
