### ISSUE TITLE
Cannot scrape episode metadata

### ISSUE THREAD

**Issue by estidiskyroamer** [tinyMediaManager/tinyMediaManager#52]
Version: 2.8.1
Build: 2016-06-15 19:06
OS: Windows 8.1 6.3
JDK: 1.8.0_45 x86 Oracle Corporation

I can scrape the TV show just fine (casts, plots, artworks all show up) but the info for individual episodes cannot be scraped.

Steps:
1. Searched for the TV show and found.
2. Scraped the TV show with all items checked, done. Episodes not scraped.
3. Tried to scrape episode metadata individually, didn't do anything.
4. Rename/cleanup works, each episode went into appropriate season folders, but the episode files are not renamed.

__Additional__
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/339150/tmm_logs.zip)

**Comment by mlaggner** [comment]
I've had a look at your logs and only found a hint at "Bizarre Foods" DVD Season 10 / EP 10 - which is (according to the website of tvdb) not available.
After having a look at the response of TVDB there is no information about DVD Seasons/Episodes for the whole show..
