### ISSUE TITLE
Feature Request: use .nomedia file to exclude folder from scan

### ISSUE THREAD

**Issue by Stefan-Code** [tinyMediaManager/tinyMediaManager#53]
[Kodi excludes folders](http://kodi.wiki/view/Set_content_and_scan)  containing a `.nomedia` file from the library when scanning. 
It would be nice to have this behaviour for tinyMediaManager, too (or at least an option to enable it).
This would be especially useful for the 'Extras' folder of many DVDs or Blurays.

**Comment by mlaggner** [comment]
`.nomedia` will be supported in the next version

**Comment by Stefan-Code** [comment]
Great, thanks.
By the way, is there some documentation regarding the build process somewhere?
Because when I try to `mvn compile` the project, it complains about three missing artifacts:
```
1) org.tinymediamanager:api-scraper:jar:2.1-SNAPSHOT
2) org.tinymediamanager.plugins:scraper-imdb:jar:1.5-SNAPSHOT
3) org.tinymediamanager.plugins:scraper-tmdb:jar:1.4-SNAPSHOT
```
Is there a quick way to resolve this? I can also open a new issue if you want to.

**Comment by mlaggner** [comment]
yes there is (in the README.md :) ):


## Developer info:
To work with the SNAPSHOTs, you need to add following repository to your ~/.m2/settings.xml

```
<repository>
  <id>ossrh-snapshot</id>
  <name>Sonatype Snapshot Repository</name>
  <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
  <releases>
    <enabled>false</enabled>
  </releases>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
</repository>
```

**Comment by Stefan-Code** [comment]
Ah, didn't see that. Thanks. Working now :smile:
