### ISSUE TITLE
copyArtwork fails if image already present and creates stupid url

### ISSUE THREAD

**Issue by Garfonso** [tinyMediaManager/tinyMediaManager#56]
__What TMM version are you using?__
Nightly from 10.07.2016, 2.8.2

__release, pre-release, nightly, or directly from GitHub/branch?__
nightly

__What is the actual behaviour?__
copyArtwork feature fails to copy an image file (error message in log) if the file is already present (because of an previous export, for example). That leads the html template img src="" to be not the url to the image file but the complete contents of the movie.

__What is the expected behaviour?__
One option would be to just overwrite the image file. Another option would be not to fail if it is already there but just skip it (should be done for other resources as well, I see this for some .css files, too). Additionally the copyArtwork-renderer should still output the correct url to the html file, even if it fails to copy  the image!

__Steps to reproduce:__
- create a template with the copyArtwork feature
- export movies to empty folder A
- look if export worked (no errors in log, html looks good, correct urls in img src fields)
- export movies to folder A again, same folder, do not delete files before export
- open html file and see that instead of url there is the complete description of the movie in the img src field, which of course is not found. Also there are error messages in the log that it could not copy image files.

__Additional__
Have you attached the Logfile from the day it happened?
Relevant excerpt from the log: https://bpaste.net/show/918a4a82bd85
(maybe there is even more broken, should it copy the contents of sub folders or the complete folders? I see that the contents of the subfolders gets mixed up in the destination folder, so I had to adjust some paths. Log speaks about subfolders, though.).

Your Operating system? (win/mac/linux? version?)
Windows 10

**Comment by mlaggner** [comment]
thanks for the hint. Will be fixed in the next version and is already fixed in the actual nightly
