### ISSUE TITLE
Rename/Cleanup of series does not rename .idx files

### ISSUE THREAD

**Issue by CyberC123** [tinyMediaManager/tinyMediaManager#57]
__What TMM version are you using?__
2.8.2-SNAPSHOT

__release, pre-release, nightly, or directly from GitHub/branch?__
PRE-RELEASE

__What is the actual behaviour?__
Renaming/Cleanup of series external subtitles (.sub and .idx files) does not rename the .idx files  but rename the .sub files.

/******************
Before:
The Returned (US) - S01E01 - Camille-forced.sub
The Returned (US) - S01E01 - Camille-forced.idx
The Returned (US) - S01E01 - Camille.sub
The Returned (US) - S01E01 - Camille.idx

After:
The Returned (US) - S01E01 - Camille.deu.forced.sub
The Returned (US) - S01E01 - Camille.forced.idx
The Returned (US) - S01E01 - Camille.deu.sub
The Returned (US) - S01E01 - Camille.idx
******************/

It's the same issue like "Rename/Cleanup of movies does not move/rename .idx files #45"

__What is the expected behaviour?__

Both .idx and .sub files are renamed.

/******************
The Returned (US) - S01E01 - Camille.deu.forced.sub
The Returned (US) - S01E01 - Camille.deu.forced.idx
The Returned (US) - S01E01 - Camille.deu.sub
The Returned (US) - S01E01 - Camille.deu.idx
******************/

__Steps to reproduce:__

Add a series with external subtitles (.sub and .idx)
Scrape and rename/cleanup

__Additional__
Your Operating system? (Win7)

**Comment by mlaggner** [comment]
thanks for pointing that out. Should be fixed now
