### ISSUE TITLE
Feature request : view missing episodes in TvShows

### ISSUE THREAD

**Issue by hellmer1234** [tinyMediaManager/tinyMediaManager#58]
Hi

Can you please add some way to identify what are missing episodes in TvShows ?

This feature could be provided by contextual menu at tvshow or season level.
Missings could be find by comparing files from local (real) and files from remote data (theorical).

Thanks

Louis

**Comment by CyberC123** [comment]
The same feature for missing seasons, please:)

**Comment by CyberC123** [comment]
also add in the main-tree the local existing and in tvdb.com existing seasons/episodes like this:
![1](https://cloud.githubusercontent.com/assets/20404622/19284880/060e9c0c-8ff8-11e6-9ffa-6dac093c83e5.png)

**Comment by mlaggner** [comment]
have included that into the V3 branch
