### ISSUE TITLE
Memory setting failure

### ISSUE THREAD

**Issue by Gridluck** [tinyMediaManager/tinyMediaManager#59]
__What TMM version are you using?__
Version: 2.8.1

__release, pre-release, nightly, or directly from GitHub/branch?__
directly from GitHub

__What is the actual behaviour?__
program doesnt start after setting memory to 2048 mb, (i've 32gb memory)

__What is the expected behaviour?__
program should start

__Steps to reproduce:__
1. set memory to 2048
2. close the program
3. start the program << nothing happens.. no error, no notification, no log

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/367377/tmm_logs.zip)

your log generator wrongly detects my system as x86, infact its x64

**Comment by mlaggner** [comment]
you will probably have a x86 Java JVM installed. Try to lower the memory settings to 512mb (at max 1GB - unless you have a really huge lib, you won't need more than 512mb)

**Comment by Gridluck** [comment]
1GB works fine, it's only 9 movies in this library..

**Comment by Gridluck** [comment]
i'm referring to:
2016/07/16 11:28:58:945 INFO n.a: ------------------ VM Info ------------------
2016/07/16 11:28:58:947 INFO n.a: -- OS Name: Windows 8.1
**2016/07/16 11:28:58:948 INFO n.a: -- OS Arch: x86**
2016/07/16 11:28:58:948 INFO n.a: -- OS Vers: 6.3
2016/07/16 11:28:58:948 INFO n.a: -- Java Vers: 1.8.0_91
2016/07/16 11:28:58:948 INFO n.a: -- Java Home: C:\Program Files (x86)\Java\jre1.8.0_91

as well as:
2016/07/16 11:28:59:005 INFO n.a: ---------------------------------------------
2016/07/16 11:28:59:005 INFO n.a: Skipping [quals=!windows, osname=windows 8.1, **osarch=x86**, key=resource, value=[!windows] tinyMediaManagerCMD.sh]
2016/07/16 11:28:59:005 INFO n.a: Skipping [quals=!windows, osname=windows 8.1, **osarch=x86**, key=resource, value=[!windows] tinyMediaManager.sh]

nothing about java version

**Comment by mlaggner** [comment]
os arch = java arch for us
if os arch = x64 and java arch = x86 we need to use x86 native libs

btw. with 9 movies you don't need more than 512mb.. I've a testbed of movies (~500) AND TV shows (~10000eps) and that works nice with 512mb

**Comment by Gridluck** [comment]
I know I don't need that much, it was for the purpose of testing.. if it works with 512, it shall work with 2048MB!

**Comment by mlaggner** [comment]
changing memory settings in Java is dangerous.
Unlike Windows native apps, upon creating the JVM, Java checks if the requested amount of memory is available in the system. 
This means: if you have 32gb ram in your machine, when starting tmm at least 2gb of ram has to be free, or Java won't even start up.

This is the only way we cannot get even a log file while starting tmm.
