### ISSUE TITLE
the tvdb - problem with special characters

### ISSUE THREAD

**Issue by balrok** [tinyMediaManager/tinyMediaManager#6]
Hello,

with the tv db:
scrapping for "Ah! My Goddess"
and "Wallace & Gromit" is not working because of their special characters.
Also äöüß-: are problematic.

I especially looked at the "force best match" feature but think this happens everywhere.

Thanks for your work! :)

**Comment by mlaggner** [comment]
i know that there is currently an issue with searching in tvdb: their api is not really tolerant. if you send the specials characters you may fall into http problems whereas sending them not causes nothing to be found :(
at the moment there is a new API fot thetvdb on the horizon, but we need to implement it at tmms side first.
all I can say now is to drink tea  and stay tuned ;)

**Comment by mlaggner** [comment]
just made some tests and with our new http engine these searches now work as intended
made some changes with tinyMediaManager/scraper-tvdb@b991d248c11759583b33c4f713f5d38e4a9daf5a
