### ISSUE TITLE
translations missing 

### ISSUE THREAD

**Issue by Gridluck** [tinyMediaManager/tinyMediaManager#61]
__What TMM version are you using?__
2.8.1

translations not reflected on uI for Russian
Certification format - movie > general

no translation for below in movies > images
_Fanart.tv provides a huge library of artwork for movies, TV shows and music. Does not provide movie poster_

no translation for below in movies > trailers
_Scraper for hd-trailers.net which is able to scrape trailers_

no translation for below in movies > subtitles
_A subtitle scraper for OpenSubtitles.org_
_password
username_

no translation for below in movies > Renamer
the _Renamer_ tab title is not translated
_Subtitle language style_ label is not translated

tv shows > scraper
not translated:
_AniDB stands for Anime DataBase. AniDB is a non-profit anime database that is open freely to the public._
_An open database for television fans. This scraper is able to scrape TV series metadata and artwork_
under images
_Fanart.tv provides a huge library of artwork for movies, TV shows and music. Does not provide movie poster_
_An open database for television fans. This scraper is able to scrape TV series metadata and artwork_

no translation for below in tv shows > subtitles
_A subtitle scraper for OpenSubtitles.org_
_password
username_

no translation for below in tv shows > Renamer
the _Renamer_ tab title is not translated
_Subtitle language style_ label is not translated

no translation exist for below in Help > About
english based "Thanks to" text and below
_The Creators of all libs I've used_
_Everyone who tested and provided feedback_

**Comment by mlaggner** [comment]
feel free to provide missing translations at https://www.transifex.com/projects/p/tinymediamanager/

**Comment by Gridluck** [comment]
100% of it is translated, the problem is in UI, the test is in english even though the UI anguage is russian..

**Comment by mlaggner** [comment]
Maybe RU wasn't fully translated when we released 2.8.1
