### ISSUE TITLE
Gui refresh on win10

### ISSUE THREAD

**Issue by kamil7732** [tinyMediaManager/tinyMediaManager#63]
Version: 2.8.2
Build: 2016-07-19 20:59
OS: Windows 10 10.0
JDK: 1.8.0_101 x86 Oracle Corporation

__What is the actual behaviour?__
gui refreshes itself quite weirdly
![tinymediamanager](https://cloud.githubusercontent.com/assets/725196/17107565/169df23e-5290-11e6-9572-1e5d9db9f150.png)
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/381915/tmm_logs.zip)

__What is the expected behaviour?__

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?
graphic card is amd..but it shouldn't be an issue

**Comment by mlaggner** [comment]
do you use any sort of remote desktop connection when using tmm?

**Comment by myron0815** [comment]
create a file "extra.txt" inside the TMM directory:
Add `-Dsun.java2d.nodraw=true`
Does this solve your problem?

**Comment by HotBlack77** [comment]
Following myron0815's advice worked for me.
