### ISSUE TITLE
Error on re-scraping movie data

### ISSUE THREAD

**Issue by littlejeem** [tinyMediaManager/tinyMediaManager#64]
Version: 2.8.2
Build: 2016-07-19 20:59
OS: Mac OS X 10.11.6
JDK: 1.8.0_101 x86_64 Oracle Corporation

after carrying out two movie re-scrapes I then get error messages appearing about Java exceptions, program prompted me to start a bug report and attach logs, please find attached
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/386892/tmm_logs.zip)

__What is the expected behaviour?__

the re-srape should complete without errors

__Steps to reproduce:__

run TMM on el-capitan set up to manage media on shared remote drive (777 permissions) load movie database to TMM and rescrape movies

__Additional__
Have you attached the logfile from the day it happened?

yes

**Comment by mlaggner** [comment]
this is a random hiccup - please try again.
I'll increase stability of multithreading soon
