### ISSUE TITLE
TV Show 'Premiered' and Episode Aired

### ISSUE THREAD

**Issue by Pipshrey** [tinyMediaManager/tinyMediaManager#65]
Version: 2.8.2
Build: 2016-07-19 20:59
OS: Mac OS X 10.11.6
JDK: 1.8.0_101 x86_64 Oracle Corporation

__What is the actual behaviour?__
1. If you leave the Premiered date as Jan, 1, 1970 (I had some concerts from this date), then the date is not written to .nfo file. Same situation for the 'Episode Aired' date.
2. At the top level of TV Shows, tiny mediamanager is not loading premiered, or genres information, despite them being in the .nfo file. For example, with 'Barenboim On Beethoven', those with ** (see code below) are not being displayed in tinymediamanager, despite the .nfo having that info:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- created on 2016-07-27 10:22:03 - tinyMediaManager 2.8.2 -->
<tvshow>
    <title>Barenboim On Beethoven</title>
    <sorttitle></sorttitle>
    <year>2005</year>
    <rating>0.0</rating>
    <votes>0</votes>
    **<plot>All 32 of the sonatas were performed live in June and July 2006 at the Staatsoper Unter den Linden in Berlin. The masterclasses took place in Chicago in January 2005, in front of a small audience.</plot>**
    **<mpaa>U</mpaa>**
    <episodeguide>
        <url></url>
    </episodeguide>
    <id></id>
    <imdbid></imdbid>
    **<genre>Concert</genre>
    <genre>Documentary</genre>
    <premiered>2005-01-01</premiered>
    <status>Ended</status>**
    <actor>
        **<name>Daniel Barenboim</name>**
        <role>unknown role</role>
        <thumb></thumb>
    </actor>
</tvshow>
```

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/389075/tmm_logs.zip)
![barenboim on beethoven](https://cloud.githubusercontent.com/assets/12278743/17223995/ef72c4dc-54f6-11e6-8fb5-5dcef819a9f1.jpg)

**Comment by myron0815** [comment]
2) is fixed, thx :)

1) yes, this is a known drawback.
Currently, our GUI field for displaying dates does not allow empty values.
We always have to set some (fake) date :|
We have choosen Date(0) which is the beginning of the UNIX timestamp... and do not write that into NFO.
Guess, we have to find a better approach... (not using a date field)
