### ISSUE TITLE
[enhancement] specify preference for default resolution of trailers in settings

### ISSUE THREAD

**Issue by Gridluck** [tinyMediaManager/tinyMediaManager#66]
Instead of looking through tens of available trailers, I'd like to have listed only trailers with preferred resolution.
for example for a movie [The Amazing Spider-Man 2], the list of trailers is enormous, but it would be great if I could just choose from 1080p trailers

thanks

**Comment by mlaggner** [comment]
filtering for a specified quality is dangerous - if the movie has no 1080p trailer, you won't see any alternative.
I may implement sorting of the table for easier finding of the desired trailer

**Comment by Gridluck** [comment]
you can leave current filtering that allows all trailers to be displayed as
default, but an option to specify quality would be great.. there's no point
to have trailers that are of lower quality than the movie files, and most
movies are 1080p here..

thanks

**Comment by mlaggner** [comment]
in the settings there is an option which allows you to specify the trailer quality which should be downloaded/selected as default.
Nevertheless a sorting for this table makes sense to me

**Comment by Gridluck** [comment]
sorting would help as well.. thanks

**Comment by mlaggner** [comment]
you will find the sorting in the version 2.8.4 (and in the nightly build tomorrow)
