### ISSUE TITLE
[enhancement]

### ISSUE THREAD

**Issue by wiggin77** [tinyMediaManager/tinyMediaManager#67]
Feature request:   allow sort by "new" in the list of Titles.  After updating data sources the new "icon" is great but hard to find in a long list.  Would like to sort so that the new ones are at the top.

__What TMM version are you using?__  2.8.2   paid
Your Operating system? -- linux

Cheers!

**Comment by mlaggner** [comment]
you can activate the filter to only show the new ones - click on the filter button and choose the filter for new movies

**Comment by wiggin77** [comment]
Perfect, thank you.
