### ISSUE TITLE
Program stops working when updating movie data sources.

### ISSUE THREAD

**Issue by Joan54** [tinyMediaManager/tinyMediaManager#68]
Version: 2.8.2
Build: 2016-07-19 20:59
OS: Windows 10 10.0
JDK: 1.8.0_91 amd64 Oracle Corporation

__What is the actual behaviour?__

When updating movie data sources, I get the message "Java(TM) platform SE binary has stopped working". This is not happening with version 2.8.1
Updating TV shows works OK.

__What is the expected behaviour?__

Updating all movie data sources.

__Steps to reproduce:__

Activate "Update data sources"

__Additional__
Have you attached the logfile from the day it happened?

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/410641/tmm_logs.zip)

**Comment by myron0815** [comment]
is already fixed in nightly & prerelease...
Will be in 2.8.3 in a few days....
