### ISSUE TITLE
How to build? -> Readme

### ISSUE THREAD

**Issue by puggan** [tinyMediaManager/tinyMediaManager#69]
__What TMM version are you using?__
commit bfdbde83a536e750888d7c09b17095ce84af5c9b

__release, pre-release, nightly, or directly from GitHub/branch?__
Github/master

__What is the actual behaviour?__
Looking in the Readme how to start it.

__What is the expected behaviour?__
No information on how to start it, so played around and so far i got:
`ant -f ant-package.xml package-app`
that gives the error:
".../tinyMediaManager/ant-package.xml:119: Warning: Could not find file .../tinyMediaManager/target/${tmmName}-${tmmVersion}.jar to copy."

__Steps to reproduce:__
- clone the project
- read the readme
- try to figure out how to build the project
- get lost and ask about it

__Additional__
OS: Gentoo

**Comment by mlaggner** [comment]
If you want the fully compiled/packaged version of tmm please download it from http://release.tinymediamanager.org
otherwise you need an IDE for running tmm (or build it yourself via maven)
