### ISSUE TITLE
Crashed when tried to retrieve info about a movie

### ISSUE THREAD

**Issue by jmauperi** [tinyMediaManager/tinyMediaManager#70]
Version: 2.8.3
Build: 2016-08-15 09:58
OS: Windows 10 10.0
JDK: 1.8.0_101 x86 Oracle Corporation

__What is the actual behaviour?__
When i right click on a movie, then select "Search and scrap selected movie", it finds it correctly but after having the right movie selected he tries to retrieve all info about it and crash. Only the movie.nfo is created but I'm not sure it's correct.

__What is the expected behaviour?__
The information about the movie should be retrieved correctly, files created (nfo and pictures)

__Steps to reproduce:__
Right click on a movie --> Search and scrap selected movie" --> "select the right movie" --> crash

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/419954/tmm_logs.zip)

__Additional__
Have you attached the logfile from the day it happened? Yes

**Comment by myron0815** [comment]
thx.
Fixed with https://github.com/tinyMediaManager/tinyMediaManager/commit/56cb6e609f37f15e431da8a8fe0a1d64df146fdf
expect a hotfix release in a few hours...

**Comment by jmauperi** [comment]
Ok perfect, waiting for the hotfix so.
See ya

**Comment by myron0815** [comment]
you also might want to try latest nightly/prerelease, to test if i really fixed your issue...

**Comment by jmauperi** [comment]
Ok I'll check with these builds and give you feedback.

**Comment by jmauperi** [comment]
The latest nightly release works fine and I didn't experience the issue.
I'll wait for the hotfix I think in order to have only one version installed.

Thank you !

**Comment by myron0815** [comment]
great, thanks.
Release published ;)
