### ISSUE TITLE
Fehler beim AUslesen der Medieninformationen : 0

### ISSUE THREAD

**Issue by Sweetbeat** [tinyMediaManager/tinyMediaManager#71]
Version: 2.8.3
Build: 2016-08-15 09:58
OS: Windows 10 10.0
JDK: 1.8.0_101 x86 Oracle Corporation

__What is the actual behaviour?__
I get the Error Message in the TMM Messages during the Collection of the film data on my NAS.
The original TMM Data were created on another Computer. 
I want to have TMM on my Notebook too so i install it there too.
During the Import the message appeared several times

__What is the expected behaviour?__

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/420119/tmm_logs.zip)

**Comment by myron0815** [comment]
thx.
Fixed with https://github.com/tinyMediaManager/tinyMediaManager/commit/56cb6e609f37f15e431da8a8fe0a1d64df146fdf
expect a hotfix release in a few hours...

**Comment by Sweetbeat** [comment]
thanks for help

yours sincerly

**Comment by myron0815** [comment]
you also might want to try latest nightly/prerelease, to test if i really fixed your issue...

**Comment by Sweetbeat** [comment]
Of Course... from where do i get it?

Best regards

**Comment by myron0815** [comment]
http://www.tinymediamanager.org/download/prerelease
just extract into a separate folder, if you want to keep your release version...

**Comment by myron0815** [comment]
release is out
