### ISSUE TITLE
No videos found

### ISSUE THREAD

**Issue by wojtulab** [tinyMediaManager/tinyMediaManager#72]
Version: 2.8.3.1
Build: 2016-08-16 15:05
OS: Windows 8.1 6.3
JDK: 1.8.0_101 amd64 Oracle Corporation

__What is the actual behaviour?__
Scanning without erros and without media files.

__What is the expected behaviour?__
found 8 - 10 media files in \\rpi\usb\seriale
It is Windows Share with full RW writes to Raspbbery device.

__Steps to reproduce:__

__Additional__
Have you attached the logfile from the day it happened?
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/421079/tmm_logs.zip)

![clipboard01](https://cloud.githubusercontent.com/assets/14801148/17712071/b649ad12-63f4-11e6-818a-8aac17299151.jpg)

**Comment by myron0815** [comment]
All series must be in their own folder.
So create separate dirs for each show like
\rpi\usb\seriale\Dexter
\rpi\usb\seriale\GameOfThrones
and move your files in...

**Comment by wojtulab** [comment]
Yes it is. I created new folder:
\rpi\usb\seriale\first
and moved all files into \first

There is no progress... why?

**Comment by wojtulab** [comment]
I created new directory in \rpi\usb\seriale\mynewdirecotry and then moved all files. There is no progress in refreshing tinyMediaManager

**Comment by wojtulab** [comment]
Thank you :) its working!
