### ISSUE TITLE
Rename/Cleanup of series or movies does not complete rename .idx files

### ISSUE THREAD

**Issue by CyberC123** [tinyMediaManager/tinyMediaManager#73]
Rename/Cleanup of series or movies does not complete rename .idx files

What TMM version are you using?
2.8.4-SNAPSHOT

release, pre-release, nightly, or directly from GitHub/branch?
Nightly

What is the actual behaviour?
Renaming/Cleanup of series/movies external subtitles (.sub and .idx files) does not "complete" rename the .idx files but rename the .sub files.

/******************
 Before:
Django Unchained Special Edition-eng.idx
Django Unchained Special Edition-eng.sub
Django Unchained Special Edition-forced.idx
Django Unchained Special Edition-forced.sub
Django Unchained Special Edition.idx
Django Unchained Special Edition.sub

After:
Django Unchained - Special Edition (2012)**.deu**.forced.sub
Django Unchained - Special Edition (2012)**.deu**.sub
Django Unchained - Special Edition (2012).eng.idx
Django Unchained - Special Edition (2012).eng.sub
**Django Unchained - Special Edition (2012).forced.idx
Django Unchained - Special Edition (2012).idx**
******************/

What is the expected behaviour?

.idx files and .sub files have the same name.

/******************
Django Unchained - Special Edition (2012).deu.forced.sub
Django Unchained - Special Edition (2012).deu.sub
Django Unchained - Special Edition (2012).eng.idx
Django Unchained - Special Edition (2012).eng.sub
Django Unchained - Special Edition (2012)**.deu**.forced.idx
Django Unchained - Special Edition (2012)**.deu**.idx
******************/

Steps to reproduce:

Add a series/movie with external subtitles (.sub and .idx)
Scrape and rename/cleanup

Additional:
Your Operating system? (Win7)

**Comment by myron0815** [comment]
just tried your example (with movies) - and it worked here.
We had this issue about 1-2 moths ago, so maybe your files are still wrong from this version?
Or did you completely remove this movie from DB and did a fresh update, with your example files?

**Comment by CyberC123** [comment]
Okay i downloaded a clean version of tmm and it worked:D
Sorry.
