### ISSUE TITLE
Since Update to tinyMediaManager 2.8.3.1, Background Fan Art Will Not Update

### ISSUE THREAD

**Issue by hahacharade** [tinyMediaManager/tinyMediaManager#74]
Version: 2.8.3.1
Build: 2016-08-16 15:05
OS: Windows 10 10.0
JDK: 1.8.0_101 x86 Oracle Corporation

__What is the actual behaviour?__

I can change the Movie Poster Fan Art fine, however the Background Fan Art does not change.  If I go in and select new background fan art, it seems to take it, but when I hit "OK" it keeps the original art in place. 

__What is the expected behaviour?__

As it worked on all other versions, Background Fan Art should change but for some reason it does not. 

__Steps to reproduce:__

[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/433836/tmm_logs.zip)

__Additional__
Have you attached the logfile from the day it happened?

Log file is attached.  I tried to reinstall the program and just copy my folders over.  It still has the same issue.  

I tried to change one and checked the error log.  A new error was recorded:

```
19:57:15.668 ERROR org.tinymediamanager.ui.dialogs.ImageChooserDialog - DownloadTask
retrofit.RetrofitError: thread interrupted
	at retrofit.RetrofitError.networkError(RetrofitError.java:27)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy33.getMovieImages(Unknown Source)
	at org.tinymediamanager.scraper.fanarttv.FanartTvMetadataProvider.getMovieArtwork(FanartTvMetadataProvider.java:129)
	at org.tinymediamanager.scraper.fanarttv.FanartTvMetadataProvider.getArtwork(FanartTvMetadataProvider.java:94)
	at org.tinymediamanager.ui.dialogs.ImageChooserDialog$DownloadTask.doInBackground(ImageChooserDialog.java:819)
	at org.tinymediamanager.ui.dialogs.ImageChooserDialog$DownloadTask.doInBackground(ImageChooserDialog.java:730)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.InterruptedIOException: thread interrupted
	at okio.Timeout.throwIfReached(Timeout.java:145)
	at okio.Okio$1.write(Okio.java:77)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
	at okhttp3.internal.http.Http1xStream.finishRequest(Http1xStream.java:159)
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:773)
	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613)
	at okhttp3.RealCall.getResponse(RealCall.java:244)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at com.jakewharton.retrofit.Ok3Client.execute(Ok3Client.java:41)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
	... 12 common frames omitted
```

**Comment by hahacharade** [comment]
Well.. After fidgeting with it for about an hour, I got it to work.  I completely ripped out TMM and used a fresh install to repoint to my sources.  Everything is working now, except my movie sets.  Movie sets won't scrape the pictures... only plots.  Everything else scrapes.  If I say "Rename and Regroup my Movies", it WILL scrape the Movie Sets.  However, I don't want to rename/regroup since I use the files for other things (Plex, etc.)  Any clue why the data won't apply to the movie sets?   Thanks again.

**Comment by myron0815** [comment]
Have no idea, why it worked with a fresh install.
(exception happens, when you choose already a picture while not all have been downloaded yet - ignore)

MovieSet seems not to work... we'll check that...
Thanks.

**Comment by mlaggner** [comment]
according to the config in your first post, you have disabled artwork scraping for movies:

```
<enableMovieSetArtworkFolder>false</enableMovieSetArtworkFolder>
<enableMovieSetArtworkMovieFolder>false</enableMovieSetArtworkMovieFolder>
```

It could be possible that tmm displays found (previous scraped) movie set artwork, but won't scrape new artwork due to this setting.

you have two options to scrape movie set artwork:

* the movie set artwork will be copied into each assigned movie (movieset-poster.jpg/movieset-fanart.jpg)
* the movie set artwork will be copied into a dedicated folder

please check your settings since everything works here..

**Comment by hahacharade** [comment]
Thanks for the replies. It doesn't matter if that setting is enabled or not in the Config XML - movie sets still will not scrape art.  I actually thought that setting related to having an individual folder created for each set of movieset art (it never did that before).  Regardless though, it doesn't change it  Movies and TV shows scrape, movie sets do not.

**Comment by hahacharade** [comment]
I appreciate the fact that movie sets kind of are wonky :)  I agree.  Is there a way to just remove the tab on the left?  I couldn't find a setting for that.

**Comment by hahacharade** [comment]
So here's what else I found.  In the interface it says no art found.  However if you click the icon that says no art found, it finds the art.  However, it will not apply anything you select to the interface for movie sets... Weird.

**Comment by hahacharade** [comment]
Tried it on a fresh system (my laptop) with everything fresh except my movies.db.  It still does it.  Definitely a bug I'm thinking.

**Comment by mlaggner** [comment]
I still did not find any issue in the code, but I've created a patch to enhance loading of artwork urls in the movie set section.
could you try the latest build from http://nightly.tinymediamanager.org with some test files?

btw, does restarting tmm show you the images?

**Comment by hahacharade** [comment]
Sure thing.  Just restarting the program did not show images (believe me I tried).
I just tried with the link you sent me -- images do show up now on movie sets! -- however the red "X" is still present under the picture column on the left side (not sure if that's normal).  Also, Extra Artwork still comes up as no-logo found.  I'll attach some screenshots.  I also attached one of how it looks in the non-test interface. Thanks! 

![nightly build test - movie set](https://cloud.githubusercontent.com/assets/21209197/17933325/450e19c2-69d9-11e6-8fa1-c0573ebe2c22.png)
![nightly build test 2 - movie set](https://cloud.githubusercontent.com/assets/21209197/17933326/451bc888-69d9-11e6-9403-d1fadc4080ec.png)
![regular test standard 2 8 3 1 - no art will apply](https://cloud.githubusercontent.com/assets/21209197/17933327/452f15b4-69d9-11e6-9783-01c391823076.png)

**Comment by hahacharade** [comment]
Sure thing. Just restarting the program did not show images (believe me I tried).
I just tried with the link you sent me -- images do show up now on movie sets! -- however the red "X" is still present under the picture column on the left side (not sure if that's normal). Also, Extra Artwork still comes up as no-logo found. I'll attach some screenshots. I also attached one of how it looks in the non-test interface. Thanks! 

![nightly build test - movie set](https://cloud.githubusercontent.com/assets/21209197/17933392/8d042cee-69d9-11e6-82e2-9ebd142c2e21.png)
![nightly build test 2 - movie set](https://cloud.githubusercontent.com/assets/21209197/17933394/8d3f7c90-69d9-11e6-9b11-4332c3116276.png)
![regular test standard 2 8 3 1 - no art will apply](https://cloud.githubusercontent.com/assets/21209197/17933393/8d3e3bb4-69d9-11e6-8fe4-1349dee5c68f.png)

**Comment by mlaggner** [comment]
this leads again to my first idea: tmm has no place to store the artwork for you (see the config parameters above). 
With the latest build tmm will show poster and fanart loaded via URLs if no local artwork has been found (I did not include this workaround for logo, banner and clearart and thus no one is visible for you).
Please try to activate _at least_ the setting `store movie set in each movie folder` and rescrape the movie set. 
Just to make sure everything worked, check the movie set folders (I assume you have a one movie per folder setup) for two new files called `movieset-poster.jpg` and `movieset-fanart.jpg`

**Comment by hahacharade** [comment]
Perhaps I'm not enabling that setting properly.  If I go into the Config XML file and change that tag to enable, it simply creates a folder in the TMM directory, for Movie sets. It stores art there, but does not populate that art to the interface.  

Also not sure how to scrape a movie set, since there's no scrape option when you naviage to the movie set tab.

**Comment by hahacharade** [comment]
I have all files in one folder.  I don't have a movie per folder.  If I do the "Rename and Cleanup My Movies" option, it puts the movies in one folder and populates the movie set as well, but that renames my SRTs, etc. and I can't have that due to Plex and other things which use that directory - It worked automatically in the previous version, so not sure why it wouldn't now.  Let me fiddle with it, but your URL update to the new build sounds promising.

**Comment by hahacharade** [comment]
Is there a setting in the GUI where you can change movie sets?  When I go into the XML it shows two tags for that folder.  If I change both to true, and restart the program, it does nothing, I go back in the file, and one is changed to false again...  Here are the settings...

<detectMovieMultiDir>false</detectMovieMultiDir>
        <enableMovieSetArtworkFolder>false</enableMovieSetArtworkFolder>
        <enableMovieSetArtworkMovieFolder>true</enableMovieSetArtworkMovieFolder>
        <imageBanner>true</imageBanner>
        <imageClearart>true</imageClearart>
        <imageColumnVisible>true</imageColumnVisible>
        <imageDiscart>true</imageDiscart>
        <imageExtraFanart>false</imageExtraFanart>
        <imageExtraFanartCount>5</imageExtraFanartCount>
        <imageExtraThumbs>false</imageExtraThumbs>
        <imageExtraThumbsCount>5</imageExtraThumbsCount>
        <imageExtraThumbsResize>true</imageExtraThumbsResize>
        <imageExtraThumbsSize>300</imageExtraThumbsSize>
        <imageFanartSize>LARGE</imageFanartSize>

**Comment by hahacharade** [comment]
Can you check these settings?  When I change the option for movieset artwork to true, true (there are two tags for it) it doesn't do anything and changes it to true/false again.  Is there a way to set it in the GUI?  

[config.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/437121/config.txt)

**Comment by myron0815** [comment]
Just to clear things up.
A MovieSet is just a name inside the movie NFO.
Same "names" are grouped together inside Kodi as a virtual "set"
There is *no* other information stored anywhere (no description, no image urls, nothing) :|

When it comes to images, there is only the possibility, to rename the poster to "movieset-poster" (and fanart respective)
Since you have all movies in one folder, this will not work (always overwriting them)
And i'm even not sure, if this is a Kodi standard feature, or only works by some plugins like http://forum.kodi.tv/showthread.php?tid=153502

What might work, is, to check the option for a dedicated ArtworkFolder.
Have to check if this still works; we reworked the image cache thing a bit <- this might be a/the bug not showing inside TMM


Just curious:
When putting one movie per folder (and renaming the subs) - what exactly does not work in Plex?
Plex should be pretty aware of the (same?) naming as Kodi?

**Comment by hahacharade** [comment]
To be honest - I didn't test Plex after I did a few movies this way by mistake.  I worked to rename them and restore them back. Subs for movies in plex with the sub .en.srt (for example) for english.  TMM was changing a lot of the name, and with the individual folder grouping - just didn't work for me.  I also browse these other ways, and having every movie have its own folder was a pain. 

The fact that the image cache was reworked might be what caused this, because I've been through about 10 updates at least to TMM, and have never had these problems.  Everything worked great.  When mlaggner made his URL update, the pics started working (for the ones he set that way).  So I don't think its how I have the folder setup.  It stores all the other PNGs, JPGs, and NFOs for the individual movies fine. It just won't do anything for movie sets... so here I am.   :)  Lol.

**Comment by hahacharade** [comment]
I've been all through the options and don't see anything for dedicated artwork folder (I remember seeing it before).  All my art, movies, nfos, everything are in one folder together.  M:/Films

**Comment by mlaggner** [comment]
Th option for the dedicated (movie set) artwork folder is in "Movies" and the tab "Images".
You may scroll down a bit

**Comment by hahacharade** [comment]
Ha, all I had to do is point the dedicated folder to the folder with the rest of my movies and it worked.  Problem solved.  Thanks a lot.
