### ISSUE TITLE
Feature request: starting movie file directly in search movie window

### ISSUE THREAD

**Issue by CyberC123** [tinyMediaManager/tinyMediaManager#75]
Hey,

can you please add a option to start the movie file directly in the search movie window?
Some movies for example have many search results with the same name.
To determine the correct record is to view the movie.

Sample:
![Search movie window](https://cloud.githubusercontent.com/assets/20404622/17938938/71f84558-6a28-11e6-9428-60243ab3ea6b.png)

Thanks

**Comment by myron0815** [comment]
yes, might be a good idea.
Also had often the need to play the movie to the ending screen, to identify by artist :p

**Comment by CyberC123** [comment]
If it's a parted movie, it's necessary to play all parts or only the last part for the ending screen.

**Comment by mlaggner** [comment]
I've included a play button with the commit 0faa0d546bace7bde8c7be17f2d801f09cfafe87 
This button starts the movie file (or first movie file if there are multiple ones). If you have a good media player it will detect that this file is a multi file movie end let you jump to the second one - so there is no need for us to do that job
