### ISSUE TITLE
Scraper issue

### ISSUE THREAD

**Issue by pigers** [tinyMediaManager/tinyMediaManager#76]
__What TMM version are you using?__
2.8.3.1 @ Windows

__release, pre-release, nightly, or directly from GitHub/branch?__
release 

__What is the actual behaviour?__
TMM is not parsing dirs containing dot or exclamation mark in name 

__What is the expected behaviour?__
Parse them or ask what to do 

__Steps to reproduce:__
mkdir "Ah! My Goddess (2005)"; create dir with such name 
echo 123 > Ah! My Goddess (2005) - 0x01.mkv; create some file with ! in name , just for test
add it to series scanner ;
press scan and find no results ;
after rename of dir without ! it works fine;

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
Windows 

Unable to do so ... in FireFox it says we do not support ZIP file (message says otherwise ... )
Grab logs from http://dev.seph.pl/tmm.zip

**Comment by cublikefoot** [comment]
I'm having a similar issue. I cannot get TMM to return a search result from TVDB when I input "Tsukiuta". I believe this is due to the full title having a period in it. The full title on TVDB is "Tsukiuta. The Animation". https://thetvdb.com/?tab=series&id=313534&lid=7

Searching using terms "Tsukiuta" and "The Animation" does not result in Tsukiuta showing up anywhere.

**Comment by myron0815** [comment]
@cublikefoot 
this kinda works for me;
Searching "Tsukiuta" returns the correct anime show here.
Searching with "the animation" returns nothing correct.

@pigers 
i'm not sure if i can reproduce your issue correctly :|

- Created folder, 
- created dummy file
- click update - show&episode displayed in gui correctly
- rightclick scrape - show found (even with "!")
- click ok - everything scraped correctly?

disn't see anything in log yet... hmm...

**Comment by pigers** [comment]
Shoot me ! After restarting tmm it worked for me too - i do guess creating empty media files confused app.

Thanks for checking it !
