### ISSUE TITLE
Refreshing a single tv show causes media info for entire library to update

### ISSUE THREAD

**Issue by gmerrall** [tinyMediaManager/tinyMediaManager#77]
Version: 2.8.3.1
Build: 2016-08-16 15:05
OS: Mac OS X 10.11.6
JDK: 1.8.0_91 x86_64 Oracle Corporation

Refreshing a single TV show forces a "getting Mediainfo" update for the entire repository. This may be due to the full repository of tv shows missing mediainfo.  

From a quick look at the source, the current behaviour when you select "update selected tv show" is to refresh the info for the show, but then run the "getting mediainfo" process which runs for the entire collection. See https://github.com/tinyMediaManager/tinyMediaManager/blob/master/src/main/java/org/tinymediamanager/core/tvshow/tasks/TvShowUpdateDatasourceTask2.java#L206 where it iterates over all tv shows.

Ideally, refreshing a single TV should only update mediainfo for the single tv show regardless of the status of the mediainfo data.

**Comment by mlaggner** [comment]
thanks for the hint. will be in the next version
