### ISSUE TITLE
Kodi can't import .nfo files for Ash vs. Evil Dead

### ISSUE THREAD

**Issue by dhwalker** [tinyMediaManager/tinyMediaManager#78]
__What TMM version are you using?__
2.8.3.1

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
tmm creates tvshow.nfo and .nfo files for all season 1 episodes, except for episode 1.  Kodi reports "WARNING: No information found for item '/DWMedia/DWMyth/VideosMetadata/TV/Ash_vs_Evil_Dead/', it won't be added to the library." when I update its library.

(Normally, I'd suspect Kodi, if it weren't that the metadata for episode 1 is not created.)

__What is the expected behaviour?__
.nfo files are created for all episodes, and Kodi can import them.

__Steps to reproduce:__
Update sources, scrape metadata, and write the .nfo files.  I've attached an ls -l of the source directory with the generated .nfo files.
[Ash-source.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/453579/Ash-source.txt)

__Additional__
Have you attached the Logfile from the day it happened?  
[tmm_logs.zip](https://github.com/tinyMediaManager/tinyMediaManager/files/453581/tmm_logs.zip)

Your Operating system? (win/mac/linux? version?)
Linux - openSUSE Leap 42.1

**Comment by dhwalker** [comment]
I've done some more investigation...  Referring to Ash-source.txt, you can see that Ash_vs_Evil_Dead_s1e1.nfo is not created.  What's interesting is that the <episodedetails> for episode 1 has been written into Ash_vs_Evil_Dead_s1e10, along with the <episodedetails> for episode 10.  Also, when looking at the Media Files tab for episode 1, you see both Ash_vs_Evil_Dead_s1e1.iso and Ash_vs_Evil_Dead_s1e10.iso listed.  All other episodes show only their episode's .iso file.

You'll note that I use symbolic links to handle .iso files that hold multiple episodes.  Perhaps this has something to do with this?

**Comment by mlaggner** [comment]
when did you import these episodes into the database? IIRC we fixed some episode detection bugs with the last release - maybe you stumbled across some of this bugs (detecting s1e1 and s1e10 as multi file episodes..)
could you try to remove these episodes from tmm and let tmm re-import them (to be sure everything works as expected, please also remove the NFO files)

**Comment by dhwalker** [comment]
Actually, I removed the episodes and re-imported them just before my post last night.  I'm currently on 2.8.3.1; I think that's the version I was on when I first ran into this issue.

**Comment by mlaggner** [comment]
did you delete the nfo too? otherwise the season/epsiode number is read from the nfo rather than from the file name

**Comment by dhwalker** [comment]
I just deleted and reloaded everything again to make sure.  Sorry, the result was the same.

**Comment by mlaggner** [comment]
Finally I was able to reproduce the issue - a fix will follow soon

**Comment by mlaggner** [comment]
this should be fixed in the next nightly/release

**Comment by dhwalker** [comment]
Thanks, Manuel!
