### ISSUE TITLE
Feature request: reduce long pathnames in "Episodes" tab

### ISSUE THREAD

**Issue by CyberC123** [tinyMediaManager/tinyMediaManager#81]
The column "Filename" in "Episodes" tab in "Edit selected TV show(s)/episodes(s)" window is confusing with long path and file names.

Can you reduce the patnames to the first different in the name, please:

D:\Example\Series 1\Season 1
D:\Example\Series 1\Season 2
to 
...\Season 1
...\Season 2

The full pathname or only the cropped part can you add as a mouse over popup.

Example:
![5](https://cloud.githubusercontent.com/assets/20404622/18814486/ec9269ce-8314-11e6-8cce-2793991e5ccc.png)

**Comment by mlaggner** [comment]
have included that into the V3 branch
