### ISSUE TITLE
Feature request: context menu in episodes overview

### ISSUE THREAD

**Issue by CyberC123** [tinyMediaManager/tinyMediaManager#82]
Hey,

Can you please add a context menu in "Episodes" tab in "Edit selected TV show(s)/episodes(s)" window like the context menu in the main window?
This menu is for one or more episodes.
The context menu could contain the same options such as in the example.

Thanks

Example:
![2](https://cloud.githubusercontent.com/assets/20404622/18814526/ffab7626-8315-11e6-9996-4353a4ee0fe6.png)

**Comment by mlaggner** [comment]
This window (editor dialog) is a special "action" inside tmm. Adding other actions inside this action could lead to data/program inconsistencies. 

You have the whole bunch of episodes in the main-tree along with all actions where everything works as expected.

won't include that feature
