### ISSUE TITLE
Parted episodes will not correctly renamed

### ISSUE THREAD

**Issue by CyberC123** [tinyMediaManager/tinyMediaManager#84]
**What TMM version are you using?**
2.8.4-SNAPSHOT

**release, pre-release, nightly, or directly from GitHub/branch?**
nightly

**What is the actual behaviour?**
I have a parted episode like:
Dr. House - S06E01 - part 1.mkv
Dr. House - S06E01 - part 2.mkv

When i rename/cleanup then the first part is renamed to
Dr. House - S06E01 - Einer flog in das Kuckucksnest.mkv
the second part keeps because "Dr. House - S06E01 - Einer flog in das Kuckucksnest.mkv" existits
Dr. House - S06E01 - part 2.mkv

the same with:
Dr. House - S06E01a.mkv
Dr. House - S06E01b.mkv
and
Dr. House - S06E01.1.mkv
Dr. House - S06E01.2.mkv

**What is the expected behaviour?**
Dr. House - S06E01 - Einer flog in das Kuckucksnest - part 1.mkv
Dr. House - S06E01 - Einer flog in das Kuckucksnest - part 2.mkv

**Additional**
http://kodi.wiki/view/TV_Shows_(Video_Library)#Split-episode

**Comment by myron0815** [comment]
First we have to differentiate between splitted episodes (which we are not able to detect correctly) and some parted ones.
The parted ones already work for movies, but has not yet been functional for episodes...

**Comment by mlaggner** [comment]
will be available at version 3
