### ISSUE TITLE
Feature request: File name "title" as search string in "search episode" window

### ISSUE THREAD

**Issue by CyberC123** [tinyMediaManager/tinyMediaManager#85]
Hey,

today my fifth issue, i hope i don't nerve;)

I have good named files (title) but the false episodes numbering.
So i writing the correct title in the search field, choose the correct title and click OK. For a couple of files okay but there are fifty alone in this season:(

Would it be possible that when i click on "search episode" that the part of file name with the title already entered in the search field and the first possible result is marked?

The search field is marked, too. So i can type another keywords when the given result are not correctly.

Example:
![8](https://cloud.githubusercontent.com/assets/20404622/18815705/5536d06e-8338-11e6-94b9-22b554347e97.png)

Thanks

**Comment by mlaggner** [comment]
well this could be a dangerous enhancement.
In this list we filter the output rather than positioning on the right one. If we put a title in the search field and find nothing, the use might get the feeling that nothing has been found at all (otherwise he would see all results)..

Maybe I could find the right entry, move it to top and select it?

**Comment by mlaggner** [comment]
added a pre-selection in the episode chooser.
Please check the behavior in the latest nightly if that suits your need

**Comment by CyberC123** [comment]
Not quite.
The pre-selection works but it selects the episode based on the S01E01 in the filename.
The pre-selection should select based on the title in the filename. Because the title in the filename are correct but the S01E01 in the filename isn't correct.

My file:
"Gummibärenbande - S05E02 - Der Weg nach Uralia.avi" the content is the episode "Der Weg nach Ursalia"

S05E02 "Doktor Dexters Zauberelixier" is selected by the pre-selection.

But at thetvdb.com is "Der Weg nach Ursalia"=S05E03

The pre-selection should select the S05E03 "Der Weg nach Ursalia

**Comment by mlaggner** [comment]
The preselection is based on the title of the episode. In your case the title still contains S05E02 - we may have to tweak our title detection more, that the season and episode number get stripped out.

btw: I've tried your example and nothing got preselected (the first entry in the list still was selected by default)

**Comment by CyberC123** [comment]
I have tested again with the file
"Ein Duke kommt selten allein/Staffel 01/Ein Duke kommt selten allein - S01E04 - Mary Kayes Baby.avi"

Still select "S01E04 - Die Nobelkarosse" instead of "S01E03 - Mary Kayes Baby"

**Comment by CyberC123** [comment]
I got this error if i type before the list in the episode chooser is loaded.

[Fehler.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/517722/Fehler.txt)

**Comment by mlaggner** [comment]
should work in the next build

**Comment by CyberC123** [comment]
No error.
But but is still selcetd by "S01E04"

**Comment by mlaggner** [comment]
I've just created the files as in your example with "Ein Duke kommt selten allein" and saw that the episode name detection was still not good enough.
But nevertheless I did not get tmm to preselect S04E04 in the episode chooser dialog? with the latest build tmm should preselect S01E03 with your example

**Comment by CyberC123** [comment]
It's strange :-D

1. Okay i download a clean tmm verison from 
 * http://nightly.tinymediamanager.org/dist/tmm_2.8.4-SNAPSHOT_c346e33_win.zip
2. Start tinyMediaManager.exe
 * Default options except TV Show Dir: G:\test
 * Content: G:\test\Ein Duke kommt selten allein\Staffel 01\Ein Duke kommt selten allein - S01E04 - Mary Kayes Baby.avi

3. TV shows->Update data sources

4. Search & scrape selected TV shows
 * Scraper: thetvdb.com
 * Language: Deutsch
 * Searchfield: Ein Duke kommt selten allein
 * OK

5. Select episode "4. Die Nobelkarosse"->Edit selected TV shows/episodes.
 * Search episode.
  * And preselect is Season 1 Episode 4 Title Die Nobelkarosse.
   * Here should be Season 1 Episode 3 Title Mary Kayes Baby:(

What am I doing wrong?

Version: 2.8.4-SNAPSHOT - NIGHTLY
Build date: 2016-10-10 07:13

My Log:[tmm.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/519818/tmm.txt)

**Comment by mlaggner** [comment]
now I understand your problem ;)
a) we parse your file name and assign it to the episodes title (along with the detected S/E) at _update data sources_ (only if no NFO has been found!)
b) when you do a scrape, you assign a new title (from tvdb) to your episode according to the S/E found 
c) if you do a _search episode_ now, the title from tvdb (which is assigned to the episode title now) is used rather than the detected title from the _update data sources_

Unless your problem is rather _unique_, I think I can put a fallback for the filename there without creating a drawback for other users

**Comment by CyberC123** [comment]
It work fine, the most of titles are correct pre-selected.:)

For the pre-selection it would be good if the title selction is case-insensitive.

Example titles they are not pre-selected:
Die Schlümpfe - S01E26 - Die Schlümpfe sehen rot.avi
Die Schlümpfe - S01E12 - Die rosa-schlumpfige Brille.avi
Die Schlümpfe - S01E29 - Hefty, der Riese.avi
Die Schlümpfe - S01E30 - Handy, der Wettermacher.avi
Die Schlümpfe - S01E33 - Der schön-schreckliche Kristall.avi
Die Schlümpfe - S01E35 - Die Schlümpfe und der Geldbaum.avi
Die Schlümpfe - S02E03 - Torti der Fettsack.avi
Die Schlümpfe - S02E05 - Verschwende nicht schlumpfe nicht.avi
Die Schlümpfe - S02E06 - Schnuffi der Wetterfrosch.avi
Die Schlümpfe - S02E23 - Die Zauber Rolle.avi

**Comment by CyberC123** [comment]
No pre-select if comma, minus or question mark in the thetvdb.com title 
and if in the file title a space between two words but in the thetvdb.com not isn't pre-select, too.

Examples:
Die Schlümpfe - S03E28 - Sag deine Meinung Farmi.avi
Die Schlümpfe - S03E02 - April Schlumpftag.avi
Die Schlümpfe - S04E05 - Die Schlumpfine-Sonate.avi
Die Schlümpfe - S03E40 - Baby Schlumpf wird vermisst.avi
Pokémon - S08E10 - Hat Max Recht.mkv

**Comment by mlaggner** [comment]
I've just added one more cleanup before checking. 
But this cannot cover all your examples: (Baby Schlumpf vs Babyschlumpf). 

I won't add more logic here because this is a real special case now and you are still able to manually select the right episode!
