### ISSUE TITLE
Drop down menu in "scrape episode metadata" window has no effect

### ISSUE THREAD

**Issue by CyberC123** [tinyMediaManager/tinyMediaManager#86]
What TMM version are you using?
 2.8.4-SNAPSHOT

release, pre-release, nightly, or directly from GitHub/branch?
 nightly

__What is the actual behaviour?__
The drop down menu in "scrape episode metadata" window has no effect to the scrape and search episode buttons.

__What is the expected behaviour?__
The drop down menu has a effect...

__Steps to reproduce:__
- open the window with a episode has different content by thetvdb.com and themoviedb.org or a series
- click the scrape/search episode button

__Additional__
Kampfstern Galactica 1978 has different content and different episode count
tmdb	501
tvdb	71173
imdb	tt0076984

**Comment by mlaggner** [comment]
this issue should also be fixed in the latest nightly
