### ISSUE TITLE
"The" Misplaced 

### ISSUE THREAD

**Issue by Adyel** [tinyMediaManager/tinyMediaManager#87]
__What TMM version are you using?__
Version : 2.8.3.1

__release, pre-release, nightly, or directly from GitHub/branch?__
Release from official website

__What is the actual behaviour?__
"The" is showing end of the title. IE: Dark Knight Rises, The

__What is the expected behaviour?__
It should look like The Dark Knight Rises

__Additional__
Manjaro Linux  based on Arch

**Comment by mlaggner** [comment]
please have a look at the wiki: https://github.com/tinyMediaManager/tinyMediaManager/wiki/General-Settings#file-types - Title sorting

**Comment by Adyel** [comment]
Ok, But why this is even a thing ? What's the use . . . :|

**Comment by myron0815** [comment]
to sort the movies more alphabetically correct...
I do not want so scroll through hundrets of "The ..." names to find a movie.

If you do not want that feature, just remove all entries from that list in settings....
