### ISSUE TITLE
No forced subs found in series/episodes

### ISSUE THREAD

**Issue by CyberC123** [tinyMediaManager/tinyMediaManager#88]
__What TMM version are you using?__
2.8.4-SNAPSHOT

__release, pre-release, nightly, or directly from GitHub/branch?__
nightly

__What is the actual behaviour?__
I have series with external forced and full subs in a directory:
star.wars.rebels.s01e08.german.dvdrip.x264.mkv
star.wars.rebels.s01e08.german.dvdrip.x264-forced.idx
star.wars.rebels.s01e08.german.dvdrip.x264-forced.sub
star.wars.rebels.s01e08.german.dvdrip.x264.idx
star.wars.rebels.s01e08.german.dvdrip.x264.sub

When i update data source only the full subs added to the media files.
By rename/cleanup all files renamed exclude the forced subs.

__What is the expected behaviour?__
Forced subs found and renamed with the other files.

__Steps to reproduce:__
-Make a directory with the example files and update data source
-Rename/clenup
-ready

__Additional__
Have you attached the Logfile from the day it happened?
[tmm.txt](https://github.com/tinyMediaManager/tinyMediaManager/files/501299/tmm.txt)

Your Operating system? (win/mac/linux? version?)
Arch Linux

**Comment by myron0815** [comment]
You're right.
We made a change with 8c9033af3b8fc67d3d20e238fc7c1e70832546f2 (to fix another detection issue), but this breaks the detection for forced subtitles now.
Have to check how we could integrate this without getting into trouble now :)

**Comment by mlaggner** [comment]
I just made a fix for that. 
Could you pull the changes and try again?

**Comment by CyberC123** [comment]
It works. :)
