### ISSUE TITLE
[REQ] Auto-rename for TV Episodes

### ISSUE THREAD

**Issue by Vallimar** [tinyMediaManager/tinyMediaManager#89]
Awhile back an option was added to auto-rename movies after scraping. (https://github.com/tinyMediaManager/tinyMediaManager/commit/78b14a30353a0557fa7744d74884ef57ea0048cb)
Can the same thing be added for TV episodes?

**Comment by mlaggner** [comment]
added to v3 with https://github.com/tinyMediaManager/tinyMediaManager/commit/a8cbf2e42f284f9ddf867dd734d431c0079dc785
