### ISSUE TITLE
Only the first studio is exported to Kodi NFO files

### ISSUE THREAD

**Issue by majutsushi** [tinyMediaManager/tinyMediaManager#9]
I recently tried filtering movies by studio in Kodi and was surprised to see that several movies were missing from the result. After investigation it turned out that TMM had only exported the first studio to the NFO file, which depending on the order in which they were defined led to rather random results. Would it be possible to have the exporter export all of the studios so that use cases like these work as expected? Thanks!

**Comment by mlaggner** [comment]
We had that at the beginning, but with commit debe4dd2ed80b173eb6a943c7d24253b2d29eef9 we've changed it to the first studio. tbh I cannot remember why (I suppose this was a hint by some users).

Does Kodi support different studio parsing (e.g. displaying all studio logos, when the tag contains more than one)?

**Comment by majutsushi** [comment]
Kodi certainly supports parsing multiple studios in general, for example studio filtering works properly when a movie has multiple ones defined. I don't know anything about studio logos since the default theme doesn't show any logos, but I would argue that if that doesn't work then that is something that should be fixed in Kodi rather than worked around in TMM. Especially since I would consider filtering functionality (and just generally having the correct information available) to be more important than logos.

**Comment by majutsushi** [comment]
Thanks!
