### ISSUE TITLE
Movie title list will not scroll until mouse button press

### ISSUE THREAD

**Issue by neopeasant** [tinyMediaManager/tinyMediaManager#90]
**What TMM version are you using?**
2.8.3.1

**release, pre-release, nightly, or directly from GitHub/branch?**
release

**What is the actual behaviour?**

when tmm starts
the first movie title is highlighted
a down-arrow keypress does not scroll down 

Scrolling behaves as expected 
once a mouse button is pressed
on the title list
**What is the expected behaviour?**
Scrolling should occur with an arrow key press

**Steps to reproduce:**
- first
  start tmm
  press down arrow key
  No scrolling occurs
- second
  click the highlighted title or other title
  down arrow key scrolls as expected
- ...

**Additional**
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
linux Fedora 24
mac OSX El Capitan

**Comment by mlaggner** [comment]
have included that into the V3 branch
