### ISSUE TITLE
Feature request: Random movie selection when tmm starts

### ISSUE THREAD

**Issue by neopeasant** [tinyMediaManager/tinyMediaManager#91]
__What TMM version are you using?__
2.8.3.1

__release, pre-release, nightly, or directly from GitHub/branch?__
release

__What is the actual behaviour?__
The first movie title is selected and displayed 
when tmm starts

__What is the expected behaviour?__
Provide an option to randomly select/display a movie title
upon tmm startup
optionally within a range of values
e.g., ratings between 6-8,  years 1965-2012, HD only

__Steps to reproduce:__
- first
- seco
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)

**Comment by mlaggner** [comment]
I am sorry, tinyMediaManager is a media manager and not a media center where you could add such a feature.
 Won't include that

**Comment by neopeasant** [comment]
Manual,

Thank you for your consideration

I understand

tMM is a wonderful media manager
we are using it here on windows, osx and linux
as a media center because kodi feels awkward, and intrusive (full screen)

Thank you for your efforts,
