### ISSUE TITLE
Poster Download Options

### ISSUE THREAD

**Issue by Cyclops1000** [tinyMediaManager/tinyMediaManager#92]
Version: 2.8.3.1
Build: 2016-08-16 15:05
OS: Windows 7 6.1
JDK: 1.8.0_31 x86 Oracle Corporation

Hello, if you config more the one poster download . For example <dynamic>.ext and folder.ext.
Only one poster file will be created. In this casemoviename.jpg.
I think all the files should be created.

__Steps to reproduce:__
Settings / Movie / Image / Poster Naming Conventions
Scrapping

**Comment by mlaggner** [comment]
please check if you have more than one movie in the movie folder.
For such multi movie folders, there is a drawback that you can only have moviename.jpg as artwork

**Comment by WolfganP** [comment]
Interesting. I observed that in a multimovies' folder I can't force the poster naming convention. Even if I choose filename.ext the pic ends up being named filename-poster.ext
It doesn't happen in the case of TV shows, so I made myself a note to investigate in the logs (but haven't had time to focus yet)
Is that a known issue as well?

**Comment by myron0815** [comment]
This got changed a few weeks ago... and should work as you described in next version :)
