### ISSUE TITLE
Folder-Renaming-Problem

### ISSUE THREAD

**Issue by Cyclops1000** [tinyMediaManager/tinyMediaManager#93]
Version: 2.8.3.1
Build: 2016-08-16 15:05
OS: Windows 7 6.1
JDK: 1.8.0_31 x86 Oracle Corporation

If a movie is in as subfolder like: movies\adventure\moviename
And you use the rename funktion the new folder is movies\moviename 2016.
The sub-folder is removed.

__What is the expected behaviour?__
movies\adventure\moviename 2015
__Steps to reproduce:__
Store a movie in subfolders of your root-movie-folder.
Use the rename function with preview.

**Comment by myron0815** [comment]
This is intended.
We walk the complete directory unlimited folders deep, to find movies :)

If you want to keep an additional Subfolder, you have to specify it in the renamer.
Like $G for genre, or $1 for the first character, etc...
