### ISSUE TITLE
Problem with TVshows convention naming - dubled titles in episode

### ISSUE THREAD

**Issue by wojtulab** [tinyMediaManager/tinyMediaManager#94]
**What TMM version are you using?**
the newest on linux and 2.8.3.1 @ win

**What is the actual behaviour?**
wrong convention naming
0108_01360-_Ghosts_-_0108_01360-_Ghosts_-_S01E08_Ghosts_2009_640x360.mp4

**What is the expected behaviour?**
S01E08_Ghosts.mp4

**Additional**
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?)
win and linx - the same situation

![image](https://cloud.githubusercontent.com/assets/14801148/19652660/e6560fd4-9a11-11e6-9930-71ceacb0c3c6.png)

![image](https://cloud.githubusercontent.com/assets/14801148/19652668/eebf10e4-9a11-11e6-812c-6c21e948c624.png)

**Comment by myron0815** [comment]
This file has too many numbers in it - it gets wrongly detected as episode 8 + 360
You might need to correct that manually in GUI (edit show, remove this one episode)
