### ISSUE TITLE
Image URLs for movies with # in their path don't get encoded correctly for HTML export

### ISSUE THREAD

**Issue by Garfonso** [tinyMediaManager/tinyMediaManager#95]
**What TMM version are you using?**
Nightly, 2.8.4, 2016-10-20 23:04

**release, pre-release, nightly, or directly from GitHub/branch?**
Nightly

**What is the actual behaviour?**
HTML Export for movie with #  in name (example: Lucky # Slevin) shows no thumbnail in list or image on detail page.

**What is the expected behaviour?**
# should be escaped as %23 in URL, so that images can be displayed.

**Steps to reproduce:**
- first: add movie with # in the name.
- second: export html with some template that creates images like this: 
  `<img src="images/${movie(../nopicture.gif);copyArtwork(type=POSTER, thumb=true, width=180, destination=images)}" />`
- third: Open export in browser, see that it won't load the thumbnail
- fourth: copy image URL of thumbnail, replace # by %23 and see that the image is there.

Should be easy to fix, as I see that space already gets encoded as %20. Issue with # is that it has a meaning in URLs and really confuses the browser. This might be an issue with default URL encoding methods, too. I don't know what you are using, but in JavaScript this is the differences between encodeURI (won't encode #, because it thinks it is part of the URL) and encodeURIComponent (which would encode # but also / and everything else).

Edit: had to escape # for Github, too. :)

**Comment by mlaggner** [comment]
well, the export engine is not HTML only - thus a "general" escape of # is not good (you don't want Lucky %23 Slevin in an CSV or Excel).
I may enhance the copyArtwork renderer by a escape parameter for that issue
