### ISSUE TITLE
Problem with sets in v2.9

### ISSUE THREAD

**Issue by overpaul** [tinyMediaManager/tinyMediaManager#97]
__What TMM version are you using?__2.9

__release, pre-release, nightly, or directly from GitHub/branch?__

__What is the actual behaviour?__imported and rewrote all NFO, sets show up fine in TMM, cleared out data on Kodi 15.2, reimported all moves, but sets are lost (get a single set, with a name of 'name' for all movies.  Something seems to be wrong with the nfo set information from TMM or Kodi's handling of it.

__What is the expected behaviour?__ sets should show up as before

__Steps to reproduce:__see above
- first
- second
- ...

__Additional__
Have you attached the Logfile from the day it happened?
Your Operating system? (win/mac/linux? version?) TMM on Windows 10, Kodi on OpenElec Pi 2

**Comment by overpaul** [comment]
Please ignore the set issue.  I thought my OpenElec had the latest version of Kodi.  When I updated OpenElec, the sets worked fine.

You might think about an option to allow the old set nfo or the new set nfo for people that don't have the latest version of Kodi.

**Comment by myron0815** [comment]
Yes, we're already thinking about it.
Although Kodi 16 has already been released back in February, there are still few people out there using a dated version...
Thx for reporting

**Comment by overpaul** [comment]
The current version of OpenElec standard Kodi is 15.  You have to do a
development upgrade (or Beta) to get Kodi 16.

Thanks for your great work.  Your software is amazing.

*Paul Oversmith*

E-Mail: pgo@overweb.com
Phone: (941) 266-3600
