### ISSUE TITLE
IMDB TV Rating not being scraped

### ISSUE THREAD

**Issue by mapleleafs89** [tinyMediaManager/tinyMediaManager#99]
Version: 2.9
Build: 2016-10-27 18:39
OS: Linux 3.10.0-327.3.1.el7.x86_64
JDK: 1.8.0_65 amd64 Oracle Corporation

__What is the actual behaviour?__
TV Show rating not being scraped from IMDB (shows 0).

__What is the expected behaviour?__
Show a rating.

__Steps to reproduce:__
Scrape a TV show using IMDB

__Additional__
Have you attached the logfile from the day it happened?

**Comment by wjanes** [comment]
Hi

I have tried to scrape a TV Show, but for me it worked.
Which TV did you use?
Please try it again an attach the TMM Log?
